### ISSUE TITLE
yapi旧版本当前插件不能兼容的问题

### ISSUE THREAD

**Issue by xlj44400** [tangcent/easy-yapi#100]
当前使用的yapi版本 **1.4.x**；
我看你们根据token获取project信息的参数只传了token，但是旧版本yapi是必须传projectId的，请问这个有没有支持提供设置projectId的入口？

**Comment by tangcent** [comment]
嗯, 没有考虑过支持太久之前的版本. 使用简单配置是无法支持的, 需要修改源码或者用[本地扩展文件](http://easyyapi.com/setting/groovy-ext-config.html)

---

如果暂时没有更新`yapi`的打算，希望使用`easy-yapi`的话,配置起来有点繁琐.

- 由于kotlin默认方法final,所以需要开放这个方法
https://github.com/tangcent/easy-yapi/blob/3d47aedec3830756295eed5fecfda34c6e64f636/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiApiHelper.kt#L39
我将在下个版本开放部分方法,你现在可以自行修改打包，或者下载附件:
[easy-yapi.1.4.1.1.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/3921311/easy-yapi.1.4.1.1.183.0.jar.zip)
- 添加本地扩展文件:https://github.com/tangcent/spring-demo/blob/feature%2Fold_yapi/.easyapi/ext/YapiExportActionExt.groovy
- 增加本地配置:
https://github.com/tangcent/spring-demo/blob/3037f9be74a9000992b1a0f190592e41b4d4ce01/cn/.easy.api.config#L134-L135
- 增加本地yapi相关配置:[.oldyapi.properties](https://github.com/tangcent/spring-demo/blob/feature%2Fold_yapi/cn/.oldyapi.properties) 并将其加入`.gitignore`
- 之后导出时根据提示,将`yapi`相关配置写入到`.oldyapi.properties`
- 以上脚本与配置都是开放式的，你可以自行修改.

**Comment by xlj44400** [comment]
好的 谢谢回复

**Comment by xlj44400** [comment]
已经升级新版本
