### ISSUE TITLE
[Feature] 是否可以支持接口备注同步

### ISSUE THREAD

**Issue by xiechur** [tangcent/easy-yapi#1004]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tangcent** [comment]
接口备注同步具体是指什么?

**Comment by xiechur** [comment]
Yapi上的接口-编辑页是有备注模块
![image](https://github.com/tangcent/easy-yapi/assets/42671116/a68a9403-e45d-4529-abb1-56d0fd5a1460)

**Comment by tangcent** [comment]
ref: #1164
