### ISSUE TITLE
[Feature] 是否可以在上传接口文档的时候，把高级mock里的期望返回也一起创建了。

### ISSUE THREAD

**Issue by SemFreud** [tangcent/easy-yapi#1005]
是否可以在上传接口文档的时候，把高级mock里的期望返回也一起创建了。

如果我有一个响应实体，字段name 的 @mock 张三(或者别的规则)， 能不能在上传接口文档的时候，把mock期望一起创建并且打开，以便于mock调用的时候  ， 优先按照期望返回。

**Comment by SemFreud** [comment]
通过这种方式可以先解决这种问题了

field.required=#mock

**Comment by tangcent** [comment]
不是很能理解你的意思，但看起来你遇到的问题似乎是required为false的字段不出现在mock结果?
