### ISSUE TITLE
[Bug] Mock 会覆盖 枚举的mock

### ISSUE THREAD

**Issue by yanye666** [tangcent/easy-yapi#1007]
我的配置存在这种兜底的mock

##兜底的mock，根据类型判断
mock.[*|integer]=@natural(0,10000)
mock.[*Rate|number]=${float_with_four}
mock.[*|number]=${float_with_two}
mock.[*|date]=@datetime
mock.[*|boolean]=@boolean

但是枚举会被覆盖掉，
![image](https://github.com/tangcent/easy-yapi/assets/42414099/b39ec40c-8d95-4049-b6f7-4238f5181936)
![image](https://github.com/tangcent/easy-yapi/assets/42414099/dcfb28bc-dc17-4bc1-b42b-8deed974638e)
![image](https://github.com/tangcent/easy-yapi/assets/42414099/5b8bc8ed-75a0-450d-9546-7ae30a5f9808)

**Comment by tangcent** [comment]
@yanye666 [easy-yapi-2.6.0.212.0.zip](https://github.com/tangcent/easy-yapi/files/12255951/easy-yapi-2.6.0.212.0.zip)

**Comment by yanye666** [comment]
> @yanye666 [easy-yapi-2.6.0.212.0.zip](https://github.com/tangcent/easy-yapi/files/12255951/easy-yapi-2.6.0.212.0.zip)

ok,Fixed
