### ISSUE TITLE
yapi dashbord 怎么清除 缓存 如下图？

### ISSUE THREAD

**Issue by xlj44400** [tangcent/easy-yapi#101]
![image](https://user-images.githubusercontent.com/8731755/70200855-c4cf5a00-174f-11ea-8f8d-c9f96fba9843.png)

**Comment by tangcent** [comment]
![image](https://user-images.githubusercontent.com/17569144/70201235-f137a600-1750-11ea-9a20-867fee58dbb5.png)

http://easyyapi.com/setting/ide-setting.html

---

或者手动删除这个文件夹:
![image](https://user-images.githubusercontent.com/17569144/70201299-22b07180-1751-11ea-8fdd-72c88dc3d4cd.png)

**Comment by xlj44400** [comment]
明白了 thx
