### ISSUE TITLE
[Feature] field ignore 扩展功能

### ISSUE THREAD

**Issue by yanye666** [tangcent/easy-yapi#1015]
我们项目是分多个端的；有租户的，有管理运营后台；
所有租户的接口都会有userId参数，但是这个参数不是前端传的（从上下文获取的），所以我会吧这个userId参数给忽略掉；
`
 @RequestBody DemoQuery query;

class DemoQuery{
      Integer userId
}
`

field.ignore=groovy: ```
logger.log(api.path())
    return it.name()=="userId"
```
经过测试field ignore 会把请求跟返回都去掉，但是param.ignore 对于post body 传参不生效；

需求：
这里能否区分 是请求参数 还是返回参数？
运营后台这种又需要前端显示传参，目前只能通过url来判断；但是这里用不了api这个属性；或者有更好的实现方式来区分？；

[TRACE]	javax.script.ScriptException: javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: api for class: Script522
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)

**Comment by tangcent** [comment]
和 #703 类似

**Comment by yanye666** [comment]
``````
#这块代码主要是忽略一下参数
json.cache.disable=true
api.class.parse.before = groovy:```
    var url = it.annValue("org.springframework.web.bind.annotation.RequestMapping")
    if(url==null){
	return null
    }
    localStorage.set("tokenModule", regex.getGroup0("([\\w-]+)",url))
```
api.class.parse.after = groovy:```
    logger.info("now localStorage.remove:tokenModule: "+localStorage.get("tokenModule"))
    localStorage.remove("tokenModule")
```
api.param.parse.before[@org.springframework.web.bind.annotation.RequestBody]=groovy:```
    session.set("json-group", "request")
```
api.param.parse.after[@org.springframework.web.bind.annotation.RequestBody]=groovy:```
    session.remove("json-group")
```
#是请求参数 && 当前环境不是support
field.ignore=groovy:```
    return it.name()=="customerId" && session.get("json-group") == "request" && localStorage.get("tokenModule") != "support"
```
``````

这也能实现这种需求；但是session 的可用范围不是很大吧，只能用localStorage替代了；

**Comment by tangcent** [comment]
`session`是放在内存里的，生命周期就是是单次导出。
`localStorage `是放在文件里的，是持久化的，可以跨操作，跨项目共享。
你这里`session`更合适。

**Comment by yanye666** [comment]
> `session`是放在内存里的，生命周期就是是单次导出。 `localStorage `是放在文件里的，是持久化的，可以跨操作，跨项目共享。 你这里`session`更合适。

这个文档建议补出来，大家不知道有这个session；
session这个api.class.parse.before 设置，但是field.ignore拿不到，我输出日志试过

**Comment by tangcent** [comment]
> 这个文档建议补出来，大家不知道有这个session；

嗯，忘了写这个文档

> session这个api.class.parse.before 设置，但是field.ignore拿不到，我输出日志试过

你是对的，这是个bug，需要处理一下。

**Comment by tangcent** [comment]
[easy-yapi-2.6.1.212.0.zip](https://github.com/tangcent/easy-yapi/files/12364415/easy-yapi-2.6.1.212.0.zip)

**Comment by ReberMusk** [comment]
为什么 api 这个对象在 field.ignore 不考虑作为全局的参数呢？
比如: `field.ignore=groovy:api.method()=="POST"&&(it.name()=="updatedBy"||it.name()=="updatedAt")`，`api` 这个对象是读不到的

**Comment by tangcent** [comment]
主要是考虑在处理`field.ignore`的时候，`api`的信息还不完整。
