### ISSUE TITLE
[Feature] export api能加一个搜索框吗

### ISSUE THREAD

**Issue by 534519560** [tangcent/easy-yapi#1017]
在接口很多的情况下,现有的搜索功能不是很方便.能参考idea数据库模块的搜索,加一个搜索框,支持粘贴关键字吗
![image](https://github.com/tangcent/easy-yapi/assets/33799740/bb8222e2-e423-4e44-a3f2-4900f5ff4011)

**Comment by tangcent** [comment]
搜索功能具体是指什么?

**Comment by 534519560** [comment]
> 搜索功能具体是指什么?

点击export api后会加载一个列表,这个列表在接口数量很多的情况下,只能通过拖动滚动条来寻找要导出的接口,我希望能有一个搜索框,输入接口名后可以快速过滤出满足条件的接口

**Comment by tangcent** [comment]
@534519560 Hi, 这个功能已经上线啦
