### ISSUE TITLE
[Question] 请问param参数如何ignore

### ISSUE THREAD

**Issue by 3813g00c** [tangcent/easy-yapi#1025]
**Describe the question**

目前公司分页参数实体为：
<img width="700" alt="image" src="https://github.com/tangcent/easy-yapi/assets/33142631/909d355b-56a4-4741-a61d-dc2cbbdc8267">
其中searchCount属性希望不要出现在api doc中，但是按照官网文档中的配置，都未生效

如：
param.ignore=@com.numaframework.data.core.PageParams#searchCount

代码中的使用方式为：
<img width="723" alt="image" src="https://github.com/tangcent/easy-yapi/assets/33142631/1f78c341-3713-46ed-ba6a-dc8be6cc3d24">

**Comment by tangcent** [comment]
虽然是PageParams是param参数，但这里的searchCount其实是field:
参考: http://easyyapi.com/setting/rules/field_ignore.html
配置`field.ignore= searchCount `应该就可以了

**Comment by 3813g00c** [comment]
> 

这个参数是框架中的，如果这样配置的话，所有服务的这个字段都会被隐藏，可能会影响到其他请求中的searchCount，请问如果只想屏蔽这个实体中的searchCount 该怎么做呢

**Comment by tangcent** [comment]
试试 `field.ignore=com.numaframework.data.core.PageParams#searchCount`

**Comment by 3813g00c** [comment]
> field.ignore=com.numaframework.data.core.PageParams#searchCount

这个试过也没有生效  但是我直接在属性上加上注解：@JsonIgnore就好了

**Comment by tangcent** [comment]
可以加日志来帮助你判断配的对不对:
``````properties
field.ignore=groovy:```
    logger.info("field:" + it)
    logger.info("is searchCount:" + (it.toString()=="com.numaframework.data.core.PageParams#searchCount"))
    it.toString()=="com.numaframework.data.core.PageParams#searchCount"
```
``````
