### ISSUE TITLE
groovy扩展移除了么

### ISSUE THREAD

**Issue by zyriontang** [tangcent/easy-yapi#1026]
groovy扩展被移除了么？新版本无法正确执行

**Comment by tangcent** [comment]
对，太难维护了。
你现在用groovy扩展实现什么功能？

**Comment by zyriontang** [comment]
https://github.com/tangcent/easy-yapi/issues/839 这个问题  
目前你解决了yapi的导出 但不知道怎么使用 但我还需要支持postman

**Comment by zyriontang** [comment]
839那个问题 也是我提出来的

**Comment by zyriontang** [comment]
https://github.com/tangcent/easy-yapi/issues/839 这个问题也是我提出来的 但你现在移除了 我没办法使用了
目前你解决了yapi的导出 但不知道怎么使用 但我还需要支持postman
当调用api.setName()会报空指针
image

脚本配置：yapi.save.before=groovy:```
api.setName("111111")

**Comment by zyriontang** [comment]
> 对，太难维护了。 你现在用groovy扩展实现什么功能？

https://github.com/tangcent/easy-yapi/issues/839 这个问题也是我提出来的 但你现在移除了 我没办法使用了
目前你解决了yapi的导出 但不知道怎么使用 但我还需要支持postman
当调用api.setName()会报空指针
image

脚本配置：yapi.save.before=groovy:```
api.setName("111111")

**Comment by zyriontang** [comment]
@tangcent 麻烦支持一下呢
