### ISSUE TITLE
如何配置每个字段具体的mock规则？

### ISSUE THREAD

**Issue by coolhwm** [tangcent/easy-yapi#103]
关于文档  https://easyyapi.com/setting/yapi-mock.html
配置了似乎不生效，具体如何配置才能在代码中配置Mock规则并同步到yapi呢？

**Comment by tangcent** [comment]
- 参见 https://github.com/Earth-1610/spring-demo/blob/b7acaafceb7df432ff24181e0abe4388d07edc64/cn/.easy.api.config#L1-L72
- mock相关的文档还没详细写, 现在的实现方式是在构造yapi数据时, 读取mock规则，渲染进yapi数据中.有一定的局限性.
https://github.com/tangcent/easy-yapi/blob/6de92df4b7dbaba31c2630770359b7368781293f/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt#L306-L412
- 至于为何这样实现，主要是希望减少对代码的侵入. 
我也一直在考虑有没有更好的配置方法. 可以在`可用性/复杂度/代码侵入`等方面取得都能接受的效果.
---

- mock除了来自规则,更多的mock可能来源于`枚举`/`常量`
如 https://easyyapi.com/setting/rules/json_rule_enum_convert.html 中的例子

枚举类:
```java
/**
 * 用户类型
 */
public enum UserType {
    //管理员
    ADMIN(1, "管理员"),

    //成员
    MEMBER(2, "成员"),

    //游客
    GUEST(3, "游客");
     
    ...
}
```

字段关联枚举:

```java
/**
* 用户类型
* @see UserType
*/
private String type;
``` 

常量类:
```java
/**
 * 用户类型
 */
public class UserTypeConstant implements Serializable {
    public static final int ADMIN = 1;//管理员
    public static final int MEMBER = 2;//成员
    public static final int GUEST = 3;//游客
}

```

字段关联常量:

```java
/**
* 用户类型
* @see UserTypeConstant
*/
private String type;
``` 

字段关联部分常量:

```java
/**
* 用户类型
* @see UserTypeConstant#ADMIN
* @see UserTypeConstant#MEMBER
*/
private String type;
``` 
---

- 具体的配置规则是这样的: 
`mock.[$path|$type]=mock_info`
这里的$type是js类型,即`string`,`integer`,`number`,`array`,`boolean`,`object`


- 从响应来看:

***例如响应为:***
```json
{
    "a": "",
    "b": 1,
    "c": {
        "d": "dd",
        "e1e": "e",
        "e2e": "ee",
        "e3e": "eee"
    },
    "d": "dd",
}
```

***做如下配置***

`mock.[a.c.d|String]=@string("number", 3)` 对 `a.b.d`有效
`mock.[*.d|String]=@string("number", 3)` 对 `a.b.d`和`a.d`都有效
`mock.[*e|String]=@string("number", 3)` 对 `e1e`/ `e2e`/ `e3e`都有效

- 从dto/vo类来看

***例如如下类***

```java
public class UserInfo {

    @NotBlank
    private String cityName;//城市名

    @NotBlank
    private String fromCityName;//来自哪个城市

    @NotBlank
    private String toCityName;//去哪个城市

}
```

***做如下配置***

`mock.[*.cityName|string]=@city` 对`cityName`有效
`mock.[*CityName|string]=@city` 对`fromCityName`和`toCityName`有效

---

- 如果规则不生效。可以先把日志级别调低, 查看日志中是否显示加载了配置.

---

- 以上，时间仓促，如有谬误，烦请见谅.

**Comment by tangcent** [comment]
Hi~
- 增加了一条新的规则:`field.mock`.
- 默认配置里给出的是:`field.mock=#mock`
- 代码中配置如下:
```java
public class UserInfo {

    private Long id;//用户id

    /**
     * @see com.itangcent.common.constant.UserType
     */
    private int type;//用户类型

    /**
     * @mock tangcent
     */
    @NotBlank
    private String name;//用户名

    /**
     * 年龄
     * @mock 1${digit}
     */
    @NotNull
    private Integer age;

...
}
```

---

默认会解析`mock`中的`${property}`,如果不需要解析可以在配置中指定
`field.mock.resolveProperty=false`

---

[easy-yapi.1.4.2.2.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/3981032/easy-yapi.1.4.2.2.183.0.jar.zip)
