### ISSUE TITLE
[Question] 请问如果项目要统一请求前缀，可以识别spring boot项目 yml配置的 context-path吗

### ISSUE THREAD

**Issue by livingz** [tangcent/easy-yapi#1031]
具体配置如下：
server:
  servlet:
    context-path:
现在的做法是同前端口述一下有一个统一前缀，所以想问问现有插件有具体的配置或者读取配置的方案吗

**Comment by tangcent** [comment]
这个? http://easyyapi.com/setting/rules/class_prefix_path.html

**Comment by livingz** [comment]
对，多谢大佬

**Comment by livingz** [comment]
http://easyyapi.com/setting/rules/class_prefix_path.html 这个方案解决了生成yapi文档的问题，请问生成postman-json有对应的配置吗

**Comment by tangcent** [comment]
生成postman-json是指?

**Comment by livingz** [comment]
![image](https://github.com/tangcent/easy-yapi/assets/32834407/8a2a2e8f-69b7-429e-a853-8e264f23a8b0)
导出postman接口的时候，现在也想带上：
server.servlet.context-path的配置

**Comment by tangcent** [comment]
这个规则应该对postman也是有效的，你的配置文件名称是什么?

**Comment by livingz** [comment]
.easy.api.config
![image](https://github.com/tangcent/easy-yapi/assets/32834407/48153e95-9e9f-4af3-8837-81445c97c076)
![image](https://github.com/tangcent/easy-yapi/assets/32834407/dc10688b-1913-453f-92d6-a43230936e76)

**Comment by livingz** [comment]
是yml位置的问题

**Comment by livingz** [comment]
大佬解决了
