### ISSUE TITLE
[Bug] Getter方法配合@JsonIgnore无效

### ISSUE THREAD

**Issue by bjhx2003** [tangcent/easy-yapi#1037]
Getter方法配合@JsonIgnore无效，是设计如此，还是BUG？

**Comment by tangcent** [comment]
是目前的实现考虑的简单了

**Comment by bjhx2003** [comment]
> 是目前的实现考虑的简单了

是否有优化的计划，目前Getter方法配合@JsonProperty也无法实现自定义扩展命名，都是以Getter方法命名的。
这类的使用在项目中很常见，目前不太灵活

**Comment by tangcent** [comment]
嗯，都统一处理

**Comment by bjhx2003** [comment]
> 嗯，都统一处理

请问有预计发布时间吗，我这边需要结合项目看下

**Comment by tangcent** [comment]
@bjhx2003 没那么快，发布估计会在这周末10月15号

**Comment by bjhx2003** [comment]
> s

何时发布新版本插件

**Comment by tangcent** [comment]
在做支持字段排序的feature，做完一起发，省的连续升级。
你可以先手动安装:[easy-yapi-2.6.3.212.0.zip](https://github.com/tangcent/easy-yapi/files/13029559/easy-yapi-2.6.3.212.0.zip)

**Comment by bjhx2003** [comment]
> 在做支持字段排序的feature，做完一起发，省的连续升级。 你可以先手动安装:[easy-yapi-2.6.3.212.0.zip](https://github.com/tangcent/easy-yapi/files/13029559/easy-yapi-2.6.3.212.0.zip)

还有个问题，如果是在属性上@JsonIgnore
然后getXXX方法上标注了 @JsonProperty，注释无法支持 @see xxx.class 或者 @see xxx.class#filed

**Comment by tangcent** [comment]
能给个例子吗?

**Comment by bjhx2003** [comment]
![image](https://github.com/tangcent/easy-yapi/assets/11609627/f118b27b-59bf-45d3-a89e-2ef7eb923ebf)
![image](https://github.com/tangcent/easy-yapi/assets/11609627/c6a163cc-3063-4d0c-b9c0-8bfe4bfb485f)
在这个例子里，由于code是Code<String>类型的，为了让API可以显示成string，我将code属性ignore。
在get方法上标记@JsonProperty，并且加上了@see 。实际的效果中，备注生效了，但是我想通过@see指向的信息没出来，如下所示：
![image](https://github.com/tangcent/easy-yapi/assets/11609627/95d65a57-393e-4e19-8888-7ad214319a40)

如果将@see放在属性上是可以显示的，但是在这种场景的方法上不生效

**Comment by bjhx2003** [comment]
> 能给个例子吗?

发布的版本解决了这个问题吗

**Comment by tangcent** [comment]
我这边测试可以，你试试
