### ISSUE TITLE
如何添加多个请求头

### ISSUE THREAD

**Issue by deanjoson** [tangcent/easy-yapi#104]
通过增加配置文件可以进行自定义配置，添加了method.additional.header配置可以添加请求头，但是我这边会要求前对传入多个请求头，如token，客户端信息、请求参数验签等，但是发现该配置（method.additional.header）只能添加一条请求头，请问一下如何添加多个请求头信息呢？

**Comment by tangcent** [comment]
- 多行配置就可以了, 例如:
```
method.additional.header={name: "token",value: "",desc: "认证Token",required:true, example:""}
method.additional.header={name: "token2",value: "",desc: "认证Token",required:true, example:""}
```

- 会生成两个`Header`:

**Headers：**

| name  |  value  |  required | example  | desc  |
| ------------ | ------------ | ------------ | ------------ | ------------ |
| token |  | YES |  | 认证Token |
| token2 |  | YES |  | 认证Token |

**Comment by deanjoson** [comment]
好吧，我最初配置多个失败了，还以为是不行，结果是我的配置中json格式写错了😅

**Comment by tangcent** [comment]
- 嗯，是我有点考虑不周了

---

- 对于解析失败的配置都应该以日志方式给出提示
- 在[配置规则页面](http://easyyapi.com/setting/config-rule.html)给出各[规则类型](https://github.com/Earth-1610/intellij-kotlin/blob/master/intellij-idea/src/main/kotlin/com/itangcent/intellij/config/rule/RuleMode.kt)
