### ISSUE TITLE
[Bug] 需要处理record类上@param注释信息

### ISSUE THREAD

**Issue by ShidaYuumi** [tangcent/easy-yapi#1052]
项目中使用SpringBoot3+JDK17来开发，接口中请求参数使用Record类作为请求参数的情况下，使用插件，无法正确的将字段的说明导入到Yapi服务中。
![image](https://github.com/tangcent/easy-yapi/assets/29854026/0ea78f44-8a56-40a3-9ef7-2be5ce530198)

**Comment by tangcent** [comment]
对，没有这种情况。
你先尝试单独加一下配置:
```
field.doc=groovy:it.containingClass().doc("param",it.name())
```

**Comment by ShidaYuumi** [comment]
抱歉限制还注意到邮件抄送，感谢您。辛苦作者大大了。
________________________________
发件人: ***@***.*** ***@***.***> 代表 tangcent ***@***.***>
发送时间: 2023年10月24日 21:34
收件人: tangcent/easy-yapi ***@***.***>
抄送: ShidaYuumi ***@***.***>; Author ***@***.***>
主题: Re: [tangcent/easy-yapi] [Bug] Xxx (Issue #1052)


对，没有这种情况。
你先尝试单独加一下配置:

field.doc=groovy:it.containingClass().doc("param",it.name())


―
