### ISSUE TITLE
生成的文档，无法展示列表接口中data里面返回的页面字段

### ISSUE THREAD

**Issue by ChidoriZZ** [tangcent/easy-yapi#1053]
**Describe the question**

<img width="1037" alt="image" src="https://github.com/tangcent/easy-yapi/assets/49048553/332b9d24-21cf-4dd0-9072-a9cbd907a7ff">
<img width="720" alt="image" src="https://github.com/tangcent/easy-yapi/assets/49048553/b27bbee3-860f-4bb7-9a1c-5667566b2d51">
<img width="755" alt="image" src="https://github.com/tangcent/easy-yapi/assets/49048553/2c11577e-a1fe-4969-8702-2510058fc788">

生成的文档无法展示data当中的信息，是哪里配置有问题么

**Comment by tangcent** [comment]
`PageResponse`的定义是怎样的?

**Comment by ChidoriZZ** [comment]
<img width="651" alt="image" src="https://github.com/tangcent/easy-yapi/assets/49048553/1a3d782f-3132-436d-8107-fc534e169d40">
奇怪的是只有我这边生成的有问题，应该和类的定义关系不大。插件的配置也是导的我同事的，不知道是否和idea的版本有关系，我的是2023.1版本

**Comment by tangcent** [comment]
加点日志看看
```properties
json.field.parse.before=groovy:logger.info("[json] before parse field:"+it+",type:" + it.type())
json.field.parse.after=groovy:logger.info("[json] after parse field:"+it+",type:" + it.type())
```

**Comment by ChidoriZZ** [comment]
不是很明白，我这个日志该加到哪里呢。插件设置里也没看到可以加日志的位置

**Comment by tangcent** [comment]
[本地文件](https://easyyapi.com/setting/local-file-config.html)或者<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>BuildInConfig</kbd>

**Comment by ChidoriZZ** [comment]
![image](https://github.com/tangcent/easy-yapi/assets/49048553/9d0bb33d-b10f-47ef-9e3d-4f003ba75752)
![image](https://github.com/tangcent/easy-yapi/assets/49048553/33cf7334-649c-4694-af51-6eb0ec4ca3c8)
![image](https://github.com/tangcent/easy-yapi/assets/49048553/a436bfa6-2146-4676-b258-1d506313d15d)
![image](https://github.com/tangcent/easy-yapi/assets/49048553/5cafa715-075d-4caf-a0fc-063f8458f89b)
type没有识别出来

**Comment by tangcent** [comment]
第一次见这种情况，看起来是Idea没有识别到你这里这个字段是什么类型。只有PageResponse解析不出来吗?

**Comment by ChidoriZZ** [comment]
目前看来只有这个PageResponse解析不出来，但是我同事的可以解析出来，所以不知道是不是IDEA版本问题

**Comment by tangcent** [comment]
试试建一个新的项目，定义相同的PageResponse，看看能不能解析出来?

**Comment by ChidoriZZ** [comment]
![image](https://github.com/tangcent/easy-yapi/assets/49048553/64bbf056-a11f-40d9-86e2-4e20401240ba)
![image](https://github.com/tangcent/easy-yapi/assets/49048553/8b3a5b43-37d3-4157-b49b-bde78cde30d5)
破案了。。。。图二我尝试了给PageResponse继承的response加个泛型，生成的文档就是正常的，之前没生成的原因是图1没传递泛型引起的，但是奇怪的就是为啥我同事他们一直都是图一那样子，生成的文档就是正常的
