### ISSUE TITLE
[Question] 是否考虑仅使用swagger或注释开关

### ISSUE THREAD

**Issue by juyubiao** [tangcent/easy-yapi#1055]
**Describe the question**

由于项目较大+历史原因 造成既有注释又有swagger的情况，并且注释形式不标准导致未能正确使用swagger生成yapi

**Expected result**

以下两项期望达到其一
1. 加个开关仅使用swagger作为接口文档导出到yapi，忽略注释
2. 可以自定义使用swagger或注释的优先级，无swagger注解再使用注释

**Comment by tangcent** [comment]
牵扯到的地方有点多，做这个改动可能需要很久。

**Comment by tangcent** [comment]
可以试试，但可能有bug。配置`doc.source.disable=true`
 [easy-yapi-2.6.4.212.0.zip](https://github.com/tangcent/easy-yapi/files/13245600/easy-yapi-2.6.4.212.0.zip)
