### ISSUE TITLE
[Question] field上的双斜杠注释如何获取？

### ISSUE THREAD

**Issue by hhgmarch** [tangcent/easy-yapi#1056]
**Describe the question**

项目中得字段注释大多都是双斜杠 //， 用it.doc()只能获取到/** */这种注释，获取不到双斜杠注释，有什么办法可以获取到双斜杠的注释吗

下面是我的配置，希望能在//注释后加上一个自定义注解的内容，但是it.doc()获取到的都是null
field.doc[@com.**.IndexField]=groovy:it.doc()+" index: " + it.ann("com.***.IndexField","index")

**Comment by tangcent** [comment]
>  用it.doc()只能获取到/** */这种注释，获取不到双斜杠注释

目前用`it.doc()`确实只能获取到block comments。

> 有什么办法可以获取到双斜杠的注释吗

目前没有好的方法，不过如果你的双斜杠的注释都是写在字段后面的，那可以尝试从`it.sourceCode()`里截取。

> 下面是我的配置，希望能在//注释后加上一个自定义注解的内容，但是it.doc()获取到的都是null
field.doc[@com..IndexField]=groovy:it.doc()+" index: " + it.ann("com.*.IndexField","index")

`field.doc`就是额外注释，你直接配`field.doc[@com..IndexField]=groovy:" index: " + it.ann("com.*.IndexField","index")`就可以了。双斜杠的注释会被插件默认处理的。

**Comment by hhgmarch** [comment]
> `field.doc`就是额外注释，你直接配`field.doc[@com..IndexField]=groovy:" index: " + it.ann("com.*.IndexField","index")`就可以了。双斜杠的注释会被插件默认处理的。

用这种方法，easyYapi上的备注就没有原来的注释了，就只剩下`groovy:" index: " + it.ann("com.*.IndexField","index")`里的内容了
比如如下字段：
>  //名称
> @IndexField(index = 1)
>  private String name;

我希望导出到easyYapi里的备注是：“名称  index:1”，但用以上方法实际备注就只有“index:1”，这种有办法解决吗

**Comment by tangcent** [comment]
😂，那和当初的预期不一样，`field.doc`应该是额外注释
