### ISSUE TITLE
[Bug] 配置method.return后，@link无法找到内部类

### ISSUE THREAD

**Issue by Gerrit1999** [tangcent/easy-yapi#1058]
**Describe the bug**

`@link`无法找到内部类，使用全限定类名不会出现这个问题

**To Reproduce**

Detailed Steps to reproduce the behavior:

1. 配置
  `method.return[#response]=groovy: helper.resolveLink(it.doc("response"))`
2. Controller
  ```java
    import com.demo.result.DocResult;

    /**
     * 查询
     *
     * @response {@link DocResult.Entity<Foo>}
     */
    @GetMapping("/get")
    public Result get(QueryEntityDTO dto) {
        return Result.ok().addEntity(baseService.getVO(dto));
    }
  ```
3. DocResult
  ```java
  @Data
  public class DocResult {
  
      /**
       * 请求状态码
       */
      private int code;
  
      /**
       * 说明
       */
      private String msg;
  
      @Data
      @EqualsAndHashCode(callSuper = true)
      public static class Entity<T> extends DocResult {
  
          /**
           * 数据内容
           */
          private Data<T> data;
  
          @lombok.Data
          public static class Data<E> {
  
              /**
               * 数据
               */
              private E entity;
          }
      }

      @Data
      @EqualsAndHashCode(callSuper = true)
      public static class List<T> extends DocResult {
  
          /**
           * 数据内容
           */
          private Data<T> data;
  
          @lombok.Data
          public static class Data<T> {
  
              /**
               * 列表
               */
              private java.util.List<T> list;
          }
      }
  }
  ```

**Logs**

[INFO]	Start export api...
[TRACE]	found config file:E:\IDEA Projects\demo\\.easy.api.config
[DEBUG]	use recommend config
[INFO]	search api from: com.demo.controller.FooController
[TRACE]	found config file:E:\IDEA Projects\demo\\.easy.api.config
[DEBUG]	use recommend config
[INFO]	search api from: com.demo.controller.FooController
[ERROR]	error to find class:DocResult.Entity<Foo>
[WARN]	error to resolve class:com.demo.result.com.demo.result.DocResult.Entity
[INFO]	Start parse apis
[INFO]	Exported data are copied to clipboard,you can paste to a md file now

**Comment by tangcent** [comment]
@Gerrit1999 我试了一下，能正确找到内部类，不过泛型解析没处理，也就是说能拿到`com.demo.result.DocResult.Entity`。你的插件版本是多少?

**Comment by Gerrit1999** [comment]
抱歉这么晚才回复。是apifox插件的问题
