### ISSUE TITLE
[Question] folder.name 能否像 spring路由一样动态指定呢

### ISSUE THREAD

**Issue by fengzijk** [tangcent/easy-yapi#1064]
您好 作者大大

folder.name 能否像 spring路由一样动态指定呢
比如下面这样  现在是取不到值

folder.name=groovy:${spring.cloud.routes}[tool.substringBetween(it.name(),"com.xxx.xxx.",".")]

**Comment by tangcent** [comment]
这样配会好一些，`${spring.cloud.routes}`这种方式更多的是用于单个值
```properties
folder.name=groovy: config .get("spring.cloud.routes"+tool.substringBetween(it.name(),"com.zhiyue.xxx.","."))
```
另外需要确认`spring.cloud.routes`所在的配置文件被读取到了

**Comment by fengzijk** [comment]
好的  非常感谢

**Comment by fengzijk** [comment]
刚试了 的确像您所说的 spring.cloud.routes  还未加载到  其实就是想动态的 生成目录  config.get("spring.cloud.routes"+tool.substringBetween(it.name(),"com.zhiyue.xxx.",".")) 您的这种写法 也未生效 
并且使用下面写法 会有空指针   您能给我个思路吗  
folder.name=groovy:config.get(tool.substringBetween(it.name(),"com.zhiyue.star.",".")) 

[TRACE]	javax.script.ScriptException: javax.script.ScriptException: java.lang.NullPointerException: Parameter specified as non-null is null: method com.itangcent.idea.plugin.rule.StandardJdkRuleParser$Config.get, parameter name
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser.eval(ScriptRuleParser.kt:111)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser.access$eval(ScriptRuleParser.kt:34)
	at com.itangcent.idea.plugin.rule.ScriptRuleParser$parseStringRule$1.invoke(ScriptRuleParser.kt:76)

**Comment by fengzijk** [comment]
您好解决了   其实只要用tool对象截取就行
