### ISSUE TITLE
[Feature] 在YAPI的请求体（JSON5）里标注是否必填

### ISSUE THREAD

**Issue by 838239178** [tangcent/easy-yapi#1070]
#1039 

希望能加入这个功能，使用相关注解后，自动在请求体JSON5注释内添加“必填”两个字

```json
{
    "must": "@string" // 这是must, 必填
}
```

**Comment by tangcent** [comment]
直接配一些[field.doc](https://easyyapi.com/setting/rules/field_doc.html)?
```properties
field.doc[@javax.validation.constraints.NotBlank]=不可为空
field.doc[@javax.validation.constraints.NotNull]=必填
```

**Comment by 838239178** [comment]
加上这个配置后可以显示必填了，但是有没有方法放在同一行？这样看起来比较简洁。

**Comment by dt-code-top** [comment]
> 直接配一些[field.doc](https://easyyapi.com/setting/rules/field_doc.html)?
> 
> ```ini
> field.doc[@javax.validation.constraints.NotBlank]=不可为空
> field.doc[@javax.validation.constraints.NotNull]=必填
> ```

你好，这么设置后，无法根据分组自动选择是否展示文本。请问目前有更好的方法吗？
