### ISSUE TITLE
idea插件乱码

### ISSUE THREAD

**Issue by majintao** [tangcent/easy-yapi#108]
https://note.youdao.com/yws/public/resource/edc716ff9e2394c852d426f8ca2a8514/xmlnote/7F603C6EF998455DA65313E3371B5454/12231

idea插件乱码了 ，而且无法修改

**Comment by tangcent** [comment]
应该是读取推荐配置时使用了默认字符集导致的.我稍晚时候修复它.

**Comment by majintao** [comment]
发布到idea插件库了？ 我重新下载可行？

**Comment by majintao** [comment]
重新下载还是一样乱码，导出的markdown也是乱码

**Comment by tangcent** [comment]
还没有哦~我还需要自用两天，看看有没有产生新的BUG
另外插件审核需要1-2天，所有可能周五或者下周才会上到IDEA仓库里.

[easy-yapi.1.4.2.2.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/3976492/easy-yapi.1.4.2.2.183.0.jar.zip)
