### ISSUE TITLE
关于最新版点击easy-yapi 导出出现的问题哦

### ISSUE THREAD

**Issue by gghxjava** [tangcent/easy-yapi#1080]
<img width="915" alt="image" src="https://github.com/tangcent/easy-yapi/assets/71490691/87efadb5-dbe7-41b8-941e-451859aa1f67">
我在方法名字上面点击导出 会发现没有api
但是我在空白位置点击导出 是没有问题的 

请问现在是故意这么设置的吗？
<img width="489" alt="image" src="https://github.com/tangcent/easy-yapi/assets/71490691/425be782-3459-45fd-b28e-669f5903a4f8">

**Comment by tangcent** [comment]
😂, 你发现了 #1050 的BUG复现方式!!

**Comment by tangcent** [comment]
试试: [easy-yapi-2.6.7.212.0.zip](https://github.com/tangcent/easy-yapi/files/13432306/easy-yapi-2.6.7.212.0.zip)

**Comment by gghxjava** [comment]
好

**Comment by gghxjava** [comment]
大佬修复了 然后您还修改了ui？ 我想知道是什么原因出现这种情况的 可以说说吗 是为啥

**Comment by tangcent** [comment]
<img width="1135" alt="image" src="https://github.com/tangcent/easy-yapi/assets/17569144/b6003bd1-fff3-49eb-9f44-f90ead9a77c9">
可以看这个PR的修改，你也可以debug看看

> 修改了ui

UI是上周修的，就是简单优化

**Comment by gghxjava** [comment]
大佬 我今天又发现了问题 你是mac电脑是吗？mac可以但是windows还是不行

**Comment by tangcent** [comment]
我用windows试了一下，好像没啥问题
