### ISSUE TITLE
[Feature] 关于枚举的注释问题优化

### ISSUE THREAD

**Issue by bjhx2003** [tangcent/easy-yapi#1082]
常见的设计中枚举会这样设计，枚举的描述会以属性的方式存在，以保证枚举的完整性。
目前yapi只能支持把java注释作为枚举的描述展示，在实际的设计中并不友好，希望能够支持自定义获取枚举的字段作为描述，如下的例子中，我希望在yapi生成的结果中，分别获取的是code和desc字段的值
public enum ResultVOEnum {

    OK(200, "请求成功"),
    /**
     * 服务端异常
     */
    FAIL_500(500, "服务端异常");

    private final Integer codeValue;
    private final String desc;
    
        ResultVOEnum(Integer codeValue, String desc) {
        this.codeValue = codeValue;
        this.desc = desc;
    }
}

**Comment by tangcent** [comment]
可以先临时加个配置:
``````
field.doc=groovy:```
if(!it.defineClass().isEnum()){
    return
}
def resource = it.getResource()
if(!resource.class.name.contains("PsiEnumConstant")){
    return
}

if(localStorage.get("__reentrant")==true){
    return
}

localStorage.set("__reentrant",true)
try {
    def index = it.defineClass().fields().collect{it.name()}.indexOf(it.name())
    //logger.info("index:"+index)
    def fieldValues = runtime.getBean("com.itangcent.intellij.jvm.standard.StandardPsiResolver").resolveEnumFields(index, resource)
    //logger.info("fieldValues:"+fieldValues)
    if(fieldValues==null){
        return
    }
    return fieldValues["params"]["desc"]
} finally {
    localStorage.remove("__reentrant")
}
```
``````

**Comment by tangcent** [comment]
新版本中可以简单配置为:
``````properties
field.doc=groovy:```
if(it.isEnumField()){
    return it.asEnumField().getParam("desc")
}
```
``````

**Comment by wzdlagrange** [comment]
> 新版本中可以简单配置为:
> 
> ```ini
> field.doc=groovy:```
> if(it.isEnumField()){
>     return it.asEnumField().getParam("desc")
> }
> ```
> ```

可以不做成全局的吗？
比如做成类似  @see UserType#type->UserType#desc
这样不好处理的话，
写两行呢？
@see UserType#type
@see UserType#desc

第一行的see是 值，第二行的see是描述
