### ISSUE TITLE
如何给返回的数据其中的某些变量重写变量说明？

### ISSUE THREAD

**Issue by notWinds** [tangcent/easy-yapi#1098]
产生问题原因:
返回类型是mybatisplus的泛型IPage类，因为IPage接口在不重写覆盖的情况下，返回的数据说明都是为空的。
想实现的需求：
能够给与IPage接口返回的数据给与写上变量说明
![1705290352501](https://github.com/tangcent/easy-yapi/assets/65955600/85e72a1a-6dff-42be-8609-760be128b713)

**Comment by tangcent** [comment]
类似这样配:
```properties
field.doc[com.itangcent.springboot.demo.dto.DocResult#code]=一个code
```

**Comment by notWinds** [comment]
> 类似这样配:
> 
> ```ini
> field.doc[com.itangcent.springboot.demo.dto.DocResult#code]=一个code
> ```

感谢，问题得到了解决！
