### ISSUE TITLE
当接口请求参数包含一个抽象类字段时如何生成API呢

### ISSUE THREAD

**Issue by yangzan0816** [tangcent/easy-yapi#1104]
**Describe the question**

当前我有一个需求需要在接口中添加一个动态字段，但我不知道如何生成它的api文档

**Demo Code**
伪代码,我希望能展示出Animal支持的两种参数，请问有实现方案吗
`
public void save(Param param)

class Param{
   private TypeEnum type;
   private Animal animal;
}

abstract class Animal{}

class Dog extends Animal{
      private BodyShapeEnum bodyShape;
}
class Bird extends Animal{
      private boolean canFly;
}
`

**Additional context**

**Comment by tangcent** [comment]
我之前是这样配置: https://easyyapi.com/qa/field_multiple_types.html
你有更好的想法吗?
