### ISSUE TITLE
[Bug] 直接使用枚举作为请求参数时，没有按照配置生成备注信息

### ISSUE THREAD

**Issue by CloudSen** [tangcent/easy-yapi#1108]
**Describe the bug**

在远程配置中，通过BaseEnum的方式，自定义使用枚举的code作为交互字段。  
实际生成的文档中，请求参数的备注和响应参数的备注还是展示的枚举name，响应参数却又是正确显示的枚举code。

**To Reproduce**
配置如下：  
```
# 使用枚举类型的code给前端
enum.use.by.type=false
enum.use.custom[groovy:it.isExtend("cn.cisdigital.datakits.framework.model.interfaces.BaseEnum")]=code
```
BaseEnum如下：  
```
public interface BaseEnum {
    @JsonValue
    int getCode();

    String getKey();

    default String getDesc(@Nullable Object[] args) {
        return I18nUtils.getMessage(this.getKey(), args);
    }

    default String getDesc() {
        return I18nUtils.getMessage(this.getKey(), (Object[])null);
    }
}
```
DevelopmentModeEnum如下：  
```
@Getter
@RequiredArgsConstructor
public enum DevelopmentModeEnum implements BaseEnum {

    /**
     * 简单模式
     */
    SIMPLE(1, "简单模式"),
    /**
     * 标准模式
     */
    STANDARD(2, "标准模式"),
    ;

    @EnumValue
    @JsonValue
    private final int code;
    private final String key;
}
```

Controller如下：  
```
@RequiredArgsConstructor
@RestController
@RequestMapping("/yapi")
public class TestYapi {

    /**
     * 测试接口
     */
    @GetMapping("/get")
    public ResVo<DevelopmentModeEnum> test(@RequestParam DevelopmentModeEnum developmentModeEnum) {
        return ResVo.ok(null);
    }
}
```

生成的文档如下：
![image](https://github.com/tangcent/easy-yapi/assets/25652685/682f9c6a-2c36-400a-9cef-cc2cf71a6617)

   
**Expected behavior**

请求参数的备注和响应参数的备注，也应该使用枚举code。
因为前端只想知道枚举参数有哪些数字，分别对应什么意思，他们不关心枚举名

**Environment (please complete the following information):**
 - OS: MacOS
 - IDEA version 2021.3.3
 - Plugin version 2.6.8.212.0
 - Yapi version 1.9.2

**CheckList**

   - [x] <kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd> Intelligent</kbd> > <kbd>enable infer</kbd>

**Comment by ya-dao** [comment]
补充一个类型上的问题, 如下图所示, 其类型应该是int而不应该是string:
<img width="825" alt="image" src="https://github.com/tangcent/easy-yapi/assets/27146728/ea6cbddf-4152-4463-8e48-27f9a8641c79">
