### ISSUE TITLE
默认配置无法替换

### ISSUE THREAD

**Issue by deanjoson** [tangcent/easy-yapi#111]
默认配置无法替换，例如我需要对过期接口进行标注tag，但是默认已经有了，但我想标注为中文结果出现两个。
```
//默认配置
api.tag[@java.lang.Deprecated]=deprecated
//配置文件中的配置
api.tag[@java.lang.Deprecated]=废弃
```
最终的结果就是出现了两个标签 deprecated 和 废弃
 
希望能替换默认配置

**Comment by tangcent** [comment]
![image](https://user-images.githubusercontent.com/17569144/71052740-4b8c2a00-2187-11ea-825f-7ffd97142682.png)
在[默认配置](http://easyyapi.com/setting/ide-setting.html)中把你不需要的`✔️`去掉试试呢

**Comment by deanjoson** [comment]
👍👍👍👍👍
