### ISSUE TITLE
[Bug] .yapi.config文件配置yapi.server不生效

### ISSUE THREAD

**Issue by lin407** [tangcent/easy-yapi#1121]
**Describe the bug**

idea插件（版本： 2.6.9.212.0）导出到yapi时，弹窗提示‘inpout server of api’，无法读取到 .yapi.config文件中yapi.server配置。

**Comment by tangcent** [comment]
@lin407 先用一下[v2.6.8](https://github.com/tangcent/easy-yapi/releases/tag/v2.6.8)

**Comment by tangcent** [comment]
[easy-yapi-2.6.9.212.0.zip](https://github.com/tangcent/easy-yapi/files/14946937/easy-yapi-2.6.9.212.0.zip)
