### ISSUE TITLE
[Question] 支持@Schema RequiredMode

### ISSUE THREAD

**Issue by sunyj-003** [tangcent/easy-yapi#1125]
<img width="668" alt="image" src="https://github.com/tangcent/easy-yapi/assets/58318214/a2e7dfb7-7567-47d0-9304-e5970926efe6">
required属性已经废弃,是否可以根据 RequiredMode.REQUIRED来标记是否必填

**Comment by tangcent** [comment]
@sunyj-003 我平常不用swagger, 你可以加一下这个配置看看效果是否符合预期:
https://github.com/tangcent/easy-yapi/blob/66fe71a0fd523335b8098abad43efe20da270e41/third/swagger3.config#L23-L31
另外，如果可以的话，你可以自行增加一些你觉得有用的配置，也可以尝试提交PR合进来。 : )

**Comment by sunyj-003** [comment]
好的，配置符合预期，感谢
