### ISSUE TITLE
[Question] 类型转换是否可以支持query传参

### ISSUE THREAD

**Issue by sunyj-003** [tangcent/easy-yapi#1126]
<img width="598" alt="image" src="https://github.com/tangcent/easy-yapi/assets/58318214/40217b2d-36f9-42ad-842e-50b95f039c5f">

<img width="765" alt="image" src="https://github.com/tangcent/easy-yapi/assets/58318214/3b7aa40e-b0b6-42e8-8da0-0fe1ef48ad03">

我希望将Long类型的字段在 文档上 显示String， 这种配置方式只能支持JSON类型的出入参，非JSON类型的该如何配置呢?

**Comment by tangcent** [comment]
没有提供这个规则
