### ISSUE TITLE
[Question] about https address Request excption.

### ISSUE THREAD

**Issue by KK-Karl** [tangcent/easy-yapi#1130]
Describe the question

I would like to inquire about the current support for HTTPS request addresses in your plugin. It seems that the plugin does not support HTTPS request addresses. I'm curious if there are any plans to add support for HTTPS addresses or if there are considerations to make SSL support a configurable option.

Expected result

I expected the plugin to support HTTPS request addresses as part of its functionality. However, when attempting to use HTTPS addresses, it seems that the plugin does not handle them properly. I'm hoping to understand if this is a known limitation or if there are plans to address this issue in future updates.

**Demo Code**

NO demo

通过搜索，发现
#531  已进行解决过，可是这个情况依然出现了。是不是添加其他的配置。

**ScreenShot**
![20240424105959](https://github.com/tangcent/easy-yapi/assets/42131197/644f0492-a969-4b06-9cad-d53c16b061dd)
![20240424110040](https://github.com/tangcent/easy-yapi/assets/42131197/0c8591d4-622c-4d2b-a126-20db98d91a26)

Looking forward to your  kindly reply,thank you.

**Comment by tangcent** [comment]
可以试试在Settings里面切换okhttp试试. [easy-yapi-2.7.0.212.0.zip](https://github.com/tangcent/easy-yapi/files/15140455/easy-yapi-2.7.0.212.0.zip)

**Comment by KK-Karl** [comment]
![112233](https://github.com/tangcent/easy-yapi/assets/42131197/9d288209-b503-4990-928f-49449c3a166b)

试了，果然正常请求了。 谢谢大神！
