### ISSUE TITLE
[Question] idea2024.1 找不到javax.validation(grouped)

### ISSUE THREAD

**Issue by minpsn** [tangcent/easy-yapi#1131]
<img width="1516" alt="image" src="https://github.com/tangcent/easy-yapi/assets/38978304/771c9e98-fda4-41ae-8862-8e797bccf0b2">
如图所示，找不到分组的这个设置

**Comment by tangcent** [comment]
改成`jakarta.validation(strict)`了:
https://github.com/tangcent/easy-yapi/pull/1013/files#diff-c4538e37e8492c4ab2f8b12f61b888cabe1f699f67db269230feed70fa13efb1

**Comment by tangcent** [comment]
如果要勾选`javax.validation(strict)`，就把`javax.validation`取消掉。

**Comment by minpsn** [comment]
感谢感谢

**Comment by minpsn** [comment]
对了，另外，文档需要更新下。
<img width="1639" alt="image" src="https://github.com/tangcent/easy-yapi/assets/38978304/0b38f12d-64ed-4b99-81c7-b02dfa0a05bd">
@tangcent
