### ISSUE TITLE
[Question] 导出为Postman格式时，URL如何设置为不带Module名称？

### ISSUE THREAD

**Issue by PiscesZhu** [tangcent/easy-yapi#1135]
**Describe the question**

目前导出为Postman格式时，总是会在url前加上Module名称，如何设置为不带Module名称？

![微信图片_20240509175907](https://github.com/tangcent/easy-yapi/assets/1022058/ff251ef6-57ff-4ab8-a90c-943f5f55488f)

**Comment by tangcent** [comment]
你是想改host?
可以配这个规则: https://easyyapi.com/setting/rules/postman_host.html

**Comment by PiscesZhu** [comment]
> 你是想改host? 可以配这个规则: https://easyyapi.com/setting/rules/postman_host.html
感谢！
在项目根目录下添加了.postman.config文件，然后配置
postman.host=/
