### ISSUE TITLE
getMapping 没有请求参数

### ISSUE THREAD

**Issue by ChenYilei2016** [tangcent/easy-yapi#114]
get请求的接口上传 没有请求参数的类型, 有木有可能把 类型参数加载备注里哈 O(∩_∩)O哈哈~

**Comment by tangcent** [comment]
> 你的意思是`没有请求参数的类型`吧？

由于不确定开发者是否都有此需求,所以并未给出内置实现.
可以自行使用配置文件实现此需求,参考: http://easyyapi.com/setting/rules/doc_param.html

**Comment by ChenYilei2016** [comment]
解决了我的一个问题,  现在我有另外一个问题~~ 我能让上传API时 , {@link  一个枚举} 中的枚举 解析出固定的格式吗

**Comment by tangcent** [comment]
(O_O)?不是很理解这里`固定的格式`的含义, 是不是可以尝试举个例?

**Comment by ChenYilei2016** [comment]
就是一般请求参数中枚举都是用 int 表示上传的吧 ,  `   /**
     * test1 方法
     * 备注
     *
     * @param a xxxx
     * @param b {@link MoneyTypeEnum}
     * @return aaaa
     */
    @GetMapping("/test1")
    public Object test1(@RequestParam(name = "a", required = true) String a, int b) {
        return new ABC();
    }`
这样上传的话, 在API文档上 b参数是显示 MoneyTypeEnum 的注解 , 有木有某种方式能显示固定的方法啥的 例如
http://easyyapi.com/setting/rules/json_rule_enum_convert.html

**Comment by ChenYilei2016** [comment]
其实我是看 枚举: 1,2,3
枚举备注: 1 :管理员 2 :成员 3 :游客
mock: @pick([1,2,3]) 这种枚举写法很棒 ,
但是 {@link 枚举} 不能显示这种格式 , 只能显示类上的注解  (⊙o⊙)…

**Comment by tangcent** [comment]
> 但是 {@link 枚举} 不能显示这种格式 , 只能显示类上的注解 (⊙o⊙)…

对于`@link`也是有尝试解析的,不过为了防止错误的解析造成误导,所以对于枚举的解析相对来说比较保
守.解析成功的效果如下:

***Query:***
![image](https://user-images.githubusercontent.com/17569144/71180571-68228200-22ad-11ea-99f1-f1af7b6df9d6.png)

***Path:***

![image](https://user-images.githubusercontent.com/17569144/71180587-71abea00-22ad-11ea-8cbd-d0d6c395acbd.png)

***Form:***

![image](https://user-images.githubusercontent.com/17569144/71180490-45906900-22ad-11ea-97fd-c4844bc5ba2e.png)

---

- 当`{@link}`修饰的目标名与枚举中的字段名一致时,可以简单注释为:
`@param type 用户类型 {@link com.itangcent.common.constant.UserType}`

- 当`{@link}`修饰的目标名与枚举中的字段名不一致时,需要指定目标枚举字段:
`@param b 用户类型 {@link com.itangcent.common.constant.UserType#type}`

**Comment by ChenYilei2016** [comment]
我试了, 可以的, !!! 牛逼

**Comment by tangcent** [comment]
:D
