### ISSUE TITLE
[Question] method.doc中如何调用函数

### ISSUE THREAD

**Issue by wowuhm** [tangcent/easy-yapi#1149]
**Describe the question**

想在method.doc中自定义内容，引入一些例如获取当前时间的函数，在接口文档中自动填入生成时间的功能。

**Comment by tangcent** [comment]
试试用`tool.now()`，文档在这里: https://easyyapi.com/setting/tools/tool.html

**Comment by wowuhm** [comment]
> 试试用`tool.now()`，文档在这里: https://easyyapi.com/setting/tools/tool.html

method.doc=groovy:tool.now()
谢谢回答，效果很好

有一个新的问题可能和插件关系不大
想问问有没有遇到过

我想在method.doc中插入markdown的表格
但是
`method.doc=groovy:"* 开发\n\n|开发类型|开发人员|开发时间|\n|-|-|-|\n|后端||"+tool.now("yyyy-MM-dd")+"|\n|前端|||\n\n* 后端SQL\n\n``` sql\n\n```"`
在上传到yapi上后
首先被识别为了WYSIWYG编辑器的文本，如下
![image](https://github.com/tangcent/easy-yapi/assets/100753510/27702edb-240a-439b-8976-4d6cc18c0a12)
并不会被直接识别为markdown表格格式
但是编辑时是正常显示的
编辑时默认就处于WYSIWYG编辑器
![image](https://github.com/tangcent/easy-yapi/assets/100753510/f87a9e22-ee01-4c6b-8aef-175a53d4756c)
需要点击保存
再次预览才会显示正常
假如不点击保存将一直处于markdown表格部分是源代码的状态

单独上传一个`|`时
`method.doc=groovy:"|"`
也是先展示在WYSIWYG编辑器中
点击markdown进行显示将会转义为`\|`

**Comment by tangcent** [comment]
有可能是[MarkdownHtmlGenerator](https://github.com/tangcent/easy-yapi/blob/master/plugin-adapter/plugin-adapter-markdown/src/main/kotlin/com/itangcent/plugin/adapter/MarkdownHtmlGenerator.kt)没有处理成功，你可以debug试试，如果能找到问题的话，欢迎提个PR修复。

**Comment by tangcent** [comment]
提交到yapi之前，会在这里处理markdown: https://github.com/tangcent/easy-yapi/blob/a574fc3d377d8a8b6f3cee3917adbca309bc49b1/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt#L866

**Comment by wowuhm** [comment]
> 提交到yapi之前，会在这里处理markdown:
> 
> https://github.com/tangcent/easy-yapi/blob/a574fc3d377d8a8b6f3cee3917adbca309bc49b1/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt#L866

好的，非常感谢！没做过插件开发，等我学一手。
