### ISSUE TITLE
导出

### ISSUE THREAD

**Issue by 398546229** [tangcent/easy-yapi#1150]
大佬，我想请教下应该在哪个地方重新封装下导出接口的信息呢，就是返回的参数，我需要放到一个自定义的map里

**Comment by tangcent** [comment]
你是指这个[method.return](https://easyyapi.com/setting/rules/method_return.html)?

**Comment by 398546229** [comment]
对，我自定义了一个响应体的类，属性有status和data，但是data里面没有数据，请问需要怎么处理才能把原来的数据放入我定义的这个data里呢？

**Comment by tangcent** [comment]
类似文档里那样不行吗？
`method.return=groovy: "com.itangcent.common.dto.Result<" +  it.returnType() +">"`

**Comment by 398546229** [comment]
请问数据是不是要自己做映射，把原来的结果放入新的响应体里面？我目前就是加了这个配置文件，然后在接口上写了注释，定义了响应体的类，就没别的操作了。我以为插件能够自动映射，自动将返回结果存入我定义的data属性里面？

**Comment by 398546229** [comment]
现在可以了，是我想多了，感谢
