### ISSUE TITLE
[Question] 支持yapi接口界面的备注功能么？

### ISSUE THREAD

**Issue by suoyiman** [tangcent/easy-yapi#1164]
现在export yapi会把界面上原来编写的备注清空
![20240912-120115](https://github.com/user-attachments/assets/022ddb34-2f91-47bf-af4f-5f46f66bff1e)

**Comment by tangcent** [comment]
你的意思是希望有个选项，导出到yapi的时候可以不覆盖在yapi接口界面手动编辑的备注?

**Comment by suoyiman** [comment]
是的，现在更新后就把界面上写的备注清空了。另外，有可以在代码中编写这里的备注，然后通过easy-yapi导出的功能么？在文档里没有查到。

**Comment by tangcent** [comment]
> 是的，现在更新后就把界面上写的备注清空了。

我看看加个配置来选择不覆盖备注。

> 另外，有可以在代码中编写这里的备注，然后通过easy-yapi导出的功能么？在文档里没有查到。

直接在API方法上写注释就行了
https://easyyapi.com/documents/java_doc_demo.html

**Comment by suoyiman** [comment]
期待。场景就是复杂接口会在备注里写哪个版本更新了哪些字段，方便前端对接。这部分没写进方法注释。

**Comment by tangcent** [comment]
> 场景就是复杂接口会在备注里写哪个版本更新了哪些字段，方便前端对接。这部分没写进方法注释。

这个信息你会写在代码注释里吗? 还是只是在yapi界面上去编辑?

**Comment by suoyiman** [comment]
> > 场景就是复杂接口会在备注里写哪个版本更新了哪些字段，方便前端对接。这部分没写进方法注释。
> 
> 这个信息你会写在代码注释里吗? 还是只是在yapi界面上去编辑?

不会在代码里写，代码有历史可以看，不用写。只在yapi界面上简单写下

**Comment by tangcent** [comment]
OK，了解
