### ISSUE TITLE
最近使用出现class handle error

### ISSUE THREAD

**Issue by qinkangdeid** [tangcent/easy-yapi#118]
最近更新的很频繁 用的最新版本
刚刚使用了下 包这个错 然后IDEA卡死 只能强制停止进程了 

![image](https://user-images.githubusercontent.com/17582522/71358618-87c6ec80-25c4-11ea-8079-7ccf40e82c47.png)

我自定义的config没有什么东西 如下：
```bash
# 过滤接口自定义参数
param.ignore=@com.baibu.platform.weapp.zhijing.offers.core.user.UserContent

# 额外要求header中携带token
method.additional.header[!@com.baibu.platform.weapp.zhijing.offers.core.user.PublicMethod]={name: "Token",value: "",desc: "登陆获取到的Token",required:true, example:"eyJhbGciO"}

```

**Comment by tangcent** [comment]
我自行测试过,没有出现这个问题. 可以提供下 IDEA版本,插件版本，操作方式吗?

**Comment by qinkangdeid** [comment]
> 我自行测试过,没有出现这个问题. 可以提供下 IDEA版本,插件版本，操作方式吗?

IDEA: 2019.3.1
插件版本：easy-yapi.1.4.2.2.183.0.jar

我的项目还是很简单
```bash
xxx-app             -----父工程
├──xxx-app-admin  -----admin web模块
├── xxx-app-api --- api web模块
└── xxx-app-common  --- 上面两个模块的公共模块
```
我执行 Export Yapi操作就报错 不管是单个 还是多个接口生成都是这样 查看报错是下面的信息：

![image](https://user-images.githubusercontent.com/17582522/71419718-d9967200-26ab-11ea-9a65-ccf8deb8fbc7.png)


有时间我剔除一个demo出来看看

**Comment by tangcent** [comment]
这个看起来好像是加载`yaml`错误,
试试在[推荐配置](http://easyyapi.com/setting/ide-setting.html)里把自动加载spring`yaml`的取消掉
![image](https://user-images.githubusercontent.com/17569144/71426359-46792e80-26e3-11ea-8693-dbb599c76a19.png)

---

你的`yaml`里有什么特殊的格式吗?

**Comment by qinkangdeid** [comment]
关闭了下面的这个就可以了 
![image](https://user-images.githubusercontent.com/17582522/71502473-4a57ad00-28ab-11ea-8d38-ca246da20717.png)
yaml没什么特殊的东西

**Comment by qinkangdeid** [comment]
application.yml里我做了文件按环境做的分割 带有`---` 类似的

```yaml
spring:
  profiles: local
  application:
    name: xxxxx

---
spring:
  profiles: dev
  application:
    name: yyyyy

```





看到报错也是提示的 
![image](https://user-images.githubusercontent.com/17582522/71504462-7fb4c880-28b4-11ea-83fb-06d9f9f10b32.png)
以为是多环境配置都写在一个环境导致的 我尝试
1. 把`application.yml`按环境分割的去除 仅保留一份配置在
2. 把所有的`application.yml`都清空了(一个空文件)

两种方式运行后 还是报这个错 只有不勾选才没问题

看规则是这样的 感觉没问啊
```bash
#Import spring properties
###set ignoreNotFoundFile = true
properties.additional=${module_path}/src/main/resources/application.properties
properties.additional=${module_path}/src/main/resources/application.yml
properties.additional=${module_path}/src/main/resources/application.yaml
###set ignoreNotFoundFile = false

```

去除是可以的  晚点我再试试 也许还是我结构有问题

**Comment by tangcent** [comment]
可能这里对yaml的解析不是很好.
https://github.com/Earth-1610/intellij-kotlin/blob/3cf4563b948d6724609dec4f1f9937f844005e35/intellij-idea/src/main/kotlin/com/itangcent/intellij/config/AbstractConfigReader.kt#L110-L125
有没有什么好的处理方法?

---

这里解析配置文件错误是不是应该只打印error log就好?跳过错误的文件继续执行解析流程?

**Comment by qinkangdeid** [comment]
> 可能这里对yaml的解析不是很好.
> https://github.com/Earth-1610/intellij-kotlin/blob/3cf4563b948d6724609dec4f1f9937f844005e35/intellij-idea/src/main/kotlin/com/itangcent/intellij/config/AbstractConfigReader.kt#L110-L125
> 有没有什么好的处理方法?
> 
> 这里解析配置文件错误是不是应该只打印error log就好?跳过错误的文件继续执行解析流程?

这个`module_path `引用是在那里获取的？感觉是这个路径可能取到了错的位置导致加载配置错了

> 这里解析配置文件错误是不是应该只打印error log就好?跳过错误的文件继续执行解析流程?

这个可以的  解析不了给个提示跳过也不错  配置文件需要解析的设置应该不多🙏

**Comment by tangcent** [comment]
> 这个module_path 引用是在那里获取的？感觉是这个路径可能取到了错的位置导致加载配置错了

https://github.com/tangcent/easy-yapi/blob/b96b863235ddf325f8185df9b4c752f7d0a3b9d4/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/config/RecommendConfigReader.kt#L77-L83
