### ISSUE TITLE
[Question] HashMap导出至Yapi的返回数据为空

### ISSUE THREAD

**Issue by Lvesfzzy** [tangcent/easy-yapi#1182]
**Describe the question**

有一个接口的返回数据是HashMap类型，但是导出至yapi却解析不了。已经试了开启infer、setter as field、getter as filed、添加泛型，但都没成功。想问一下大佬这种应该怎么处理呢。

**Screenshots**

<img width="1128" alt="iShot_2024-12-31_15 09 49" src="https://github.com/user-attachments/assets/c1ab14b4-a8a8-4abc-9a17-0316ba22e881" />

**Demo Code**
```java
@GetMapping(value = "/{serverId}")
public AjaxResult getInfo(@PathVariable Long serverId)
{
    return Optional.ofNullable(serverInfoService.getById(serverId))
            .map(this::success)
            .orElseGet(() -> error("此服务器编号不存在"));
}

------------------------------------------------------------------------------------------------------------------------------

public class AjaxResult extends HashMap<String, Object>
{
    private static final long serialVersionUID = 1L;

    /** 状态码 */
    public static final String CODE_TAG = "code";

    /** 返回内容 */
    public static final String MSG_TAG = "msg";

    /** 数据对象 */
    public static final String DATA_TAG = "data";

    /**
     * 初始化一个新创建的 AjaxResult 对象，使其表示一个空消息。
     */
    public AjaxResult()
    {
    }

    /**
     * 初始化一个新创建的 AjaxResult 对象
     * 
     * @param code 状态码
     * @param msg 返回内容
     */
    public AjaxResult(int code, String msg)
    {
        super.put(CODE_TAG, code);
        super.put(MSG_TAG, msg);
    }

    /**
     * 初始化一个新创建的 AjaxResult 对象
     * 
     * @param code 状态码
     * @param msg 返回内容
     * @param data 数据对象
     */
    public AjaxResult(int code, String msg, Object data)
    {
        super.put(CODE_TAG, code);
        super.put(MSG_TAG, msg);
        if (StringUtils.isNotNull(data))
        {
            super.put(DATA_TAG, data);
        }
    }

    /**
     * 返回成功消息
     * 
     * @return 成功消息
     */
    public static AjaxResult success()
    {
        return AjaxResult.success("操作成功");
    }

    /**
     * 返回成功数据
     * 
     * @return 成功消息
     */
    public static AjaxResult success(Object data)
    {
        return AjaxResult.success("操作成功", data);
    }

    /**
     * 返回成功消息
     * 
     * @param msg 返回内容
     * @return 成功消息
     */
    public static AjaxResult success(String msg)
    {
        return AjaxResult.success(msg, null);
    }

    /**
     * 返回成功消息
     * 
     * @param msg 返回内容
     * @param data 数据对象
     * @return 成功消息
     */
    public static AjaxResult success(String msg, Object data)
    {
        return new AjaxResult(HttpStatus.SUCCESS, msg, data);
    }

    /**
     * 返回警告消息
     *
     * @param msg 返回内容
     * @return 警告消息
     */
    public static AjaxResult warn(String msg)
    {
        return AjaxResult.warn(msg, null);
    }

    /**
     * 返回警告消息
     *
     * @param msg 返回内容
     * @param data 数据对象
     * @return 警告消息
     */
    public static AjaxResult warn(String msg, Object data)
    {
        return new AjaxResult(HttpStatus.WARN, msg, data);
    }

    /**
     * 返回错误消息
     * 
     * @return 错误消息
     */
    public static AjaxResult error()
    {
        return AjaxResult.error("操作失败");
    }

    /**
     * 返回错误消息
     * 
     * @param msg 返回内容
     * @return 错误消息
     */
    public static AjaxResult error(String msg)
    {
        return AjaxResult.error(msg, null);
    }

    /**
     * 返回错误消息
     * 
     * @param msg 返回内容
     * @param data 数据对象
     * @return 错误消息
     */
    public static AjaxResult error(String msg, Object data)
    {
        return new AjaxResult(HttpStatus.ERROR, msg, data);
    }

    /**
     * 返回错误消息
     * 
     * @param code 状态码
     * @param msg 返回内容
     * @return 错误消息
     */
    public static AjaxResult error(int code, String msg)
    {
        return new AjaxResult(code, msg, null);
    }
}
```

**Comment by tangcent** [comment]
@Lvesfzzy 你这个情况可能要配[export.after](https://easyyapi.com/setting/rules/export_after.html), 然后用注释来标记返回的`data`.
配置:
``````properties
export.after[#return]=groovy:```
    def returnClass = helper.resolveLink(it.doc("return"))
    if(returnClass == null){
        return
    }
    def returnObj = returnClass.toObject(true,true,true)
    api.setResponseBody([
        code: 200,
        data: returnObj,
        msg: "success"
    ])
```
``````

然后在api方法上注释:
```java
    /**
     * xxxxxxx
     *
     * @return {@link XxxxxDTO}
     */
    @GetMapping(value = "/{serverId}")
    public AjaxResult getInfo(@PathVariable Long serverId)
    {
        return Optional.ofNullable(serverInfoService.getById(serverId))
                .map(this::success)
                .orElseGet(() -> error("此服务器编号不存在"));
    }
```

**Comment by Lvesfzzy** [comment]
可以啦，谢谢大佬。那这样写的话code和msg如何指定它们的字段注释呢？

**Comment by Lvesfzzy** [comment]
可以啦，谢谢大佬。还有一个问题是 怎么导出时每个接口都默认带一个Header中的Authorization字段呢？
<img width="837" alt="image" src="https://github.com/user-attachments/assets/9f16ac72-aac2-44a7-8ab9-76aded5b72ee" />

**Comment by Lvesfzzy** [comment]
可以啦，谢谢大佬。那这样写的话怎么给code字段和msg字段加字段注释呢？

**Comment by Lvesfzzy** [comment]
还有一个问题，我配置了全局添加header。当我只填写了example没有填写value时，example的配置没有生效。
<img width="980" alt="image" src="https://github.com/user-attachments/assets/0bcbc39a-39ce-4118-ab60-23f026536a7b" />

<img width="1110" alt="image" src="https://github.com/user-attachments/assets/c786a84a-ee50-40e3-bae2-baeefe625bdd" />

**Comment by tangcent** [comment]
> 可以啦，谢谢大佬。那这样写的话怎么给code字段和msg字段加字段注释呢？

有点tricky :)
``````properties
export.after[#return]=groovy:```
    def returnClass = helper.resolveLink(it.doc("return"))
    if(returnClass == null){
        return
    }
    def returnObj = returnClass.toObject(true,true,true)
    api.setResponseBody([
        "@comment": [code: "状态码", data: "数据对象", msg: "返回内容"],
        code: 200,
        data: returnObj,
        msg: "success"
    ])
```
``````



> 还有一个问题，我配置了全局添加header。当我只填写了example没有填写value时，example的配置没有生效。 <img alt="image" width="980" src="https://private-user-images.githubusercontent.com/51805556/399436629-0bcbc39a-39ce-4118-ab60-23f026536a7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MzQ3NDgsIm5iZiI6MTczNTYzNDQ0OCwicGF0aCI6Ii81MTgwNTU1Ni8zOTk0MzY2MjktMGJjYmMzOWEtMzljZS00MTE4LWFiNjAtMjNmMDI2NTM2YTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDA4NDA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMmNhYWY3OTdjODUyMmYxYWFkYzg3NTU1OGYyYWZhYTUxYWVlYWJmYjMxMWU0M2QyMDA4NTQwN2VhYjU4MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CjywiRgb2gOtPEc_Ha0kJ1jRRAGAlE5qBjXDQomz8XQ">
> 
> <img alt="image" width="1110" src="https://private-user-images.githubusercontent.com/51805556/399436594-c786a84a-ee50-40e3-bae2-baeefe625bdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MzQ3NDgsIm5iZiI6MTczNTYzNDQ0OCwicGF0aCI6Ii81MTgwNTU1Ni8zOTk0MzY1OTQtYzc4NmE4NGEtZWU1MC00MGUzLWJhZTItYmFlZWZlNjI1YmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMxVDA4NDA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0MzBlN2E5OWIxN2FhNzc0ZWQ3YWVmZTJmMmJlYTQ4N2FjNWM1NjY1OTQ0N2VmMWE3M2Q5NTUwZjI5NTAzOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.spY53ZS6IC7W9d9nWX3rtaESVuGzihlVvf8VeGsNYns">

不好意思，文档没更新。这里的key是`demo`不是`example`
``````properties
# 全局认证
method.additional.header={name: "Authorization",demo: "eyJhbGciOiJIUzUxMiJ9.....",desc: "认证Token",required:true}
``````

**Comment by Lvesfzzy** [comment]
感谢解惑，祝大佬元旦快乐~
