### ISSUE TITLE
参数字段排序问题

### ISSUE THREAD

**Issue by deanjoson** [tangcent/easy-yapi#119]
能否支持按参数的字段顺序生成yapi参数表格。
我有一个接口的参数有点多，前端是划分了三个区域的，代码是原型的先后写的字段，但是生成的yapi接口文档中参数的顺序就是乱的，很难查找，希望能有办法对参数进行排序

**Comment by tangcent** [comment]
我试了下，默认应该是按参数的字段顺序生成的。
不过推断里面好像有点问题.

**Comment by NowBro** [comment]
你好, 我发现导出到markdown是按照定义的顺序, 但是导出到yapi api却不是按照field在bean中的顺序, 是不是需要什么额外配置呢?

**Comment by tangcent** [comment]
> 你好, 我发现导出到markdown是按照定义的顺序, 但是导出到yapi api却不是按照field在bean中的顺序, 是不是需要什么额外配置呢?

see #187  
It'll get fixed in the next version.
