### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by simonpdh** [tangcent/easy-yapi#121]
![企业微信截图_1577940855743](https://user-images.githubusercontent.com/23329416/71652296-576b1500-2d5f-11ea-9f98-1356d4caa309.png)
![image](https://user-images.githubusercontent.com/23329416/71652347-cb0d2200-2d5f-11ea-90d1-92a2c5bcec91.png)
@tangcent

**Comment by tangcent** [comment]
- 我尝试重现出来了，应该是推断中处理枚举值的问题，我晚些时候尝试修复它
- 你可以暂时关闭[返回值推断功能](http://easyyapi.com/setting/ide-setting.html)

**Comment by simonpdh** [comment]
A继承B，生成的接口文档我只想要A类下的属性，不想要B类下的属性该如何设置？

**Comment by tangcent** [comment]
> A继承B，生成的接口文档我只想要A类下的属性，不想要B类下的属性该如何设置？

目前的规则很难实现这个效果,一般是直接[忽略某些字段](http://easyyapi.com/setting/rules/json_rule_field_ignore.html),比如:
```properties
json.rule.field.ignore=groovy:it.containingClass().name()=="xxx.xxx.B"
```

**Comment by simonpdh** [comment]
> > A继承B，生成的接口文档我只想要A类下的属性，不想要B类下的属性该如何设置？
> 
> 目前的规则很难实现这个效果,一般是直接[忽略某些字段](http://easyyapi.com/setting/rules/json_rule_field_ignore.html),比如:
> 
> ```ini
> json.rule.field.ignore=groovy:it.containingClass().name()=="xxx.xxx.B"
> ```
能否实现排除某类

**Comment by tangcent** [comment]
> 能否实现排除某类

排除某类是指?

**Comment by simonpdh** [comment]
> > 能否实现排除某类
> 
> 排除某类是指?

即A继承B，把B排除，只生成A的

**Comment by tangcent** [comment]
```properties
json.rule.field.ignore=groovy:it.containingClass().name()=="xxx.xxx.B"
```
应该有用,不过导致的后果是 C继承B，也会把B排除，只生成C的

**Comment by simonpdh** [comment]
> ```ini
> json.rule.field.ignore=groovy:it.containingClass().name()=="xxx.xxx.B"
> ```
> 
> 应该有用,不过导致的后果是 C继承B，也会把B排除，只生成C的

好的，我试下，谢谢

**Comment by tangcent** [comment]
这是修复枚举解析的插件包:
[easy-yapi.1.5.1.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4016091/easy-yapi.1.5.1.0.183.0.jar.zip)
你也可以自行打包.

**Comment by simonpdh** [comment]
> 这是修复枚举解析的插件包:
> [easy-yapi.1.5.1.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4016091/easy-yapi.1.5.1.0.183.0.jar.zip)
> 你也可以自行打包.

好的，做完试了下忽略某类的，发现没有用json.rule.field.ignore=groovy:it.containingClass().name()=="具体类路径"

**Comment by tangcent** [comment]
- 有没有加载到你的配置的日志
```
[TRACE]	find config file:xxxxxxxxx
```

- 我试了下，可以

***IgnoredFields.java***

```java
package com.itangcent.common.dto;

public class IgnoredFields {
    private String field1;
    private String field2;

    public String getField1() {
        return field1;
    }

    public void setField1(String field1) {
        this.field1 = field1;
    }

    public String getField2() {
        return field2;
    }

    public void setField2(String field2) {
        this.field2 = field2;
    }
}

```

***UserInfo.java***

```java
package com.itangcent.common.model;

import com.itangcent.common.dto.IgnoredFields;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class UserInfo extends IgnoredFields {

    private Long id;//用户id

    /**
     * @see com.itangcent.common.constant.UserType
     */
    private int type;//用户类型

    /**
     * @mock tangcent
     */
    @NotBlank
    private String name;//用户名

    /**
     * 年龄
     *
     * @mock 1${digit}
     */
    @NotNull
    private Integer age;

    /**
     * @deprecated It's a secret
     */
    private Integer sex;

    //生日
    private LocalDate birthDay;

    //注册时间
    private LocalDateTime regtime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public LocalDate getBirthDay() {
        return birthDay;
    }

    public void setBirthDay(LocalDate birthDay) {
        this.birthDay = birthDay;
    }

    public LocalDateTime getRegtime() {
        return regtime;
    }

    public void setRegtime(LocalDateTime regtime) {
        this.regtime = regtime;
    }
}

```

***FileCtrl.java***

```java
package com.itangcent.springboot.demo.controller;

import com.itangcent.common.dto.IResult;
import com.itangcent.common.dto.Result;
import com.itangcent.common.dto.UserDto;
import com.itangcent.common.model.UserInfo;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

/**
 * 用户相关(附加文件)
 *
 * @module user
 */
@RestController
@RequestMapping(value = "file")
public class FileCtrl {
    /**
     * 增加新用户(上传头像)
     */
    @PostMapping("/add")
    public IResult add(@ModelAttribute UserDto userDto) {
        return Result.success("保存成功");
    }

    /**
     * 另一种增加新用户(上传头像)
     * 文件单独一个参数
     *
     * @undone
     */
    @PostMapping("/add2")
    public IResult add(UserInfo userInfo,
                       @RequestParam(name = "profileImg") MultipartFile profileImg) {
        return Result.success("保存成功");
    }

    /**
     * 试试上传多个头像
     *
     * @undone
     */
    @PostMapping("/add3")
    public IResult add(UserInfo userInfo,
                       @RequestParam(name = "profileImg") MultipartFile[] profileImgs) {
        return Result.success("保存成功");
    }
}
```

- 未配置时导出如下:

**Form：**

| name  |  value  | required |  type  |  desc  |
| ------------ | ------------ | ------------ | ------------ | ------------ |
| profileImg | null | NO | file | 头像 |
| id | null | NO | text | 用户id |
| type | null | NO | text | 用户类型<br>1 :管理员<br>2 :成员<br>3 :游客 |
| name | null | NO | text | 用户名 |
| age | null | YES | text | 年龄 |
| sex | null | NO | text | 「已废弃」It's a secret |
| birthDay | null | NO | text | 生日 |
| regtime | null | NO | text | 注册时间 |
| field1 | null | NO | text |  |
| field2 | null | NO | text |  |

- 配置后导出如下:

**Form：**

| name  |  value  | required |  type  |  desc  |
| ------------ | ------------ | ------------ | ------------ | ------------ |
| profileImg | null | NO | file | 头像 |
| id | null | NO | text | 用户id |
| type | null | NO | text | 用户类型<br>1 :管理员<br>2 :成员<br>3 :游客 |
| name | null | NO | text | 用户名 |
| age | null | YES | text | 年龄 |
| sex | null | NO | text | 「已废弃」It's a secret |
| birthDay | null | NO | text | 生日 |
| regtime | null | NO | text | 注册时间 |


- 配置是这样的:

```properties
json.rule.field.ignore=groovy:it.containingClass().name()=="com.itangcent.common.dto.IgnoredFields"
```

**Comment by simonpdh** [comment]
好的，谢谢，可以了
