### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by Derek-FFFFF** [tangcent/easy-yapi#125]
在获取项目信息的时候需要传入id参数，YApi的文档中没有写，但是实际调用需要传入项目id。导致出现Invalid Token

**Comment by tangcent** [comment]
- see https://hellosean1025.github.io/yapi/openapi.html
- 可能是你的`yapi`版本太低了
- see https://github.com/tangcent/easy-yapi/issues/100

**Comment by Derek-FFFFF** [comment]
谢谢
