### ISSUE TITLE
post 参数继承问题

### ISSUE THREAD

**Issue by yongchongwu** [tangcent/easy-yapi#126]
post 参数继承问题

**Comment by tangcent** [comment]
***usages like this:***
- model: https://github.com/Earth-1610/spring-demo/blob/master/cn/common/src/main/java/com/itangcent/common/dto/UserDto.java
- api: https://github.com/Earth-1610/spring-demo/blob/4a5c1bfbe32cf1c1c8b1b4853427b0506c88b6aa/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/FileCtrl.java#L18-L24

**Comment by yongchongwu** [comment]
@RequestBody 接收参数时，继承父类，生成文档没有父类的参数

**Comment by tangcent** [comment]
- see https://github.com/Earth-1610/spring-demo/blob/4a5c1bfbe32cf1c1c8b1b4853427b0506c88b6aa/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/TestJsonCtrl.java#L41-L48
- body参数的类型是`TestLogBean`，继承了`TestJsonFieldBean`, 导出的结果中有`TestJsonFieldBean`中的字段`a`和`b`.

- 导出结果如下:
---
### 测试transient字段忽略

<a id=测试transient字段忽略> </a>

#### BASIC

**Path：** /demo/test/json/ignore/transient

**Method：** POST

**Desc：**

<p>测试transient字段忽略</p>

#### REQUEST


**Headers：**

| name  |  value  |  required | example  | desc  |
| ------------ | ------------ | ------------ | ------------ | ------------ |
| Content-Type | application/json | YES |  |  |
| token |  | YES |  | 认证Token |

**RequestBody**

| name  |  type  |  desc  |
| ------------ | ------------ | ------------ |
| a | integer |  |
| b | integer |  |

**Request Demo：**

```json
{
  "a": 0,
  "b": 0
}
```


#### RESPONSE

**Header：**

| name  |  value  |  required | example  | desc  |
| ------------ | ------------ | ------------ | ------------ | ------------ |
| content-type | application/json;charset=UTF-8 | NO |  |  |

**Body：**

| name  |  type  |  desc  |
| ------------ | ------------ | ------------ |
| a | integer |  |
| b | integer |  |

**Response Demo：**

```json
{
  "a": 0,
  "b": 0
}
```

---

- 可能的原因是你的父类中的字段是`public`？
