### ISSUE TITLE
NotBlank注解不起作用

### ISSUE THREAD

**Issue by yongchongwu** [tangcent/easy-yapi#127]
#[javax.validation]
#Support for javax.validation annotations
param.required=@javax.validation.constraints.NotBlank
field.required=@"javax.validation.constraints.NotBlank
param.required=@"javax.validation.constraints.NotNull
field.required=@javax.validation.constraints.NotNull
param.required=@javax.validation.constraints.NotEmpty
field.required=@javax.validation.constraints.NotEmpty

因为field.required=@"javax.validation.constraints.NotBlank多了个双引号"

**Comment by yongchongwu** [comment]
field.required=@"javax.validation.constraints.NotBlank
param.required=@"javax.validation.constraints.NotNull

**Comment by yongchongwu** [comment]
多了双引号，

**Comment by tangcent** [comment]
- 你是对的~这里写错了

**Comment by tangcent** [comment]
你可以使用本地配置,也可以下载[easy-yapi.1.5.2.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4053542/easy-yapi.1.5.2.0.183.0.jar.zip),以支持NotBlank.
