### ISSUE TITLE
上传API报错

### ISSUE THREAD

**Issue by ChenYilei2016** [tangcent/easy-yapi#129]
**config中配置了:**
java.to.js.type=(function(type){type = type.replace("ja:va.lang.","");return type.replace(type[0],type[0].toLowerCase());})
doc.param=js:"\n类型:"+${java.to.js.type}(it.type().name());

**上传API时:** 
[ERROR]	unsupported script type:JavaScript,script:"类型:"+it.type().name();
[ERROR]	unsupported script type:JavaScript,script:"类型:"+it.type().name();
[ERROR]	unsupported script type:JavaScript,script:"类型:"+it.type().name();
[ERROR]	unsupported script type:JavaScript,script:"类型:"+it.type().name();

以前上传没问题的,  现在上传带不了参数类型了...

我昨天升级了 IDEA 2019.3.2 和最新easyyapi插件 , 后就出现了这样的问题~~

**Comment by tangcent** [comment]
这个`unsupported script type:JavaScript`是`JDK`问题，`IDEA`高版本默认的`JDK`中没有提供`js`引擎

***尝试将规则引擎切换成`groovy`***
写法大概是这样:
```
java.to.js.type=def uncapitalize = { type -> type = type.replace("java.lang.",""); type[0].toLowerCase()+type[1..-1] }
doc.param=groovy:${java.to.js.type};"类型:"+uncapitalize.call(it.type().name())
```

---

- 虽然不建议,但是你也可以尝试修改`IDEA`使用的`JDK`

**Comment by ChenYilei2016** [comment]
ok~~ 这个有点坑, 突然用不了
