### ISSUE TITLE
可以生成返回参数的json串在下面吗？

### ISSUE THREAD

**Issue by qinkangdeid** [tangcent/easy-yapi#130]
现在的生成是一个表格 可以再生成返回参数的json串在下面吗？前端是想要json串转成对象方便些
![image](https://user-images.githubusercontent.com/17582522/74237867-76ba7200-4d0f-11ea-9a7d-6cf25a2632b0.png)

**Comment by tangcent** [comment]
- 我最近在尝试赋能脚本更多可用的工具，完成之后，应该能满足你的需求
- 受限于老家网络情况,还需要几天

**Comment by tangcent** [comment]
- [releases v1.6.0.0](https://github.com/tangcent/easy-yapi/releases/tag/v1.6.0.0)
- 配置大致如此:
```properties
doc.method=groovy:"return:\n```json\n"+it.returnJson(true,true)+"\n```\n"
```

**Comment by qinkangdeid** [comment]
多谢🙏 我马上试试

**Comment by qinkangdeid** [comment]
生成了 不过备注哪里没法 解析 markdown语法
![image](https://user-images.githubusercontent.com/17582522/74351937-bf972700-4df2-11ea-932f-8a2672054d0a.png)

**Comment by qinkangdeid** [comment]
好像是 yapi版本（1.7.0）的问题 我点一次编辑-保存 在看就可以了
![image](https://user-images.githubusercontent.com/17582522/74352256-2f0d1680-4df3-11ea-9902-6a3edfcefe5d.png)

**Comment by tangcent** [comment]
- 有点麻烦，`yapi`的前面的渲染不是即时的,是保存的时候前端js渲染的
https://github.com/YMFE/yapi/blob/c3da40228a99d637246ce8ead8612851b81e814d/client/containers/Project/Interface/InterfaceList/InterfaceEditForm.js#L237-L238
- 我稍晚些时候找找看，如何渲染能达到与`yapi`一致的效果.

**Comment by qinkangdeid** [comment]
之前文档没部到ydoc记得有一个groovy取值对照表 罗列了一些取值方法 现在找不到了😭
如果我要增加 `接口是json传参的` 参数json串也像返回参数一样列出来在备注 是取那个方法？

使用 `json-schema` 表格展示参数 是不是为了方便mock？
如果用`json5` 直接将注释写在后面
```json
{
"name":"dasd" // 名称
}
```

**Comment by tangcent** [comment]
- http://easyyapi.com/setting/config-rule.html
- 列出备注这个现在应该做不到
https://github.com/tangcent/easy-yapi/blob/4228ca1199626ee0e89857d986c0bf8550fed5bf/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/ScriptRuleParser.kt#L276-L280
https://github.com/tangcent/easy-yapi/blob/4228ca1199626ee0e89857d986c0bf8550fed5bf/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/rule/ScriptRuleParser.kt#L418-L429
各个`toJson`的方法，我都没开放`JsonOption.READ_COMMENT`,而且得到的结果和`json5`还有点区别，可能还需要给出转`json5`的工具.

---

提供了`Debug`: <kbd>Code</kbd> > <kbd>Debug</kbd>, 可以做简单的调试
![image](https://user-images.githubusercontent.com/17569144/74400259-61049400-4e58-11ea-8513-c6cd64073e7b.png)

- 调试功能和提供的工具这块还需要几次小迭代，目标期望是简单的需求开发者都可以通过简单配置来完成

**Comment by tangcent** [comment]
现在的问题是`yapi`里的备注渲染是前端js渲染出来的.所以大方面来说有两个方法:
1.写yapi插件，在更新接口时尝试渲染备注
2.easy-yapi上传接口前，自行渲染

`markdown`的语法是一致的，但`html`样式各有不同.不同的编辑器,不同的渲染包渲染出来的`html`都各有各的规则和`css`.

---

目前尝试的一个解决方案是从`tui.editor`中提取相关代码，以维持与`yapi`渲染效果一致.

`yapi`备注渲染方案: https://github.com/tangcent/easy-yapi/commit/64474a7afaf50c7d5d4736777ea1ec9b018c3ed5

打包的插件:[easy-yapi.1.6.0.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4230453/easy-yapi.1.6.0.0.183.0.jar.zip)

clone [yapi-markdown-render](https://github.com/easyyapi/yapi-markdown-render)
按照[README.md](https://github.com/easyyapi/yapi-markdown-render/blob/master/README.md)操作.

---

考虑内置一个可选的简单的渲染,但是要和`yapi`渲染效果一致很难做到.
但考虑到目前需要渲染的情况不多,大部分开发者应该用不到.
so. 后续再视情况增加或者优化渲染途径.

**Comment by qinkangdeid** [comment]
这应该算是yapi的局限吧 看到接口编辑界面里没有请求示例一栏 
 就是想像swagger或其他API管理工具那种 
使用json做前后端传输数据方式的话 有参数的表格说明和参数的json示例串 前端除了想要字段说明 还想方便的拿json串转换出实体对象😂返回也是一个意思  有的话 easyyapi+yapi一起就非常完善了 😄
 你这个插件非常的方便了 也规范了代码的注释（因为不想手写文档 就得写好注释😄）
![image](https://user-images.githubusercontent.com/17582522/75041644-f6a6c000-54f7-11ea-96b3-90ec32e151fc.png)

**Comment by qinkangdeid** [comment]
配了那个渲染  出来的是格式化好的了  很nice💗前端确实不懂 只会照做😂 @RequestBody 参数也是这样配置的吧
![image](https://user-images.githubusercontent.com/17582522/75044408-8e0e1200-54fc-11ea-9c69-c31c859b10f3.png)

**Comment by tangcent** [comment]
类似,配置大概是这样:
```properties
doc.method=groovy: for(arg in it.args()){ if(arg.hasAnn("org.springframework.web.bind.annotation.RequestBody")) return "request:\n```json\n" + arg.type().toJson(true) +"\n```\n" }
```

---

脚本书写困难，可以尝试用<kbd>Code</kbd> > <kbd>Debug</kbd>

**Comment by qinkangdeid** [comment]
谢谢🙏 已经可以了

**Comment by tangcent** [comment]
[easy-yapi.1.6.0.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4241304/easy-yapi.1.6.0.0.183.0.jar.zip)

试了下走`http`请求`node`渲染来达到一样的效果:
http://easyyapi.com/documents/yapi_render.html

---

目前测试来看正常使用的情况下[yapi-markdown-render](https://github.com/easyyapi/yapi-markdown-render)对资源消耗有限,随便找台服务器部署都够一个小团队的人使用.

**Comment by qinkangdeid** [comment]
## IDEA版本
- 2020.2

## yapi版本

- 版本: 1.9.2

## easy-yapi版本

- 2.0.3.0.183.0

yapi版本升级到1.9.2后 渲染md文件好像不起作用了 还是需要点击编辑一次api再保存才有效的显示出备注的md内容 Yapi Render 使用最新clone下来的本地渲染
![image](https://user-images.githubusercontent.com/17582522/94403815-8ef8d780-01a0-11eb-8623-e0582bcabf6f.png)

**Comment by tangcent** [comment]
我这边测试本地渲染和远程渲染都是ok的~
你要不试试远程渲染看看?
