### ISSUE TITLE
是否支持Json字段由驼峰变为下划线

### ISSUE THREAD

**Issue by gcdd1993** [tangcent/easy-yapi#140]
**描述**
由于Jackson使用了全局配置`FEATURE_PROPERTIES_NAMING_STRATEGY=SNAKE_CASE`，所以`RequestBody`和`ResponseBody`在序列化为Json时，都会相应的由驼峰转为下划线。

我查询了EasyYApi的配置文档，没有找到如何能满足我需求（由驼峰转为下划线）的方法。

请帮忙下，谢谢！

**Comment by tangcent** [comment]
`easy-yapi`尝试尽量支持更多的框架与自定义策略，所以这些字段策略没有提供相应的固定配置，一般都通过[json.rule.field.name](http://easyyapi.com/setting/rules/json_rule_field_name.html)来完成
另外`groovy`对正则的语法支持比较好，很容易书写不同的字段名转换策略.

---

你可以尝试如下配置:
```properties
json.rule.field.name=groovy: it.name().replaceAll("[A-Z]+") {it ->"_"+it[0].toLowerCase()}
```

---

[tools](http://easyyapi.com/setting/tools.html)将持续加入一些常用的工具方法.有任何想法建议，欢迎给出issue.

**Comment by gcdd1993** [comment]
@tangcent 谢谢，上述配置完美解决了我的问题。

另外，这个插件非常棒，帮助了我很多！

**Comment by tangcent** [comment]
很高兴能帮助到你
