### ISSUE TITLE
ApiDashboard加载Postman性能问题

### ISSUE THREAD

**Issue by gcdd1993** [tangcent/easy-yapi#141]
# 问题描述
在Postman里面本身已经存在的collection和api过多的时候，加载`ApiDashboard`很慢，而且很消耗CPU

![](https://i.loli.net/2020/02/24/Rt2dKA9pMF6NmhW.png)

![](https://i.loli.net/2020/02/24/C9Bxe7bjEaY2kcf.png)

到最后Idea卡死了，不得不从任务管理器删除Idea进程才能恢复。

# 期望
我不清楚`ApiDashboard`的执行逻辑，但是我猜测是否是加载本地项目的所有接口信息，然后去加载Postman的信息，期间还做了两边接口的Diff？

最后，在这部分，是否有优化的空间？

感谢！

**Comment by tangcent** [comment]
> 我不清楚`ApiDashboard`的执行逻辑

- `ApiDashboard`使用了本地缓存,但是第一次加载的时候需要扫描本地项目所有接口信息并使用`postman`的`openapi`拉取`postman`中所有的`api`。二次打开时，对于未变动的文件会直接加载缓存.

- 缓存的实现分别是`CachedRequestClassExporter`与`PostmanCachedApiHelper`.


---

- `postman`的`openapi`可能需要科学上网才能流畅访问，否则响应比较慢.另外非pro用户api有请求次数限制.

- `ApiDashBoard`的初衷主要是为了满足不愿意在代码中配置[module(分组信息)](https://easyyapi.com/setting/rules/module.html)又希望将同一个模块中的`api`导入到不同的文件夹中的需求.

---

我将找个时间`review`一下`ApiDashBoard`,考虑增加部分并发限制,减少资源消耗.

**Comment by gcdd1993** [comment]
> ApiDashboard使用了本地缓存
是的，我第二次打开，比第一次好多了，但是还是没能够等到加载完成。因为`Postman`的`OpenApi`过慢，我把`HttpTimeout`的时间调成了30s，由此造成了过多的网络等待，产生了资源的过度消耗。
