### ISSUE TITLE
使用中遇到doc.param未生效问题

### ISSUE THREAD

**Issue by cnderrick** [tangcent/easy-yapi#149]
环境：
OS => MacOS 10.15.3
IDE => IDEA 2019 3.3
插件=> EasyYApi 1.7.0.0.183.0
服务 => YApi 1.8.8
Project JDK=> Oracle JDK 1.8.0_162
项目结构 => 
<img width="424" alt="a" src="https://user-images.githubusercontent.com/6166461/75543247-53f0c300-5a5c-11ea-9514-6071698ec553.png">

.yapi.config中的内容：
```
ignore=#ignore
field.mock=#mock
api.status=#status
java.to.js.type=def uncapitalize = { type -> type = type.replace("java.lang.",""); type[0].toLowerCase()+type[1..-1] }
doc.param=groovy:${java.to.js.type};"类型:"+uncapitalize.call(it.type().name())
doc.method[#result]=groovy: it.docs("result").collect{helper.resolveLink(it)}.grep{it!=null}.collect{"可能的返回:\n\n```json\n"+it.toJson(true)+"\n```\n\n"}.join("\n")
```

代码片段：
```
    /**
     * 根据词典类型获取分页数据
     *
     * @status done
     * @param typeName
     *            字典类型，{@link DictionaryType#getMsg}
     * @param pageModel
     *            {@link PageModel}
     * @result {@link ReturnModel<NotValidResultModel>}
     * @result {@link DictionaryResponseBean}
     */
@GetMapping("/{typeName}")
public ReturnModel<PageResultModel<DictionaryResponseBean>>
        getList(@Valid @NotNull @PathVariable("typeName") String typeName, @Valid PageModel pageModel) {
    ………………
    ………………
}
```

问题： 期望在输入参数的备注中说明类型，真实效果并未出现。
参考文档：
https://easyyapi.com/setting/rules/doc_param.html
说明：官方中给出了JS和Groovy两种方式。我都尝试了。JS的提示没有引擎出错，跟你之前给出的[解答](https://github.com/tangcent/easy-yapi/issues/129)一致。使用Groovy的引擎处理后日志中并无错误，整个过程会成功，但就是看不到跟官方一样的效果。不知道我哪里不对，配置是按照官方中给出的，未做改动。

附上YApi中的截图：
![image](https://user-images.githubusercontent.com/6166461/75544012-0c6b3680-5a5e-11ea-83e1-66385e679342.png)

使用中的疑问：
Query Param的示例值和 Body Param的默认值 可以通过该工具生成么？我自己要怎么配置。

——————

感谢提供这么友好的工具！

**Comment by tangcent** [comment]
hi~,[doc.param](https://easyyapi.com/setting/rules/doc_param.html)是针对单个参数的.
例如这样的:

```java
    /**
     * 更新用户名
     *
     * @param id      用户id
     * @param newName 新的用户名
     * @param slogon  个人签名
     * @deprecated 改用{@link #update(UserInfo)}
     */
    @RequestMapping(value = "/set", method = RequestMethod.PUT)
    public Object set(long id,
                      @RequestParam String newName,
                      @RequestParam(required = false, defaultValue = "haha") String slogon,
                      @RequestParam(required = false, defaultValue = "10") long times) {

        UserInfo userInfo = new UserInfo();

        userInfo.setId(id);
        userInfo.setName(newName);
        userInfo.setAge(45);
        return Result.success(userInfo);
    }
```

对于`对象`可以考虑[doc.field](https://easyyapi.com/setting/rules/doc_field.html)

---

现在插件中提拱了[tools](https://easyyapi.com/setting/tools.html),所以可以这样配:

```porperties
doc.param=js:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.",""))
```

另外你可能需要这个: [yapi_render](https://easyyapi.com/documents/yapi_render.html)

---

> Query Param的示例值和 Body Param的默认值

目前只支持单参数的默认值[param.default.value](https://easyyapi.com/setting/rules/param_default_value.html)

关于`Query Param的示例值和 Body Param的默认值`以前开发的时候还不具备解析条件。现在有了初步的方案，可以由字段相关规则配置,可能是这样的`field.default.value`, 如果顺利的话可能可以在下个版本提供.

**Comment by tangcent** [comment]
我review了下代码，发现上传`yapi`接口中示例参数的字段名写错了.see https://github.com/tangcent/easy-yapi/pull/150

[easy-yapi.1.4.2.3.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4267279/easy-yapi.1.4.2.3.183.0.jar.zip)

**Comment by cnderrick** [comment]
> 我review了下代码，发现上传`yapi`接口中示例参数的字段名写错了.see #150
> 
> [easy-yapi.1.4.2.3.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4267279/easy-yapi.1.4.2.3.183.0.jar.zip)

我使用了指定的这个版本的插件，依然不可以。

**Comment by tangcent** [comment]
sorry~~~

PR: https://github.com/tangcent/easy-yapi/pull/151
DOC: [field_default_value](http://easyyapi.com/setting/rules/field_default_value.html)

---

[easy-yapi.1.7.0.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4270319/easy-yapi.1.7.0.0.183.0.jar.zip)

**Comment by cnderrick** [comment]
> sorry~~~
> 
> PR: #151
> DOC: [field_default_value](http://easyyapi.com/setting/rules/field_default_value.html)
> 
> [easy-yapi.1.7.0.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4270319/easy-yapi.1.7.0.0.183.0.jar.zip)

辛苦👍 

我又试了下，还是有几个问题。

代码片段如下：
```
    /**
     * 单条用字自定义词典下获取词条分页数据
     *
     * @status done
     * @param dictionaryId
     *            {@link DictionaryResponseBean#getId}
     * @param name
     *            词条名称包含关键字
     * @param pageModel
     *            {@link PageModel}
     * @result {@link ReturnModel<NotValidResultModel>}
     * @return {@link DictionaryItemResponseBean}
     */
    @GetMapping("/user/{dictionaryId}/items")
    public ReturnModel<PageResultModel<DictionaryItemResponseBean>> getItemList(
        @Valid @Positive @PathVariable("dictionaryId") Long dictionaryId, String name, @Valid PageModel pageModel) {
……
}


@Data
public class PageModel {

    public static final int DEFAULT_PAGE_NO = 1;
    public static final int DEFAULT_PAGE_SIZE = 10;
    /**
     * 页码，从1开始，默认为：1
     *
     * @default 1
     * @mock @integer(1, 10)
     */
    @Positive
    private int pageNo = DEFAULT_PAGE_NO;
    /**
     * 单页条数，默认为：10
     *
     * @default 10
     * @mock @integer(10, 20)
     */
    @Positive
    private int pageSize = DEFAULT_PAGE_SIZE;
}
```

解析出的结果：
![image](https://user-images.githubusercontent.com/6166461/75608904-b91ce500-5b3e-11ea-819c-0c3f12aa33c6.png)

可以看到：
1. 路径参数的类型加上去了；
2. Query Param中是Java基本类型的可以识别，自定义对象就无法识别属性类型；
3. Body Param因为是用@RequestBody + 自定义对象接收数据，同样也存在与第二条一样的问题。无法识别出属性类型。

@default 可以正常使用，感谢增加的功能支持。👍👍 🤝

**Comment by tangcent** [comment]
see https://github.com/tangcent/easy-yapi/issues/149#issuecomment-592503692

你这样配置的是额外的参数的注释
```properties
doc.param=js:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.",""))
```

---

也许你可以尝试`额外的字段的注释`
```properties
doc.field=js:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.",""))
```

**Comment by cnderrick** [comment]
> see [#149 (comment)](https://github.com/tangcent/easy-yapi/issues/149#issuecomment-592503692)
> 
> 你这样配置的是额外的参数的注释
> 
> ```ini
> doc.param=js:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.",""))
> ```
> 
> 也许你可以尝试`额外的字段的注释`
> 
> ```ini
> doc.field=js:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.",""))
> ```

按照你给出的方法，我对配置文件做了调整
.yapi.config  内容：
```
ignore=#ignore
field.mock=#mock
api.status=#status
doc.param=groovy:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.",""))
doc.field=groovy:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.",""))
doc.method[#result]=groovy: it.docs("result").collect{helper.resolveLink(it)}.grep{it!=null}.collect{"参数校验错误的返回:\n\n```json\n"+it.toJson(true)+"\n```\n\n"}.join("\n")
field.default.value=#default
```
目前生成的结果：
![image](https://user-images.githubusercontent.com/6166461/75610821-c9898b80-5b4f-11ea-9a87-9cd7e69bf274.png)

![image](https://user-images.githubusercontent.com/6166461/75610834-ede56800-5b4f-11ea-8972-929cf49a2790.png)

doc.field是作用在类属性上的，不区分是request还是response类。

我现在想把自己定义的枚举类的信息抹去，截图中的SkillType内容。Groovy语法不怎么会，是在按照下面类似的内容写么。感谢解答。
```
groovy:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.","").replace("com.abc.xxxx", ""))
```

**Comment by tangcent** [comment]
`Groovy`语法不熟悉的话，可以直接当`java`写，是ok的.

---

> doc.field是作用在类属性上的，不区分是request还是response类。

这一点有点麻烦，需要区分的话需要在很多地方做处理，主要还是涉及到缓存这块，暂时没有想到好的解决方案. 可能要等以后想到好的解决方案再处理吧.

---

> 我现在想把自己定义的枚举类的信息抹去，截图中的SkillType内容。Groovy语法不怎么会，是在按照下面类似的内容写么。感谢解答。

一般需要过滤的配置有两种写法:

- `key[filter]=value `
- `key=if(filter) return value`

***你这里的需求看情况处理***

- 简单的处理:

```properties
doc.field[groovy:it.type().name().startsWith("java.lang")]=groovy:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.",""))
```

- 也可以尝试自定义需要的类型

```properties
java.basic.types=["java.lang.Long","java.lang.Integer","java.lang.String"]
doc.field[groovy:${java.basic.types}.contains(it.type().name())]=groovy:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.",""))
```

- 更进一步, 自定义需要展示的类型

```properties
java.basic.types=["java.lang.Long":"long","java.lang.Integer":"int","java.lang.String":"string","java.time.LocalDate":"string"]
doc.field[groovy:${java.basic.types}.containsKey(it.type().name())]=groovy:"类型:"+${java.basic.types}[it.type().name()]
```

**Comment by cnderrick** [comment]
好的，太感谢了。
