### ISSUE TITLE
是否可以支持API中类型参数的解析

### ISSUE THREAD

**Issue by wuzhengwen2019** [tangcent/easy-yapi#153]
`@Controller
@RequestMapping(value = "protected/v1/safetyRecord")
public class TestApi extends BaseApi<SearchDTO, CreateDto, UpdateDto> {
}`

`public abstract class BaseApi<T extends Entity, CREATE, UPDATE> {
    public BaseApi() {}
	
    @RequestMapping(value = {"/{id}/read"}, method = {RequestMethod.POST, RequestMethod.GET})
    @ResponseBody
    public Object read(@PathVariable Serializable id) {
        
    }

    @RequestMapping(value = {"/create"}, method = {RequestMethod.POST})
    @ResponseBody
    public Object create(@RequestBody @Valid CREATE obj) {
        
    }

    @RequestMapping(value = {"/{id}/remove"}, method = {RequestMethod.POST, RequestMethod.GET})
    @ResponseBody
    public Object remove(@PathVariable Serializable id) {
        
    }

    @RequestMapping(value = {"/search"}, method = {RequestMethod.POST})
    @ResponseBody
    public Object search(@RequestBody @Valid PageSearch pageRequest) {
        
    }

    @RequestMapping(value = {"/{id}/update"}, method = {RequestMethod.POST})
    @ResponseBody
    public Object update(@PathVariable Serializable id, @Valid @RequestBody UPDATE obj) {
     
    }
}`

**Comment by tangcent** [comment]
- 这一点没有考虑到
- 目前解析过程中没有传递当前类相关信息，这导致解析解析方法时无法获取继承类上的泛型类型.

**Comment by wuzhengwen2019** [comment]
> * 这一点没有考虑到
> * 目前解析过程中没有传递当前类相关信息，这导致解析解析方法时无法获取继承类上的泛型类型.

请问后续是否会支持

**Comment by tangcent** [comment]
> 请问后续是否会支持

WIP.

**Comment by tangcent** [comment]
- see #154

- 目前还需要一段时间来测试.但如果你需要的话，可以尝试使用.

---

[easy-yapi.1.7.0.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4306996/easy-yapi.1.7.0.0.183.0.jar.zip)

**Comment by tangcent** [comment]
see [v1.8.0.0](https://github.com/tangcent/easy-yapi/releases/tag/v1.8.0.0)
