### ISSUE TITLE
导出为Markdown时，将boolean解析成为了object类型

### ISSUE THREAD

**Issue by jelipo** [tangcent/easy-yapi#157]
![image](https://user-images.githubusercontent.com/16136814/76498202-66fd8d00-6477-11ea-946e-074d64c363e6.png)
![image](https://user-images.githubusercontent.com/16136814/76498234-7381e580-6477-11ea-8a16-3b5082dd4fa1.png)

**Comment by tangcent** [comment]
WIP.
