### ISSUE TITLE
是否可以支持 Url Template，如 @GetMapping(params = "username")，@GetMapping(params = "name")

### ISSUE THREAD

**Issue by batizhao** [tangcent/easy-yapi#160]
业务接口如下 @RequestMapping("user")

接口一：根据用户名查询用户
```java
@ApiOperation(value = "根据用户名查询用户")
@GetMapping(params = "username")
public ResponseInfo<UserVO> findByUsername(@ApiParam(value = "用户名", required = true) @RequestParam String username) 
```

接口二：根据姓名查询用户
```java
@ApiOperation(value = "根据姓名查询用户")
@GetMapping(params = "name")
public ResponseInfo<List<UserVO>> findByName(@ApiParam(value = "用户姓名", required = true) @RequestParam("name") String name) 
```

Swagger 可以通过 Docket.build().enableUrlTemplating(true) 打开这个特性。
导入到 Yapi 以后是可以正常使用的。

<img width="488" alt="截屏2020-03-16下午1 03 07" src="https://user-images.githubusercontent.com/431816/76724608-81d94580-6786-11ea-8ef5-c236d554b27d.png">

因为目前已经使用 EasyApi 来单向同步接口，不再使用 swagger。
那么，EasyApi 是否可以支持这个特性呢？谢谢！

**Comment by tangcent** [comment]
- wow,由于`yapi`不允许同路径`api`,所以没考虑解析`params`信息.
- 如图所示的解决方案应该可行:
```
@GetMapping(path="xxx",params = "yyy")
```
解析为`xxx{?yyy}`

- 如有其它需要补充的，回复此`issue`

---

另外:[swagger support](http://easyyapi.com/framwork/swagger.html)

**Comment by batizhao** [comment]
您好！感谢回复。

* `Yapi` 本身应该是支持 `/user/{?name}` 和 `/user/{?username}` 这种方式的，因为从 swagger 导入时，可以实现。
* `Swagger` 本身默认也不支持，需要在配置中 `enableUrlTemplating(true)`

假设根路径是：

```java
@RequestMapping("user")
public class UserController
```

您的回复理解没错的话应该是这样，两个 url 分别是（path 不一样）：

* `@GetMapping(path="username", params = "username")` 
localhost/user/username?username=zhangsan 
* `@GetMapping(path="name", params = "name")` 
localhost/user/name?name=tom

那肯定是没问题的。

但我的需求是（path 一样，感觉这样更优雅）：

* `@GetMapping(params = "username")`
localhost/user?username=zhangsan
* `@GetMapping(params = "name")`
localhost/user?name=tom

**是否可以考虑支持这种方式呢？**

---

另，你链接中提到的 Swagger 配置中

* `doc.class=@io.swagger.annotations.Api#value` 无效
* 您链接的文档中少了一个 `field.required=@io.swagger.annotations.ApiModelProperty#required`

在我的实践中，综合考虑了 Swagger 和 Yapi，我把其中三个配置去掉了（用 javadoc 解析）
```
#doc.param=@io.swagger.annotations.ApiParam#value
#doc.class=@io.swagger.annotations.Api#value
#doc.method=@io.swagger.annotations.ApiOperation#value

doc.param=groovy:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.",""))
method.return.main[groovy:it.returnType().isExtend("ResponseInfo")]=data
```

**Comment by tangcent** [comment]
看起来似乎可行, 我稍晚些时候尝试一下.

**Comment by tangcent** [comment]
在<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>yapi</kbd> 增加了`enableUrlTemplating`

---

[easy-yapi.1.8.0.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4351861/easy-yapi.1.8.0.0.183.0.jar.zip)

**Comment by batizhao** [comment]
Good job. 这个问题已经解决了。
另外，Issues #165 HttpHeaders.AUTHORIZATION 也已经可以正常识别。

但是，发现了一个新的问题，原来是不存在的。

#为内部调用增加一个 request header 属性
```
method.additional.header[@me.common.security.annotation.Inner]={name: "from",value: "",desc: "内部还是外部调用",required:true, example:"Y"}

@ApiOperation(value = "根据用户名查询用户及其角色")
@GetMapping
@Inner
public ResponseInfo<UserVO> loadUserByUsername
```

这个不起作用了，我又换回了 market 里的公开版本。

**Comment by tangcent** [comment]
先试试 https://github.com/tangcent/easy-yapi/releases/tag/v1.9.0.0

看看是不是合并分支的时候出现的问题.

**Comment by tangcent** [comment]
https://github.com/tangcent/easy-yapi/releases/tag/v1.9.0.0

**Comment by batizhao** [comment]
确认 v1.9.0.0 也有这个 Bug。

**Comment by tangcent** [comment]
> 确认 v1.9.0.0 也有这个 Bug。

是这个吗? https://github.com/tangcent/easy-yapi/releases/download/v1.9.0.0/easy-yapi.1.9.0.0.183.0-patch-1.jar
我测试了下，这个是OK的.
这个bug修复的commit是这个: https://github.com/tangcent/easy-yapi/commit/7594ec5977a0e3043a0911d9138c241d6f9602aa

**Comment by batizhao** [comment]
patch-1 解决了这个 bug。

LOL

**Comment by tangcent** [comment]
hi~
`1.9.0.0`已经发布完成, `patch-1`存在一个可能的兼容问题, 最好可以从官方market下载:https://plugins.jetbrains.com/plugin/12458-easyyapi/update/81583

**Comment by batizhao** [comment]
@tangcent 今天更新了一下v1.9.5.0，发现又出现这个问题了。
yapi 1.9.2

**Comment by tangcent** [comment]
hi~，是哪个功能出问题了呀?

**Comment by batizhao** [comment]
@tangcent

v1.9.5.0
```
/user/username/{username} 
/user/name/{name}
```

v1.9.0.0 修复过这个问题
```
/user?username={username} 
/user?name={name}
```

**Comment by tangcent** [comment]
抱歉，发现了是 https://github.com/tangcent/easy-yapi/pull/181/files 的问题.
我会尽早修复它.

**Comment by tangcent** [comment]
see https://github.com/tangcent/easy-yapi/pull/200

[easy-yapi.1.9.5.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4846501/easy-yapi.1.9.5.0.183.0.jar.zip)

---

抱歉，一个人精力有限，我还在寻找可能的自动化测试方案.o(╥﹏╥)o

**Comment by batizhao** [comment]
更新之后，应该是修复了。
