### ISSUE TITLE
GET方法生成的接口信息中含有错误Content-Type信息

### ISSUE THREAD

**Issue by cnderrick** [tangcent/easy-yapi#161]
**Describe the bug**
使用EasyYApi插件生成GET接口信息中包含有Headers内容。可以编写接口代码时未定义Content-Type。生成的Content-Type 为 application/x-www-form-urlencoded。

**To Reproduce**
1. 选择GET接口，使用快捷键显示弹出框
2. 在弹出框中勾选并接口
3. 确认执行
4. 登录YApi查看，即可看到错误信息

**Expected behavior**
Get方法在未声明Headers，YApi接口中应该没有Headers内容。一般GET方法也不会用该Content-Type

**Screenshots**
![image](https://user-images.githubusercontent.com/6166461/76817901-2323d280-683f-11ea-845e-5d75700d84f8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - EasyYapi: [手动打出的easy-yapi.1.7.0.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/issues/149)
 - YApi: 1.8.9

**Additional context**
推测问题在生成时，默认使用了 Content-Type为 application/x-www-form-urlencoded。

**Comment by tangcent** [comment]
Yes.

**Comment by tangcent** [comment]
fixed by https://github.com/tangcent/easy-api/pull/258 & #164 

---

[easy-yapi.1.8.0.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4351861/easy-yapi.1.8.0.0.183.0.jar.zip)

**Comment by cnderrick** [comment]
Great！👍👍
