### ISSUE TITLE
关于 @RequestHeader 的识别问题

### ISSUE THREAD

**Issue by batizhao** [tangcent/easy-yapi#165]
目前关于 @RequestHeader 应该是有两种方式：

1、在 config 中增加配置【指定或者排除】某个注解
`method.additional.header[@me.xxx.annotation.Inner]={name: "from",value: "",desc: "内部还是外部调用",required:true, example:"Y"}`

这种方式适合 RequestHeader 隐式传递的场景，非常好用。

2、在代码中通过 param 提取
```java
/**
 * 我是谁
 * 从认证信息中提取当前用户
 *
 * @param authHeader Bearer Access Token
 * @return 用户名
*/
@ApiOperation(value = "我是谁")
@GetMapping("/whoiam")
public ResponseInfo<String> getCurrentUser(@RequestHeader(name = HttpHeaders.AUTHORIZATION) String authHeader){
    log.info("authHeader: {}", authHeader);
    String access_token = authHeader.substring("Bearer ".length());
}
```

在这种情况下的问题是，HttpHeaders.AUTHORIZATION 会被直接带进“参数名称”，而我期望的参数名称是"Authorization"这个字符串，这个有办法解析吗？

<img width="872" alt="截屏2020-03-19下午1 35 28" src="https://user-images.githubusercontent.com/431816/77036365-f102a400-69e9-11ea-87f2-2e9b7e723ffd.png">

谢谢！

**Comment by batizhao** [comment]
这个问题我又试了下，实际情况调用方必须要传递 Authorization，所以 authHeader 是不需要再传递了，那有没有办法在 Yapi 中不显示这个参数呢？

**Comment by batizhao** [comment]
刚看到这个 Issues #76 ，使用了以下配置解决了。

```
param.ignore[@org.springframework.web.bind.annotation.RequestHeader]=groovy:it.ann("org.springframework.web.bind.annotation.RequestHeader","name") == "HttpHeaders.AUTHORIZATION"
param.ignore[@org.springframework.web.bind.annotation.RequestHeader]=groovy:it.ann("org.springframework.web.bind.annotation.RequestHeader","value") == "HttpHeaders.AUTHORIZATION"
```

不过发现要去掉 `param.ignore=@io.swagger.annotations.ApiParam#hidden` 才能起作用。

**Comment by tangcent** [comment]
`HttpHeaders.AUTHORIZATION`这个应该被识别.
这里应该是底层处理问题.

---

请保持这个`issue`open,我将在稍晚时候通过PR关闭.

我临时打包了一下,你可以尝试使用一下:
[easy-yapi.1.8.0.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4353127/easy-yapi.1.8.0.0.183.0.jar.zip)

---

> 不过发现要去掉 param.ignore=@io.swagger.annotations.ApiParam#hidden 才能起作用。

这个问题我稍晚时候再看看.
