### ISSUE TITLE
希望支持下@Length注解。还有Long类型，上传后都是Integer

### ISSUE THREAD

**Issue by Liesport758** [tangcent/easy-yapi#166]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tangcent** [comment]
> 希望支持下@Length注解

- 可以自行参考:http://easyyapi.com/setting/rules/field_mock.html
- 有时间我会继续补充到文档中.

> 还有Long类型，上传后都是Integer

- 这个是`js`中的类型:
![image](https://user-images.githubusercontent.com/17569144/77147912-5b3e4600-6ac9-11ea-80f8-c3954d04d465.png)
- 如果需要注释出java类型, 可以参考配置:https://github.com/tangcent/easy-yapi/issues/149#issuecomment-592954949

**Comment by Liesport758** [comment]
谢谢。我用以下实现了
`  java.basic.types2=["java.lang.String":"string"]
  doc.field[groovy:${java.basic.types2}.containsKey(it.type().name())&& it.hasAnn("org.hibernate.validator.constraints.Length")]=groovy:",长度:"+it.ann("org.hibernate.validator.constraints.Length","min")+"到"+it.ann("org.hibernate.validator.constraints.Length","max")
`
