### ISSUE TITLE
yapi多模块下,如果为每个模块配置token

### ISSUE THREAD

**Issue by w420372197** [tangcent/easy-yapi#168]

**Comment by tangcent** [comment]
see http://easyyapi.com/setting/rules/module.html

默认推荐配置中有
```properties
module=#module
```
如果代码项目中一个模块多个类希望分配到不同的`yapi`模块的话可以在每个API类中声明当前API所属模块.
```java
/**
* Mock Apis
*
* @module mock
*/
@RestController
@RequestMapping(value = "mock")
public class MockCtrl {
}
```

---

配置很自由,你甚至可以直接配置
```properties
module=test_module_name
```

**Comment by w420372197** [comment]
但是另为一个模块是不同的token,如何配置

**Comment by w420372197** [comment]
没有模块的url也是不同的

**Comment by tangcent** [comment]
> 但是另外一个模块是不同的token,如何配置

see http://easyyapi.com/setting/yapi.html

token不建议手动配置，只需要规划好module,每个module对应yapi中的一个项目
直接尝试导出api,如果module没有配置过token,会弹窗让开发者输入.

**Comment by w420372197** [comment]
懂了,每个模块都会要输入token,第二次会根据模块自动找对yapi上对应的模块

**Comment by tangcent** [comment]
> 懂了,每个模块都会要输入token,第二次会根据模块自动找对yapi上对应的模块

perfect!
