### ISSUE TITLE
spring里的ResponseEntity返回无效啊,没有返回参数

### ISSUE THREAD

**Issue by tutuerhao** [tangcent/easy-yapi#17]
![image](https://user-images.githubusercontent.com/29938085/59590254-36720800-911e-11e9-8130-fe70621303fa.png)
![image](https://user-images.githubusercontent.com/29938085/59590227-28bc8280-911e-11e9-9312-541062dbe89e.png)

这种该怎么处理呢

**Comment by tangcent** [comment]
Hi~
很抱歉没有考虑到使用org.springframework.http.HttpEntity/org.springframework.http.ResponseEntity返回响应。
我会尽快修复它。

**Comment by tangcent** [comment]
- https://github.com/tangcent/easy-yapi-plugins/raw/master/idea/easy-yapi.0.7.1.1.jar

**Comment by tutuerhao** [comment]
@tangcent 老哥支持了ResponseEntity吗

**Comment by tangcent** [comment]
Hi~,更新最新的插件试试吧
我在demo里写了这样的Controller:

https://github.com/tangcent/spring-demo/blob/master/springboot-demo/src/main/java/com/itangcent/springboot/demo/cn/controller/EntityCtrl.java

导出结果如下:
![image](https://user-images.githubusercontent.com/17569144/59647687-b647b300-91ae-11e9-90f3-fb9ebd3250ca.png)

如果你还是导不出来，可以尝试写份测试代码到[demo](https://github.com/tangcent/spring-demo)里，
我会在空闲时处理。

**Comment by tutuerhao** [comment]
@tangcent 好的,谢谢老哥,可以啦
