### ISSUE TITLE
@RequestBody String类型问题

### ISSUE THREAD

**Issue by mfd2033** [tangcent/easy-yapi#172]
```java
/**
* @param name 新名称
*/
public void rename(@RequestBody String name) {}
```
同步后name“是否必须”显示的是“非必须”，不是应该显示“必须”吗？备注也没有显示“新名称”
![image](https://user-images.githubusercontent.com/6327826/79880325-71218c80-8422-11ea-992d-8399638c2ce6.png)

**Comment by tangcent** [comment]
> 备注也没有显示“新名称”

- 这里的备注丢失是没考虑到简单类型的`RequestBody `.

---
> 同步后name“是否必须”显示的是“非必须”，不是应该显示“必须”吗？

- 为何这里应该显示`必须`?

**Comment by liucaidong** [comment]
BUG依然存在，我用的是 1.9.5.0.183.0 版本，IDE是IDEA，导出的结果跟楼主的一样，无法识别String类型的变量

**Comment by liucaidong** [comment]
@tangcent

**Comment by tangcent** [comment]
> 无法识别String类型的变量

无法识别是指?

我测试尝试给出如下api:

```java
    /**
     * 测试RequestBody
     *
     * @param body body内容
     */
    @RequestMapping("/body")
    public String bodyString(
            @RequestBody String body) {
        return body;
    }
```

导出结果如下:

![image](https://user-images.githubusercontent.com/17569144/86463464-24322e80-bd60-11ea-95d4-a8425887738a.png)

**Comment by liucaidong** [comment]
@tangcent 无法识别名称，就是红框的这里是空白，应该是字段的名称

**Comment by tangcent** [comment]
关于这一点，你可以在yapi中试试.
![image](https://user-images.githubusercontent.com/17569144/86510751-1692ac80-be25-11ea-9e00-dc93b8e77e81.png)
选择string后，是没有办法填充名称的.

**Comment by liucaidong** [comment]
> 关于这一点，你可以在yapi中试试.
> ![image](https://user-images.githubusercontent.com/17569144/86510751-1692ac80-be25-11ea-9e00-dc93b8e77e81.png)
> 选择string后，是没有办法填充名称的.

收到，了解了，看来是我理解错了，多谢！！！
