### ISSUE TITLE
如何设置开放接口

### ISSUE THREAD

**Issue by Songzhizong** [tangcent/easy-yapi#178]
我希望将部分接口设置为开放接口，以备导出api文档时只导出公开接口。

**Comment by tangcent** [comment]
- 目前没有支持，默认全部是不开放的.

**Comment by tangcent** [comment]
Patch with #179: [easy-yapi.1.9.3.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4557623/easy-yapi.1.9.3.0.183.0.jar.zip)
Download and unzip it. [Install](https://easyyapi.com/documents/installation.html) to IDEA.

---

- 尝试配置:
```properties
api.open=#open
api.tag[#open]=open
```

- 在api上注释`@open`
```java
    /**
     * 更新用户信息
     *
     * @open
     */
    @PostMapping("update")
    public IResult update(UserInfo userInfo) {
        return Result.success(userInfo);
    }
```

- yapi:

![image](https://user-images.githubusercontent.com/17569144/80699546-ba529a00-8b0e-11ea-9765-71f5aa47d4b6.png)

---

Visit https://easyyapi.com to get more.

**Comment by tangcent** [comment]
PS:
我现在很难确认这个需求是否普遍.
为性能考虑，暂时不会加入到[默认推荐配置](https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/main/resources/.recommend.easy.api.config)当中.

**Comment by tangcent** [comment]
see http://easyyapi.com/setting/rules/api_open.html
