### ISSUE TITLE
class.prefix.path配置无效

### ISSUE THREAD

**Issue by ciweigg2** [tangcent/easy-yapi#184]
class.prefix.path=固定值 可以
class.prefix.path=${server.servlet.context-path} 不可以
[ERROR]	unable to resolve property:server.servlet.context-path
按照文档设置了server.servlet.context-path
依然无法获取

**Comment by tangcent** [comment]
> class.prefix.path=${server.servlet.context-path}

`server.servlet.context-path`的值怎么给的?
配置解析是顺序的，需要把引用的配置写在前面.

**Comment by ciweigg2** [comment]
![image](https://user-images.githubusercontent.com/41536971/81368276-f34bc980-9121-11ea-98cc-139a03cce9a7.png)
![image](https://user-images.githubusercontent.com/41536971/81368297-0199e580-9122-11ea-8247-b0a5c977f2e0.png)
还是不行

**Comment by ciweigg2** [comment]
我不确定你能不能看到图
我把他卸载.easy.api.config最前面了
application.properties也配置了还是取不到

**Comment by tangcent** [comment]
确认下:
![image](https://user-images.githubusercontent.com/17569144/81371034-52f9a300-9129-11ea-9a3e-9e9ac9e7a68f.png)
是否有勾选？

---

see https://github.com/Earth-1610/spring-demo/blob/master/cn/springboot-demo/src/main/resources/application.properties

我测试这个是可以的.

**Comment by ciweigg2** [comment]
不行啊 是否有联系方式我给你复现下 我和你描述的操作完全一致

**Comment by tangcent** [comment]
wechat itangcent

**Comment by lizhenjuan** [comment]
我也是同样的配置，class.prefix.path=/st，
 并且也勾选了 resove_spring_properties ，还是未起作用

**Comment by tangcent** [comment]
@lizhenjuan 
<img width="714" alt="image" src="https://github.com/tangcent/easy-yapi/assets/17569144/c0bb9c9b-1901-47b9-a80b-2a834af6127b">
