### ISSUE TITLE
请问可以考虑兼容下@NotNull @NotBlank @NotEmpty 等注解的group属性吗? 这样的话就可以对field做分组校验了

### ISSUE THREAD

**Issue by NowBro** [tangcent/easy-yapi#185]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tangcent** [comment]
考虑过,但一直没想到好的解决方案.

我希望找到一个实现,可以支持不同的校验框架, 所以想的有点复杂, 现在想想, 却是我执着了.

现在有了些许思路,过两天试试.

**Comment by NowBro** [comment]
非常感谢提供这么好的工具, 为大家提高生产效率, 期待您更优秀的作品. ^_^

**Comment by NowBro** [comment]
@tangcent  你好, 请问这个功能会在之后的版本中加入吗? (#^.^#)

**Comment by tangcent** [comment]
最近两个月有点忙, 没法抽出大片的时间做这种相对来说影响面比较大的功能.
主要是支持分组后还需要修改当前的缓存逻辑.
这个功能可能还需要一段时间.

**Comment by tangcent** [comment]
@stale please don't close this issue

**Comment by tangcent** [comment]
I will work on it the next two weeks.

**Comment by clarkhan** [comment]
很棒，现在支持分组了。不过测了下，分组接口的继承规则不支持。`session.get("json-group"),it["groups"])` 只包含 声明的group，这些 group extend 的注解不在其中

**Comment by tangcent** [comment]
> 分组接口的继承规则不支持

我没用过这种用法，有时间的话，提个新的issue，给个简单的demo，来讨论下如何处理吧

**Comment by clarkhan** [comment]
> > 分组接口的继承规则不支持
> 
> 我没用过这种用法，有时间的话，提个新的issue，给个简单的demo，来讨论下如何处理吧

目的是复用一些公共的规则，demo 可以先简单看这篇文章：[【SpringBoot】Spring Validation 分组校验](https://blog.csdn.net/ABIGJUN/article/details/97425805)

如果考虑支持这种场景，可以有空单独提个 issue

**Comment by leach** [comment]
> 很棒，现在支持分组了。不过测了下，分组接口的继承规则不支持。`session.get("json-group"),it["groups"])` 只包含 声明的group，这些 group extend 的祖先group不在其中

你好，是怎么实现分组的？ 我现在了最新插件，没生效，是不是还需要修改？

**Comment by leach** [comment]
`    /**
     * 新增用户
     * @param user 用户信息
     * @return User 用户列表
     */
    @PostMapping()
    public int add(@Validated(ValidationGroups.Create.class) @RequestBody User user){
        return 1;
    }`

`/**
     * 查询用户列表
     * @param param 查询参数
     * @tag 用户接口
     * @return 用户列表
     */
    @GetMapping()
    public List<User> list(User param){
        List<User> list = new ArrayList<>(2);
        return list;
    }`


第一个方法加了@Validated，第二个方法没加，导出的接口文档里面，两个方法@NotNull注解对应的字段，都显示必填了，是我没用好这个插件吗？

**Comment by tangcent** [comment]
@leach ，see http://easyyapi.com/framwork/javax_validation.html
是否切换为`javax.validation(grouped)`了?
