### ISSUE TITLE
微服务的话，如何在路径上加上对应的前缀，这些前缀路由都在网关里配置的

### ISSUE THREAD

**Issue by wangkuide** [tangcent/easy-yapi#201]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wangkuide** [comment]
用的是springcloud，模块路由都在网关里配置，想在每个接口的路径上加上对应模块的前缀

**Comment by tangcent** [comment]
see http://easyyapi.com/setting/rules/class_prefix_path.html

---

简单的用法就是配置: 
```
class.prefix.path=/demo
```

---

> 模块路由都在网关里配置，想在每个接口的路径上加上对应模块的前缀

需要确认你这边的逻辑，对应模块的前缀怎么拿到?

**Comment by wangkuide** [comment]
我用的是springcloud，网关是gateway，在网关里定义具体的路由配置
![image](https://user-images.githubusercontent.com/66928495/86222027-42f5c100-bbb8-11ea-969b-211b10edd11c.png)
上图路径中带user和login的都会路由到用户模块，
![image](https://user-images.githubusercontent.com/66928495/86222242-8d773d80-bbb8-11ea-8042-e6828722ccf6.png)
这是具体的接口路径，我直接生成文档的话，路径只是 /login但其实我想生成的是 login/login
![image](https://user-images.githubusercontent.com/66928495/86222403-c57e8080-bbb8-11ea-876c-de6963eacd60.png)
获取用户信息的接口生成的路径是/user 但是我想生成的是/user/userinfo

**Comment by tangcent** [comment]
解析这个路由有点难度.

目前来说可能添加需要部分注释来帮助插件识别模块.

---

简单的方法是在`.yapi.config`里配置:

```
spring.cloud.routes=["user":"/user","login":"/login","common":"/common"]
class.prefix.path=groovy:${spring.cloud.routes}[it.doc("module")]
```

然后在你的controller类上注释:
```java
/**
 * @module user
 */
```

---

如果你不同的模块的包名有区别，比如:
```
com.xxx.user
com.xxx.login
com.xxx.common
```
那可以尝试分析类名来区分模块:

```
spring.cloud.routes=["user":"/user","login":"/login","common":"/common"]
class.prefix.path=groovy:${spring.cloud.routes}[tool.substringBetween(it.name(),"com.xxx.",".")]
```

--- 

总的来说就是在配置里声明```spring.cloud.routes```,然后想办法从类上获得模块信息.

另一种简单粗暴的方式是配置```class.prefix.path=#path```,然后类上直接注释前缀:
```java
/**
 * @path user
 */
```

**Comment by wangkuide** [comment]
非常感谢，对我有帮助

**Comment by tangcent** [comment]
:)
