### ISSUE TITLE
如何设置，请求参数不是在Query中，而是在Body内

### ISSUE THREAD

**Issue by wangkuide** [tangcent/easy-yapi#203]
1.post请求提交form表单的话生成的请求参数都在query中，实际上应该在body中。
2.还有一个就是，微服务有好多模块，生成的接口文档是一个控制器一个文件夹，我想是把一个模块的控制器放在对应模块的文件夹下
```
 user
   ---controller
        ---loginController
        ---registerController
 websocker
   ---controller
        ---wechatController
        ---wechatListController
生成的接口文档目录
loginController
registerController
wechatController
wechatListController
但是我想生成
user
---loginController
---registerController
websocker
---wechatController
 ---wechatListController
我用了@module好像没用
```

**Comment by tangcent** [comment]
> 1.post请求提交form表单的话生成的请求参数都在query中，实际上应该在body中。

hi~,目前的逻辑是:
https://github.com/tangcent/easy-yapi/blob/d5b7c61bb30d779180883c214610d2745db340d1/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SpringRequestClassExporter.kt#L57-L180


目前来说，只有注解了@ModelAttribute的参数会被作为form表单处理，另外当参数包含文件字段时，也会被转为表单处理，其他情况默认用了Query.
暂时没有配置可以修改这个行为，我在考虑提供配置`content-type`，然后根据`content-type`来调整这个行为.

---

> 2.还有一个就是，微服务有好多模块，生成的接口文档是一个控制器一个文件夹，我想是把一个模块的控制器放在对应模块的文件夹下

你这里的需求应该是: [folder.name](http://easyyapi.com/setting/rules/folder_name.html)
尝试在配置文件里增加配置:
```
# read folder name from tag `folder`
folder.name=#folder
```

然后在类上注释:
```java
/**
 * 用户相关
 *
 * @module user
 * @folder 用户相关的接口
 */

```
这样本来落在文件夹`用户相关`的接口就会落到`用户相关的接口`里.


---

关于`module`:

`module`对应的是`yapi`里的`project`,对于每个`module`插件都会要求提供对应的`project`的`token`

对于`module`的使用可以参考:
https://github.com/Earth-1610/spring-demo/blob/4a5c1bfbe32cf1c1c8b1b4853427b0506c88b6aa/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/UserCtrl.java#L16-L20

`@module`生效的前提是你有在配置文件中配置规则:`module=#module`
或者在[设置](http://easyyapi.com/setting/ide-setting.html)里勾选`use recommend config`


---

以上规则最好根据项目实际情况配置，已减少不必要的注释侵入.

**Comment by snoopy1412** [comment]
> > 1.post请求提交form表单的话生成的请求参数都在query中，实际上应该在body中。
> 
> hi~,目前的逻辑是:
> https://github.com/tangcent/easy-yapi/blob/d5b7c61bb30d779180883c214610d2745db340d1/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SpringRequestClassExporter.kt#L57-L180
> 
> 目前来说，只有注解了@ModelAttribute的参数会被作为form表单处理，另外当参数包含文件字段时，也会被转为表单处理，其他情况默认用了Query.
> 暂时没有配置可以修改这个行为，我在考虑提供配置`content-type`，然后根据`content-type`来调整这个行为.
> 
> > 2.还有一个就是，微服务有好多模块，生成的接口文档是一个控制器一个文件夹，我想是把一个模块的控制器放在对应模块的文件夹下
> 
> 你这里的需求应该是: [folder.name](http://easyyapi.com/setting/rules/folder_name.html)
> 尝试在配置文件里增加配置:
> 
> ```
> # read folder name from tag `folder`
> folder.name=#folder
> ```
> 
> 然后在类上注释:
> 
> ```java
> /**
>  * 用户相关
>  *
>  * @module user
>  * @folder 用户相关的接口
>  */
> ```
> 
> 这样本来落在文件夹`用户相关`的接口就会落到`用户相关的接口`里.
> 
> 关于`module`:
> 
> `module`对应的是`yapi`里的`project`,对于每个`module`插件都会要求提供对应的`project`的`token`
> 
> 对于`module`的使用可以参考:
> https://github.com/Earth-1610/spring-demo/blob/4a5c1bfbe32cf1c1c8b1b4853427b0506c88b6aa/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/UserCtrl.java#L16-L20
> 
> `@module`生效的前提是你有在配置文件中配置规则:`module=#module`
> 或者在[设置](http://easyyapi.com/setting/ide-setting.html)里勾选`use recommend config`
> 
> 以上规则最好根据项目实际情况配置，已减少不必要的注释侵入.



> > 1.post请求提交form表单的话生成的请求参数都在query中，实际上应该在body中。
> 
> hi~,目前的逻辑是:
> https://github.com/tangcent/easy-yapi/blob/d5b7c61bb30d779180883c214610d2745db340d1/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SpringRequestClassExporter.kt#L57-L180
> 
> 目前来说，只有注解了@ModelAttribute的参数会被作为form表单处理，另外当参数包含文件字段时，也会被转为表单处理，其他情况默认用了Query.
> 暂时没有配置可以修改这个行为，我在考虑提供配置`content-type`，然后根据`content-type`来调整这个行为.
> 
> > 2.还有一个就是，微服务有好多模块，生成的接口文档是一个控制器一个文件夹，我想是把一个模块的控制器放在对应模块的文件夹下
> 
> 你这里的需求应该是: [folder.name](http://easyyapi.com/setting/rules/folder_name.html)
> 尝试在配置文件里增加配置:
> 
> ```
> # read folder name from tag `folder`
> folder.name=#folder
> ```
> 
> 然后在类上注释:
> 
> ```java
> /**
>  * 用户相关
>  *
>  * @module user
>  * @folder 用户相关的接口
>  */
> ```
> 
> 这样本来落在文件夹`用户相关`的接口就会落到`用户相关的接口`里.
> 
> 关于`module`:
> 
> `module`对应的是`yapi`里的`project`,对于每个`module`插件都会要求提供对应的`project`的`token`
> 
> 对于`module`的使用可以参考:
> https://github.com/Earth-1610/spring-demo/blob/4a5c1bfbe32cf1c1c8b1b4853427b0506c88b6aa/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/UserCtrl.java#L16-L20
> 
> `@module`生效的前提是你有在配置文件中配置规则:`module=#module`
> 或者在[设置](http://easyyapi.com/setting/ide-setting.html)里勾选`use recommend config`
> 
> 以上规则最好根据项目实际情况配置，已减少不必要的注释侵入.

期待，非常需要配置content-type调整body还是query.

**Comment by tangcent** [comment]
WIP.

`folder.name`是否可以解决你的第二个问题?

**Comment by wangkuide** [comment]
抱歉可能是我描述的有误
项目结构是这样的
user
   ---controller
        ---loginController
             ---method1
             ---method2
        ---registerController
             ---method3
             ---method4
websocket
   ---controller
        ---wechatController
             ---method5
             ---method6
         ---wechatListController
             ---method7
             ---method8
现在yarp生成的目录结构是这样的
loginController（文件夹）
 ---method1
 ---method2
registerController（文件夹）
 ---method1
 ---method2
wechatController（文件夹）
  ---method5
  ---method6
wechatListController（文件夹）
   ---method7
   ---method8
但是我有多个和user并列的服务，所以我想生成是这样的
user（文件夹）
  ---loginController（文件夹）
      ---method1
      ---method2
 ---registerController（文件夹）
      ---method3
      ---method4
websocker（文件夹）
  ---wechatController（文件夹）
      ---method5
      ---method6
 ---wechatListController（文件夹）
      ---method7
      ---method8
非常感谢您~

**Comment by tangcent** [comment]
目前`yapi`官方并不支持多级目录.所以插件也无法提供此功能.

**Comment by tangcent** [comment]
Patch with #206 & #207 : [easy-yapi.1.9.6.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4875021/easy-yapi.1.9.6.183.0.jar.zip)
Download and unzip it. Install to IDEA.

---

- see: https://github.com/tangcent/easy-yapi/blob/3104e5c86c19056ade11f59eeb0474b7916b67cc/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSpringRequestClassExporter.kt#L208-L212
 默认非GET请求，复杂参数做form处理

- see: https://github.com/tangcent/easy-yapi/blob/3104e5c86c19056ade11f59eeb0474b7916b67cc/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSpringRequestClassExporter.kt#L175-L199
允许```param.without.ann.type=form```来设置无注解参数作为`form`/`body`/`query`.

- 可能有bug，还在测试.

**Comment by snoopy1412** [comment]
> Patch with #206 & #207 : [easy-yapi.1.9.6.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4875021/easy-yapi.1.9.6.183.0.jar.zip)
> Download and unzip it. Install to IDEA.
> 
> * see: https://github.com/tangcent/easy-yapi/blob/3104e5c86c19056ade11f59eeb0474b7916b67cc/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSpringRequestClassExporter.kt#L208-L212
>   
>   默认非GET请求，复杂参数做form处理
> * see: https://github.com/tangcent/easy-yapi/blob/3104e5c86c19056ade11f59eeb0474b7916b67cc/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiSpringRequestClassExporter.kt#L175-L199
>   
>   允许`param.without.ann.type=form`来设置无注解参数作为`form`/`body`/`query`.
> * 可能有bug，还在测试.

nice!!

**Comment by wangkuide** [comment]
是把这个jar包添加到项目中，然后在yapi中加入param.without.ann.type=form来设置无注解参数作为form/body/query这个配置是吗？

**Comment by wangkuide** [comment]
按照你的配置，我一个post请求，把配置改成param.without.ann.type=body
这是我的接口
![image](https://user-images.githubusercontent.com/66928495/86547464-afcbdb00-bf6b-11ea-8671-69913dcb02aa.png)
这是yapi生成的
![image](https://user-images.githubusercontent.com/66928495/86547483-c6723200-bf6b-11ea-9d97-f0e2d25f86f7.png)

**Comment by tangcent** [comment]
- 下载插件 [easy-yapi.1.9.6.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4875021/easy-yapi.1.9.6.183.0.jar.zip) 并解压 -> 打开IDEA -> <kbd>Preferences(Settings)</kbd> > <kbd>Plugins</kbd> > <kbd>Install plugin from disk...</kbd>

![image](https://user-images.githubusercontent.com/17569144/86547822-d0486500-bf6c-11ea-8cd0-26c458e0297c.png)

**Comment by tangcent** [comment]
> 按照你的配置，我一个post请求，把配置改成param.without.ann.type=body
> 这是我的接口
> ![image](https://user-images.githubusercontent.com/66928495/86547464-afcbdb00-bf6b-11ea-8671-69913dcb02aa.png)
> 这是yapi生成的
> ![image](https://user-images.githubusercontent.com/66928495/86547483-c6723200-bf6b-11ea-9d97-f0e2d25f86f7.png)
> 多出来一个body，但是里面没有任何数据

原来你是这种情况.让我再考虑下.
我以为是这种情况
```java
    @PutMapping("update")
    public IResult update(UserInfo userInfo)
```

**Comment by tangcent** [comment]
Patch with #208 : [easy-yapi.1.9.6.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4881748/easy-yapi.1.9.6.183.0.jar.zip)
Download and unzip it. Install to IDEA.

---

将规则修改为`param.http.type`,see https://github.com/tangcent/easy-api/issues/297 & https://github.com/tangcent/easy-api/pull/298
适用于两种情况:

- param without none of annotations like 
  * `org.springframework.web.bind.annotation.RequestHeader`
  * `org.springframework.web.bind.annotation.PathVariable`
  * `org.springframework.web.bind.annotation.ModelAttribute`
  * `org.springframework.web.bind.annotation.RequestBody`
- param annotated with `org.springframework.web.bind.annotation.RequestParam` and the handle method has not explicate the http method as `GET`

配置规则如下:

- 全设置为form:
```properties
param.http.type=form
```
- RequestParam作为query,其他做为form:
```properties
param.http.type[@org.springframework.web.bind.annotation.RequestParam]=query
param.http.type=form
```

---

可能有bug，还在测试.

**Comment by wangkuide** [comment]
可以了，但是还有一点小问题
![image](https://user-images.githubusercontent.com/66928495/86702155-44eed280-c045-11ea-9c3b-beb57a4c1a74.png)
![image](https://user-images.githubusercontent.com/66928495/86702227-56d07580-c045-11ea-9d1d-0a9a9399902f.png)
如图所示，生成的文档里面是否必须那一列全是否，但是name那个参数是必须的。

**Comment by tangcent** [comment]
Patch with #209 : [easy-yapi.1.9.6.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4882610/easy-yapi.1.9.6.183.0.jar.zip)
Download and unzip it. Install to IDEA.

**Comment by wangkuide** [comment]
可以了，非常感谢

**Comment by tangcent** [comment]
released
