### ISSUE TITLE
yapi dashboard 假死并且无法关闭

### ISSUE THREAD

**Issue by liucaidong** [tangcent/easy-yapi#204]
**Describe the bug**
打开yapi dashboard后，无法进行操作或者操作很卡，然后会假死并且无法关闭该弹窗
**To Reproduce**
![image](https://user-images.githubusercontent.com/20674980/86442554-93982600-bd40-11ea-8216-9eb27f95f5ed.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/20674980/86442639-ae6a9a80-bd40-11ea-84ce-81017a5436bc.png)

![image](https://user-images.githubusercontent.com/20674980/86442668-bb878980-bd40-11ea-924d-40cf8a356ab9.png)

- IDE
![image](https://user-images.githubusercontent.com/20674980/86443010-33ee4a80-bd41-11ea-80fc-e3f46b75dc31.png)

**Comment by tangcent** [comment]
hi~
这里可能是尝试推断api返回导致资源占用过多的问题.
你可以尝试关闭智能推断后再试.
![image](https://user-images.githubusercontent.com/17569144/86461766-0fa06700-bd5d-11ea-8f4d-691cc55afa0d.png)

---

虽然说是智能推断，但是现在还只是很简陋的版本.

**Comment by liucaidong** [comment]
@tangcent 今天在家里的电脑试了一下是可以的，没有卡死，我明天去单位，用单位的电脑再试一下

**Comment by liucaidong** [comment]
@tangcent 把inferEnable前面的复选框勾掉，假死现象消失，勾上整个IDEA就无响应了，所以我现在用公司的电脑，只要不勾选这个选项，程序正常
![image](https://user-images.githubusercontent.com/20674980/87114752-f3904e80-c2a3-11ea-902b-56f88ed4a90b.png)

**Comment by tangcent** [comment]
- 关于返回类型推断这个，暂时还没有找到好的解决方案。
- 由于推断过程中用了很多延迟计算的逻辑, 所以如果使用发生错误，目前很难定位到具体哪里推断有问题，可能的规避方法只能是关闭它.
