### ISSUE TITLE
多环境情况下，spring的yaml中有maven变量，easy yapi总是取源码中的yaml，于是出现问题

### ISSUE THREAD

**Issue by shadewly** [tangcent/easy-yapi#205]
#######################spinrg 配置###########################
spring:
  profiles:
    active: @profile.active@
#######################error log###########################
[INFO]	Start find apis...
[TRACE]	No config [.yapi.config] be found
[TRACE]	No config [.yapi.yml] be found
[TRACE]	No config [.yapi.yaml] be found
[TRACE]	No config [.easy.api.config] be found
[TRACE]	No config [.easy.api.yml] be found
[TRACE]	No config [.easy.api.yaml] be found
[WARN]	error handle class
[INFO]	Apis exported completed
[TRACE]	while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 6, column 13:
        active: @profile.active@
                ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:418)

建议修复取编译后取class中的。如果与设计违背，可否设置变量替换？

**Comment by tangcent** [comment]
可以在[推荐配置](http://easyyapi.com/setting/ide-setting.html)里把加载spring的配置去掉:
![image](https://user-images.githubusercontent.com/17569144/86458694-40ca6880-bd58-11ea-8b38-74b07dbc4217.png)

**Comment by shadewly** [comment]
Thanks, it works.

**Comment by tangcent** [comment]
目前没发现一个好的办法来忽略解析yaml中出现的错误继续解析后续配置信息.

暂时做异常忽略处理:https://github.com/Earth-1610/intellij-kotlin/pull/49/files#diff-7512c77c056c7f3ae22d0d5cb1cd762d

后续如果发现好的解决方案，再来处理.

如果你有好的想法，可以提一个PR到: https://github.com/Earth-1610/intellij-kotlin
