### ISSUE TITLE
能否增加swagger注解识别的支持

### ISSUE THREAD

**Issue by xiaostart977** [tangcent/easy-yapi#210]

**Comment by tangcent** [comment]
对swagger的支持全部由配置提供.

http://easyyapi.com/framwork/swagger.html

see https://github.com/tangcent/easy-yapi/issues/196

过两天有空整理一下.你有需要支持的注解，可在此issue下回复.

**Comment by tangcent** [comment]
:)

**Comment by FJiayang** [comment]
使用https://github.com/tangcent/easy-yapi/blob/master/third/swagger3.config 配置无法识别@Schema注解
