### ISSUE TITLE
复杂的返回值好像不支持生成

### ISSUE THREAD

**Issue by 52885199** [tangcent/easy-yapi#214]
目前版本 v1.9.7.0.183.0(2020-07-12)
如果返回值是一个自定义对象,然后里面泛型是个对象好像就解析不了了,还是我哪里配置不对,例如  Response<UserDTO>

**Comment by tangcent** [comment]
see https://github.com/Earth-1610/spring-demo/blob/master/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/UserCtrl.java
