### ISSUE TITLE
properties.additional读取配置文件‘not be found’

### ISSUE THREAD

**Issue by miaoshuaigit** [tangcent/easy-yapi#215]
读取配置文件提示not be found
环境
IDEA：2020.1
EasyYapi：1.9.7.0.183.0

项目结构
![image](https://user-images.githubusercontent.com/19604143/87756581-c14e9600-c83b-11ea-8692-6f708591a2f0.png)

easy.api.config配置
```
method.additional.header[!@com.myzczk.base.annotation.Public]={name: "Authorization",value: "bearer ",desc: "认证Token",required:true}
properties.additional=${module_path}/src/main/resources/bootstrap.yml
class.prefix.path=${server.servlet.context-path}

```
控制台输出
```
[INFO]	Start find apis...
[TRACE]	No config [.yapi.config] be found
[TRACE]	No config [.yapi.yml] be found
[TRACE]	No config [.yapi.yaml] be found
[TRACE]	find config file:E:\Software\Develop\Project\myzczk-cloud\.easy.api.config
[ERROR]	E:/Software/Develop/Project/myzczk-cloud/myzczk-service/myzczk-account-service/src/main/resources/bootstrap.yml not be found
[ERROR]	unable to resolve property:server.servlet.context-path
[INFO]	To ignore this error,surround with:
###set ignoreUnresolved = true
###set ignoreUnresolved = false
[INFO]	use recommend config
```

**Comment by tangcent** [comment]
这个文件`E:/Software/Develop/Project/myzczk-cloud/myzczk-service/myzczk-account-service/src/main/resources/bootstrap.yml`存在吗?

**Comment by miaoshuaigit** [comment]
@tangcent 对的

**Comment by miaoshuaigit** [comment]
@tangcent 同事的mac上面没有这个问题

**Comment by miaoshuaigit** [comment]
存在




| |
ms
邮箱：miaoshuait@163.com
|

Signature is customized by Netease Mail Master

在2020年07月17日 19:53，tangcent 写道：

这个文件E:/Software/Develop/Project/myzczk-cloud/myzczk-service/myzczk-account-service/src/main/resources/bootstrap.yml存在吗?

**Comment by tangcent** [comment]
我需要一些时间来准备windows开发环境. orz

---

如果可以的话，你可以自行debug试试，
加载额外配置文件的地方在
`com.itangcent.intellij.config.AbstractConfigReader`
代码如下:
```kotlin

    private fun loadConfigFile(path: String) {
        val configFile = File(resolvePath(path))
        if (configFile.exists() && configFile.isFile) {
            put("curr_path", path)
            val configInfoContent = FileUtils.read(configFile)
            if (!configInfoContent.isNullOrEmpty()) {
                loadConfigInfoContent(configInfoContent!!, path.substringAfterLast("."))
                return
            } else if (!ignoreNotFoundFile) {
                logger!!.error("$path is an empty file")
            }
        } else if (!ignoreNotFoundFile) {
            logger!!.error("$path not be found")
        }
    }
```
修改的话，PR要提交到这: https://github.com/Earth-1610/intellij-kotlin

**Comment by tangcent** [comment]
@echo-layker see this issue.

**Comment by echo-layker** [comment]
> @echo-layker see this issue.

ok, I am trying to fix it

**Comment by tangcent** [comment]
fixed by https://github.com/tangcent/easy-yapi/releases/tag/v1.9.8.0

**Comment by tangcent** [comment]
@miaoshuaigit hi~,这个问题在新的版本是否得到了修复?

**Comment by miaoshuaigit** [comment]
已经修复了
| |
ms
邮箱：miaoshuait@163.com
|

Signature is customized by Netease Mail Master

在2020年07月21日 21:44，tangcent 写道：

@miaoshuaigit hi~,这个问题在新的版本是否得到了修复?

**Comment by tangcent** [comment]
: )
