### ISSUE TITLE
Get请求如何设置参数必填

### ISSUE THREAD

**Issue by fengbinTester** [tangcent/easy-yapi#217]
Get请求如何设置参数必填，使用以下代码导入YAPI后，参数显示非必填
    

/**
     * 获取api名称
     * api描述
     * @param id 用户id
     * @param group 用户分组
     * @return 返回描述
     */
    @RequestMapping(value = "/getName",method = RequestMethod.GET)
    @ResponseBody

    public User getName(@RequestParam(value = "id") String id ,@RequestParam(value = "group") String group){
        User user = new User();
        user.setAge(20);
        user.setName("mgg");
        return user;
    }

**Comment by tangcent** [comment]
Patch with #219 : [easy-yapi.1.9.8.0.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/4966739/easy-yapi.1.9.8.0.183.0.jar.zip)
Download and unzip it. Install to IDEA.
