### ISSUE TITLE
能够根据注释tag生成文档的tag

### ISSUE THREAD

**Issue by dartick** [tangcent/easy-yapi#222]
例如：
/**
  * 查询用户信息
  *
  * @param userId 用户ID
  * @usepage 我的,会员
  */
可以根据usepage获取到需要生成的tag（我的、会员）
我尝试过通过配置的方式来获取：
api.tag=groovy:it.hasDoc("usepage")?tool.split(it.doc("usepage"), ","):null
但是只会生成一个tag（[我的, 会员]）

**Comment by tangcent** [comment]
- 因我使用过程中，都是根据不同的情况增加tag

```properties
api.tag[@java.lang.Deprecated]=deprecated
api.tag[#deprecated]=deprecated
api.tag[groovy:it.containingClass().hasAnn("java.lang.Deprecated")]=deprecated
api.tag[groovy:it.containingClass().hasDoc("deprecated")]=deprecated
api.tag[#public]=public
api.tag=groovy:it.containingClass().name().endsWith("Client")?"dubbo":null
```

---

- 可以暂时使用如下配置:

```api.tag[#usepage]=groovy:it.doc("usepage").replaceAll(",","\n")```

**Comment by dartick** [comment]
完美！！！
