### ISSUE TITLE
support `postman.prerequest&postman.test` for collection.

### ISSUE THREAD

**Issue by tangcent** [tangcent/easy-yapi#225]
see https://learning.postman.com/docs/writing-scripts/pre-request-scripts/

-  Add pre-request scripts to entire collections as well as to folders within collections.
This script will execute before every request in this collection or folder. 
-  Add test scripts to entire collections as well as to folders within collections.
These tests will execute after every request in this collection. 
---

rules:

- [ ]  `class.postman.prerequest`  
- [ ]  `class.postman.test`

**Comment by xuguoqin** [comment]
针对class.postman使用的过程中发现这样一种情况

- 如果是单个类导出，collection上会通过class定义的脚本进行生成

- 如果以多个类进行导出postman的时候，会生成collection -> folder -> request的结构，此时配置的脚本会生成到每个folder上，其实我更希望的是生成到顶级目录collection里面

- 这里可以考虑做个区分吗，class以当前顶级目录为单位

**Comment by xuguoqin** [comment]
或者是考虑导出的时候都默认生成collection -> folder -> request的结构, class.postman生成的脚本就一直会在collection里面，因为没有区分folder和collection
这样和easyyapi就会形成这种对应
postman -> easyyapi
collection -> module
folder -> folder
request -> api

**Comment by tangcent** [comment]
hi~. 由于postman的开放接口在很多情况下响应时间较长,另外防止意外覆盖的情况.
所以目前导出到postman的主要思路是，导出需要的api到一个新的文件夹然后由开发者自行调整(拖拽)到目标文件夹.

---

这里考虑增加一个可选择的特性: 
导出postman时,做一次检查.
当一个collection/folder的所有子folder具有相同的`prerequest&test`时
移除所有子folder上的`prerequest&test`,放在collection/父folder上.
是否可行?

**Comment by xuguoqin** [comment]
这样当然也能解决那个顶层的问题，只是如果以单个类去生成postman文档的话，只会生成collection -&gt; request的结构，postman拖动的话貌似不支持collection直接拖动，我测试的时候folder拖动是ok的如果更灵活的话当然是希望，每次生成都能生成3级结构，然后有针对collection，针对folder，针对request的配置




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tangcent"<notifications@github.com&gt;; 
发送时间: 2020年7月31日(星期五) 晚上6:42
收件人: "tangcent/easy-yapi"<easy-yapi@noreply.github.com&gt;; 
抄送: "努力，奋斗!"<775275027@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [tangcent/easy-yapi] support `postman.prerequest&amp;postman.test` for collection. (#225)





 
hi~. 由于postman的开放接口在很多情况下响应时间较长,另外防止意外覆盖的情况.
 所以目前导出到postman的主要思路是，导出需要的api到一个新的文件夹然后由开发者自行调整(拖拽)到目标文件夹.
 
 
这里考虑增加一个可选择的特性:
 导出postman时,做一次检查.
 当一个collection/folder的所有子folder具有相同的prerequest&amp;test时
 移除所有子folder上的prerequest&amp;test,放在collection/父folder上.
 是否可行?

**Comment by tangcent** [comment]
也许可以在setting里加个选项,  是否默认包装一个collection,至少扩展到collection -> folder -> request三层结构.

**Comment by xuguoqin** [comment]
这样也是可以的，不过我使用的过程中已经看出，如果导入的只有单个类默认没有collection，多个类就会有，然后如果是有collection结构的话，那么目前通过class.postman配置的脚本都是在所有folder下面，他们都是完全一样的，应该没啥意义，如果都生成脚本到collection，那么就没有专门针对folder的脚本配置




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tangcent"<notifications@github.com&gt;; 
发送时间: 2020年7月31日(星期五) 晚上10:15
收件人: "tangcent/easy-yapi"<easy-yapi@noreply.github.com&gt;; 
抄送: "努力，奋斗!"<775275027@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [tangcent/easy-yapi] support `postman.prerequest&amp;postman.test` for collection. (#225)





 
也许可以在setting里加个选项,  是否默认包装一个collection,至少扩展到collection -&gt; folder -&gt; request三层结构.

**Comment by tangcent** [comment]
这是由当前的使用场景决定的. 当所有的类的脚本都是一致的时候的确是这种情况.
但是考虑可能存在的不一致的情况, 比如:
- 大多数接口需要登录
- 有几个工具类接口, 不需要登录.
- 有几个开放类接口, 需要使用秘钥访问.

这个时候可能的配置是:

``````
#一般需要登录的接口
class.postman.prerequest[@com.itangcent.common.annotation.LoginRequired]=```
var a = "1";
var b = "1";
```
class.postman.test[@com.itangcent.common.annotation.LoginRequired]=```
var a = "1";
var b = "1";
```

#不需要登录的接口
class.postman.prerequest[@com.itangcent.common.annotation.Public]=```
var c = "1";
var d = "1";
```
class.postman.test[@com.itangcent.common.annotation.Public]=```
var c = "1";
var d = "1";
```

#开放接口
class.postman.prerequest[@com.itangcent.common.annotation.Open]=```
var e = "1";
var f = "1";
```
class.postman.test[@com.itangcent.common.annotation.Open]=```
var e = "1";
var f = "1";
```

``````


---

原则上:
- 插件尽量提供给开发者更多的可能性，已适配不一样的项目.
- 插件尽量不强行指定开发者需要遵守特定的注释/注解规则.

所以这里采用`class.postman.prerequest`的原因也是使得开发者可以根据本身项目的特征, 允许对不同的`class`制定不一样的脚本.

但另一方面也应该考虑部分开发者希望所有的`class`制定全局一样的脚本.

---

就你目前的使用来看，是希望prerequest落在folder还是collection?

**Comment by xuguoqin** [comment]
抱歉，我使用的时候基本都是针对整个模块的配置，所以应该folder里面的内容都是一样的，如果有不一样的情况的确应该考虑，还有就是你发的这个demo在网站上没有，所以我之前没想到这种使用方法，可能是对这个语言不太熟

可以按照你之前说的那种策略，如果所有folder的配置一样就可以考虑移动到collection里面，这个也可以通过增加一个配置判断要不要合并并把脚本从folder上移直collection


同时最好也可以有一个能配置单个类是否需要生成collection -&gt; folder -&gt; request 三层的结构，目前单个类只有collection -&gt; request，不方便批量请求迁移




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tangcent"<notifications@github.com&gt;; 
发送时间: 2020年8月1日(星期六) 上午6:23
收件人: "tangcent/easy-yapi"<easy-yapi@noreply.github.com&gt;; 
抄送: "努力，奋斗!"<775275027@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [tangcent/easy-yapi] support `postman.prerequest&amp;postman.test` for collection. (#225)





 
这是由当前的使用场景决定的. 当所有的类的脚本都是一致的时候的确是这种情况.
 但是考虑可能存在的不一致的情况, 比如:
  
大多数接口需要登录
 
有几个工具类接口, 不需要登录.
 
有几个开放类接口, 需要使用秘钥访问.
  
这个时候可能的配置是:
 #一般需要登录的接口 class.postman.prerequest[@com.itangcent.common.annotation.LoginRequired]=``` var a = "1"; var b = "1"; ``` class.postman.test[@com.itangcent.common.annotation.LoginRequired]=``` var a = "1"; var b = "1"; ``` #不需要登录的接口 class.postman.prerequest[@com.itangcent.common.annotation.Public]=``` var c = "1"; var d = "1"; ``` class.postman.test[@com.itangcent.common.annotation.Public]=``` var c = "1"; var d = "1"; ``` #开放接口 class.postman.prerequest[@com.itangcent.common.annotation.Open]=``` var e = "1"; var f = "1"; ``` class.postman.test[@com.itangcent.common.annotation.Open]=``` var e = "1"; var f = "1"; ```  
 
原则上:
  
插件尽量提供给开发者更多的可能性，已适配不一样的项目.
 
插件尽量不强行指定开发者需要遵守特定的注释/注解规则.
  
所以这里采用class.postman.prerequest的原因也是使得开发者可以根据本身项目的特征, 允许对不同的class制定不一样的脚本.
 
但另一方面也应该考虑部分开发者希望所有的class制定全局一样的脚本.
 
 
就你目前的使用来看，是希望prerequest落在folder还是collection?

**Comment by xuguoqin** [comment]
还有就是我们自己会维护一份顶级目录的脚本，如果每个子目录也有脚本对于脚本变动的修改比较麻烦，而且大多数内容都是一样的，所以在拖动的时候大多数生成的folder是不太需要脚本的，生成的collection里面有脚本对我们有后续自己拖动管理的需求会比较友好






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tangcent"<notifications@github.com&gt;; 
发送时间: 2020年8月1日(星期六) 上午6:23
收件人: "tangcent/easy-yapi"<easy-yapi@noreply.github.com&gt;; 
抄送: "努力，奋斗!"<775275027@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [tangcent/easy-yapi] support `postman.prerequest&amp;postman.test` for collection. (#225)





 
这是由当前的使用场景决定的. 当所有的类的脚本都是一致的时候的确是这种情况.
 但是考虑可能存在的不一致的情况, 比如:
  
大多数接口需要登录
 
有几个工具类接口, 不需要登录.
 
有几个开放类接口, 需要使用秘钥访问.
  
这个时候可能的配置是:
 #一般需要登录的接口 class.postman.prerequest[@com.itangcent.common.annotation.LoginRequired]=``` var a = "1"; var b = "1"; ``` class.postman.test[@com.itangcent.common.annotation.LoginRequired]=``` var a = "1"; var b = "1"; ``` #不需要登录的接口 class.postman.prerequest[@com.itangcent.common.annotation.Public]=``` var c = "1"; var d = "1"; ``` class.postman.test[@com.itangcent.common.annotation.Public]=``` var c = "1"; var d = "1"; ``` #开放接口 class.postman.prerequest[@com.itangcent.common.annotation.Open]=``` var e = "1"; var f = "1"; ``` class.postman.test[@com.itangcent.common.annotation.Open]=``` var e = "1"; var f = "1"; ```  
 
原则上:
  
插件尽量提供给开发者更多的可能性，已适配不一样的项目.
 
插件尽量不强行指定开发者需要遵守特定的注释/注解规则.
  
所以这里采用class.postman.prerequest的原因也是使得开发者可以根据本身项目的特征, 允许对不同的class制定不一样的脚本.
 
但另一方面也应该考虑部分开发者希望所有的class制定全局一样的脚本.
 
 
就你目前的使用来看，是希望prerequest落在folder还是collection?

**Comment by tangcent** [comment]
规则描述在这: http://easyyapi.com/setting/local-file-config.html

---

综合考虑来看,
 可以增加配置: `collection.postman.prerequest`&`collection.postman.test`

**Comment by xuguoqin** [comment]
能刚好针对postman的三层结构灵活的进行配置，这样子就很完美了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tangcent"<notifications@github.com&gt;; 
发送时间: 2020年8月1日(星期六) 中午12:16
收件人: "tangcent/easy-yapi"<easy-yapi@noreply.github.com&gt;; 
抄送: "努力，奋斗!"<775275027@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [tangcent/easy-yapi] support `postman.prerequest&amp;postman.test` for collection. (#225)





 
规则描述在这: http://easyyapi.com/setting/local-file-config.html
 
 
综合考虑来看,
 可以增加配置: collection.postman.prerequest&amp;collection.postman.test

**Comment by xuguoqin** [comment]
还有个问题想请教下，我同一个工程下controller有两个个目录，front目录代表是前台的接口目录，back代表的是后台的接口目录，能通过配置easyyai的配置文档，按照包区分，把他们的yapi文档生成到两个项目里面去吗貌似没看到这种配置，每个类去写module对代码侵入太大了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tangcent"<notifications@github.com&gt;; 
发送时间: 2020年8月1日(星期六) 中午12:16
收件人: "tangcent/easy-yapi"<easy-yapi@noreply.github.com&gt;; 
抄送: "努力，奋斗!"<775275027@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [tangcent/easy-yapi] support `postman.prerequest&amp;postman.test` for collection. (#225)





 
规则描述在这: http://easyyapi.com/setting/local-file-config.html
 
 
综合考虑来看,
 可以增加配置: collection.postman.prerequest&amp;collection.postman.test

**Comment by tangcent** [comment]
考虑:
```
module=groovy:tool.substringBetween(it.toString(), "com.itangcent.springboot.", ".")
```
将`com.itangcent.springboot.`替换成你这里的公共包名.
