### ISSUE TITLE
param.ignore是否支持忽略类中的字段

### ISSUE THREAD

**Issue by sunshinexb** [tangcent/easy-yapi#230]
class UserContent{
    private String username;
   private String password;
}
    @PostMapping("/test")
    public void test(UserContent userContent)  {
    }

比如使用上面的类作为参数，想忽略UserContent类中的password字段，该怎么做？

**Comment by tangcent** [comment]
hi~, 需要使用 [json.rule.field.ignore](http://easyyapi.com/setting/rules/json_rule_field_ignore.html)

- 使用注释:
```java
class UserContent{
private String username;
/**
 * @ignore
 */
private String password;
}
```

- 单独配置:

全路径包名:
```properties
json.rule.field.ignore=groovy:it.toString()=="包名.UserContent#password"
```
或者:
```properties
json.rule.field.ignore=groovy:it.toString().endsWith("UserContent#password")
```

**Comment by sunshinexb** [comment]
谢谢
