### ISSUE TITLE
怎样将@ApiResponse指定的response类型解析到yapi的”返回数据“中去?

### ISSUE THREAD

**Issue by mostcool** [tangcent/easy-yapi#241]
怎样将@ApiResponse指定的response类型解析到yapi的”返回数据“中去?

**Comment by tangcent** [comment]
试试:
```properties
method.return=@io.swagger.annotations.ApiResponse#response
```

**Comment by mostcool** [comment]
> 试试:
> 
> ```ini
> method.return=@io.swagger.annotations.ApiResponse#response
> ```

不支持@ApiResponse中的responseContainer和reference吗?

**Comment by tangcent** [comment]
可以尝试:

``````properties
method.return[@io.swagger.annotations.ApiResponse]=groovy:```
def responseContainer = it.ann("io.swagger.annotations.ApiResponse","responseContainer")
if(responseContainer.isEmpty()){
    return it.ann("io.swagger.annotations.ApiResponse","reference")
}else {
    return responseContainer +"<" + it.ann("io.swagger.annotations.ApiResponse","reference") +">"
}
```
``````

---

理论上插件不提供除了`spring`外任何框架的原生支持.
全部由开发者自行定义[规则](http://easyyapi.com/setting/config-rule.html)

可以用[script_executor](http://easyyapi.com/documents/script_executor.html)来写规则脚本:
![image](https://user-images.githubusercontent.com/17569144/91127909-c542c300-e6d9-11ea-96a9-c4e355957585.png)

note： groovy与java兼容, groovy不熟悉的话, 你可以直接写java代码
