### ISSUE TITLE
Mac电脑中运行YapiDashBoard会导致卡死

### ISSUE THREAD

**Issue by zhuzhiqiang997** [tangcent/easy-yapi#242]
Mac电脑中运行YapiDashBoard会导致卡死

打开YapiDashBoard 会出现Low Memory警告 然后造成卡顿
VMOptions:
  -Xms512m
  -Xmx2048m
OS: Mac
Version: 2.0.2.0.183.0

**Comment by tangcent** [comment]
see #204 

---

关于返回类型推断这个问题，我还是没有找到好的解决方案。
你可以尝试关闭智能推断使用

**Comment by zhuzhiqiang997** [comment]
关闭过后问题依然存在

**Comment by zhuzhiqiang997** [comment]
![01AC0A7D-D037-43F0-BB49-1F874E7CFE56](https://user-images.githubusercontent.com/32608346/91652509-9017e580-eaca-11ea-847e-86b028611e82.png)
[
<img width="247" alt="QQ20200830-140721@2x" src="https://user-images.githubusercontent.com/32608346/91652513-9ad27a80-eaca-11ea-89b8-a6ee5c5d7436.png">
<img width="463" alt="QQ20200830-140700@2x" src="https://user-images.githubusercontent.com/32608346/91652514-a160f200-eaca-11ea-988d-0f63ff8f8d35.png">

**Comment by tangcent** [comment]
如果不是推断的问题, 那很难确定具体原因.
我再尝试寻找可能的原因.
