### ISSUE TITLE
生成dubbo文档如何自定义接口路径和content_type

### ISSUE THREAD

**Issue by simonpdh** [tangcent/easy-yapi#249]
在生成dubbo文档的时候发现只有全局的配置content_type，接口路径也无法改，在有网关的项目中使用起来很麻烦。能否将mdoc.method.path改成mdoc.method.path=#{注解名}，然后在方法注释上直接用@注解名，生成的文档自动用改注解名对应的文档路径，method.content.type，mdoc.method.http.method这两个也希望能自定义 @tangcent

**Comment by tangcent** [comment]
这两个现在没办法自定义吗?
http://easyyapi.com/setting/rules/mdoc_method_path.html
http://easyyapi.com/setting/rules/mdoc_method_http_method.html

---

有没有试过使用[配置文件](http://easyyapi.com/setting/local-file-config.html)
然后给出规则:
```
mdoc.method.path=#path
mdoc.method.http.method=#method
```

dubbo的client方法上注释:
```java
    /**
     * 增加新用户
     *
     * @path /add/user
     * @method POST
     */
    public UserInfo add(UserInfo userInfo);
```

---

`method.content.type`还未支持

**Comment by simonpdh** [comment]
@path 生成的接口路径最前面带上了/，如何去掉，还有针对rpc文档content_type什么时候可以支持自定义

**Comment by tangcent** [comment]
> @path 生成的接口路径最前面带上了/，如何去掉，

yapi限制: path第一位必需为 /, 只允许由 字母数字-/_:.! 组成

> 还有针对rpc文档content_type什么时候可以支持自定义

现在入参默认都是处理为json, 自定义的话需要考虑如何处理

**Comment by simonpdh** [comment]
感谢，希望后续能支持content_type自定义，因为很多接口其实不是json

**Comment by tangcent** [comment]
> 感谢，希望后续能支持content_type自定义，因为很多接口其实不是json

我这边几乎没有导出dubbo文档到yapi的需求, 所以不是特别清楚你们希望导出的文档是什么样的.
有没有可能举几个例子?
例如接口方法是什么样的，导出的yapi是什么样的?

**Comment by simonpdh** [comment]
导出的dubbo接口文档是这样的
接口路径：https://domain/project/function/business
接口请求方式：GET/POST/PUT/DELETE
content-type: application/json

请求参数和返回值目前能满足

**Comment by simonpdh** [comment]
> > 感谢，希望后续能支持content_type自定义，因为很多接口其实不是json
> 
> 我这边几乎没有导出dubbo文档到yapi的需求, 所以不是特别清楚你们希望导出的文档是什么样的.
> 有没有可能举几个例子?
> 例如接口方法是什么样的，导出的yapi是什么样的?

@tangcent  生成的dubbo接口文档如果GET的请求，不会生成body，能否将GET的参数自动补到path后面，举例如下：
接口路径：https://domain/project/function/business?a=&b=&c=
接口请求方式：GET

其中接口路径里的?a=&b=&c=为入参，目前使用@path，并且请求方式是GET的话，不会自动生成入参

**Comment by simonpdh** [comment]
> 感谢，希望后续能支持content_type自定义，因为很多接口其实不是json


@tangcent 现在rpc接口支持自定义content-type了吗？

**Comment by tangcent** [comment]
hello, 受`yapi`影响: 提交时`content-type`会被`yapi`根据请求方式重置掉。
https://github.com/YMFE/yapi/blob/ed6771a25a5437562f6a7c277d86a778436a0769/client/containers/Project/Interface/InterfaceList/InterfaceEditForm.js#L268-L305
所以我一直没对`content-type`提供自定义规则。

---

目前对于`rpc`的支持是这样的: http://easyyapi.com/framwork/dubbo.html
总的来说，如何```将rpc转换为http```的问题依旧存在, 没有一套通用的标准。
需要根据自己的理解来配置: http://easyyapi.com/documents/generic.html
这可能不好用，但目前我还没有想到更好的解决方案。

**Comment by simonpdh** [comment]
> 据自己的理解来配

我需要指定dubbo接口的content-type如何配置

**Comment by tangcent** [comment]
> 指定dubbo接口的content-type

``````
method.content.type=groovy:```
    //判断是不是dubbo
    if(!it.containingClass().name().endsWith("Client")){
        return
    }
    return "application/json"
```
``````

> http的server.servlet.context-path 

可以修改这两个配置:
https://github.com/tangcent/easy-yapi/blob/f0253edc65fb71ab99da26cbaf6661add3d5d27c/third/dubbo.config#L3-L8
如果是需要给所有dubbo导出的api加前缀，可以这样配:
``````
class.prefix.path=groovy:```
    //判断是不是dubbo
    if(!it.name().endsWith("Client")){
        return
    }
    return "/dubbo"
```
``````

**Comment by simonpdh** [comment]
> 指定dubbo接口的content-type

**Comment by simonpdh** [comment]
> > 指定dubbo接口的content-type
> 
> ```
> method.content.type=groovy:```
>     //判断是不是dubbo
>     if(!it.containingClass().name().endsWith("Client")){
>         return
>     }
>     return "application/json"
> ```
> ```
> 
> > http的server.servlet.context-path
> 
> 可以修改这两个配置:
> 
> https://github.com/tangcent/easy-yapi/blob/f0253edc65fb71ab99da26cbaf6661add3d5d27c/third/dubbo.config#L3-L8
> 
> 
> 如果是需要给所有dubbo导出的api加前缀，可以这样配:
> ```
> class.prefix.path=groovy:```
>     //判断是不是dubbo
>     if(!it.name().endsWith("Client")){
>         return
>     }
>     return "/dubbo"
> ```
> ```


dubbo那个配置只能设置全局的吧，有办法设置单个接口维度吗？跟着get  post走

**Comment by tangcent** [comment]
> dubbo那个配置只能设置全局的吧，有办法设置单个接口维度吗？跟着get post走

我不能完全确定你的想法。
目前配置里是这样判断是否用`GET`的。
https://github.com/tangcent/easy-yapi/blob/f0253edc65fb71ab99da26cbaf6661add3d5d27c/third/dubbo.config#L9-L11

所以也许你的想法是这样?
``````
method.content.type=groovy:```
    //判断是不是dubbo
    if(!it.containingClass().name().endsWith("Client")){
        return
    }
    return (it.argCnt()==0||it.args().every{it.type().isNormalType()})?null:"application/json"
```
``````

**Comment by tangcent** [comment]
那配置
```
method.content.type=#Content-Type
```
试试

**Comment by simonpdh** [comment]
> application/json

感谢感谢，dubbo和http接口用这个配置都可以了，还有一个问题需要请教下你，每个含http接口的应用都有server.servlet.context-path，但生成的接口默认是不会带上server.servlet.context-path指定的路径的，如果我想加上在生成的接口文档默认带上server.servlet.context-path的路径该如何配置，dubbo的不存在这个问题，http的存在

**Comment by tangcent** [comment]
推荐配置里有这个:
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/17569144/162946929-4976e9d6-7e03-4f7e-a793-f242a1d17489.png">

<img width="968" alt="image" src="https://user-images.githubusercontent.com/17569144/162946821-c022195e-bd71-4ea0-9ea9-d59337d5e9a8.png">

---

http://easyyapi.com/setting/rules/class_prefix_path.html

**Comment by simonpdh** [comment]
> 推荐配置里有这个: <img alt="image" width="1011" src="https://user-images.githubusercontent.com/17569144/162946929-4976e9d6-7e03-4f7e-a793-f242a1d17489.png">
> 
> <img alt="image" width="968" src="https://user-images.githubusercontent.com/17569144/162946821-c022195e-bd71-4ea0-9ea9-d59337d5e9a8.png">
> 
> http://easyyapi.com/setting/rules/class_prefix_path.html

按找图中配置后生成的接口地址未带server.servlet.context-path指定的前缀

**Comment by tangcent** [comment]
> 按找图中配置后生成的接口地址未带server.servlet.context-path指定的前缀，easyYapi版本 2.3.1.183.0

我不能确定这个原因。

1. 有可能是这里的逻辑有问题或者不匹配你的项目, 比如你的`controller`模块中并不存在`application`配置?
https://github.com/tangcent/easy-yapi/blob/f0253edc65fb71ab99da26cbaf6661add3d5d27c/idea-plugin/src/main/resources/.recommend.easy.api.config#L213-L215
2. 你使用的是`application.yaml`?
目前对于`yaml`的解析兼容性不是很好，比如`yaml`中存在占位符的情况`xx : {xxx}`会导致无法解析，
你如果有好的想法，可以讨论一下。
https://github.com/Earth-1610/intellij-kotlin/blob/a87d071e72c88117f526f6c63de0682ffd913218/intellij-idea/src/main/kotlin/com/itangcent/intellij/config/AbstractConfigReader.kt#L296-L312

---

如果内置的解决方案无效，你可以直接配置`class.prefix.path`来达到你的目的:
```
class.prefix.path=/xxx
```

**Comment by simonpdh** [comment]
> > 按找图中配置后生成的接口地址未带server.servlet.context-path指定的前缀，easyYapi版本 2.3.1.183.0
> 
> 我不能确定这个原因。
> 
> 1. 有可能是这里的逻辑有问题或者不匹配你的项目, 比如你的`controller`模块中并不存在`application`配置?
>    https://github.com/tangcent/easy-yapi/blob/f0253edc65fb71ab99da26cbaf6661add3d5d27c/idea-plugin/src/main/resources/.recommend.easy.api.config#L213-L215
> 2. 你使用的是`application.yaml`?
>    目前对于`yaml`的解析兼容性不是很好，比如`yaml`中存在占位符的情况`xx : {xxx}`会导致无法解析，
>    你如果有好的想法，可以讨论一下。
>    https://github.com/Earth-1610/intellij-kotlin/blob/a87d071e72c88117f526f6c63de0682ffd913218/intellij-idea/src/main/kotlin/com/itangcent/intellij/config/AbstractConfigReader.kt#L296-L312
> 
> 如果内置的解决方案无效，你可以直接配置`class.prefix.path`来达到你的目的:
> 
> ```
> class.prefix.path=/xxx
> ```

我的项目配置符合这个 properties.additional=${module_path}/src/main/resources/application.properties 

刚才试了下直接配置这个也不行（class.prefix.path=/xxx）

**Comment by tangcent** [comment]
我没办法复现你这个问题。
<img width="738" alt="image" src="https://user-images.githubusercontent.com/17569144/163404450-b28e7f93-6f1d-48b1-8b75-d2755af1dda7.png">

**Comment by simonpdh** [comment]
> 我没办法复现你这个问题。 <img alt="image" width="738" src="https://user-images.githubusercontent.com/17569144/163404450-b28e7f93-6f1d-48b1-8b75-d2755af1dda7.png">

我加你微信了，我把配置截图给你看下
