### ISSUE TITLE
关于泛型参数的几个问题

### ISSUE THREAD

**Issue by ulyn** [tangcent/easy-yapi#255]
**Describe the bug**
对泛型参数的支持程度是怎么样？期望大牛们能支持一下。

1. 对于泛型List入参解析有问题
```
  @PostMapping("/delete")
    public Result<Boolean> delete(@RequestBody List<Integer> userIds) {
        return Result.of(true);
    }
```
![image](https://user-images.githubusercontent.com/3728320/93955337-177f0e80-fd82-11ea-951f-77772add706a.png)

2. 对于复杂泛型参数解析有遗漏

```
    @PostMapping("/list")
    public ShareListResponse<UserSearch, UserSearchResult> searchUser(@RequestBody ShareListRequest<UserSearch> request){
        return (ShareListResponse) listDataEngine.query("user", request);
    }

@Data
public class ShareListResponse<I, O> {

    String schemeId;
    PageOut page;
    List<O> list;
    boolean fromCache;
    LocalDateTime cacheTime;
    ShareListRequest<I> request;
}
@Data
public class PageOut {

    int currentPage;
    int linesPerPage;
    long totalNum;
    int totalPage;
}

@Data
public class ShareListRequest<I> {

    private PageIn page;
    private I data;
    private boolean ignoreCache = false;
}
@Data
public class PageIn {

    int currentPage = 1;
    int linesPerPage = 10;
    List<OrderBy> orderBys = new ArrayList<>();
}
@Data
public class OrderBy {
    String sortField;
    String sortType = "asc";
}
```
![image](https://user-images.githubusercontent.com/3728320/93955686-e2bf8700-fd82-11ea-82e6-91b7d98814fb.png)

**Comment by tangcent** [comment]
> 1. 对于泛型List入参解析有问题

关于List的解析，可以先尝试手动在yapi中录入，看看效果:
![image](https://user-images.githubusercontent.com/17569144/93959101-895b5600-fd8a-11ea-8fc5-c7943c743d97.png)

**Comment by tangcent** [comment]
> 2. 对于复杂泛型参数解析有遗漏
这里可能与泛型解析无关, 可以尝试关闭推荐配置中的`#only keep private/protected field`,
推荐配置中默认只处理`private/protected`字段
- <kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd>
![image](https://user-images.githubusercontent.com/17569144/93962015-5c0fa780-fd8c-11ea-8be1-0ec4838bbe94.png)

**Comment by ulyn** [comment]
感谢回复！

第一个问题是我理解有误，yapi中这样显示是对的。
第二个问题，按你说的关闭推荐配置中的#only keep private/protected field, 有效果。看起来是不能省去private了？这算不算是个BUG？
![image](https://user-images.githubusercontent.com/3728320/93973688-3643cc00-fda7-11ea-89f2-875eb5d7c319.png)

**Comment by tangcent** [comment]
- wow~ 这个一开始纯粹是我一直遵循的规则:POJO所有属性为private
后来扩展了`推荐配置`这个功能后将所有非`spring`核心的解析之外的处理尽量迁移到了`推荐配置`中
目前来说主要是为了保持插件的一致性，防止插件升级后字段不一致.
- 考虑在未来找个机会移除此推荐.

**Comment by ulyn** [comment]
感谢 easy-yapi开源给我们带来的便利
