### ISSUE TITLE
SpringMvc 接口上有常量 可以解析吗？@RequestMapping(VERSION_1 + "/test")

### ISSUE THREAD

**Issue by qinkangdeid** [tangcent/easy-yapi#257]
## IDEA版本
- 2020.2

## yapi版本

- 版本: 1.9.2

## easy-yapi版本

- 2.0.3.0.183.0

现在有这样一个需求

目前接口做版本化的做法是在请求url加上一个version前缀 例如  /xxx/v1/test  这个v1 我们做成了一个常量字符串：VERSION_1

所以在写Controller的时候 引用了这个字符串作为 接口的一部分：
```java

@RestController
@RequestMapping(VERSION_1 + "/test")
public class TestController {

    @PostMapping("/t")
    public DataResponse<String> t() {
        return ok();
    }

}

```
目前生成的api地址会带着这个常量名 而不是具体的值 请问能够支持这样的写法吗？ 

![image](https://user-images.githubusercontent.com/17582522/94400712-24459d00-019c-11eb-8f1c-e3c243461462.png)

**Comment by tangcent** [comment]
fixed by https://github.com/tangcent/easy-yapi/releases/tag/v2.0.4
