### ISSUE TITLE
org.springframework.data.domain.Pageable 做为分页参数，不能被导出

### ISSUE THREAD

**Issue by laocui** [tangcent/easy-yapi#258]
如题，该怎么处理

**Comment by tangcent** [comment]
处理泛型信息时没考虑纯接口参数

**Comment by laocui** [comment]
用这个办法完美解决了
method.additional.param[groovy:it.defineCode().contains("Pageable")]={name: "page",value: "0",desc: "第几页, 从0开始, 默认0",required:false}
method.additional.param[groovy:it.defineCode().contains("Pageable")]={name: "size",value: "20",desc: "每页数据条数, 默认20",required:false}
method.additional.param[groovy:it.defineCode().contains("Pageable")]={name: "sort",value: "id,desc",desc: "按属性排序, 格式:属性名[,asc|desc],通常返回值中的一级属性均可用于排序",required:false}

**Comment by batizhao** [comment]
config
```
method.return=#real_return
method.return[#real_return]=groovy: helper.resolveLink(it.doc("real_return"))
```

class
`@real_return R<Pageable<XXX>>`

**Comment by tangcent** [comment]
@batizhao If you encounter a problem, please create a new issue.
