### ISSUE TITLE
可否支持Jackson 中PropertyNamingStrategy

### ISSUE THREAD

**Issue by hao-lele-xia** [tangcent/easy-yapi#262]
在上传yapi时，有些类的字段特别多，在类上直接使用了PropertyNamingStrategy，但目前的easy-yapi没法识别此注解，需要手动一个一个地添加

**Comment by tangcent** [comment]
easy-yapi的配置很灵活，相对的，初次配置的话需要理解一下:
- 规则
http://easyyapi.com/setting/rules/json_rule_field_name.html
- 工具
http://easyyapi.com/setting/tools.html

- 例如这里如果配置字段名首字母大写，大概是这样子:
```properties
#Support for Jackson annotations
json.rule.field.name[@com.fasterxml.jackson.annotation.PropertyNamingStrategy.CamelCase]=groovy:tool.capitalize(it.name())
```

**Comment by hao-lele-xia** [comment]
> easy-yapi的配置很灵活，相对的，初次配置的话需要理解一下:
> 
> * 规则
>   http://easyyapi.com/setting/rules/json_rule_field_name.html
> * 工具
>   http://easyyapi.com/setting/tools.html
> * 例如这里如果配置字段名首字母大写，大概是这样子:
> 
> ```ini
> #Support for Jackson annotations
> json.rule.field.name[@com.fasterxml.jackson.annotation.PropertyNamingStrategy.CamelCase]=groovy:tool.capitalize(it.name())
> ```

主要是Jackson注解在类上，而不是字段上面，比如：

@JsonNaming(PropertyNamingStrategy.SnakCaseStrategy.class)
public class Student{
   private Integer stuId;
   private String stuName;
}

在上传yapi的过程中，我杨把stuId，映射成stu_id这种，这种怎么配置呢，求教大神。

**Comment by hao-lele-xia** [comment]
> > easy-yapi的配置很灵活，相对的，初次配置的话需要理解一下:
> > 
> > * 规则
> >   http://easyyapi.com/setting/rules/json_rule_field_name.html
> > * 工具
> >   http://easyyapi.com/setting/tools.html
> > * 例如这里如果配置字段名首字母大写，大概是这样子:
> > 
> > ```ini
> > #Support for Jackson annotations
> > json.rule.field.name[@com.fasterxml.jackson.annotation.PropertyNamingStrategy.CamelCase]=groovy:tool.capitalize(it.name())
> > ```
> 
> 主要是Jackson注解在类上，而不是字段上面，比如：
> 
> @JsonNaming(PropertyNamingStrategy.SnakCaseStrategy.class)
> public class Student{
> private Integer stuId;
> private String stuName;
> }
> 
> 在上传yapi的过程中，我杨把stuId，映射成stu_id这种，这种怎么配置呢，求教大神。

**Comment by hao-lele-xia** [comment]
十分感谢@tangcent 的提醒，我找到了一个比较笨的方法，就是配置
json.rule.field.name=groovy:```
public def trans(input){
  //转换成下划线的逻辑
  return result;
}
return trans(it.name())
```

不过这种方法不灵活，不知道大神有什么更加灵活的配置

**Comment by tangcent** [comment]
试试:
``````
field.name[groovy:it.containingClass().ann("com.fasterxml.jackson.databind.annotation.JsonNaming")=="com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy"] = groovy:it.name().collect{c -> ((char)c).isUpperCase() ? '_' + c.toLowerCase() : c}.join('')
``````
