### ISSUE TITLE
配置页面打不开

### ISSUE THREAD

**Issue by AbenrE** [tangcent/easy-yapi#269]
最新版本的2.0.4.183.0配置Easy Yapi的页面打不开，换了之前的版本2.0.3.0.183.0后能打开
idea 是2019.3.5的

**Comment by tangcent** [comment]
merge错误

**Comment by tangcent** [comment]
release: https://github.com/tangcent/easy-yapi/releases/tag/v2.0.5
plugin: https://github.com/tangcent/easy-yapi/releases/download/v2.0.5/easy-yapi.2.0.5.183.0.jar
