### ISSUE TITLE
可以自定义处理的注解吗？

### ISSUE THREAD

**Issue by peng051410** [tangcent/easy-yapi#27]
可以自定义处理的注解吗？我们的项目没有使用Spring的那些注解，但是大体表现形式上是一样，这样的我要怎么扩展一下呢？

**Comment by tangcent** [comment]
- 抱歉，目前核心解析api使用的是spring的注解
代码如下:[SpringClassExporter](https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SpringClassExporter.kt)
- 我考虑过提供配置定制化此部分核心的解析:
  - api.method
  - api.path
  - api.contentType
  - param.isHeader
  - param.isPath
- 但是我担心的是进行这些配置的复杂度以及完整性
- 所以一个解决方案是fork后按照ClassExporter给出自定义实现
- 如果对SpringClassExporter中的代码有不清楚的地方，可以随时在这里评论或者邮件给我
- 如果你觉得提供相应核心解析的配置支持很有用的话，也可以告诉我，不过这可能需要一点时间来实现

**Comment by peng051410** [comment]
我看了一下SpringClassExporter的实现，目前我对Idea的插件开发不是很清楚，如果我自己实现一个解析其它注解的Exporter的话都需要修改哪些配置呢？我看了一下是需要将ApiExportAction中的"delegate_classExporter"的值修改成我自定义的Export就可以吗？还是会有其它地方的修改？

**Comment by tangcent** [comment]
- 呃，抱歉，我昨天晚上提交一次Comment，但是看起来好像没有成功
- 今天只能写简单点啦~总的来说大部分逻辑，包括注释的处理都无需修改,只需要修改spring相关的代码就可以了

- 首先是修改读RequestMapping的代码，主要是获取HttpMethod和Path

https://github.com/tangcent/easy-yapi/blob/21eb817e07dae071b70eb6403b666ca0b4e0eef1/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SpringClassExporter.kt#L121-L132

- 然后是处理参数的代码

https://github.com/tangcent/easy-yapi/blob/21eb817e07dae071b70eb6403b666ca0b4e0eef1/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SpringClassExporter.kt#L406-L481

   - 这里发现RequestBody,contentType会处理为application/json
   - 发现File参数,contentType会处理为multipart/form-data
   - 其他情况contentType会处理为application/x-www-form-urlencoded

**Comment by peng051410** [comment]
好的，我试试，非常感谢

**Comment by tangcent** [comment]
Hi,你的问题解决了吗?
- 我有个想法, 当前插件有提供[groovy配置](https://github.com/tangcent/easy-yapi/wiki/%E6%94%AF%E6%8C%81%E7%9A%84%E9%85%8D%E7%BD%AE%E8%A7%84%E5%88%99),所以我在想如果提供在配置中允许加载独立的groovy脚本,例如
`import.files=./yapi/scripts`,那么可以在脚本中使用groovy实现高度定制化的ClassExporter以满足使用者的特殊需要，又可以自由升级插件，获得插件升级的功能。
- 我在认真考虑可行性,期待你的想法

**Comment by peng051410** [comment]
可以啊，我还在学习kotlin，准备这周开始弄了，你这语言储备相当可以👍

**Comment by tangcent** [comment]
- 这恰恰是问题所在, kotlin还是需要一点学习成本的。
而groovy对于java开发者来说学习成本近乎于0,而用过gradle的开发者多多少少都算接触过groovy了。
所以支持groovy的话，对于有定制化需求的开发者来说，开发定制功能会容易很多。
- 对于groovy的支持我已经完成了初始化，加载，解析，注入。接下来将改造部分核心功能使其易于通过继承来扩展行为.
- 预计这周可以完成.你看情况吧，如果对kotlin有兴趣，可以继续用kotlin试试。也可以选择等待groovy的扩展功能。

**Comment by peng051410** [comment]
好的，非常感谢！

**Comment by tangcent** [comment]
- 支持了使用本地groovy扩展插件行为
- 可惜的是由于插件本身是kotlin写的，对于kotlin不熟悉的话，可能无法正确的理解kotlin类生成的class中结构，这导致书写groovy扩展并不简单
- 好处是在不需要二次开发的前提下,能够支持更多的自定义功能
- demo: https://github.com/tangcent/spring-demo/blob/master/.easyapi/ext/YapiExportActionExt.groovy
- 有任何问题或想法，你可以随时提交一个新的issue
