### ISSUE TITLE
Postman能否支持导出到自定义workspace？

### ISSUE THREAD

**Issue by gcdd1993** [tangcent/easy-yapi#283]
# 需求
我在postman中有多个以项目名划分的workspace，希望导出到postman时，能够导出至指定的workspace

# 可行性分析
目前EasyYapi的导出到postman 使用的接口为`https://api.getpostman.com/import/exported`，只支持导出至默认的workspace。Postman Api中提供了以下几个接口，通过组合使用，或许能完成这个功能。
- Create a Fork：`https://api.getpostman.com/collections/fork/{{collection_uid}}?workspace={{workspace_id}}`
- Merge a Fork：`https://api.getpostman.com/collections/merge`
- Delete Collection：`https://api.getpostman.com/collections/{{collection_uid}}`

# 可行步骤
1、导出至默认workspace
2、创建fork到目标workspace，`{{collection_uid}}`为刚创建的`collection_uid`
3、合并merge
4、删除最开始创建的默认workspace中的collection

@tangcent 您看下是否可行？

**Comment by tangcent** [comment]
see  [Create Collection](https://documenter.getpostman.com/view/631643/JsLs#99810ef3-3cc0-a6cc-06f5-d8e2ae9d84e4)
![image](https://user-images.githubusercontent.com/17569144/98541426-6816e080-22ca-11eb-9415-da8356c8095f.png)


---

这个参数或许有用. 不过这里麻烦的是开发者获取workspace的id比较麻烦
所以这里可能需要弹出一个窗口选择目标workspace.
然后使用 [Create Collection](https://documenter.getpostman.com/view/631643/JsLs#99810ef3-3cc0-a6cc-06f5-d8e2ae9d84e4)来完成api的导出.

**Comment by gcdd1993** [comment]
一般来说，一个项目应该只会导出至同一个workspace，所以应该可以在配置界面添加本项目所属workspace的uid就可以了

**Comment by tangcent** [comment]
Good idea. 也许做成可填可下拉比较方便.

**Comment by tangcent** [comment]
如果你有时间, 愿意尝试一下，我可以把这个issue assign给你，等你提交PR.

**Comment by gcdd1993** [comment]
@tangcent 我周末研究一下，提个pr
