### ISSUE TITLE
导出Postman的Example信息没有注释的，需要怎么配置才有注释信息呢

### ISSUE THREAD

**Issue by q405161779** [tangcent/easy-yapi#284]
![image](http://user-images.githubusercontent.com/33777928/98659408-082e4180-237f-11eb-8ff8-d6da09cdda24.png)

**Comment by tangcent** [comment]
这里注释要怎么写合适? 有个例子吗?

**Comment by q405161779** [comment]
![Uploading image.png…]()

**Comment by tangcent** [comment]
wow, 我尝试更新了Postman，最新版本看起来有对json5的支持.
see #285
