### ISSUE TITLE
Spring Web接口继承的问题

### ISSUE THREAD

**Issue by CobraStarLE** [tangcent/easy-yapi#289]
我把@PostMapping类似的注解写在了一个接口中，然后我再用一个类（类有注解@RestController）去实现这个接口，你们能否实现根据这个类去生成文档？
谢谢！

**Comment by tangcent** [comment]
不是很理解, 类似这个? https://github.com/Earth-1610/spring-demo/blob/master/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/BaseController.java

**Comment by CobraStarLE** [comment]
您好，我看了您提供的代码，我想要的和你提供的差不多，只不过您那边的controller继承的是一个公共类BaseController，而我这边的controller实现的是一个公共api接口，在我这边生成文档的时候就变成了这个样子
<img width="842" alt="image" src="https://user-images.githubusercontent.com/30492390/100400895-e3321200-3092-11eb-9c39-e10ba80d1aa0.png">，接口地址是有问题的，不过生成的请求参数和返回参数是没问题的。

**Comment by tangcent** [comment]
wow, 看起来也是这个问题 https://github.com/tangcent/easy-yapi/issues/290#issuecomment-734181765

因为没有注解`org.springframework.web.bind.annotation.RestController`或是`org.springframework.stereotype.Controller`
被当做rpc类做导出了.
