### ISSUE TITLE
有更详细的说明文档吗

### ISSUE THREAD

**Issue by zhenglzh** [tangcent/easy-yapi#290]
如何把本地的api 一键上传到 远程yapi上

**Comment by tangcent** [comment]
http://easyyapi.com/documents/export2yapi.html

**Comment by zhenglzh** [comment]
> http://easyyapi.com/documents/export2yapi.html

这个的搜索逻辑是怎么样的，比如spring boot项目中，路劲写在接口层旧没办法被提取出来
![image](https://user-images.githubusercontent.com/45551992/100331045-a6223d00-300a-11eb-8a29-e74c22ceba69.png)

![image](https://user-images.githubusercontent.com/45551992/100331113-bb976700-300a-11eb-9eb0-76e1f1bb3fb9.png)

**Comment by tangcent** [comment]
这里只处理了有注解`org.springframework.web.bind.annotation.RestController`或是`org.springframework.stereotype.Controller`的类

https://github.com/tangcent/easy-yapi/blob/4480e34187ff0ae1e5d91b6ca5af9d2882b9a1b4/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/SpringRequestClassExporter.kt#L43-L47
