### ISSUE TITLE
@method=GET结合@path使用时不会自动生成入参

### ISSUE THREAD

**Issue by simonpdh** [tangcent/easy-yapi#291]
生成的dubbo接口文档如果GET的请求，不会生成body，能否将GET的参数自动补到path后面，举例如下：
接口路径：https://domain/project/function/business?a=&b=&c=
接口请求方式：GET

其中接口路径里的?a=&b=&c=为入参，目前使用@path，并且请求方式是GET的话，不会自动生成入参，或者能不能不区分请求的方式，所有的入参都生成body，这样会直观些
@tangcent

**Comment by tangcent** [comment]
能否尝试给一个demo?
导出为markdown还是yapi?

**Comment by simonpdh** [comment]
> 能否尝试给一个demo?
> 导出为markdown还是yapi?

导出到yapi

demo如下：
入参为：a,b,c三个参数

当前情况：
接口路径：https://domain/project/function/business
接口请求方式：GET
生成文档无任何入参

期望结果(两者之一)：
1、
接口路径：https://domain/project/function/business?a=&b=&c=
接口请求方式：GET

2、
接口路径：https://domain/project/function/business
接口请求方式：GET
body:{
a:123,
b:234,
c:456
}
