### ISSUE TITLE
如何进行全局统一返回对象设置

### ISSUE THREAD

**Issue by 18256086350** [tangcent/easy-yapi#296]
有这样的场景，麻烦大佬给与解答：
    springboot工程，通过aop做全局的统一结果处理，统一对象定义如下，其中data是每个接口返回的对象。

@ApiModel(value = "接口返回统一对象")
public class Response implements Serializable {

    @ApiModelProperty(value = "是否成功")
    private boolean success=true;
    @ApiModelProperty(value = "接口响应状态码")
    private Integer statusCode;
    @ApiModelProperty(value = "接口错误信息")
    private String message;
    @ApiModelProperty(value = "接口查询时间")
    private Long spendTime;
    @ApiModelProperty(value = "返回结果")
    private Object data;

如何在配置文件进行配置，使得上传到yapi中的接口返回参数描述正确，即data是每个接口返回对象的描述

**Comment by mostcool** [comment]
同问

**Comment by tangcent** [comment]
see [method.return](http://easyyapi.com/setting/rules/method_return.html)

如果封装的返回对象有泛型的话比较容易配置,类似于这样:
```properties
method.return=groovy:"com.itangcent.common.dto.Result<" + it.returnType().toString() + ">"
```

---

如你这样`Response`中的`data `使用`Object`而不是泛型的目前难以配置
结合[method.return](http://easyyapi.com/setting/rules/method_return.html)和[json.rule.convert](http://easyyapi.com/setting/rules/json_rule_convert.html)可以勉强实现, 但过于复杂.
我需要考虑一下如何提供对这种情况的支持.
