### ISSUE TITLE
导出接口到YAPI

### ISSUE THREAD

**Issue by qzbaozi** [tangcent/easy-yapi#298]
不能读取接口上的注解

`
@RequestMapping(value = "file")
public interface FileCtrlInter {
    /**
     * 增加新用户(上传头像)
     */
    @PostMapping("/add")
    IResult add(@RequestBody UserDto userDto);
}

[INFO]	Start find apis...
[TRACE]	find config file:E:\work\project\spring-demo\cn
[INFO]	use recommend config
[INFO]	ignore class:com.itangcent.springboot.demo.controller.FileCtrlInter
[INFO]	Apis exported completed

Process finished with exit code 0
`

**Comment by tangcent** [comment]
see https://github.com/tangcent/easy-yapi/issues/292

需要配置[class.is.ctrl](http://easyyapi.com/setting/rules/class_is_ctrl.html)
根据你的代码特征，可以尝试配置为

```
class.is.ctrl=groovy:it.name().endsWith("CtrlInter")
```
