### ISSUE TITLE
这内存。。

### ISSUE THREAD

**Issue by zhusaidong** [tangcent/easy-yapi#299]
**Describe the bug**
![image](https://user-images.githubusercontent.com/3039961/102464547-6d183e00-4087-11eb-8c39-5db3153b805f.png)

**Comment by tangcent** [comment]
可能是尝试推断api返回导致资源占用过多的问题.
你可以尝试关闭智能推断后再试.

http://easyyapi.com/setting/ide-setting.html

![image](https://user-images.githubusercontent.com/17569144/86461766-0fa06700-bd5d-11ea-8f4d-691cc55afa0d.png)

**Comment by zhusaidong** [comment]
取消勾选，确实好了。建议加个提示，或者默认不勾选
