### ISSUE TITLE
M1 mac idea2020.3 版本使用时输入了服务器和token还是没有项目

### ISSUE THREAD

**Issue by JQKAHZ** [tangcent/easy-yapi#304]
![image](https://user-images.githubusercontent.com/41499158/103964284-07a30300-5196-11eb-98d7-5622acb3f9d4.png)

**Comment by tangcent** [comment]
`yapi`的`token`配置格式:`module=token`:
```
#
#Thu Nov 26 19:59:14 CST 2020
user=fdbf44d5a8afb77127a8eab2443390d4d1a7bf420b4e03caa2128d44d76852cb

```
`yapi`的`token`配置正确的话，打开`YapiDashBoard `时，控制台应该会输出token加载:
```
[INFO]	load token:fdbf44d518afb77122a8eab24433s0d4d1a7bf420b4e03caa2128d44d76852c
```

**Comment by JQKAHZ** [comment]
控制台输出token加载信息但是还是没有反应
![image](https://user-images.githubusercontent.com/41499158/104091350-d02c7780-52b7-11eb-9c51-112c04fdc14e.png)
![image](https://user-images.githubusercontent.com/41499158/104091355-dc183980-52b7-11eb-8554-6363800df0f3.png)

**Comment by JQKAHZ** [comment]
控制台输出token加载信息但是还是没有反应
[TRACE]	No config be found
[INFO]	use recommend config
[INFO]	search api XXXXXxXXXXX
[INFO]	load token:3e6fecbd0910f5ac7c2692bd68dfd849a074XXXXXXX
[TRACE]	No config be found
[INFO]	use recommend config
[TRACE]	No config be found
[INFO]	use recommend config

**Comment by tangcent** [comment]
可以尝试在项目最外面添加[配置](http://easyyapi.com/setting/rules/http_call_before.html):
```
http.call.before=groovy:logger.info("call:"+request.url())
```
控制台输出:
```
[INFO]	load token:fdbf44d518afb77122a8eab24433s0d4d1a7bf420b4e03caa2128d44d76852c
[INFO]	call:http://127.0.0.1:3000/api/project/get?token=fdbf44d518afb77122a8eab24433s0d4d1a7bf420b4e03caa2128d44d76852c&id=279
[INFO]	call:http://127.0.0.1:3000/api/interface/list_cat?token=fdbf44d518afb77122a8eab24433s0d4d1a7bf420b4e03caa2128d44d76852c&catid=3624&limit=1000
```
可以手动访问这里出现的url，看看是否可访问.

**Comment by JQKAHZ** [comment]
可以访问，但是还是不行  
[TRACE] No config be found
[INFO] use recommend config

**Comment by tangcent** [comment]
以目前提供的信息实在无法重现，你可以尝试使用其他插件.
