### ISSUE TITLE
kotlin+spring-boot controller 添加任意@描述 导出 yapi 时每次都会创建新的文件夹

### ISSUE THREAD

**Issue by EarthChen** [tangcent/easy-yapi#312]
# 环境
- idea 2020.3.1
- easyyapi 2.1.0.183.0

#  问题1: kotlin controller 添加任意@描述 导出 yapi 时每次都会创建新的文件夹

使用 kotlin 在类上添加任意@注释时导出均会创建新文件夹

## eg1
```kotlin
/**
 * test
 *
 * @module APP
 * @author earthchen
 * @date 2021/1/12
 */
@RestController
@RequestMapping("/test")
class TestController {
    /**
     * test1
     *
     * @return
     */
    @GetMapping
    fun test1(): JsonResult<String> {
        return success("ok")
    }
}
```

## eg2
```
/**
 * test
 *
 * @author earthchen
 * @date 2021/1/12
 */
@RestController
@RequestMapping("/test")
class TestController {
    /**
     * test1
     *
     * @return
     */
    @GetMapping
    fun test1(): JsonResult<String> {
        return success("ok")
    }
}
```

>- java 版不会重复创建文件夹
![image](https://user-images.githubusercontent.com/20179425/104295864-efb3e200-54fb-11eb-92f4-d806b14e280e.png)

## yapi

导出日志 
![image](https://user-images.githubusercontent.com/20179425/104295981-14a85500-54fc-11eb-8a2e-cb9212fc4fe6.png)

# 问题2：@module xxx 语法当xxx在 yapi 中不存在时会导致 idea 未响应(不区分 java/kotlin)
```/**
 * test
 *
 * @module xxx
 * @author earthchen
 * @date 2021/1/12
 **/
@RestController
@RequestMapping("/test")
public class TestController {

    /**
     * test1
     *
     * @return
     */
    @GetMapping
    public JsonResult<String> test1() {
        return JsonResult.Companion.success("ok");
    }
}
```

**Comment by tangcent** [comment]
> 问题1: kotlin controller 添加任意@描述 导出 yapi 时每次都会创建新的文件夹

这个是个bug，没有trim的原因

> 问题2：@module xxx 语法当xxx在 yapi 中不存在时会导致 idea 未响应(不区分 java/kotlin)

在 yapi 中不存在是指没有配相应的token?
我这边使用正常，会弹框输入token:
![image](https://user-images.githubusercontent.com/17569144/104321935-3d8e1180-551f-11eb-9ef2-5c54ce02ebc1.png)

**Comment by EarthChen** [comment]
> > 问题1: kotlin controller 添加任意@描述 导出 yapi 时每次都会创建新的文件夹
> 
> 这个是个bug，没有trim的原因
> 
> > 问题2：@module xxx 语法当xxx在 yapi 中不存在时会导致 idea 未响应(不区分 java/kotlin)
> 
> 在 yapi 中不存在是指没有配相应的token?
> 我这边使用正常，会弹框输入token:
> ![image](https://user-images.githubusercontent.com/17569144/104321935-3d8e1180-551f-11eb-9ef2-5c54ce02ebc1.png)

问题2的正常逻辑不是 idea 会弹出输入框 token ？在我本地 idea 会直接未响应(有时候别的情况也会未相应 主要没有日志 无法排查)

**Comment by tangcent** [comment]
需要点时间，调整一下上下文调度逻辑，再加些dev日志
来判断是插件线程调度问题，还是idea UI线程阻塞.

**Comment by EarthChen** [comment]
> 需要点时间，调整一下上下文调度逻辑，再加些dev日志
> 来判断是插件线程调度问题，还是idea UI线程阻塞.

好的  感谢，有时间可否写个文档介绍一下这个工具的整体架构和逻辑  这样有bug 也能debug 能自己解决的就提个pr

**Comment by tangcent** [comment]
close by https://github.com/tangcent/easy-yapi/releases/tag/v2.1.1
