### ISSUE TITLE
对象包含递归字段导出到yapi会丢失递归字段

### ISSUE THREAD

**Issue by zyf8827** [tangcent/easy-yapi#319]
[版本] 2.1.0.183.0
[现象] 返接口返回对象包含递归，导出到yapi后递归字段丢失
![image](https://user-images.githubusercontent.com/5118661/105011340-d0770080-5a77-11eb-9ee0-3cc013b6395e.png)
![image](https://user-images.githubusercontent.com/5118661/105011434-e84e8480-5a77-11eb-97e9-0af23cfafdb7.png)

**Comment by tangcent** [comment]
为了解决递归问题，会缓存已处理过的类型的解析结果.
解析`AreaInfo`会构建`AreaInfo`的缓存，
解析其中的`children`时开始构建`List<AreaInfo>`的缓存，而这时候`AreaInfo`并未解析完毕，导致`List<AreaInfo>`对应的解析结果缺失了`children`
