### ISSUE TITLE
使用real_return导致部分文档无法生成

### ISSUE THREAD

**Issue by Semoz** [tangcent/easy-yapi#322]
使用版本 `2.1.1`

操作系统 `macOS 10.14.6`

IDEA `2019.2.2`

使用配置
```
method.return[#real_return]=groovy: helper.resolveLink(it.doc("real_return"))
```

在接口注释中增加
```
@real_return {@link ApiResult<MyPage<UserPageListVO>>}
```

ApiResult
```
public final class ApiResult<T> {
    private T       result;
    private String  message; 
    private Integer code;
}
```
MyPage
```
public class MyPage<T> {
    private long total = 0;
    private List<T> rows;

    public MyPage(long total, List<T> rows) {
        this.total = total;
        this.rows = rows;
    }
}
```
问题现象
1. 在两个Controller中同样采用real_return的形式返回，通过`Ctrl+E`生成文档
>` @real_return {@link ApiResult<MyPage<UserPageListVO>>}`
>` @real_return {@link ApiResult<MyPage<BookPageListVO>>}`

其中User报错，Book提示成功
```
.
.
[INFO]	use recommend config
[INFO]	search api from:com.company.project.controller.user.UserController
[ERROR]	error to find class:MyPage<UserPageListVO>
[INFO]	try infer return type of method[com.company.project.controller.user.UserController#pageList(com.company.project.controller.user.form.UserPageListForm)]
[INFO]	Export to http://yapi.xxxx.net/project/11/interface/api/cat_66 success
.
.
```
另一个则生成正常

尝试过的方案：
1. 将配置改成method.return=#real_return，使用完整路径描述ApiResult、MyPage、UserPageListVO（正常）
2. 去掉出现问题的MyPage写成`@real_return {@link ApiResult<BookPageListVO>}）`（正常）但这不是我们需要的返回结构
3. 在UserController中直接使用Book的Page返回配置（错误）
4. 在BookController中直接使用User的Page返回配置（正常）
5. 通过Code -> YapiDashBoard 拖动Page到右侧对应目录（正常）

想得到的结果
为什么用Ctrl+E生成Page系列嵌套多层的real_return会出现这种奇怪的现象，而且不是所有Controller都是失败的？
目前只能使用YapiDashBoard来上传，另一位开发人员使用同样的插件和配置没有任何问题

**Comment by tangcent** [comment]
这里需要配置`qualifiedName`, 否则难以解析类(主要是为了防止潜在的同名类导致的错误的解析).
所以可以尝试注释`qualifiedName`类似于:
```
@real_return {@link com.itangcent.common.dto.ApiResult<com.itangcent.common.dto.MyPage<com.itangcent.common.dto.UserPageListVO>>}
```

**Comment by Semoz** [comment]
已知ApiResult和MyPage整个项目公用且唯一，
UserPageListVO按照一定的命名规范user/pageList的形式命名也可以保证唯一

感觉说不通，为什么CTRL+E无法生成，YapiDashBoard却可以生成
另外原来可以生成代码的BookPageList 目前也提示Error了
如果使用全路径的`qualifiedName `，那这个[real_return](http://easyyapi.com/setting/rules/method_return.html)配置的用意是什么？

**Comment by tangcent** [comment]
> 为什么CTRL+E无法生成，YapiDashBoard却可以生成

这个是由于插件内部缓存问题，为了减少类名解析，做了缓存
也就是`UserPageListVO `在前面的`Controller`处理过了，后面的`Controller`直接拿的是缓存

> 为什么相同的返回格式，其他的Controller可以生成这种结构返回

- 目前对类名的解析逻辑在这: 
https://github.com/Earth-1610/intellij-kotlin/blob/0271ca12e8884194d36392f61ea2c37c66d154c1/intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/DuckTypeHelper.kt#L282-L288
- 插件有处理`import`
ref: https://github.com/Earth-1610/intellij-kotlin/blob/0271ca12e8884194d36392f61ea2c37c66d154c1/intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/DuckTypeHelper.kt#L310-L335

![image](https://user-images.githubusercontent.com/17569144/106210590-0ba8ca80-6202-11eb-875a-2348c777ea1b.png)

- 如上，理论上当注释书写正确，idea提供跳转时，插件亦能通过`import`解析出对应的类.

> 如果使用全路径的qualifiedName ，那这个real_return配置的用意是什么？

实际上最初的用处是为了兼容使用`ResponseBodyAdvice`进行响应自动包装的项目.
如接口方法返回`A`,实际响应为`Result<T>`.

> 已知ApiResult和MyPage整个项目公用且唯一，
UserPageListVO按照一定的命名规范user/pageList的形式命名也可以保证唯一

- 我尝试一下，看能不能通过shortName拿到对应的类,
- 另外也考虑提供设置全局解析路径的规则, 比如 
   - `global.import=com.itangcent.dto,com.itangcent.vo,com.itangcent.model.*`
   - `global.import=com.itangcent.dto.UserDTO`


---

能否较为完全的提供你目前遇到的不能解析的代码(只需要部分结构&注释即可，不需要具体方法内容)

**Comment by Semoz** [comment]
根据你的描述，我仔细检查了下代码，发现了问题所在
在出现CTRL+E错误的Controller文件中发现VO所在的包 是以通配符的形式引入的
 ``` 
import com.company.project.vo.user.*; 
```
没有出错的Controller文件是
 ``` 
import com.company.project.vo.book.*;
import com.company.project.vo.book.BookPageListVO;
```

做过测试，只要加上 
``` 
import com.company.project.vo.book.UserPageListVO;
```
UserController就可以通过CTRL+E就可以生成PageList的文档了，非常感谢

---
进一步考虑了下
问题：同一个文件，头部引入`import com.company.project.vo.user.*; `的情况下，两层结构例如`@real_return {@link ApiResult<UserPageListVO>}）`是可以正常生成文档的，再加一层Page就解析失败了，是否可以考虑优化？

解决方法：结合开发习惯，我会开启IDEA自动引入class，要解决这个问题，需要将默认的`Class count to use import with '*' `和 `Names count to use static import with '*' `设置为 `9999`，就避免了自动合并成`*`

**Comment by tangcent** [comment]
有点奇怪, 按说这里有处理通配符`import xxx.*`:
https://github.com/Earth-1610/intellij-kotlin/blob/0271ca12e8884194d36392f61ea2c37c66d154c1/intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/DuckTypeHelper.kt#L327-L332

**Comment by tangcent** [comment]
找到这个bug了
