### ISSUE TITLE
参数在query string中的时候，没有类型

### ISSUE THREAD

**Issue by Willing-Xyz** [tangcent/easy-yapi#323]
参数在query string的时候，没有类型：
![image](https://user-images.githubusercontent.com/12200332/106226984-5dae1800-6223-11eb-952d-1c609c293899.png)
参数在body的时候，有类型：
![image](https://user-images.githubusercontent.com/12200332/106227113-9c43d280-6223-11eb-85c3-5137aaa52b50.png)

我知道，因为参数在url或form形式，参数值都是字符串。
可不可以加一个开关，开关打开时，把参数类型加载备注里，例如  `[integer] 备注`

**Comment by tangcent** [comment]
ref: http://easyyapi.com/setting/rules/param_doc.html
