### ISSUE TITLE
Content-Type

### ISSUE THREAD

**Issue by chenshun00** [tangcent/easy-yapi#324]
各个请求头生成场景
 * application/x-www-form-urlencoded
 * multipart/form-data
 * application/json

第三个是使用@RequestBody

请问上边2个一个是 `File` , 一个是正常的 `表单` 吗，我看正常的表单里边也会有 `form-data` 的情况

**Comment by tangcent** [comment]
现在的逻辑是
- `org.springframework.web.bind.annotation.RequestBody`使用`application/json`
- 存在文件的情况下使用:`multipart/form-data`
- 其他情况默认使用`application/x-www-form-urlencoded`

---

有特殊需要的话，可以使用[method.additional.header](http://easyyapi.com/setting/rules/method_additional_header.html)来覆盖默认的`Content-Type`

**Comment by chenshun00** [comment]
good
