### ISSUE TITLE
怎么忽略某个参数，不解析？

### ISSUE THREAD

**Issue by mostcool** [tangcent/easy-yapi#329]
![image](https://user-images.githubusercontent.com/2172570/106547354-0a500880-6548-11eb-9a94-4d094532c940.png)
如图，ModelMap解析不了，报错。所以不想解析它。怎么忽略掉呢？

**Comment by tangcent** [comment]
ref: http://easyyapi.com/setting/rules/param_ignore.html

```
param.ignore=groovy:it.type().name()=="你要忽略的类型qualifiedName"
```

**Comment by mostcool** [comment]
thank you
