### ISSUE TITLE
有支持的dubbo类RPC接口的计划吗

### ISSUE THREAD

**Issue by yintiefu** [tangcent/easy-yapi#33]

**Comment by tangcent** [comment]
- 这个支持倒是不难，就是不大清楚这种RPC接口在yapi里的展示效果
- 可以展示一下你觉得合适的接口在yapi里的效果吗？

**Comment by yintiefu** [comment]
- 去掉部分http协议相关的参数（http_method,header）

- 入参需要指定参数类型

- 请求参数为json结构或者基本类型

- 运行有点麻烦，需要支持连接注册中心，可以先不实现

![image](https://user-images.githubusercontent.com/2860398/62820047-d8e3c000-bb90-11e9-8783-b7080f21fdda.png)

**Comment by tangcent** [comment]
- 基本上都ok
- 只是入参只能使用json来表示，这将导致单参数的时候，看起来颇有些怪异
- 这个功能可能需要进行多个迭代才能用于生产环境

**Comment by yintiefu** [comment]
请求参数为json结构或者基本类型,不是只能用json来表示

**Comment by tangcent** [comment]
假设有这样的类
```java
public interface ADubboClient{
  void addUser(User user);

  //假设这有多个参数
  void addUser(int x,User user);

  void updateName(int id,String name);

  void deleteUser(int id);
}
```
***
以下是我猜测请求参数可能的表达方式
***
`void addUser(User user);`的请求参数表示如下:

| name  |  type  |  desc  |
| ------------ | ------------ | ------------ |
| use | object | 用户信息 |
| &ensp;&ensp;&#124;─id | integer | 用户id |
| &ensp;&ensp;&#124;─name | string | 用户名 |
| &ensp;&ensp;&#124;─age | integer | 年龄 |
| &ensp;&ensp;&#124;─sex | integer | It's a secret |

` void addUser(int x,User user);`的请求参数表示如下:

| name  |  type  |  desc  |
| ------------ | ------------ | ------------ |
| x | integer | 一个奇怪的x参数，没什么用|
| use | object | 用户信息 |
| &ensp;&ensp;&#124;─id | integer | 用户id |
| &ensp;&ensp;&#124;─name | string | 用户名 |
| &ensp;&ensp;&#124;─age | integer | 年龄 |
| &ensp;&ensp;&#124;─sex | integer | It's a secret |


`void updateName(int id,String name);`的请求参数表示如下:

| name  |  type  |  desc  |
| ------------ | ------------ | ------------ |
| id | integer | 用户id |
| name | string | 用户名 |

`void deleteUser(int id);`的请求参数表示如下:

| name  |  type  |  desc  |
| ------------ | ------------ | ------------ |
| id | integer | 用户id |

***

**Comment by yintiefu** [comment]
是的，跟你描述的一样

**Comment by tangcent** [comment]
- rpc接口的支持已经通过审核，相关文档将在未来几天补全.
- 默认是关闭状态，需要
在<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd>> <kbd>Support</kbd>中选择methodDoc
- 可以根据需要加上以下配置
```
#声明哪些类需要导出RPC接口
mdoc.class.filter=groovy:it.name().endsWith("Client")
#为这些接口加上tag
api.tag=groovy:it.containingClass().name().endsWith("Client")?"dubbo":null
```

**Comment by yintiefu** [comment]
```java 
package com.test
public interface ADubboClient{
  void addUser(User user);

  //假设这有多个参数
  void addUser(User user);

  void updateName(int id,String name);

  void deleteUser(int id);
}
```
今天使用了一下  发现这个接口路径显示有点问题
理论上是显示  package.className.methodName 这样  
用上面的示例 现在接口显示  /com.test.ADubboClient/deleteUser/com.test.User
实际应该显示  /com.test.ADubboClient/deleteUser

**Comment by tangcent** [comment]
- 为了解决重载方法覆盖,默认生成的path后加上了参数信息.
- 对于方法导出有[如下规则](https://github.com/tangcent/easy-yapi/blob/master/docs/cn/2.%20%E6%94%AF%E6%8C%81%E7%9A%84%E9%85%8D%E7%BD%AE%E8%A7%84%E5%88%99.md)可以使用
![image](https://user-images.githubusercontent.com/17569144/63992392-3333c900-cb1e-11e9-9ca0-15f6b16ddf27.png)
- 所以，如果确认无重载方法，可以尝试使用配置:
```
mdoc.method.path=groovy:it.containingClass().name()+"/"+it.name()
```

**Comment by yintiefu** [comment]
了解，考虑的全面 👍
