### ISSUE TITLE
`org.sqlite.SQLiteConfig#setBusyTimeout`  signature change

### ISSUE THREAD

**Issue by pchel-** [tangcent/easy-yapi#332]
In the upcoming IDEA 2021.1 updated version of sqlite-jdbc is used, where `org.sqlite.SQLiteConfig#setBusyTimeout` signature has changed - see https://github.com/xerial/sqlite-jdbc/commit/926e281c03c508d982193d09da6ea2824d5f7e81.

So `com.itangcent.idea.sqlite.SqliteDataResourceHelper#getSD` should be fixed.

You could for instance use `sqLiteConfig.busyTimeout = 60000` + specify `since-build` for new version of your plugin.
Or you could directly use `sqLiteConfig.setPragma(SQLiteConfig.Pragma.BUSY_TIMEOUT, "60000")` which should work for both sqlite-jdbc versions.

Thanks.

**Comment by tangcent** [comment]
Thanks.I will use `sqLiteConfig.setPragma(SQLiteConfig.Pragma.BUSY_TIMEOUT, "60000")` to keep the compatibility for the upcoming update.
