### ISSUE TITLE
后续是否会考虑增加自动导出到yapi的能力？

### ISSUE THREAD

**Issue by visionarygit** [tangcent/easy-yapi#337]
**在调研是否能通过某些hook之类的东西来触发easyYapi自动导出文档到yapi.**
原因：简化开发同学的使用成本，避免长期使用下来文档难以维护的问题，使yapi上的文档能保持最新可用

**初步构想结合maven deploy来进行操作**
初步有个想法结合maven deploy来进行，但是目前没有看到maven插件和idea插件互调的可行性，我对插件的开发不是很熟悉，希望能一起交流下，有没有一些好的idea

**Comment by tangcent** [comment]
> 在调研是否能通过某些hook之类的东西来触发easyYapi自动导出文档到yapi.
原因：简化开发同学的使用成本，避免长期使用下来文档难以维护的问题，使yapi上的文档能保持最新可用

git-commit是个很好的时机，发生提交后，尝试处理发生变更的文件中的`api`, 如果进一步解析`diff`, 则可以精准定位到发生变更的`api`

> 初步构想结合maven deploy来进行操作
初步有个想法结合maven deploy来进行，但是目前没有看到maven插件和idea插件互调的可行性，我对插件的开发不是很熟悉，希望能一起交流下，有没有一些好的idea

插件可以监听端口，但是这里没必要`maven插件和idea插件互调`。
可以考虑根据`maven`生命周期的特性来实现, 由 `idea插件`监听某些文件, 比如模块中的`/build`或者更具体点`/target`等文件夹的变化来感知`maven`的执行


---

- 我以前开发过一个内部`api`文档管理系统, 用[javaparser](http://javaparser.org/)实现`api`解析, 主要问题在于解析效率很低,占用很高的内存, 实现也很复杂.
较之用插件的好处是可以脱离`idea`, 将`api`的更新挂载到git-hook,Jenkins-hook等节点
而idea插件的优势在于借助idea解析出的结构, 可以避免自行解析源代码.
- 另外, 对于`简化开发同学的使用成本，避免长期使用下来文档难以维护的问题，使yapi上的文档能保持最新可用`是否有其他的解决办法?
比如插件一直有提供`文件夹`导出功能, 在`Project`panel中选择一个文件夹(可以是根文件夹)就可以用快捷键导出整个文件夹中的`api`

**Comment by visionarygit** [comment]
老铁，easyYapi这个插件是否考虑下将export能力作为端点扩展出来，这样方便其它插件能够集成easyYapi的导出能力

**Comment by tangcent** [comment]
可以试试，过段时间研究一下

**Comment by visionarygit** [comment]
好，我临时整了个版本先用着了
