### ISSUE TITLE
idea get 请求 是否必填没用

### ISSUE THREAD

**Issue by zhuangjiaju** [tangcent/easy-yapi#338]
springboot 的get请求 我用一个对象去接收 里面加了`@NotNull` 注解 但是 导出来的 是否必填还是否

**Comment by tangcent** [comment]
需要更多信息.
1. 确认推荐配置中启用了`javax.validation`或者`javax.validation(grouped)`
2. 确认注解的类为: `javax.validation.constraints.NotNull`
