### ISSUE TITLE
Yapi MethodDoc 类型友好显示问题

### ISSUE THREAD

**Issue by visionarygit** [tangcent/easy-yapi#344]
现在生成的yapi针对dubbo 接口生成的文档显示的类型 只是object string 这种 没有全限定名 （com.xxx.xxx.Demo）这样会导致一些不能使用interface的端（比如nodeJs）在对接的时候无法准确知道类型，是否能优化下这块？

**Comment by tangcent** [comment]
具体是指哪一块?

**Comment by visionarygit** [comment]
![mmexport1613915154065](https://user-images.githubusercontent.com/35750176/108627001-2e8b6f00-748e-11eb-92d7-bf8dd47ddc9a.png)
这里 导出来没有明确的java类型

**Comment by tangcent** [comment]
这个类型只能选`yapi`提供的，具体类型可以通过配置来写到备注里.
```properties
param.doc=groovy:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.",""))
```

---

重构一下，让`methodDoc`也支持`param.doc`

**Comment by visionarygit** [comment]
![rBAoMGA0YyKAVnS1AABG7hgFx9g991](https://user-images.githubusercontent.com/35750176/108793755-41519100-75bf-11eb-8937-6c145833b875.png)
这种方式不能 生成参数对象内的 类型

**Comment by tangcent** [comment]
试试再加一条[field.doc](http://easyyapi.com/setting/rules/field_doc.html)
```
field.doc=groovy:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.",""))
```
