### ISSUE TITLE
解析参数遇到树状结构会无限制递归导致栈溢出

### ISSUE THREAD

**Issue by visionarygit** [tangcent/easy-yapi#352]
![rBAoL2A4WJOAQN2nAADn3G4uumc813](https://user-images.githubusercontent.com/35750176/109245285-224f3b00-781b-11eb-91c1-fd71ddd66521.png)
遇到类似下边这种结构
![rBAoMGA4WJSALdUuAAAomwjHop8542](https://user-images.githubusercontent.com/35750176/109245307-2e3afd00-781b-11eb-88ca-5df05c561307.png)
![rBAoL2A4WJSAcRI8AAHSx7z4TKc403](https://user-images.githubusercontent.com/35750176/109245361-4a3e9e80-781b-11eb-93eb-e78d460cc746.png)
是否考虑增加递归深度限制或者相同引用终止条件

**Comment by tangcent** [comment]
这个是早期的方法，应该要废弃的。
我晚些时候清理一遍
