### ISSUE TITLE
新版本是否没有做兼容，貌似yapi.config中部分能力不生效了

### ISSUE THREAD

**Issue by visionarygit** [tangcent/easy-yapi#360]
更新最新版本后yapi method文档导出出现两个问题（貌似是.yapi.config不生效了？）：
1、生成的接口名称由原来的 只导出第一行注释变成了 所有注释
![rBAoMGBBvLyAA4jiAAAclV0RCxQ481](https://user-images.githubusercontent.com/35750176/110070275-8aba9100-7db4-11eb-899c-b94c97790663.png)

2、java.validation(grouped)的是否必填控制失效了，生成的所有文档属性都是非必填了
![rBAoMGBBvNOAHfnoAABIGADUenU656](https://user-images.githubusercontent.com/35750176/110070285-91e19f00-7db4-11eb-8461-e6e487aef551.png)

**Comment by tangcent** [comment]
根据Jetbrain的提示，有一些方法即将在未来版本移除。
在优化这部分的时候顺手改了点日志中提示线程调度问题,结果引入了bug~~ 

**以后rc版到正式版的时候还是不做任何优化了，只修bug.**
**以后rc版到正式版的时候还是不做任何优化了，只修bug.**
**以后rc版到正式版的时候还是不做任何优化了，只修bug.**

---

试试:
[easy-yapi.2.1.7.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/6088483/easy-yapi.2.1.7.183.0.jar.zip)

**Comment by visionarygit** [comment]
> 根据Jetbrain的提示，有一些方法即将在未来版本移除。
> 在优化这部分的时候顺手改了点日志中提示线程调度问题,结果引入了bug~~
> 
> **以后rc版到正式版的时候还是不做任何优化了，只修bug.**
> **以后rc版到正式版的时候还是不做任何优化了，只修bug.**
> **以后rc版到正式版的时候还是不做任何优化了，只修bug.**
> 
> 试试:
> [easy-yapi.2.1.7.183.0.jar.zip](https://github.com/tangcent/easy-yapi/files/6088483/easy-yapi.2.1.7.183.0.jar.zip)

这个版本上边描述的两个问题是可以了  还有另外的一个问题 就是参数的备注信息都没有导出来了 应是field.doc

**Comment by tangcent** [comment]
ref: https://github.com/tangcent/easy-yapi/issues/363

**Comment by tangcent** [comment]
fixed by  [v2.1.8](https://plugins.jetbrains.com/plugin/12458-easyyapi/versions/stable/112985)
