### ISSUE TITLE
项目 token 太多了

### ISSUE THREAD

**Issue by chenshun00** [tangcent/easy-yapi#361]
手头项目比较多，每次导入导出之前就得提前切换一下 token，这个有想过什么好的方式吗

**Comment by tangcent** [comment]
> 切换一下 token

这个怎么理解?

---

目前来说，不喜欢用`token`的话可以参照: http://easyyapi.com/documents/login_mode_yapi.html
使用自动登录的方式，这样就不再配`token`,而是配置`projectId`

**Comment by chenshun00** [comment]
就是可能我有5个项目，每次导出的时候，我需要先手动切换一下配置的token，不然就将A项目的接口导到B项目上边去了

**Comment by tangcent** [comment]
是否需要module的概念:[module](http://easyyapi.com/setting/rules/module.html)

**Comment by chenshun00** [comment]
这个还是可以的，我先看看
