### ISSUE TITLE
请问一些问题, service层api导出, 字段无注释

### ISSUE THREAD

**Issue by GZHua** [tangcent/easy-yapi#362]
1. 由于项目接口链接限制, 我现在入口controller 只能有一个,  所以现在的实际上的接口层在service, 用service导入到yapi时接口路径是类名+方法名
![image](https://user-images.githubusercontent.com/33946039/110076793-0a9a2880-7dc0-11eb-8b76-424edafb9be2.png)
有指定接口路径的办法吗?

2. 字段全部没有注释  如何解决
![image](https://user-images.githubusercontent.com/33946039/110076948-4af9a680-7dc0-11eb-97e6-8f7e3bad6212.png)

接口定义:
![image](https://user-images.githubusercontent.com/33946039/110077034-7381a080-7dc0-11eb-9107-d03e74679794.png)

入参定义:
![image](https://user-images.githubusercontent.com/33946039/110077063-7da39f00-7dc0-11eb-94d3-69a1167fd921.png)

统一返回定义:
![image](https://user-images.githubusercontent.com/33946039/110077115-8f854200-7dc0-11eb-8769-3a382e7f2696.png)

具体返回定义:
![image](https://user-images.githubusercontent.com/33946039/110077157-9c099a80-7dc0-11eb-922f-0a40c1ed9b78.png)

**Comment by tangcent** [comment]
> 由于项目接口链接限制, 我现在入口controller 只能有一个, 所以现在的实际上的接口层在service, 用service导入到yapi时接口路径是类名+方法名

ref: http://easyyapi.com/setting/rules/mdoc_method_path.html

> 字段全部没有注释 如何解决

当前版本的bug，ref: #363

**Comment by GZHua** [comment]
> > 由于项目接口链接限制, 我现在入口controller 只能有一个, 所以现在的实际上的接口层在service, 用service导入到yapi时接口路径是类名+方法名
> 
> ref:
> http://easyyapi.com/setting/rules/mdoc_method_path.html
> http://easyyapi.com/setting/rules/class_prefix_path.html
> 
> > 字段全部没有注释 如何解决
> 
> 当前版本的bug，ref: #363

自定义配置文件 需要把内置推荐的也写上吗?

**Comment by tangcent** [comment]
不需要的

---

- 目前插件分为`推荐配置`和`内置配置`

- `推荐配置`里是一些通用性的功能,但是`通用性`并非100%通用.
之所以开发`推荐配置`这个功能就是为了让开发者可以选择性的去掉不需要的`通用性的功能`或选择一些因通用性一般而未默认选中的功能


- 通过自定义配置文件可以更好的满足不同的公司/项目的特性，但使用相对来说比较麻烦，所以开始引入`内置配置`的功能

- 目前在进行 [properties.additional](http://easyyapi.com/setting/local-file-config.html#properties.additional)的升级优化，以支持远程加载自定义配置,例如:`properties.additional=https://raw.githubusercontent.com/tangcent/easy-yapi/master/third/swagger.advanced.config`

- 将自定义配置放在内部gitlab等仓库中，然后在 <kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Built-in Config</kbd>中配置`properties.additional=配置文件地址`来实现跨团队跨项目共享自定义配置，以实现插件的个性化定制
