### ISSUE TITLE
请教如何给某个包下的方法增加自定义header

### ISSUE THREAD

**Issue by anjia0532** [tangcent/easy-yapi#379]
easy-yapi 版本号 2.1.7.183.0
idea 版本号 2020.3.2
参考文档 https://easyyapi.com/setting/rules/method_additional_header.html

假设 包名分别为 `com.test.api.a`, `com.test.api.b`, `com.test.api.c` 想给 , `com.test.api.b` 添加指定header

```bash

method.additional.header[groovy:it.name().startsWith("com.test.api.b")]={name: "Authorization",value: "",desc: "认证Token",required:true}

```
在scripts执行器里表达式是正确的
![image](https://user-images.githubusercontent.com/15098916/110284865-5695d900-801d-11eb-83fe-203f50977932.png)

但是导出到yapi，还是没有自定义header

![image](https://user-images.githubusercontent.com/15098916/110284999-90ff7600-801d-11eb-8b13-a6c6b376eefa.png)

**Comment by tangcent** [comment]
`method.additional.header`的`content`是`method`:
![image](https://user-images.githubusercontent.com/17569144/110297599-a630d080-802e-11eb-8ae9-8e5181f266fa.png)
你可以尝试设置为:
```
method.additional.header[groovy:it.containingClass().name().startsWith("com.test.api.b")]={name: "Authorization",value: "",desc: "认证Token",required:true}
```
![image](https://user-images.githubusercontent.com/17569144/110297837-d6786f00-802e-11eb-9e57-28199940c70d.png)

**Comment by anjia0532** [comment]
@tangcent 非常感谢，回复太及时了。已经试验成功了，我待会给文档提个PR，总结一下这个问题

**Comment by anjia0532** [comment]
找了半天没有找到在哪可以给 https://easyyapi.com/setting/rules/method_additional_header.html 提PR
找到其他几个类似的issues，在此进行关联，便于后边人检索

[是否考虑做接口项目的全局配置例如全局统一header全局统一api前缀 #78](https://github.com/tangcent/easy-yapi/issues/78)

[希望可以配置全局header #1510](https://github.com/YMFE/yapi/issues/1510)

**Comment by tangcent** [comment]
看这里哦: https://github.com/tangcent/easy-yapi#%E8%B4%A1%E7%8C%AE

**Comment by anjia0532** [comment]
@tangcent 好了，提交了 https://github.com/easyyapi/easyyapi.github.io/pull/1
