### ISSUE TITLE
提几个功能建议

### ISSUE THREAD

**Issue by cjw0511** [tangcent/easy-yapi#382]
提几个功能建议：

1. 生成 YAPI、并为 api-doc 指定所在目（参数 folder.name）录时，目前只支持一级目录，希望可以通过 类似于 "/" 分隔符的方式，例如  "folder1/folder2/folder3" 这种格式，可以为 api-doc 指定多层级目录

2. 目前只支持为 Controller 类型生成 YAPI 文档，希望可以为 【接口/interface】也能生成 api-doc 文档

3. 当需要为  controller 、或者 接口生成 YAPI文档时，针对某个 REST-API 方法的 api 名称、参数等，目前的查找方式顺序是
    a. 先查找方法自身的 java-doc-@tag 
    b. 如果找不到则使用 java-doc 首行
    c. 再找不到则使用 java 方法名
    希望查找所有的 api 相关名称元素（包括api名称、folder目录 等），查找的方式为：
    a. 优先查找方法本身的 java-doc-@tag
    b. 如果查不到，**则查找父级类型（及接口）的 java-doc-@tag**
    c. 如果找不到则使用当前 java 方法的 doc注释 首行
    d. 如果还找不到，**则查找父级类型（及接口）的 java-doc**
    e. 再找不到则使用 java 方法名
   及，关于 API-doc 的查找，能使用到 父级类型、及接口的 相关注释内容

**Comment by tangcent** [comment]
> * 生成 YAPI、并为 api-doc 指定所在目（参数 folder.name）录时，目前只支持一级目录，希望可以通过 类似于 "/" 分隔符的方式，例如  "folder1/folder2/folder3" 这种格式，可以为 api-doc 指定多层级目录

目前`yapi`官方版本仅支持一级目录，这使得插件只能处理一级目录
实际上我公司内部亦是对`yapi`的做了二次开发亦支持多级目录
而对比网上其他二次开发版本，对如何组织多级目录各自实现方式不一.
我目前还没有想到如何抽象出处理多级目录的规则让用户自行配置.

> * 目前只支持为 Controller 类型生成 YAPI 文档，希望可以为 【接口/interface】也能生成 api-doc 文档

ref: http://easyyapi.com/documents/export_rpc.html

> * 当需要为  controller 、或者 接口生成 YAPI文档时，针对某个 REST-API 方法的 api 名称、参数等，目前的查找方式顺序是
>   a. 先查找方法自身的 java-doc-@tag
>   b. 如果找不到则使用 java-doc 首行
>   c. 再找不到则使用 java 方法名
>   希望查找所有的 api 相关名称元素（包括api名称、folder目录 等），查找的方式为：
>   a. 优先查找方法本身的 java-doc-@tag
>   b. 如果查不到，**则查找父级类型（及接口）的 java-doc-@tag**
>   c. 如果找不到则使用当前 java 方法的 doc注释 首行
>   d. 如果还找不到，**则查找父级类型（及接口）的 java-doc**
>   e. 再找不到则使用 java 方法名
>   及，关于 API-doc 的查找，能使用到 父级类型、及接口的 相关注释内容

插件只提供默认的实现，以使得开发者们在零配置的情况下能得到较为完整的文档.
实际上每个企业都有不一样的情况,不一样的需求.
所以可以考虑一下这里的需求是否可以通过配置达成: http://easyyapi.com/setting/rules/folder_name.html
