### ISSUE TITLE
返回结构上传到yapi失败

### ISSUE THREAD

**Issue by tutuerhao** [tangcent/easy-yapi#39]
**Describe the bug**
`为啥我自定义的通用返回对象在yapi中无法显示,难道一定要用你demo里的result对象吗`

![image](https://user-images.githubusercontent.com/29938085/62851308-42daa180-bd18-11e9-8323-588d488c1ea4.png)
![image](https://user-images.githubusercontent.com/29938085/62851325-4ec66380-bd18-11e9-8f1f-e31adf4e2e89.png)

![image](https://user-images.githubusercontent.com/29938085/62851369-73bad680-bd18-11e9-915a-48aec831c3eb.png)

**Comment by tangcent** [comment]
> 为啥我自定义的通用返回对象在yapi中无法显示,难道一定要用你demo里的result对象吗

`不用，demo里的Result也是我随手写的`

出现这个问题应该是字段没有限定符,现在默认是取private/protected字段
是基于java规范与解析性能的考虑.

按照以下步骤尝试:
1. 在<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd>中将readGetter选中试试通过getter方法获取字段信息
2. 如果1不行的话，你是否可以将字段设置为private?
3. 如果有需要的话，我可以提供配置，允许解析public/package字段，不过这将需要几天时间

**Comment by tutuerhao** [comment]
@tangcent 有鸟,好厉害,就是限定符的问题
