### ISSUE TITLE
@NotBlank 也需要必填

### ISSUE THREAD

**Issue by zhuangjiaju** [tangcent/easy-yapi#394]
如果使用了 NotNull 注解 是否必填显示 是
但是 使用了 NotBlank 是否必填显示否

**Comment by tangcent** [comment]
不是这个`javax.validation.constraints.NotBlank `吗?

https://github.com/tangcent/easy-yapi/blob/1863dd0b715329418da69bb45713f97b4d8a0066/idea-plugin/src/main/resources/.recommend.easy.api.config#L109-L110

**Comment by zhuangjiaju** [comment]
感谢 我再看下
