### ISSUE TITLE
关于 kotlin Controller、Git Submodule 配置和推荐配置

### ISSUE THREAD

**Issue by clarkhan** [tangcent/easy-yapi#40]
插件版本：0.9.1.183.0.5
Intellij IDEA：2019.2 Build 192.5728.98

最近新发现的这个工具，谢谢作者~
使用的时候遇到几个困惑：

1. 试了下 Kotlin 的 Controller 可以生成 API，但貌似读不到注释。
    接口分类和接口名都是 code,而不是来自注释
    接口备注也是空的
2. 使用 GitSubmodule 组织的项目，在Intellij 中也是同样结构的 Module。`.yapi.config` 放在子模块或父模块的根目录生成的时候都提示 `[TRACE]	No config [.yapi.config] be found     [TRACE]	No config [.easy.api.config] be found` 。(•_•)?
3. 因为自定义配置无效，使用推荐的配置在 Java 的 Controller 中注释中的 `@undone` `@public` 并不能对应到 yapi 的未完成和开放接口?

**Comment by tangcent** [comment]
感谢你的issue ( ´･ᴗ･` )
> 1:试了下 Kotlin 的 Controller 可以生成 API，但貌似读不到注释。
接口分类和接口名都是 code,而不是来自注释
接口备注也是空的
-  对于Kotlin的支持本计划在1.0版本后进行
- 我目前在进行 [RPC接口的支持](https://github.com/tangcent/easy-yapi/issues/33)
> 2:使用 GitSubmodule 组织的项目，在Intellij 中也是同样结构的 Module。.yapi.config 放在子模块或父模块的根目录生成的时候都提示 [TRACE]	No config [.yapi.config] be found [TRACE] No config [.easy.api.config] be found 。(•_•)?
- 这个情况我还未曾遇到,能否提供一些信息，以便我能够重现此问题?
- 当然你也可以自行调试
- 目前配置的获取方法是:[PathSearchConfigReader](https://github.com/tangcent/intellij-kotlin/blob/6eb2310891ff8f12e3cd7eda48e61c300d4e9004/src/main/kotlin/com/itangcent/intellij/config/PathSearchConfigReader.kt#L13-L34)
- 当在<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> 选择使用推荐配置时,推荐配置会生效:[RecommendConfigReader](https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/config/RecommendConfigReader.kt
)

> 3. 因为自定义配置无效，使用推荐的配置在 Java 的 Controller 中注释中的 @undone @public 并不能对应到 yapi 的未完成和开放接口?
- 是的，目前[api.status=groovy:it.hasDoc("undone")?"undone":"done"](https://github.com/tangcent/spring-demo/blob/fcc0c3db3ee2f5f3b55efdcbed1766e84923e27a/.easy.api.config#L95-L96)不属于推荐配置,需要配置文件生效
***
- 我希望在没有配置的时候，插件基本功能能够正常运行
- 开发者又可以利用配置完成自身业务相关的定制

**Comment by clarkhan** [comment]
@tangcent 谢谢回复，期待 1.0 之后的 Kotlin 支持。PathSearch的问题可以到时候我自己调试下，应该是小众需求或者我本地配置有误~ Thanks♪(･ω･)ﾉ

**Comment by tangcent** [comment]
support of kotlin see https://github.com/tangcent/easy-yapi/issues/45

**Comment by tangcent** [comment]
- 很高兴告诉你对kotlin的支持基本完成了(泛型返回值推导还需要做进一步的处理),当然正式上线前还需要一些时间测试检验.
- 另外也很抱歉，我才反应过来 
> 使用 GitSubmodule 组织的项目，在Intellij 中也是同样结构的 Module。.yapi.config 放在子模块或父模块的根目录生成的时候都提示 [TRACE] No config [.yapi.config] be found [TRACE] No config [.easy.api.config] be found 。(•_•)?

你的这个问题可能是这个[BUG](https://github.com/tangcent/easy-yapi/issues/48)，已被[PR49](https://github.com/tangcent/easy-yapi/pull/49)修复
- 祝好
[easy-yapi.jar.zip](https://github.com/tangcent/easy-yapi/files/3603084/easy-yapi.jar.zip)

**Comment by clarkhan** [comment]
@tangcent  👍 赞一个，效率杠杠的！

已经试用了，很棒！
