### ISSUE TITLE
为啥目录不支持中文命名

### ISSUE THREAD

**Issue by tutuerhao** [tangcent/easy-yapi#42]
**Describe the bug**

为啥不支持中文命名
![image](https://user-images.githubusercontent.com/29938085/63240289-918cbc00-c281-11e9-9e80-a216d3487d3b.png)

![image](https://user-images.githubusercontent.com/29938085/63240284-8b96db00-c281-11e9-8191-77ec4a8b613a.png)

**Comment by tangcent** [comment]
- 我尝试重现，未能成功
- 从你的图片来看，应该是由于GBK编码导致
- 尝试在IDEA右下方修改编码
![image](https://user-images.githubusercontent.com/17569144/63261517-48a32a80-c2b6-11e9-8cc0-7caea9eeedbc.png)

- 需要确认一些信息:
  - 系统
  - 系统默认字符集
  - IDEA版本
  - 当前项目字符集
  - 当前文件字符集

**Comment by tutuerhao** [comment]
系统:win7
系统默认字符集:活动代码页: 936(应该是简体中文gbk吧)
IDEA版本:2019.1.12
当前项目字符集:下图
当前文件字符集下图
![image](https://user-images.githubusercontent.com/29938085/63311716-94df8080-c331-11e9-83d6-4cacebf1baee.png)

**Comment by tangcent** [comment]
嗯，应该是GBK编码导致的
https://github.com/tangcent/easy-yapi/blob/d8a005bad27c80dee81a9ba2931669c7c7e31470/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiApiHelper.kt#L109-L118
这里错误的使用了系统默认编码来提交。
这里可以尝试使用json提交

**Comment by tangcent** [comment]
我本地不是很好模拟这种情况，可以尝试一下吗？
[easy-yapi.jar.zip](https://github.com/tangcent/easy-yapi/files/3518495/easy-yapi.jar.zip)

**Comment by tutuerhao** [comment]
@tangcent 好的,稍候我试试

**Comment by tangcent** [comment]
我准备更新插件版本，提供对rpc接口的支持，所以先行merge此PR，如果这个BUG没修复，你重新打开这个issue即可

**Comment by tutuerhao** [comment]
@tangcent 老板,你给的jar包还是不行呀,能远程吗,让你看看环境

**Comment by tangcent** [comment]
- 尝试在仓库里升级到0.9.5.183.0.1，
已经修复为使用json提交创建目录了，所以提交导致的编码问题应该是可以排除了
https://github.com/tangcent/easy-yapi/blob/63936d4174e4e6d144d938a15c4e36073136052f/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiApiHelper.kt#L105-L111

**Comment by tutuerhao** [comment]
可以了老哥
@tangcent
