### ISSUE TITLE
如何能支持json5呢? 

### ISSUE THREAD

**Issue by kaimeng110091** [tangcent/easy-yapi#420]
如何设置, 可以生成json5格式的请求体和响应体呢? 注释在值的后方.
目前创建的是json-schema格式的.

**Comment by tangcent** [comment]
目前json5只在导出postman时使用,
导出yapi一直采用json-schema。
这个支持放到下个版本实现.
目前有需要的话只能通过配置把json5放到api描述里

**Comment by kaimeng110091** [comment]
万分感谢

**Comment by tangcent** [comment]
ref: https://github.com/tangcent/easy-yapi/pull/430
