### ISSUE TITLE
loginMode不支持

### ISSUE THREAD

**Issue by kaimeng110091** [tangcent/easy-yapi#421]
**在General设置-Yapi分区中, 勾选了loginMode后, 点击导出Yapi, log日志打印: 请登录... 但是没有弹窗请求登录账号和密码**
没有用来设置账号密码的地方. 希望能开发出这个功能, 且安全保存和发送.

**Comment by tangcent** [comment]
ref: http://easyyapi.com/documents/login_mode_yapi.html

**Comment by kaimeng110091** [comment]
如果不勾选loginMode, 使用token上传api, 接口的创建者不是本人.

**Comment by tangcent** [comment]
> 如果不勾选loginMode, 使用token上传api, 接口的创建者不是本人.

我没有碰到过这种情况，是不是你使用的yapi版本过低或者定制过?

**Comment by kaimeng110091** [comment]
参考文档中对于配置鉴权逻辑的描述不全, 按照提供的groovy配置格式写入.yapi.config后, exportYapi报错, javax.script.ScriptException: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
应该是groovy脚本的格式不正确导致. 希望能提供一份可以允许的配置. 感谢.

**Comment by tangcent** [comment]
配置中的 [\`\`\`]是配置的一部分,不要手动删掉
``````
yapi.export.before=groovy:```
    httpClient.request().url("http://127.0.0.1:3000/api/user/login")
                .method("POST")
                .contentType("application/json")
                .body(["email":"xxx@xxx.com","password":"*******"])
                .call();
```
``````

**Comment by kaimeng110091** [comment]
未删除[```], 我尝试下解决它. 谢谢啦.
