### ISSUE TITLE
返回值多层嵌套显示问题  只显示到第3层, 且没有显示完整 , 第4层没有显示

### ISSUE THREAD

**Issue by GZHua** [tangcent/easy-yapi#425]
**Describe the bug**
返回值多层嵌套  只显示到第3层  第4层没有显示

**To Reproduce**
所有bean类都有加@Data注解

1. 返回值
![image](https://user-images.githubusercontent.com/33946039/113686720-257ef600-96fa-11eb-960a-d86cb57857ee.png)

2. 第一层
![image](https://user-images.githubusercontent.com/33946039/113686783-3af42000-96fa-11eb-8781-67a397364e38.png)

3. 第二层
![image](https://user-images.githubusercontent.com/33946039/113686881-52cba400-96fa-11eb-8634-21c65f963d54.png)

4. 第三层 红框处的都没有展示出来
![image](https://user-images.githubusercontent.com/33946039/113686978-6e36af00-96fa-11eb-803e-80d774ef9b5b.png)

5.yapi展示
![image](https://user-images.githubusercontent.com/33946039/113687140-9b835d00-96fa-11eb-810d-d247c06860a7.png)

**Expected behavior**
任意层级都显示出来

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win 10 
 - Browser: Chrome  89.0.4389.90  64位
 - Version: 2.1.9.183.0

**Smartphone (please complete the following information):**

**Additional context**
配置截图
![image](https://user-images.githubusercontent.com/33946039/113688153-9d99eb80-96fb-11eb-847a-35b14146b75c.png)

**Comment by tangcent** [comment]
在<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Recommend</kbd>中取消勾选`private_protected_field_only`试试

**Comment by GZHua** [comment]
> 在Preferences(Settings)> Other Settings> EasyApi>Recommend中取消勾选`private_protected_field_only`试试

可以了
