### ISSUE TITLE
@method=GET结合@path使用时不会自动生成入参 ，生成dubbo接口

### ISSUE THREAD

**Issue by simonpdh** [tangcent/easy-yapi#428]
生成的dubbo接口文档如果GET的请求，不会生成body，能否将GET的参数自动补到path后面，举例如下：
接口路径：https://domain/project/function/business?a=&b=&c=
接口请求方式：GET

其中接口路径里的?a=&b=&c=为入参，目前使用@path，并且请求方式是GET的话，不会自动生成入参，或者能不能不区分请求的方式，所有的入参都生成body，这样会直观些

**Comment by simonpdh** [comment]
导出Dubbo接口到yapi

demo如下：
入参为：a,b,c三个参数

当前情况：
接口路径：https://domain/project/function/business
接口请求方式：GET
生成文档无任何入参

期望结果(两者之一)：
1、
接口路径：https://domain/project/function/business?a=&b=&c=
接口请求方式：GET

2、
接口路径：https://domain/project/function/business
接口请求方式：GET
body:{
a:123,
b:234,
c:456
}

**Comment by tangcent** [comment]
ref: #432

**Comment by simonpdh** [comment]
> ref: #432

升级到最新的版本发现，可以带上参数，如果参数是一个java对象的话，对象里的属性只会展示在示例里，非常的丑
