### ISSUE TITLE
我想自己编辑一下easyyapi的界面，可是增加和删除都使用不了

### ISSUE THREAD

**Issue by chenshun00** [tangcent/easy-yapi#439]
RT
我想自己编辑一下easyyapi的界面，可是增加和删除都使用不了

这个是有什么限制么

**Comment by tangcent** [comment]
主要是kotlin/swing的问题
- 增加应该是可以的
- 删除的话idea解析不了，需要手动修改界面源码

**Comment by chenshun00** [comment]
嗯，请问这块能具体有个截图什么的么 :)，因为我发现修改了源代码以后，package不通过了  😂

**Comment by tangcent** [comment]
> 嗯，请问这块能具体有个截图什么的么 :)

没有什么特殊的操作需要截图来说明

> package不通过

按照错误提示修改即可，多数手动修改后产生的错误原因都是未修复`row`或者`column`数量产生的。

---

实际上如果你对`swing`的布局熟悉的话，欢迎重写，用`JAVA code`代替`form`

**Comment by chenshun00** [comment]
嗯，这里我再去看看，我看到配置上有个 `推断` , 请问这个哪里有文档么.  或者可以详细说一下么

**Comment by tangcent** [comment]
很遗憾，并未整理相关文档。
甚至目前对`推断`的实现还是很粗糙。
目前的实现: https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/DefaultMethodInferHelper.kt

也许你可以尝试通过test case来了解`推断`过程: https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/core/DefaultMethodInferHelperTest.kt

**Comment by chenshun00** [comment]
嗯，现在的推断只能推断当前方法的吧

**Comment by tangcent** [comment]
何意?

**Comment by chenshun00** [comment]
不好意思，没有表述清楚，是这个意思

```java
public Map<String,Object> method(){
    retrun service.biz();
}
```

**Comment by tangcent** [comment]
会继续推断`service.biz()`

**Comment by chenshun00** [comment]
嗯，好滴，我继续debug看看这个推断的过程

**Comment by chenshun00** [comment]
我估摸着这块可能还得作者出一个文档，kotlin的代码稍微还是有点玄学 ，😂   😂    😂

**Comment by tangcent** [comment]
🤣我太难了，等过些时候有空了再说吧。

**Comment by chenshun00** [comment]
嗯，我测试发现，this.biz() 还可以推断，service.biz() 就不能推断了。

`no matched ele`

**Comment by chenshun00** [comment]
有个PsiMethodImpl没有处理 😂  😂
