### ISSUE TITLE
希望添加基本数据类型以及@java.beans.Transient支持

### ISSUE THREAD

**Issue by Songzhizong** [tangcent/easy-yapi#440]
![image](https://user-images.githubusercontent.com/22743270/115349980-16627280-a1e7-11eb-9ffe-a3d9bec9fa74.png)

我的controller接口返回结果是一个Result<T>接口，我期望的结果是生成的文档中有两个必需字段 `id`和`success`。为了忽略`failure `字段我在default boolean isFailure()方法上添加了@java.beans.Transient注解阻止它被序列化。
此外boolean isSuccess()方法返回的是一个基本数据类型，基本数据类型是不可能为null的，但生成的文档中success却是非必须的。

因此我希望easy-yapi能够添加以下两个识别功能：
1. 基本数据类型默认为必须
2. 生成文档中忽略添加了@java.beans.Transient注解的方法

如果可以的话我希望能够额外添加对jsr305的支持，即@javax.annotation.Nonnull和@javax.annotation.Nullable注解
目前我在配置文件中添加了配置`field.required=@javax.annotation.Nonnull`也能实现我需要的效果

**Comment by tangcent** [comment]
- 适用于某个项目的配置，建议使用项目中的配置文件
- 适用于多个项目的配置，建议在github/gitlab中创建配置库存放配置，然后在<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Built-in Config</kbd>中配置`properties.additional=配置文件地址`来实现跨团队跨项目共享自定义配置，以实现插件的个性化定制
- 适用于某个被广泛使用的框架的配置，欢迎提供到[.recommend.easy.api.config](https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/main/resources/.recommend.easy.api.config)中作为内置的推荐配置

---

> 基本数据类型默认为必须

这个需求建议是自行配置，目前`class`上下文未提供判断是否为`基本数据类型`的方法，目前可以使用:
```
field.required=groovy:["byte","int","long","double","float","short","boolean","char"].contains(it.type().name())
```

> 生成文档中忽略添加了@java.beans.Transient注解的方法

这个可以考虑放到[.recommend.easy.api.config](https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/main/resources/.recommend.easy.api.config)里

> 额外添加对jsr305的支持

这个可以考虑放到[.recommend.easy.api.config](https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/main/resources/.recommend.easy.api.config)里
