### ISSUE TITLE
返回方法 泛型包裹泛型 无法解析

### ISSUE THREAD

**Issue by zzz583974851** [tangcent/easy-yapi#445]
package borui.core.commons.utils;
import java.io.Serializable;
/**
 * 返回数据
 *
 * @author Mark sunlightcs@gmail.com
 */
public class R<T> implements Serializable {
	public static final long serialVersionUID = 1L;
	private int code;
	private String msg;
	private T data;

	public R(){

	}

	public R(int code, String message, T data) {
		this.code = code;
		this.setMsg(message);
		this.data = data;
	}

	public R(int code, T data) {
		this.code = code;
		this.data = data;
	}

	public R(int code, String message) {
		this.code = code;
		this.setMsg(message);
	}

	/**
	 * 成功时-返回data
	 * @param <T>
	 * @return
	 */
	public static <T> R<T> success(T data){
		return new R<T>(200, null, data);
	}

	/**
	 * 成功-不返回data
	 * @param <T>
	 * @return
	 */
	public static <T> R<T> success(String msg){
		return new R<T>(200, msg);
	}

	/**
	 * 成功-返回data+msg
	 * @param <T>
	 * @return
	 */
	public static <T> R<T> success(String msg, T data){
		return new R<T>(200, msg, data);
	}

	/**
	 * 失败
	 * @param <T>
	 * @return
	 */
	public static <T> R<T> fail(){
		return new R<T>(500, null,null);
	}

	/**
	 * 失败
	 * @param <T>
	 * @return
	 */
	public static <T> R<T> fail(String msg){
		return new R<T>(500, msg,null);
	}

	/**
	 * 失败-code
	 * @param <T>
	 * @return
	 */
	public static <T> R<T> fail(int code, String msg){
		return new R<T>(code, msg,null);
	}

	public int getCode() {
		return code;
	}

	public String getMsg() {
		return msg;
	}

	public T getData() {
		return data;
	}

	public void setCode(int code) {
		this.code = code;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	public void setData(T data) {
		this.data = data;
	}

	@Override
	public String toString() {
		return "R{" + "code=" + code + ", msg='" + msg + '\'' +", data=" + data +'}';
	}
}

package borui.core.commons.utils;

import com.baomidou.mybatisplus.core.metadata.IPage;
import org.springframework.beans.BeanUtils;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * 分页工具类
 *
 * @author Mark sunlightcs@gmail.com
 */
public class PageUtils implements Serializable {
	public static final long serialVersionUID = 1L;
	/**
	 * 总记录数
	 */
	public int totalCount;
	/**
	 * 每页记录数
	 */
	public int pageSize;
	/**
	 * 总页数
	 */
	public int totalPage;
	/**
	 * 当前页数
	 */
	public int currPage;
	/**
	 * 列表数据
	 */
	public List<?> list;

	/**
	 * 分页
	 * @param list        列表数据
	 * @param totalCount  总记录数
	 * @param pageSize    每页记录数
	 * @param currPage    当前页数
	 */
	public PageUtils(List<?> list, int totalCount, int pageSize, int currPage) {
		this.list = list;
		this.totalCount = totalCount;
		this.pageSize = pageSize;
		this.currPage = currPage;
		this.totalPage = (int)Math.ceil((double)totalCount/pageSize);
	}

	/**
	 * 分页
	 */
	public PageUtils(IPage<?> page) {
		this.list = page.getRecords();
		this.totalCount = (int)page.getTotal();
		this.pageSize = (int)page.getSize();
		this.currPage = (int)page.getCurrent();
		this.totalPage = (int)page.getPages();
	}

	/**
	 * 分页
	 */
	public PageUtils(IPage<?> page, Class<?> object) {
		List<Object> objectList= Collections.synchronizedList(new ArrayList<>());
		page.getRecords().parallelStream().forEach(item->{
			Object o= null;
			try {
				o = object.newInstance();
			} catch (InstantiationException e) {
				e.printStackTrace();
			} catch (IllegalAccessException e) {
				e.printStackTrace();
			}
			BeanUtils.copyProperties(item,o);
			objectList.add(o);
		});
		this.list = objectList;
		this.totalCount = (int)page.getTotal();
		this.pageSize = (int)page.getSize();
		this.currPage = (int)page.getCurrent();
		this.totalPage = (int)page.getPages();
	}

	public int getTotalCount() {
		return totalCount;
	}

	public void setTotalCount(int totalCount) {
		this.totalCount = totalCount;
	}

	public int getPageSize() {
		return pageSize;
	}

	public void setPageSize(int pageSize) {
		this.pageSize = pageSize;
	}

	public int getTotalPage() {
		return totalPage;
	}

	public void setTotalPage(int totalPage) {
		this.totalPage = totalPage;
	}

	public int getCurrPage() {
		return currPage;
	}

	public void setCurrPage(int currPage) {
		this.currPage = currPage;
	}

	public List<?> getList() {
		return list;
	}

	public void setList(List<?> list) {
		this.list = list;
	}

}

无法解析 PageUtils list()里面实际实体

**Comment by tangcent** [comment]
> 泛型包裹泛型

对于`泛型包裹泛型`的情况是可以正常解析的

> 无法解析 PageUtils list()里面实际实体

这里无法解析的原因可能是`public List<?> list;`并非采用泛型而是通配符的原因, 这导致插件拿不到`list`的具体类型。
处理如下的泛型是可以的:
```java
public class Page<T> implements Serializable {
...

      /*
      列表数据
      */
      private List<T> list;
}
```

---

另外请确认在<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Recommend</kbd>中取消勾选`private_protected_field_only`

**Comment by zzz583974851** [comment]
谢谢，我表达错误，是泛型里面镶套的实体，里面有个list<？>通配符 然后无法解析 我看了下配置 private_protected_field_only 已经是没有勾选状态

**Comment by tangcent** [comment]
以前有人问过类似的问题，一直没有好的想法来解决。

---

构想一个方案如下:
1. 在方法上通过额外的注释来标记`list`的真实类型
2. 再通过`method.parse.before`中读取它并设置到`session`里，
3. 然后配置`field.type`来从`session`里读取`list`对应的真实类型

可以参考`javax.validation`的解决方案: https://github.com/tangcent/easy-yapi/blob/0438f675b78905710d81f42df6599237a721db18/idea-plugin/src/main/resources/.recommend.easy.api.config#L116-L137

---

要实现这个方案需要增加支持两条配置规则:

- [ ] `method.parse.before`: 方法解析前回调
  - [ ] `method.parse.after`: 方法解析后回调，作为`method.parse.before`的对称实现

- [ ] `field.type`: 配置字段类型，覆盖代码定义的类型

**Comment by zzz583974851** [comment]
我已经通过修改我返回实体的封装，将不可见全部改为可见，最多2层泛型，拒绝全部map&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月22日(星期四) 晚上6:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tangcent/easy-yapi] 返回方法 泛型包裹泛型 无法解析 (#445)





 
以前有人问过类似的问题，一直没有好的想法来解决。
 
 
构想一个方案如下:
  
在方法上通过额外的注释来标记list的真实类型
 
再通过method.parse.before中读取它并设置到session里，
 
然后配置field.type来从session里读取list对应的真实类型
  
可以参考javax.validation的解决方案: https://github.com/tangcent/easy-yapi/blob/0438f675b78905710d81f42df6599237a721db18/idea-plugin/src/main/resources/.recommend.easy.api.config#L116-L137
 
 
要实现这个方案需要增加支持两条配置规则:
  
 
 method.parse.before: 方法解析前回调
  
 method.parse.after: 方法解析后回调，作为method.parse.before的对称实现
  
 
 
 field.type: 配置字段类型，覆盖代码定义的类型
