### ISSUE TITLE
上传卡在了search api from:xxxx

### ISSUE THREAD

**Issue by jiajiancheng** [tangcent/easy-yapi#446]
![微信截图_20210422191019](https://user-images.githubusercontent.com/5448824/115705156-c9c19780-a39e-11eb-97ad-2e9dfd5188fa.png)

**Comment by tangcent** [comment]
我之前有碰到这种情况，是http连接池的问题，在#434 修复了
你试试: [easy-yapi-2.2.0.183.0.zip](https://github.com/tangcent/easy-yapi/files/6357817/easy-yapi-2.2.0.183.0.zip)，看看能不能解决

**Comment by jiajiancheng** [comment]
可以了，比心
