### ISSUE TITLE
如何开启javax_validation分组校验

### ISSUE THREAD

**Issue by zzz583974851** [tangcent/easy-yapi#448]
我已经按照qa 去做，流程如下 参见javax_validation, 在 Preferences(Settings) > Other Settings > EasyApi >Recommend 中移除勾选javax.validation, 勾选javax.validation(grouped)
然后.easy.api.config文件里面复杂如下代码
#[javax.validation(grouped)]
json.cache.disable=true
param.before=groovy:```
    logger.info("set curr groups:"+it.annValue("org.springframework.validation.annotation.Validated"))
    session.set("json-group", it.annValue("org.springframework.validation.annotation.Validated"))
```
param.after=groovy:```
    session.remove("json-group")
```
param.required=@javax.validation.constraints.NotBlank
param.required=@javax.validation.constraints.NotNull
param.required=@javax.validation.constraints.NotEmpty
field.required[@javax.validation.constraints.NotBlank]=groovy:```
    it.annMaps("javax.validation.constraints.NotBlank")?.any{tool.equalOrIntersect(session.get("json-group"),it["groups"])}
```
field.required[@javax.validation.constraints.NotNull]=groovy:```
    it.annMaps("javax.validation.constraints.NotNull")?.any{tool.equalOrIntersect(session.get("json-group"),it["groups"])}
```
field.required[@javax.validation.constraints.NotEmpty]=groovy:```
    it.annMaps("javax.validation.constraints.NotEmpty")?.any{tool.equalOrIntersect(session.get("json-group"),it["groups"])}
```



entity如下
package borui.pojo.entity.sys;

import borui.commons.validator.group.UpdateGroup;
import com.baomidou.mybatisplus.annotation.FieldFill;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import lombok.Data;

import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * @author chendianbo
 * @version 1.0
 * @email 583974851@qq.com
 * @date 2021-04-23 14:26
 */
@Data
public abstract class AbstractEntityBase {
	/**
	 * 自增id
	 */
	@NotNull(message = "更新id不能为空!", groups = UpdateGroup.class)
	@TableId
	public Long id;

	/**
	 * 创建时间
	 */
	@TableField(fill = FieldFill.INSERT)
	public Date createTime;
	/**
	 * 最后更新时间
	 */
	@TableField(fill = FieldFill.UPDATE)
	public Date lastUpdateTime;
	/**
	 * 创建用户id
	 */
	public Long createUserId;
	/**
	 * 创建人,组织id，公司id,集团id,租户id
	 */
	public String createOrgId;
}


生成的id在ypi里面 保存方法id还是必须条件 ，请问如何才能生效。保存时候id不是不要条件，更新时候id是必要条件
谢谢

**Comment by tangcent** [comment]
按照这边提示http://easyyapi.com/qa/index.html#%e5%a6%82%e4%bd%95%e5%bc%80%e5%90%afjavax_validation%e5%88%86%e7%bb%84%e6%a0%a1%e9%aa%8c
勾选好之后不需要额外在`.easy.api.config`文件里面配置了

---

你可以尝试导出demo来验证配置是否正确: https://github.com/Earth-1610/spring-demo/blob/master/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/ValidationCtrl.java

**Comment by zzz583974851** [comment]
谢谢兔子老哥

**Comment by zzz583974851** [comment]
我尝试了已经完美解决我的问题了
