### ISSUE TITLE
springboot Controller @param @link 无法正常使用

### ISSUE THREAD

**Issue by zzz583974851** [tangcent/easy-yapi#451]
[代码图片](https://ftp.bmp.ovh/imgs/2021/04/acbe8cf819fd6b87.png)
[代码图片](https://ftp.bmp.ovh/imgs/2021/04/41b7343acc919ad2.png)
[代码图片](https://ftp.bmp.ovh/imgs/2021/04/507d01a143568ab5.png)

package borui.web.sys;
import borui.core.commons.utils.R;
import borui.core.errorcode.ErrorCodeEnum;
import borui.service.sys.SysFileService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
/**
 * 文件上传
 * @author chendianbo
 * @email 583974851@qq.com
 * @date 2021-04-20 16:59
 * @description //TODO
 **/
@RestController
@RequestMapping("/sys/file")
public class SysFileController {
	@Autowired
	public SysFileService sysFileService;

	/**
	 * 临时文件上传
	 * @param fileTypeCode  文件类型  {@link borui.core.errorcode.ErrorCodeEnum}
	 * @param multipartFile 文件流
	 * @param auth  是否授权，true授权为私有文件，false设置为公开文件
	 * @return
	 */
	@PostMapping("/tempUpload")
	public R upload(Long fileTypeCode,MultipartFile multipartFile, Boolean auth) {
		return R.success(sysFileService.tempSave(fileTypeCode,multipartFile,auth));
	}

}

或者加上别名 

package borui.web.sys;
import borui.core.commons.utils.R;
import borui.core.errorcode.ErrorCodeEnum;
import borui.service.sys.SysFileService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
/**
 * 文件上传
 * @author chendianbo
 * @email 583974851@qq.com
 * @date 2021-04-20 16:59
 * @description //TODO
 **/
@RestController
@RequestMapping("/sys/file")
public class SysFileController {
	@Autowired
	public SysFileService sysFileService;

	/**
	 * 临时文件上传
	 * @param fileTypeCode  文件类型  {@link borui.core.constant.FileTypeEnum#code}
	 * @param multipartFile 文件流
	 * @param auth  是否授权，true授权为私有文件，false设置为公开文件
	 * @return
	 */
	@PostMapping("/tempUpload")
	public R upload(int fileTypeCode,MultipartFile multipartFile, Boolean auth) {
		return R.success(sysFileService.tempSave(Long.valueOf(fileTypeCode),multipartFile,auth));
	}

}

yapi 备注显示：

fileTypeCode | 否 | 0 | 文件类型  [borui.core.constant.FileTypeEnum#code]

package borui.core.errorcode;

/**
 * @author chend
 */
public enum ErrorCodeEnum {
	/**
	 * 账号相关
	 */
	ACCOUNT_OR_PASSWORD_ERROR(1000, "账号或者密码错误"),
	ip_lock(1001, "当前ip达到错误登录次数限制，已被限制登录"),
	ACCOUNT_LOCK(1002, "账号已冻结"),

	/**
	 * 文件上传
	 */
	File_UPDATE_FAILE(2000, "文件上传失败!"),
	File_ENTITY_SAVE_FAILE(2001, "SysFileEntity保存失败!"),
	FILE_ID_NOT_EXIST(2002, "文件id不存在!"),
	FILE_AUTH_ERROR(2003, "文件授权错误!");

	ErrorCodeEnum(int number, String description) {
		this.code = number;
		this.description = description;
	}

	public int code;
	public String description;

	public int getCode() {
		return code;
	}

	public String getDescription() {
		return description;
	}

}

无法正常解析这个枚举 ，yapi显示 

fileTypeCode | 否 | 0 | 文件类型  [ErrorCodeEnum]

**Comment by tangcent** [comment]
>   ErrorCodeEnum(int number, String description) {
>   this.code = number;
>   this.description = description;
>   }

可能是这里参数名与字段名不一致的原因
尝试改成相同的名称试试:
```java
ErrorCodeEnum(int code, String description) {
     this.code = code;
     this.description = description;
}
```

---

对应的解析代码: https://github.com/Earth-1610/intellij-kotlin/blob/09deb5b3363fd1aa6873db5a0076056892702232/intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardPsiResolver.kt#L265-L302
这里都是直接用的参数名，没有解析构造函数体:
https://github.com/Earth-1610/intellij-kotlin/blob/09deb5b3363fd1aa6873db5a0076056892702232/intellij-jvm/src/main/kotlin/com/itangcent/intellij/jvm/standard/StandardPsiResolver.kt#L277

**Comment by zzz583974851** [comment]
好了谢谢，的确是参数名与字段名不一致的原因，但是这个应该安装变量名去找吧

**Comment by tangcent** [comment]
> 好了谢谢，的确是参数名与字段名不一致的原因，但是这个应该安装变量名去找吧

嗯，不过属于基础包需要解决的问题，先挂在Earth-1610/intellij-kotlin#120 等有空去做。

**Comment by hellsof** [comment]
内部枚举类也不能使用

**Comment by tangcent** [comment]
> 内部枚举类也不能使用

具体情况?

**Comment by hellsof** [comment]
> > 内部枚举类也不能使用
> 
> 具体情况?
例如这里`ErrorCodeEnum`如果是`ErrorCode`类的内部枚举类，
`
import borui.core.errorcode.ErrorCode;
@param fileTypeCode 文件类型 {@link ErrorCode.ErrorCodeEnum}
`
上面的的这个写法无效，下面的写法才有效：
`
import borui.core.errorcode.ErrorCode.ErrorCodeEnum;
@param fileTypeCode 文件类型 {@link ErrorCodeEnum}
`

**Comment by tangcent** [comment]
我试了一下:
```java

package com.itangcent.springboot.demo.controller;

import com.itangcent.common.dto.Result;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * 内部类测试
 *
 * @module user
 */
@RestController
@RequestMapping(value = "inner")
public class InnerClassCtrl extends BaseController {

    /**
     * 增加新用户
     *
     * @param opt op {@link Opt#value}
     */
    @PostMapping("/add")
    public Result<UserInfo> add(
            Integer opt,
            @RequestBody UserInfo userInfo) {
        return Result.success(userInfo);
    }

    public static class UserInfo {

        private Long id;//用户id

        /**
         * @see com.itangcent.common.constant.UserType
         */
        private int type;//用户类型

        @NotBlank
        private String name;//用户名

        //年龄
        @NotNull
        private Integer age;

        /**
         * @deprecated It's a secret
         */
        private Integer sex;

        //生日
        private LocalDate birthDay;

        //注册时间
        private LocalDateTime regtime;

        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }

        public int getType() {
            return type;
        }

        public void setType(int type) {
            this.type = type;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public Integer getAge() {
            return age;
        }

        public void setAge(Integer age) {
            this.age = age;
        }

        public Integer getSex() {
            return sex;
        }

        public void setSex(Integer sex) {
            this.sex = sex;
        }

        public LocalDate getBirthDay() {
            return birthDay;
        }

        public void setBirthDay(LocalDate birthDay) {
            this.birthDay = birthDay;
        }

        public LocalDateTime getRegtime() {
            return regtime;
        }

        public void setRegtime(LocalDateTime regtime) {
            this.regtime = regtime;
        }
    }

    private enum Opt {
        FIRST(0),
        SECOND(1);

        private int value;

        Opt(int value) {
            this.value = value;
        }
    }
}

```

导出结果是:

## 增加新用户

### BASIC

**Path：** inner/add

**Method：** POST

### REQUEST


**Headers：**

| name  |  value  |  required  | desc  |
| ------------ | ------------ | ------------ | ------------ |
| Content-Type | application/json | YES |  |
| token |  | YES | 认证Token |

**Query：**

| name  |  value  |  required | desc  |
| ------------ | ------------ | ------------ | ------------ |
| opt | 0 | NO | op [com.itangcent.springboot.demo.controller.InnerClassCtrl.Opt#value]<br>0 :FIRST<br>1 :SECOND |

**RequestBody**

| name | type | required | default | desc |
| ------------ | ------------ | ------------ | ------------ | ------------ |
| id | integer | NO |  | 用户id | 
| type | integer | NO |  | 用户类型<br>1 :管理员<br>2 :成员<br>3 :游客 | 
| name | string | YES |  | 用户名 | 
| age | integer | YES |  | 年龄 | 
| sex | integer | NO |  | 「已废弃」It's a secret | 
| birthDay | string | NO |  | 生日 | 
| regtime | string | NO |  | 注册时间 | 

---

看起来是符合预期的。

**Comment by hellsof** [comment]
> 我试了一下:
> 
> ```java
> package com.itangcent.springboot.demo.controller;
> 
> import com.itangcent.common.dto.Result;
> import org.springframework.web.bind.annotation.PostMapping;
> import org.springframework.web.bind.annotation.RequestBody;
> import org.springframework.web.bind.annotation.RequestMapping;
> import org.springframework.web.bind.annotation.RestController;
> 
> import javax.validation.constraints.NotBlank;
> import javax.validation.constraints.NotNull;
> import java.time.LocalDate;
> import java.time.LocalDateTime;
> 
> /**
>  * 内部类测试
>  *
>  * @module user
>  */
> @RestController
> @RequestMapping(value = "inner")
> public class InnerClassCtrl extends BaseController {
> 
>     /**
>      * 增加新用户
>      *
>      * @param opt op {@link Opt#value}
>      */
>     @PostMapping("/add")
>     public Result<UserInfo> add(
>             Integer opt,
>             @RequestBody UserInfo userInfo) {
>         return Result.success(userInfo);
>     }
> 
>     public static class UserInfo {
> 
>         private Long id;//用户id
> 
>         /**
>          * @see com.itangcent.common.constant.UserType
>          */
>         private int type;//用户类型
> 
>         @NotBlank
>         private String name;//用户名
> 
>         //年龄
>         @NotNull
>         private Integer age;
> 
>         /**
>          * @deprecated It's a secret
>          */
>         private Integer sex;
> 
>         //生日
>         private LocalDate birthDay;
> 
>         //注册时间
>         private LocalDateTime regtime;
> 
>         public Long getId() {
>             return id;
>         }
> 
>         public void setId(Long id) {
>             this.id = id;
>         }
> 
>         public int getType() {
>             return type;
>         }
> 
>         public void setType(int type) {
>             this.type = type;
>         }
> 
>         public String getName() {
>             return name;
>         }
> 
>         public void setName(String name) {
>             this.name = name;
>         }
> 
>         public Integer getAge() {
>             return age;
>         }
> 
>         public void setAge(Integer age) {
>             this.age = age;
>         }
> 
>         public Integer getSex() {
>             return sex;
>         }
> 
>         public void setSex(Integer sex) {
>             this.sex = sex;
>         }
> 
>         public LocalDate getBirthDay() {
>             return birthDay;
>         }
> 
>         public void setBirthDay(LocalDate birthDay) {
>             this.birthDay = birthDay;
>         }
> 
>         public LocalDateTime getRegtime() {
>             return regtime;
>         }
> 
>         public void setRegtime(LocalDateTime regtime) {
>             this.regtime = regtime;
>         }
>     }
> 
>     private enum Opt {
>         FIRST(0),
>         SECOND(1);
> 
>         private int value;
> 
>         Opt(int value) {
>             this.value = value;
>         }
>     }
> }
> ```
> 
> 导出结果是:
> 
> ## 增加新用户
> ### BASIC
> **Path：** inner/add
> 
> **Method：** POST
> 
> ### REQUEST
> **Headers：**
> 
> name	value	required	desc
> Content-Type	application/json	YES	
> token		YES	认证Token
> **Query：**
> 
> name	value	required	desc
> opt	0	NO	op [com.itangcent.springboot.demo.controller.InnerClassCtrl.Opt#value]
> 0 :FIRST
> 1 :SECOND
> **RequestBody**
> 
> name	type	required	default	desc
> id	integer	NO		用户id
> type	integer	NO		用户类型
> 1 :管理员
> 2 :成员
> 3 :游客
> name	string	YES		用户名
> age	integer	YES		年龄
> sex	integer	NO		「已废弃」It's a secret
> birthDay	string	NO		生日
> regtime	string	NO		注册时间
> 看起来是符合预期的。

需要在不同的包下，且`import`时只导入父类，在`@param {@link 父类.内部枚举类}`这样才不生效

**Comment by tangcent** [comment]
see https://github.com/Earth-1610/intellij-kotlin/pull/143

[easy-yapi-2.3.0.183.0.zip](https://github.com/tangcent/easy-yapi/files/7688994/easy-yapi-2.3.0.183.0.zip)

**Comment by zzz583974851** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hellsof** [comment]
> see [Earth-1610/intellij-kotlin#143](https://github.com/Earth-1610/intellij-kotlin/pull/143)
> 
> [easy-yapi-2.3.0.183.0.zip](https://github.com/tangcent/easy-yapi/files/7688994/easy-yapi-2.3.0.183.0.zip)

非常感谢🙏
