### ISSUE TITLE
最新版本2.2.0.183.0无法生成接口文档了，2.1.4.183.0是可以的

### ISSUE THREAD

**Issue by simonpdh** [tangcent/easy-yapi#453]
search api from 这个日志打印完就一直停在哪里，不进行请求

**Comment by tangcent** [comment]
我之前有碰到这种情况，可能是`http`连接池的问题，在#434 修复了
你试试: [easy-yapi-2.2.0.183.0.zip](https://github.com/tangcent/easy-yapi/files/6375749/easy-yapi-2.2.0.183.0.zip)，看看能不能解决

**Comment by simonpdh** [comment]
> 我之前有碰到这种情况，可能是`http`连接池的问题，在#434 修复了
> 你试试: [easy-yapi-2.2.0.183.0.zip](https://github.com/tangcent/easy-yapi/files/6375749/easy-yapi-2.2.0.183.0.zip)，看看能不能解决

能否出一个最新版本，我们这边大家更新后都不能使用了，降版本麻烦

**Comment by tangcent** [comment]
Released: https://github.com/tangcent/easy-yapi/releases/tag/v2.2.1-rc
It's now pending JetBrain's review and approval in order to be publicly available.
The request will be processed within two business days.

**Comment by simonpdh** [comment]
> Released: https://github.com/tangcent/easy-yapi/releases/tag/v2.2.1-rc
> It's now pending JetBrain's review and approval in order to be publicly available.
> The request will be processed within two business days.

感谢作者大大

**Comment by tangcent** [comment]
Version 2.2.1-rc of the EasyYapi plugin has been approved by JetBrains and is now publicly available by the following link: https://plugins.jetbrains.com/plugin/12458-easyyapi/versions/stable/118232.
