### ISSUE TITLE
dubbo接口生成，@method=GET，参数为JAVA实体

### ISSUE THREAD

**Issue by simonpdh** [tangcent/easy-yapi#458]
原issue链接： https://github.com/tangcent/easy-yapi/issues/428

生成的dubbo接口，get请求方式，参数为java实体对象，实体属性生成被展示在示例里

**Comment by tangcent** [comment]
`yapi`限制了`GET`没有`body`
目前是放到`query`里了:https://github.com/tangcent/easy-yapi/blob/5bccac47cf571bd0c7c9c7a63e3f09d0c11b7db5/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt#L112-L122

**Comment by simonpdh** [comment]
> `yapi`限制了`GET`没有`body`
> 目前是放到`query`里了:
> 
> https://github.com/tangcent/easy-yapi/blob/5bccac47cf571bd0c7c9c7a63e3f09d0c11b7db5/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt#L112-L122

但生成的文档很丑，也不知道字段类型，全部是json耦在一块，能否生成controller里get请求的那种格式

**Comment by tangcent** [comment]
你试试在`yapi`里编辑一个接口，然后把你觉得展示ok的`api`截图给我看看?

**Comment by simonpdh** [comment]
> 你试试在`yapi`里编辑一个接口，然后把你觉得展示ok的`api`截图给我看看?

对dubbo的get接口方便生成这种格式的接口吗？

代码接口
@GetMapping(value = "/queryToUpgradeSongList")
 public BaseResponse<PageDTO<AuthSongDTO>> querySongList(SongListRequest request) {}

下图截图的字段为SongListRequest属性

![image](https://user-images.githubusercontent.com/23329416/116243831-ee9c7d00-a799-11eb-97d1-5da4bf9d18bc.png)

**Comment by tangcent** [comment]
`yapi` `GET`接口没有`body`。没办法做成这样吧?你用的`yapi`被二次开发过吗?
选了`GET`,只能填`Query`:
![image](https://user-images.githubusercontent.com/17569144/116253317-f4e32700-a7a2-11eb-87ef-7cb44605633c.png)

**Comment by simonpdh** [comment]
> `yapi` `GET`接口没有`body`。没办法做成这样吧?你用的`yapi`被二次开发过吗?
> 选了`GET`,只能填`Query`:
> ![image](https://user-images.githubusercontent.com/17569144/116253317-f4e32700-a7a2-11eb-87ef-7cb44605633c.png)

生成query也没问题，但对象里的属性起码希望能这样展示
![image](https://user-images.githubusercontent.com/23329416/116254832-4344f580-a7a4-11eb-9c93-cab76c125eef.png)

**Comment by tangcent** [comment]
1. 对于多个参数的方法要如何处理?
```java
@GetMapping(value = "/queryToUpgradeSongList")
public BaseResponse<PageDTO> querySongList(SongListRequest request,String userId) {
}
```
2. 对于参数有多层的方法要如何处理?
```java
@GetMapping(value = "/queryToUpgradeSongList")
public BaseResponse<PageDTO> querySongList(PageRequest<SongListRequest> request) {
}
```

**Comment by simonpdh** [comment]
> 1. 对于多个参数的方法要如何处理?
> 
> ```java
> @GetMapping(value = "/queryToUpgradeSongList")
> public BaseResponse<PageDTO> querySongList(SongListRequest request,String userId) {
> }
> ```
> 
> 1. 对于参数有多层的方法要如何处理?
> 
> ```java
> @GetMapping(value = "/queryToUpgradeSongList")
> public BaseResponse<PageDTO> querySongList(PageRequest<SongListRequest> request) {
> }
> ```
![image](https://user-images.githubusercontent.com/23329416/116366998-74bbd080-a839-11eb-9d61-cd26df03554a.png)
1、2可否这样处理

**Comment by tangcent** [comment]
即使这样也还是只能处理两层。还是无法处理无限层的问题。
为什么不用`POST`呢？

**Comment by simonpdh** [comment]
> 即使这样也还是只能处理两层。还是无法处理无限层的问题。
> 为什么不用`POST`呢？

主要是我们这边的接口不存在这种
@GetMapping(value = "/queryToUpgradeSongList")
public BaseResponse<PageDTO> querySongList(SongListRequest request,String userId) {
}

大部分是这种
@GetMapping(value = "/queryToUpgradeSongList")
public BaseResponse<PageDTO> querySongList(SongListRequest request) {
}

**Comment by tangcent** [comment]
假设有
```java
public class Point {
    private int x;
    private int y;
}
```
要如何区分以下两个方法导出的`api`:
```java
public BaseResponse methodA(Point point)
```
```java
public BaseResponse methodB(int x,  int y)
```

**Comment by tangcent** [comment]
也许可以给出一个配置选项，允许默认展开单入参方法的`query`, 类似于http中`@RequestBody`的效果。
但是这样会不会导致插件使用过于复杂?

**Comment by simonpdh** [comment]
> 假设有
> 
> ```java
> public class Point {
>     private int x;
>     private int y;
> }
> ```
> 
> 要如何区分以下两个方法导出的`api`:
> 
> ```java
> public BaseResponse methodA(Point point)
> ```
> 
> ```java
> public BaseResponse methodB(int x,  int y)
> ```

你这个@GetMapping也存在这样的

**Comment by simonpdh** [comment]
> 也许可以给出一个配置选项，允许默认展开单入参方法的`query`, 类似于http中`@RequestBody`的效果。
> 但是这样会不会导致插件使用过于复杂?

可以默认不选中，需要的用户自己勾选配置即可

**Comment by simonpdh** [comment]
> 也许可以给出一个配置选项，允许默认展开单入参方法的`query`, 类似于http中`@RequestBody`的效果。
> 但是这样会不会导致插件使用过于复杂?

目前http接口，Controller的Get请求
@GetMapping(value = "/config")
public XxxConfigVO config(XxxConfigRequest request,String abc) {}
public class ActivityConfigRequest{ private String Id;}

生成文档如下
![image](https://user-images.githubusercontent.com/23329416/117667156-329a7380-b1d7-11eb-9dae-a4ef2f4fe28a.png)


如果是dubbo接口的GET请求，是否也可以类似这样处理呐

还有目前dubbo接口POST请求生成的文档会带实体对象名，例子如下
/**
     * 更新二维码状态
     *
     * @param request
     * @return
     * @path /xxx-gateway/xxx/xxx/update
     * @method POST
     */
    BaseResponse updateQrCodeStatus(XxxxUpdateRequest request);
![image](https://user-images.githubusercontent.com/23329416/117667577-958c0a80-b1d7-11eb-8c49-fd3158393676.png)

**Comment by tangcent** [comment]
ref: https://github.com/tangcent/easy-yapi/pull/482
