### ISSUE TITLE
怎么支持spring自带的page对象

### ISSUE THREAD

**Issue by tutuerhao** [tangcent/easy-yapi#459]
org.springframework.data.domain.Page没法解析呀

**Comment by tutuerhao** [comment]
![image](https://user-images.githubusercontent.com/29938085/116217925-9dca5b80-a77c-11eb-8513-b04d8a71ba12.png)

**Comment by tangcent** [comment]
是否有在<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>General</kbd>> <kbd>Intelligent</kbd> 中勾选了`getter as field`?

**Comment by tutuerhao** [comment]
> 是否有在Preferences(Settings) > Other Settings > EasyApi > General> Intelligent 中勾选了`getter as field`?
![image](https://user-images.githubusercontent.com/29938085/116331570-a9606580-a802-11eb-8e25-34f7a934034c.png)
木有呀

**Comment by tutuerhao** [comment]
> 是否有在Preferences(Settings) > Other Settings > EasyApi > General> Intelligent 中勾选了`getter as field`?

勾选就可以啦，谢谢作者
