### ISSUE TITLE
使用Docker部署Yapi，执行导出到yapi没有记录导入

### ISSUE THREAD

**Issue by peng051410** [tangcent/easy-yapi#46]
使用Docker部署Yapi，执行导出到yapi没有记录导入，我的配置如下

![image](https://user-images.githubusercontent.com/5512326/63492974-221b0480-c4ed-11e9-915e-936638b48327.png)

我使用的测试项目是spring-demo，在controller上执行的ExportYapi操作，我还需要做其它什么操作吗？

**Comment by peng051410** [comment]
找到问题了，spring-boot-starter-parent的version要修改为2.1.6.RELEASE 这样idea就会自动导入maven依赖了

**Comment by tangcent** [comment]
建议视情况开启inferEnable~
使用过程中发现推导问题，及时沟通，我会尽快处理的.

**Comment by peng051410** [comment]
收到！
