### ISSUE TITLE
导出yapi文档必填选项不识别@NotBlank，NotEmpty

### ISSUE THREAD

**Issue by inbrcvb** [tangcent/easy-yapi#460]
希望可以支持一下这两个注解

**Comment by tangcent** [comment]
是否有在<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Recommend</kbd>中勾选`javax.validation`?

**Comment by inbrcvb** [comment]
got it
