### ISSUE TITLE
更新接口文档，覆盖返回数据问题！

### ISSUE THREAD

**Issue by inbrcvb** [tangcent/easy-yapi#461]
每次更新接口文档，都会覆盖原来导入的json返回数据，需要更新后再导入一次，很麻烦，能否提供一个开关，每次更新接口文档不覆盖原来填写的返回数据！

**Comment by tangcent** [comment]
这个问题在最初就有考虑过，但是未能找到一个通用的`merge`逻辑。
比如以下情况:
1. 开发者在代码中增加了一个新的字段, 再重新上传
2. 开发者在代码中删除了一个新的字段 , 再重新上传
3. 开发者在`yapi`中手动增加了一个新的字段 , 再重新上传
4. 开发者在`yapi`中手动删除了一个新的字段 , 再重新上传

需要解决的问题是如何判断`diff`是代码产生的还是开发者在`yapi`中手动操作产生的。

> 不覆盖原来填写的返回数据

 即这里需要一个方法来判断什么是`原来填写的返回数据`


---

我目前的处理方式主要是:
1. 尽可能通过配置来输出更加完整、符合开发者需求的`yapi`文档。
2. 对于极个别必须手动修改的`api`,导出到`yapi`后，标记为[`ignore`](http://easyyapi.com/setting/rules/ignore.html),以后不再通过插件导出.

**Comment by inbrcvb** [comment]
不好意思我想先明确下，easyyapi支持对api返参的文档的自动生成吗？如果是需要开发者自己手动导入json返参来生成文档的话，比如我某一次更新了aip到yapi。上次导入的json返参所生成的文档就被删掉了，这个时候是不是可以考虑一下，当更新api到yipi的时候只针对入参覆盖并重新渲染文档，而返参的文档是否重新渲染以开发者手动倒入返参json来决定。

**Comment by tangcent** [comment]
> easyyapi支持对api返参的文档的自动生成吗？

当然是自动生成, 我也不愿写文档

> 比如我某一次更新了api到yapi。上次导入的json返参所生成的文档就被删掉了

你这里的`上次导入`是指在`yapi`里编辑?

> 这个时候是不是可以考虑一下，当更新api到yapi的时候只针对入参覆盖并重新渲染文档，而返参的文档是否重新渲染以开发者手动导入返参json来决定。

有这个需求的开发者似乎很少，目前我接触到的开发者用了插件后都没有`手动导入返参json`了

---

你似乎在使用这个插件的过程中遇到了些问题, 是不能正常导出`api`的响应，还是导出的响应不满足你的需求?

**Comment by inbrcvb** [comment]
我现在的问题是无法生成aip响应，响应字段放在private Object data里，但是文档只生成到data，data里的具体字段没有生成，我看demo是private <T> data, 我换了 <T> data还是没有生成，请问是我哪里操作不规范么？

**Comment by inbrcvb** [comment]
我现在的问题是无法生成aip响应，响应字段放在private Object data里，但是文档只生成到data，data里的具体字段没有生成，我看demo是private <T> data, 我换了 <T> data还是没有生成，请问是我哪里操作不规范么？

**Comment by inbrcvb** [comment]
我现在的问题是无法生成aip响应，响应字段放在private Object data里，但是文档只生成到data，data里的具体字段没有生成，我看demo是private T data, 我换了 T data还是没有生成，请问是我哪里操作不规范么？

**Comment by tangcent** [comment]
参考: https://github.com/Earth-1610/spring-demo/blob/master/cn/common/src/main/java/com/itangcent/common/dto/Result.java

```java
public class Result<T>  {
    private T data;//响应数据
}
```

**Comment by inbrcvb** [comment]
楼主我又来了......又发现了一个最新的问题。 Result<T>如果单独打成工具jar供所有服务引用，class文件会出现泛型擦除就无法生成api的响应文档了，但是如一个项目里放一个Result<T>的话就可以生成。不都是用的class文件么，请问有什么不同吗？

**Comment by tangcent** [comment]
> 楼主我又来了......又发现了一个最新的问题。 Result如果单独打成工具jar供所有服务引用，class文件会出现泛型擦除就无法生成api的响应文档了，但是如一个项目里放一个Result的话就可以生成。不都是用的class文件么，请问有什么不同吗？

应该不至于出现泛型擦除。
通过`maven/gradle`引入jar包之后，如果没有在idea中操作`Download Source`的话会丢失注释,这是由于idea没有关联引入包的源码包。
只要打开丢失注释的类文件，点击`Download Source`之后重新导入即可。
![image](https://user-images.githubusercontent.com/17569144/118449709-fd85a800-b725-11eb-86fe-4910708df910.png)

**Comment by inbrcvb** [comment]
工具包是用gradle管理的，其他项目是maven，其他项目引入工具包的jar后，关联源码之后return new  Result<> 的泛型是在的，但是依旧无法生成API响应文档，很迷茫......大佬有时间的话麻烦复现一下。

**Comment by tangcent** [comment]
怕是很难重现，我自己日常也还是在使用这个插件，api的`Result`也是通过`maven`引入的，却没有遇到过你这种情况。

1. 可以尝试确认关联到了源码, 简单的体现就是在web项目中点开引入包的`Result`类，能跳到`Result.java`而不是`Result.class`
2. 可以尝试clone插件源码`debug`试试
