### ISSUE TITLE
BaseResponse 问题

### ISSUE THREAD

**Issue by gaojunjun2016** [tangcent/easy-yapi#462]
例如我的一个 Controller 返回值是 BaseResponse，我希望他的泛型是结果集的<T>，而不是 错误码等等,因为这里会判断保持返回给业务

**Comment by tangcent** [comment]
不是很能理解你的问题
类似于这个吗?
https://github.com/Earth-1610/spring-demo/blob/22cab730bf938982c59d9de5ccc4684686b7d2fe/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/UserCtrl.java#L88-L94
