### ISSUE TITLE
Void泛型出现StockOverflow

### ISSUE THREAD

**Issue by chenshun00** [tangcent/easy-yapi#463]
背景是我们会使用一个Response<T>的泛型来处理响应数据，但是有些只要简单的返回code和msg就行了，然后我们采用了Void来作为泛型会报错。 Void===>java.lang.Void

```java
public Response<Void> method(){
    //biz
   return xxx;
}
```

**Comment by tangcent** [comment]
未能在此重现: https://github.com/Earth-1610/spring-demo/blob/d49e8b67e82bf9ef04a54ce9c0213a7a5999bb88/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/TestCtrl.java#L90-L103

**Comment by chenshun00** [comment]
嗯，我试一下，确实是其他的问题，3Q
