### ISSUE TITLE
No token be found for xxx

### ISSUE THREAD

**Issue by wenfer** [tangcent/easy-yapi#464]
tokens里面也配置了，日志打印 token:9a277293bb565acd4a98 may be invalid.

生成的时候还是会弹框让我填token，填了还是会报No token be found for xxx

**Comment by wenfer** [comment]
idea 2020.2.4   plugin 2.2.1.183.0-rc

**Comment by tangcent** [comment]
- 你这里的`token`是`20`位的, 应该是旧版本的`yapi`, 新版本的`yapi`的`token`是`64`位。
- 旧版本的`yapi`缺少部分[`openapi`](https://hellosean1025.github.io/yapi/openapi.html), 需要使用[`loginMode`](http://easyyapi.com/documents/login_mode_yapi.html)
