### ISSUE TITLE
@NotNull 生成的Markdown，RequestBody和ResponseBody没有required一列

### ISSUE THREAD

**Issue by kaywer** [tangcent/easy-yapi#466]
在IDEA plugins 直接install的EasyYapi，版本为2.2.1.183.0-rc，使用的是默认配置。

在RequestBody的DTO中，为字段加了@NotNull，  import javax.validation.constraints.NotNull;
但是生成出来的Markdown文档，没有required一列。

如下：

<html>
<body>
<p md-src-pos="2603..2618" style="box-sizing: border-box; margin-top: 16px; margin-bottom: 16px; color: rgb(187, 187, 187); font-family: Helvetica, Arial, freesans, sans-serif; font-size: 17px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(43, 43, 43); text-decoration-style: initial; text-decoration-color: initial;"><strong md-src-pos="2603..2618" style="font-weight: bold; box-sizing: border-box;">RequestBody</strong></p>

name | type | desc
-- | -- | --
str | string |  
notEmpty | string |  

<br class="Apple-interchange-newline">
</body>
</html>

请问是否哪未配置正确？

IDEA版本为：2020.3

**Comment by tangcent** [comment]
尝试将<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Markdown</kbd> > <kbd>format type</kbd>切换为`ULTIMATE`
