### ISSUE TITLE
Rpc文档不支持method.additional.header吗？

### ISSUE THREAD

**Issue by simonpdh** [tangcent/easy-yapi#467]
今天尝试在生成rpc文档的时候使用method.additional.header添加接口的header，但无效，请问rpc接口如何添加header

**Comment by tangcent** [comment]
`method.additional.header`对导出`rpc`无效, 当前`rpc`->`yapi`的过程是:
1. [`GenericMethodDocClassExporter`](https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/generic/GenericMethodDocClassExporter.kt)解析`rpc` -> [`MethodDoc`](https://github.com/tangcent/easy-yapi/blob/master/common-api/src/main/kotlin/com/itangcent/common/model/MethodDoc.kt)
2. [`YapiFormatter`](https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt) 将[`MethodDoc`](https://github.com/tangcent/easy-yapi/blob/master/common-api/src/main/kotlin/com/itangcent/common/model/MethodDoc.kt)解析成`yapi`接受的`api`格式

---

实际上第一步解析`rpc`不涉及到任何`http`相关逻辑, 比如针对场景`rpc`->`methodDoc`->`markdown`就不需要任何`http`相关信息。故从`rpc`->[`request`](https://github.com/tangcent/easy-yapi/blob/master/common-api/src/main/kotlin/com/itangcent/common/model/Request.kt)有处理`http`相关配置，而`rpc`->`methodDoc`并未处理。
这里如果要使`rpc`->`yapi`支持`method.additional.header`的话，应该要在https://github.com/tangcent/easy-yapi/blob/75ad153eedef9dabbcec7c69e55305f816d45a49/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiMethodDocBuilderListener.kt#L46-L60 中处理`method.additional.header`到`methodDoc`的`exts `中，然后由https://github.com/tangcent/easy-yapi/blob/75ad153eedef9dabbcec7c69e55305f816d45a49/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt#L68 处理到`yapi`

---

总的来说处理不难，问题还是在于对`rpc`做这么多`http`相关的配置是否合理、是否通用?

**Comment by simonpdh** [comment]
> `method.additional.header`对导出`rpc`无效, 当前`rpc`->`yapi`的过程是:
> 
> 1. [`GenericMethodDocClassExporter`](https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/generic/GenericMethodDocClassExporter.kt)解析`rpc` -> [`MethodDoc`](https://github.com/tangcent/easy-yapi/blob/master/common-api/src/main/kotlin/com/itangcent/common/model/MethodDoc.kt)
> 2. [`YapiFormatter`](https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt) 将[`MethodDoc`](https://github.com/tangcent/easy-yapi/blob/master/common-api/src/main/kotlin/com/itangcent/common/model/MethodDoc.kt)解析成`yapi`接受的`api`格式
> 
> 实际上第一步解析`rpc`不涉及到任何`http`相关逻辑, 比如针对场景`rpc`->`methodDoc`->`markdown`就不需要任何`http`相关信息。故从`rpc`->[`request`](https://github.com/tangcent/easy-yapi/blob/master/common-api/src/main/kotlin/com/itangcent/common/model/Request.kt)有处理`http`相关配置，而`rpc`->`methodDoc`并未处理。
> 这里如果要使`rpc`->`yapi`支持`method.additional.header`的话，应该要在
> 
> https://github.com/tangcent/easy-yapi/blob/75ad153eedef9dabbcec7c69e55305f816d45a49/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiMethodDocBuilderListener.kt#L46-L60
> 
> 中处理`method.additional.header`到`methodDoc`的`exts `中，然后由
> https://github.com/tangcent/easy-yapi/blob/75ad153eedef9dabbcec7c69e55305f816d45a49/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiFormatter.kt#L68
> 
> 处理到`yapi`
> 总的来说处理不难，问题还是在于对`rpc`做这么多`http`相关的配置是否合理、是否通用?


我们这边目前使用的是微服务，很多请求要先经过网关，网关是直接调用底层的RPC接口，但网关是不关系业务的，所以在底层的RPC接口文档就需要体现接口参数以及一些header信息，目前微服务场景下这种接口文档应该会比较普遍

**Comment by tangcent** [comment]
原来不对劲的逻辑在这:
我把`yapi`当做存放`methodDoc`的一个渠道，你们需求将`dubbo method`解析为`request`。
这样看的话，实际上应当构造`DubboRequestClassExporter`,将`dubbo method`解析为`request`。

**Comment by simonpdh** [comment]
> 原来不对劲的逻辑在这:
> 我把`yapi`当做存放`methodDoc`的一个渠道，你们需求将`dubbo method`解析为`request`。
> 这样看的话，实际上应当构造`DubboRequestClassExporter`,将`dubbo method`解析为`request`。

虽然没懂你说的，但我隐约感觉你应该懂了我说的需求，不知道啥时候rpc可以支持自定义header，感谢大佬

**Comment by tangcent** [comment]
> 虽然没懂你说的

你可以看一下[`MethodDoc`](https://github.com/tangcent/easy-yapi/blob/master/common-api/src/main/kotlin/com/itangcent/common/model/MethodDoc.kt)和[`Request`](https://github.com/tangcent/easy-yapi/blob/master/common-api/src/main/kotlin/com/itangcent/common/model/Request.kt)，
严格来说插件并没有提供针对`dubbo`的任何支持，它只是被当做普通方法解析为[`MethodDoc`](https://github.com/tangcent/easy-yapi/blob/master/common-api/src/main/kotlin/com/itangcent/common/model/MethodDoc.kt)然后强行导入`yapi`。

> 不知道啥时候rpc可以支持自定义header

这次改动不小，不再将`dubbo的method`解析为[`MethodDoc`](https://github.com/tangcent/easy-yapi/blob/master/common-api/src/main/kotlin/com/itangcent/common/model/MethodDoc.kt)强行导入`yapi`
而是提供一个通用的由开发者配置所有如何从一个`method`上解析出[`api`](https://github.com/tangcent/easy-yapi/blob/master/common-api/src/main/kotlin/com/itangcent/common/model/Request.kt)。
这可能需要开发者配置十多个`key`，所以会提供一个`spring`版的`demo config`作参考，
也将尝试提供一个`dubbo`版的`demo config`。
它们都将被防止在[third](https://github.com/tangcent/easy-yapi/tree/master/third)下。

---

这次改动后，#419 或者其他的`web`框架也许都可以靠一份配置来支持。

**Comment by simonpdh** [comment]
> > 虽然没懂你说的
> 
> 你可以看一下[`MethodDoc`](https://github.com/tangcent/easy-yapi/blob/master/common-api/src/main/kotlin/com/itangcent/common/model/MethodDoc.kt)和[`Request`](https://github.com/tangcent/easy-yapi/blob/master/common-api/src/main/kotlin/com/itangcent/common/model/Request.kt)，
> 严格来说插件并没有提供针对`dubbo`的任何支持，它只是被当做普通方法解析为[`MethodDoc`](https://github.com/tangcent/easy-yapi/blob/master/common-api/src/main/kotlin/com/itangcent/common/model/MethodDoc.kt)然后强行导入`yapi`。
> 
> > 不知道啥时候rpc可以支持自定义header
> 
> 这次改动不小，不再将`dubbo的method`解析为[`MethodDoc`](https://github.com/tangcent/easy-yapi/blob/master/common-api/src/main/kotlin/com/itangcent/common/model/MethodDoc.kt)强行导入`yapi`
> 而是提供一个通用的由开发者配置所有如何从一个`method`上解析出[`api`](https://github.com/tangcent/easy-yapi/blob/master/common-api/src/main/kotlin/com/itangcent/common/model/Request.kt)。
> 这可能需要开发者配置十多个`key`，所以会提供一个`spring`版的`demo config`作参考，
> 也将尝试提供一个`dubbo`版的`demo config`。
> 它们都将被防止在[third](https://github.com/tangcent/easy-yapi/tree/master/third)下。
> 
> 这次改动后，#419 或者其他的`web`框架也许都可以靠一份配置来支持。

有具体的demo配置吗？我尝试使用下

**Comment by tangcent** [comment]
> 有具体的demo配置吗？我尝试使用下

还没呢，最近有点忙

**Comment by simonpdh** [comment]
> > 有具体的demo配置吗？我尝试使用下
> 
> 还没呢，最近有点忙

好，期待

**Comment by tangcent** [comment]
ref: https://github.com/tangcent/easy-yapi/pull/482
![image](https://user-images.githubusercontent.com/17569144/120262625-9989e480-c2cc-11eb-8212-05c792ce7183.png)
demo配置: https://github.com/tangcent/easy-yapi/blob/master/third/dubbo.config
具体文档还没写~ 配置也是需要根据你自己的项目来改以满足你的需求

**Comment by simonpdh** [comment]
> ref: #482
> ![image](https://user-images.githubusercontent.com/17569144/120262625-9989e480-c2cc-11eb-8212-05c792ce7183.png)
> demo配置: https://github.com/tangcent/easy-yapi/blob/master/third/dubbo.config
> 具体文档还没写~ 配置也是需要根据你自己的项目来改以满足你的需求

非常感谢，刚才试了下不生成request了，而且优先级没mdoc高
当前配置如下

generic.class.has.api=groovy:it.name().endsWith("Facade")
generic.class.has.api=groovy:it.name().endsWith("Service")
generic.path=#path

generic.http.method=#method
generic.http.method[#post]=POST
generic.http.method[#POST]=POST
generic.http.method[#get]=GET
generic.http.method[#GET]=GET
#use POST by default
generic.http.method=POST
#always true
generic.method.has.api=true
generic.param.as.json.body=groovy:!it.type().isNormalType()
generic.param.as.form.body=true
