### ISSUE TITLE
怎么为每个项目单独配置token呢

### ISSUE THREAD

**Issue by LovingCoder** [tangcent/easy-yapi#474]
你好，怎么为每个项目在easy.api.config中配置yapi 的token跟host呢？

**Comment by tangcent** [comment]
> 为每个项目在easy.api.config中配置yapi 的host

- 可以用`yapi.server=你这个项目用的yapi地址`来覆盖setting里的配置

> 为每个项目在easy.api.config中配置yapi 的token

- 如果你整个项目要导入yapi的同一个`project`下的话，不需要做额外配置，直接导出，会有弹框让你输入对应`project`的`token`。
- 如果你要将一个项目中的api导入yapi的不同`project`下的话，参考http://easyyapi.com/setting/rules/module.html , 在类上注释`@module xxxx`来将不同的类分为不同的`module`，之后导出时会以弹框的形式让你输入每个`module`对应的`yapi project`的`token`

**Comment by LovingCoder** [comment]
作者你好，是这样的

> 现在有一个projectA，projectA下面有moduleOne，moduleTwo，然后现在我又创建了个一个projectB，projectB下面有moduleOne，moduleTwo，按照作者的描述，我是不是应该在projectA和projectB下面的每一个类，都加上 @module 的注解 ，就是说，

- projectA的moduleOne每一个类加上 @mudule projectA-moduelOne,moduleTwo每一个类加上 @mudule projectA-moduleTwo，
- projectB的moduleOne每一个类加上 @mudule projectB-moduelOne,moduleTwo每一个类加上 @mudule projectB-moduleTwo

因为如果不这样做的话，当我先export projectA的所有api到yapi之后，再去export projectB的所有api到ypai，这个时候，projectB会把projectA的api给覆盖掉，因为他们的两个module名称都是moduleOne和moduleTwo

我需要怎么解决这个问题呢

**Comment by tangcent** [comment]
ref: http://easyyapi.com/setting/local-file-config.html

- 也许你可以尝试在projectA的moduleOne下创建`.easy.api.config`,直接配置`module=projectA-moduelOne`,这将使得projectA的moduleOne下的所有`api`归于`projectA-moduelOne`。同理你可以在每个`module`下使用配置文件来指定`module`。
- 当然如果你能总结出一个适合你的通用的计算`module`的方法也可以。比如如果projectA的moduleOne每一个类的包名都是`com.xxx.projectA.moduleOne.Xxxxx`，那么可以通过配置从包名计算出`projectA-moduleOne`。

**Comment by LovingCoder** [comment]
可不可以这样理解，现在这个插件如果通过module方式指定的话，依然还是要在这个module下的每个类上加 @module 注解？

**Comment by tangcent** [comment]
> 可不可以这样理解，现在这个插件如果通过module方式指定的话，依然还是要在这个module下的每个类上加 @module 注解？

完全理解错了。

- 不添加任何配置文件时，在内置的推荐配置里有`module=@module`,这个意思是在每个`class`上尝试读取`module`
- 你在projectA的moduleOne下创建.easy.api.config,直接配置`module=projectA-moduelOne`，意思是`projectA的moduleOne`所有的api的module都是`projectA-moduelOne`

---

ref: http://easyyapi.com/setting/config-rule.html

`module=abc` -> module固定abc
`module=#module`  -> 尝试从类上读注释`module`

**Comment by LovingCoder** [comment]
感谢作者解答，已经理解了 .easy.api.config的module配置，我还有一个疑问

> 就是能否在 .easy.api.config 中单独配置这个项目的 token，从而不用更新到idea的setting中呢？这样的话这个token可以跟随项目文件一块提交到git仓库，进行团队协同开发，不然的话，我们每一个开发人员在首次export的时候，都需要在idea的弹出框中配置token。

> 这个开源项目的源码里面，是在哪个地方解析的 .easy.api.config 这个文件内容呢？

**Comment by LovingCoder** [comment]
补充一下 在 .easy.api.config 中单独配置token，就是能否类似 yapi.server=http://xxx.com 的方式进行配置 例如： yapi.tokens=xxxx 这种形式

**Comment by tangcent** [comment]
每个token都是每个人独有的，使用自己的token导出项目时，`yapi`中能看到是谁导出的:
![image](https://user-images.githubusercontent.com/17569144/119128316-182e8880-ba68-11eb-975e-f0830b5afa53.png)
所以目前只提供了在配置文件中指定`yapi.server`来应对多个`yapi`服务的情况，而并没有对`tokens `提供类似的支持。
也许由开发人员自行填写更为合适?

**Comment by LovingCoder** [comment]
好的，既然同一个项目为不同的用户生成了一个token，确实应该是每个开发人员应该使用自己的token，而不应该统一使用同一个token。非常感谢作者的回答，谢谢
