### ISSUE TITLE
controller base response type extend HashMap can't export reponse data to yapi

### ISSUE THREAD

**Issue by wowo404** [tangcent/easy-yapi#475]
**Describe the bug**
in my project,the controller layer's base reponse type is AjaxResult,this type extend HashMap,when i export yapi,it's can't export response data.

**To Reproduce**
1. choose controller package
2. choose code --> click export yapi

**Expected behavior**

**Screenshots**
[](url)

**idea env:**
 - OS: windows
 - Version 2.2.1.183.0-rc

**yapi env:**
- OS:centos
- version: 1.9.2

**Comment by tangcent** [comment]
I have tested this situation. The test results show that class which inherit from HashMap will be parsed as `map` correctly(
at least met my expectations). 
When a class is a map, it should be {k:v}, so the fields defined in it will not be parsed, and this is also consistent with the behavior of most json parsing frameworks like `Gson`、`Jackson`...
May be you want to show the fields defined in `AjaxResult` to `yapi`? Let me know what `it's can't export response data.` means, No response data? Or the api exported not meet your expectations?
And please consider providing a spring project to reproduce this situation. You can fork the demo project: https://github.com/Earth-1610/spring-demo
