### ISSUE TITLE
error to resolve class:{@link xxx}

### ISSUE THREAD

**Issue by jdinosaur** [tangcent/easy-yapi#479]
自定义配置添加了  
```
method.return=#real_return
method.return[#real_return]=groovy: helper.resolveLink(it.doc("real_return"))
```
注释上写的`@real_return {@link XxxResponse}`  
导出到yapi时，日志打印`[WARN]	error to resolve class:{@link XxxResponse}`，解析错误  
改为`@real_return com.demo.XxxResponse`则可以解析成功

**Comment by tangcent** [comment]
这两种规则不应该同时配。

1. `method.return=#real_return`表示读取注释`@real_return`作为方法的返回
对应的注释是`@real_return XxxResponse`

2. `method.return[#real_return]=groovy: helper.resolveLink(it.doc("real_return"))`表示当方法上有`@real_return`注释时，解析里面的`@link`作为方法的返回
对应的注释是`@real_return {@link XxxResponse}`
