### ISSUE TITLE
无法读取配置文件和@mouble 注解没用

### ISSUE THREAD

**Issue by zhuangjiaju** [tangcent/easy-yapi#48]
您好，非常感谢您开发了这么好用的插件。但是我有一点小疑问。
1. 我已经配了
```
module=#module

#忽略不解析
ignore=#ignore

#额外的json解析规则
#支持jackson注解
json.rule.field.name=@com.fasterxml.jackson.annotation.JsonProperty#value
#ObjectId和Date处理为String
json.rule.convert[org.bson.types.ObjectId]=java.lang.String
json.rule.convert[java.util.Date]=java.lang.String
```
且 日志已经有了
```
[TRACE]	find config file:D:\git\wakanda\wakanda-home\src\main\java\com\ideacome\wakanda\home\controller\permission/.easy.api.config
```
我的java代码：
```java
/**
 * 账号管理1 #moulde 父类啊
 *
 * @module 父类
 * @author 罗成
 */
@RestController
@RequestMapping("permission/user")
public class UserController {
```
但是 实际上 去yapi里面看：
![image](https://user-images.githubusercontent.com/18475586/64088876-0b3ea280-cd76-11e9-82e9-9159ca18c038.png)
并没有创建父类接口
2. 我在 
![image](https://user-images.githubusercontent.com/18475586/64088908-26111700-cd76-11e9-8f5a-7f96cfb4253c.png)

很多地方加了配置，只有在java文件所在的目录配置才能生效，根目录配置无法读取到。麻烦作者大大看到了帮忙解决下

**Comment by clevertension** [comment]
![image](https://user-images.githubusercontent.com/346723/64089977-63c46e80-cd7b-11e9-95cb-58eca1bf9983.png)


findCurrentPath() should be findCurrentPathList()

![image](https://user-images.githubusercontent.com/346723/64090003-7b035c00-cd7b-11e9-911c-acaa0bc675a5.png)

while(iterator the current path list), if we can find the config file, it will be added into **configFiles**

**Comment by tangcent** [comment]
- First, feel free to use Chinese in easy-yapi
> module=#module
- 这条规则在导出postman时表现为一层目录
- 但是yapi官方版并不支持多层目录,所以这条规则表现为获取不同的token,即yapi中不同的项目
比如在不同的类上分别标注
`@module=user`和`@module=account`
那么插件将分别要求提供`use`与`account`对应的项目token

> config生效问题
-  我一开始是准备支持运行时允许不同的类使用不用的配置,但是后来这带来的消耗(不仅是指编码，还有使用时产生的延迟)超过了它的好处.另外,从第一批试用的小伙伴的情况看,都是在项目的最外层创建了配置文件.
-  现在的代码中保留有多级搜索的原因主要还是针对多module的项目,当然,对于采取了多配置文件的项目, 是并不适合一次性同时导出. 每次导出的范围应该控制在一个配置文件的影响范围内. 
- 当然,可能是我考虑的不够全面, 如果可以的话,是否可以简单描述一下，这里需要多配置文件的原因?

**Comment by clevertension** [comment]
![image](https://user-images.githubusercontent.com/346723/64090749-60cb7d00-cd7f-11e9-99ec-4da8f6391e82.png)

@tangcent 你的机器是不是 mac, 代码这里有向上搜索的功能, 但是貌似对windows 的path没有进行处理

**Comment by clevertension** [comment]
我觉得 new File(currentPath).getParent() 比 currentPath = currentPath.substringBeforeLast("/") 是不是要更好

**Comment by tangcent** [comment]
你是对的,这里对文件路径的处理是有些问题的.
如果可以的话，欢迎你给出一个PR.
当然，我也会在稍晚些时候，仔细检查一下项目中所有对文件路径的处理.
Thanks

**Comment by zhuangjiaju** [comment]
> ,这里对文件路径的处理是有些问题的.
> 如果可以的话，欢迎你给出一个PR.

hello 那个 @module 是不是也有问题。有的话 我就等您更新了。准备在我们公司推广

**Comment by tangcent** [comment]
> > ,这里对文件路径的处理是有些问题的.
> > 如果可以的话，欢迎你给出一个PR.
> 
> hello 那个 @module 是不是也有问题。有的话 我就等您更新了。准备在我们公司推广

- 文件路径的处理问题应该没有影响到这里的`@module`的解析.
- 如果你这里没有将标注不同的`@module=some`引入不同项目中的话，应该是文件路径的问题导致配置未生效
- 文件路径问题会尽快修复的

**Comment by zhuangjiaju** [comment]
> > > ,这里对文件路径的处理是有些问题的.
> > > 如果可以的话，欢迎你给出一个PR.
> > 
> > 
> > hello 那个 @module 是不是也有问题。有的话 我就等您更新了。准备在我们公司推广
> 
> * 文件路径的处理问题应该没有影响到这里的`@module`的解析.
> * 如果你这里没有将标注不同的`@module=some`引入不同项目中的话，应该是文件路径的问题导致配置未生效
> * 文件路径问题会尽快修复的

配置我文件是我是放在和java一个目录的 所以是生效了的。我也看到了生效的日志。就是不会创建父的目录

**Comment by tangcent** [comment]
> 配置我文件是我是放在和java一个目录的 所以是生效了的。我也看到了生效的日志。就是不会创建父的目录
- 对于这里的`父目录`，我们是否理解一致?
- yapi官方好像不支持多层目录结构,提供的结构是
`分组->项目->分类->接口`
且开放api并不支持新增项目.
- 所以一直以来，我和小伙伴们的用法都是使用`@module=project_code`将api导入到不同的项目中
- 你这里提到的`父目录`是否为定制版yapi增加的功能?

**Comment by zhuangjiaju** [comment]
谢谢谢您的耐心回答。最最最后一个问题。
```java
    /**
     * 真实姓名/昵称/电话1
     * 
     * @alias dd1
     * @json.rule.field.name dd2
     * @doc.field 测试file
     * @df 测试file11
     */
    private String search;
```
我配置了
```
json.rule.field.name=alias
doc.field=df
```
是不是这样做的？实际上 我最后出来的字段名字 没有变 还有 备注也灭有变

**Comment by tangcent** [comment]
maybe:
```
json.rule.field.name=#alias
doc.field=#df
```

- 很抱歉,我不是很擅长编写文档,给使用者带来了很多不便.
你可以看一下[简单规则](https://github.com/tangcent/easy-yapi/blob/master/docs/cn/2.%20%E6%94%AF%E6%8C%81%E7%9A%84%E9%85%8D%E7%BD%AE%E8%A7%84%E5%88%99.md#%E7%AE%80%E5%8D%95%E8%A7%84%E5%88%99)

---
# 简单规则
- \# 读取注释上的tag
- @ 读取注解
   - @xxx 读取方法或字段上的注解
   - @xxx#yyy 读取方法或字段上的注解中的attr值

---

**Comment by zhuangjiaju** [comment]
哇哇 可以了 非常 非常感谢 我自己没注意到。坐等大佬更新 读取配置支持根目录的问题。

**Comment by tangcent** [comment]
可以尝试:
[easy-yapi.jar.zip](https://github.com/tangcent/easy-yapi/files/3566584/easy-yapi.jar.zip)

**Comment by zhuangjiaju** [comment]
已经用了idea 里面的最新版本就可以了啊 辛苦辛苦 点赞
