### ISSUE TITLE
Map参数过滤

### ISSUE THREAD

**Issue by chenshun00** [tangcent/easy-yapi#483]
怎么通过配置过滤掉Map<String,String>这种参数呢，因为他是通过jar包的方式提供的，让对方去改已经不太实际了，有可以通过配置进行过滤的么

**Comment by tangcent** [comment]
- 这里的参数是指方法入参还是字段?
对应的是两个规则:
http://easyyapi.com/setting/rules/param_ignore.html
http://easyyapi.com/setting/rules/json_rule_field_ignore.html
- 你需要的是不是这样的?
`param.ignore=groovy:it.type().name()=="java.util.Map<java.lang.String,java.lang.String>"`
或者
`json.rule.field.ignore=groovy:it.type().name()=="java.util.Map<java.lang.String,java.lang.String>"`

**Comment by chenshun00** [comment]
是的

`param.ignore=groovy:it.type().name()=="java.util.Map<java.lang.String,java.lang.String>"`  我去试试这个

**Comment by chenshun00** [comment]
emmm, 请问这个是需要手动打包到插件里边去么

**Comment by chenshun00** [comment]
我应该是要用 
`field.ignore=param.ignore=groovy:it.type().name()=="java.util.Map<java.lang.String,java.lang.String>"`

**Comment by tangcent** [comment]
http://easyyapi.com/setting/local-file-config.html

**Comment by chenshun00** [comment]
好的，感谢，我测试了一下，可行
