### ISSUE TITLE
更新后，无法使用项目文件配置

### ISSUE THREAD

**Issue by HuangChao5** [tangcent/easy-yapi#484]
![image](https://user-images.githubusercontent.com/38639556/120265392-8e39b780-c2d2-11eb-88fc-14d7ac9c1260.png)
更新最新版本插件后无法使用自定义配置，
idea: 2021.1.1
easy-yapi: 1.2.4-RC4

**Comment by tangcent** [comment]
- 目前最新版本是 v2.2.1, 请确认一下版本.

- 我在mac上测试正常。你可不可以clone这个插件项目，
测试一下: https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiConfigReaderTest.kt

**Comment by HuangChao5** [comment]
> * 目前最新版本是 v2.2.1, 请确认一下版本.
> * 我在mac上测试正常。你可不可以clone这个插件项目，
>   测试一下: https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/yapi/YapiConfigReaderTest.kt

抱歉，版本发错了  
easy-yapi:   2.2.1.183.0

**Comment by tangcent** [comment]
@HuangChao5 我发现idea有个api在windows上返回的文件路径用的分割符是`/`而不是`\`。
你试试: [easy-yapi-2.2.1.183.0.zip](https://github.com/tangcent/easy-yapi/releases/download/v2.2.1/easy-yapi-2.2.1.183.0.zip)

**Comment by HuangChao5** [comment]
> @HuangChao5 我发现idea有个api在windows上返回的文件路径用的分割符是`/`而不是`\`。
> 你试试: [easy-yapi-2.2.1.183.0.zip](https://github.com/tangcent/easy-yapi/releases/download/v2.2.1/easy-yapi-2.2.1.183.0.zip)

好的  我回滚成这个版本就没问题了  谢谢你
