### ISSUE TITLE
When I define an HTTP get interface, if the input parameter is a generic object, when exporting to Yapi, the corresponding generic attribute in the object is not nested

### ISSUE THREAD

**Issue by 18819808012** [tangcent/easy-yapi#485]
**Describe the bug**
When I define an HTTP get interface, if the input parameter is a generic object, when exporting to Yapi, the corresponding generic attribute in the object is not nested.

The code is as follows:
![image](https://user-images.githubusercontent.com/17026375/120292491-eedaeb80-c2f6-11eb-823d-11c442726597.png)
![image](https://user-images.githubusercontent.com/17026375/120292575-01552500-c2f7-11eb-9db5-95ddd6e2f67c.png)

The generated Yapi is as follows

![image](https://user-images.githubusercontent.com/17026375/120292640-103bd780-c2f7-11eb-8da3-298914627eb6.png)

**Comment by tangcent** [comment]
WIP :)

**Comment by tangcent** [comment]
ref: #488
