### ISSUE TITLE
> ref: #482

### ISSUE THREAD

**Issue by simonpdh** [tangcent/easy-yapi#486]
> ref: #482
> ![image](https://user-images.githubusercontent.com/17569144/120262625-9989e480-c2cc-11eb-8212-05c792ce7183.png)
> demo配置: https://github.com/tangcent/easy-yapi/blob/master/third/dubbo.config
> 具体文档还没写~ 配置也是需要根据你自己的项目来改以满足你的需求

非常感谢，刚才试了下不生成request了，而且优先级没mdoc高
当前配置如下

generic.class.has.api=groovy:it.name().endsWith("Facade")
generic.class.has.api=groovy:it.name().endsWith("Service")
generic.path=#path

generic.http.method=#method
generic.http.method[#post]=POST
generic.http.method[#POST]=POST
generic.http.method[#get]=GET
generic.http.method[#GET]=GET
#use POST by default
generic.http.method=POST
#always true
generic.method.has.api=true
generic.param.as.json.body=groovy:!it.type().isNormalType()
generic.param.as.form.body=true

dubbo接口如下
/**
     * xxxx
     *
     * @param request
     * @return
     * @path /xxx/list
     * @method GET
     */
    BaseRpcResponse<List<XxxDTO>> xxx(XxxRequest request);

生成结果
![image](https://user-images.githubusercontent.com/23329416/120319854-0a082400-c314-11eb-8216-c5e939d12d0a.png)
@tangcent

还有header该如何使用？

_Originally posted by @simonpdh in https://github.com/tangcent/easy-yapi/issues/467#issuecomment-852065036_

**Comment by tangcent** [comment]
https://github.com/tangcent/easy-yapi/blob/45d41905d7e5ed609a242585723ce83c18387f10/idea-plugin/src/test/kotlin/com/itangcent/idea/plugin/api/export/generic/GenericRequestClassExporterTest.kt#L79-L80

支持`method.additional.header`与`method.additional.param`

**Comment by simonpdh** [comment]
> param

param入参也需要这样手写吗？那多麻烦呀，不能根据request自动生成吗？

**Comment by tangcent** [comment]
> > param
> 
> param入参也需要这样手写吗？那多麻烦呀，不能根据request自动生成吗？

额外的参数可以通过`method.additional.param`配置。

---

你试试设置`generic.param.as.form.body=false`,
你这里设为true的话，相当于所有的参数都注解了spring中的`ModelAttribute`
你的method又是`GET`，这会导致参数无法解析

**Comment by simonpdh** [comment]
> > > param
> > 
> > 
> > param入参也需要这样手写吗？那多麻烦呀，不能根据request自动生成吗？
> 
> 额外的参数可以通过`method.additional.param`配置。
> 
> 你试试设置`generic.param.as.form.body=false`,
> 你这里设为true的话，相当于所有的参数都注解了spring中的`ModelAttribute`
> 你的method又是`GET`，这会导致参数无法解析

true和false都试过，都不生成request

**Comment by tangcent** [comment]
我用https://github.com/tangcent/easy-yapi/blob/master/third/dubbo.config导出
https://github.com/Earth-1610/spring-demo/blob/master/cn/dubbo-demo/dubbo-client/src/main/java/com/itangcent/dubbo/demo/client/UserClient.java
结果如下:
![image](https://user-images.githubusercontent.com/17569144/120424268-9b23dd00-c39e-11eb-9080-c1725f0b52bc.png)
![image](https://user-images.githubusercontent.com/17569144/120424267-9b23dd00-c39e-11eb-99e8-2de039166f7f.png)
![image](https://user-images.githubusercontent.com/17569144/120424283-a0812780-c39e-11eb-819f-0345d5dfa48c.png)

----

看起来没什么问题

**Comment by tangcent** [comment]
你的意思是不是: `generic.class.has.api=groovy:it.name().endsWith("Facade")||it.name().endsWith("Service")`

**Comment by tangcent** [comment]
你现在的问题是没法弹出这个页面吗?
![image](https://user-images.githubusercontent.com/17569144/120424550-32893000-c39f-11eb-8dfd-90050426a1fb.png)

**Comment by simonpdh** [comment]
> 你现在的问题是没法弹出这个页面吗?
> ![image](https://user-images.githubusercontent.com/17569144/120424550-32893000-c39f-11eb-8dfd-90050426a1fb.png)

不是

**Comment by simonpdh** [comment]
> 你现在的问题是没法弹出这个页面吗?
> ![image](https://user-images.githubusercontent.com/17569144/120424550-32893000-c39f-11eb-8dfd-90050426a1fb.png)

不是

**Comment by simonpdh** [comment]
> 我用[https://github.com/tangcent/easy-yapi/blob/master/third/dubbo.config导出](https://github.com/tangcent/easy-yapi/blob/master/third/dubbo.config%E5%AF%BC%E5%87%BA)
> https://github.com/Earth-1610/spring-demo/blob/master/cn/dubbo-demo/dubbo-client/src/main/java/com/itangcent/dubbo/demo/client/UserClient.java
> 结果如下:
> ![image](https://user-images.githubusercontent.com/17569144/120424268-9b23dd00-c39e-11eb-9080-c1725f0b52bc.png)
> ![image](https://user-images.githubusercontent.com/17569144/120424267-9b23dd00-c39e-11eb-99e8-2de039166f7f.png)
> ![image](https://user-images.githubusercontent.com/17569144/120424283-a0812780-c39e-11eb-819f-0345d5dfa48c.png)
> 
> 看起来没什么问题


使用generic.class.has.api=groovy:it.name().endsWith("Client")可以
使用generic.class.has.api=groovy:it.name().endsWith("Facade")不行

**Comment by tangcent** [comment]
`generic.class.has.api`的规则是告诉插件这个类有`api`需要导出.

---

我不大确定是不是你现在的情况没有被覆盖，抑或是原来处理的逻辑有BUG。
你试试fock这个项目https://github.com/Earth-1610/spring-demo/blob/master/cn/dubbo-demo/dubbo-client/src/main/java/com/itangcent/dubbo/demo/client/UserClient.java
在你的分支修改成你现在的情况，我试试能不能正确的导出

**Comment by simonpdh** [comment]
> `generic.class.has.api`的规则是告诉插件这个类有`api`需要导出.
> 
> 我不大确定是不是你现在的情况没有被覆盖，抑或是原来处理的逻辑有BUG。
> 你试试fock这个项目https://github.com/Earth-1610/spring-demo/blob/master/cn/dubbo-demo/dubbo-client/src/main/java/com/itangcent/dubbo/demo/client/UserClient.java
> 在你的分支修改成你现在的情况，我试试能不能正确的导出



由于我这边不能提交代码到外网，你复制下下面的代码试下


`/**
 * 用户相关Facade
 *
 * @module userFacade
 */
public interface UserFacade {
    /**
     * 新增用户
     *
     * @param userInfo
     * @return
     * @path /user/add
     * @method POST
     */
    public UserInfo add(UserInfo userInfo);

    /**
     * 更新用户
     *
     * @param userInfo
     * @return
     * @path /user/update
     * @method UPDATE
     */
    public void update(UserInfo userInfo);

    /**
     * 获取用户列表，主要是这个方法不成功
     *
     * @param userInfo
     * @return
     * @path /user/list
     * @method GET
     */
    public List<UserInfo> list(UserInfo userInfo);

    /**
     * 删除用户信息
     *
     * @param id 用户id
     */
    public UserInfo delete(Long id);`

**Comment by tangcent** [comment]
got it.

**Comment by tangcent** [comment]
这个BUG出现的原因是:
- `@method GET`指定了httpMethod为`GET`
- `generic.param.as.json.body=groovy:!it.type().isNormalType()`使得这里的`UserInfo userInfo`识别为了`request body`
- `yapi`不支持`GET`接口的`request body`


---

- 如果整个项目的`generic`接口导出都不需要`POST`,可以移除`generic.param.as.json.body=groovy:!it.type().isNormalType()`
- 否则的话需要修改`generic.param.as.json.body`:
``````
#Indicating a method parameter should be bound to the body of the web request.
generic.param.as.json.body=groovy:```
if(it.type().isNormalType()){
    return false
}
if(it.method().hasDoc("GET")||it.method().hasDoc("get")){
    return false
}
def method = it.method().doc("method")
if(method=="GET"||method=="get"){
    return false
}
return true
```
``````

---

另外我发现依旧无法处理多个POJO入参的情况: `void twoArg(UserInfo userInfo, UserDto userDto);`

**Comment by simonpdh** [comment]
> 这个BUG出现的原因是:
> 
> * `@method GET`指定了httpMethod为`GET`
> * `generic.param.as.json.body=groovy:!it.type().isNormalType()`使得这里的`UserInfo userInfo`识别为了`request body`
> * `yapi`不支持`GET`接口的`request body`
> 
> * 如果整个项目的`generic`接口导出都不需要`POST`,可以移除`generic.param.as.json.body=groovy:!it.type().isNormalType()`
> * 否则的话需要修改`generic.param.as.json.body`:
> 
> ```
> #Indicating a method parameter should be bound to the body of the web request.
> generic.param.as.json.body=groovy:```
> if(it.type().isNormalType()){
>     return false
> }
> if(it.method().hasDoc("GET")||it.method().hasDoc("get")){
>     return false
> }
> def method = it.method().doc("method")
> if(method=="GET"||method=="get"){
>     return false
> }
> return true
> ```
> ```
> 
> 另外我发现依旧无法处理多个POJO入参的情况: `void twoArg(UserInfo userInfo, UserDto userDto);`


多个POJO入参的情况: void twoArg(UserInfo userInfo, UserDto userDto);   这种情况在我们这边是不存在的，因为既然要封装成pojo对象就没要封装成2个，一个就可以了
