### ISSUE TITLE
调试功能

### ISSUE THREAD

**Issue by HuangChao5** [tangcent/easy-yapi#487]
有很多配置只通过官网介绍不是很理解，如果可以的话，可以新增一个功能能实时的调试某个配置，
例如: 
param.http.type
param.http.type[@org.springframework.web.bind.annotation.PostMapping]=body,不生效，使用grovvy中的it也不知道it的注入对象是class还是method或者param，或者写了之后也不知道能不能成功，完全是凭感觉操作，如果能一个控制台可以调试一下这种就更棒了

**Comment by tangcent** [comment]
试试: http://easyyapi.com/documents/script_executor.html

**Comment by tangcent** [comment]
如果文档有觉得写得不好的地方，可以提PR到https://github.com/easyyapi/easyyapi.github.io/tree/dev
