### ISSUE TITLE
Something Wrong When I Nest A Object.

### ISSUE THREAD

**Issue by junjie2018** [tangcent/easy-yapi#501]
**Describe the bug**

when i write code like this: 

![image](https://user-images.githubusercontent.com/20703732/121118270-23492d00-c84c-11eb-978c-4d3a11c2b361.png)

my yapi will be, it is not what i want

![image](https://user-images.githubusercontent.com/20703732/121118314-352ad000-c84c-11eb-8c56-0c896d808a55.png)

when i write code like this:

![image](https://user-images.githubusercontent.com/20703732/121118621-c1d58e00-c84c-11eb-823f-7ffd8b11a813.png)

my yapi will be like this. this is what i want, but i do not want write code like this.

![image](https://user-images.githubusercontent.com/20703732/121118538-9783d080-c84c-11eb-8d5f-e1063021c6d0.png)

my controller code like this:

![image](https://user-images.githubusercontent.com/20703732/121118673-dca80280-c84c-11eb-8eae-f27eb0a88c27.png)

**Comment by tangcent** [comment]
release https://github.com/tangcent/easy-yapi/releases/tag/v2.2.2-rc

**Comment by junjie2018** [comment]
> release https://github.com/tangcent/easy-yapi/releases/tag/v2.2.2-rc

3QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ
