### ISSUE TITLE
list枚举值导出失败

### ISSUE THREAD

**Issue by bingyiyu1** [tangcent/easy-yapi#505]
我定义了一个list字段，listitem的类型为枚举值，但是导出到yapi的时候为itemType为string
/**
     * 单位类型
     */
    @Size(min = 1,message = "请至少选择一种单位类型")
    public List<CompanyTypeEnum> companyTypes;
![image](https://user-images.githubusercontent.com/21303785/121278495-4552b600-c905-11eb-94cd-e62848dff28d.png)

**Comment by tangcent** [comment]
ref: http://easyyapi.com/setting/rules/json_rule_enum_convert.html

**Comment by bingyiyu1** [comment]
@NotNull
    @Size(min = 1,message = "请至少选择一种单位类型")
    public List<CompanyTypeEnum> companyTypes;

**Comment by tangcent** [comment]
这里类型就是枚举的话，不需要额外see，但是你需要配置来告诉插件如何处理这种情况。
因为插件默认行为和spring一样，是将枚举作为String处理的。

你这里没有给出CompanyTypeEnum的代码，亦未描述你希望的解析结果，所以我无法给你提供你需要的配置。
你可以自行参考一下: http://easyyapi.com/setting/rules/json_rule_enum_convert.html

**Comment by bingyiyu1** [comment]
CompanyTypeEnum代码![image](https://user-images.githubusercontent.com/21303785/121280794-6d441880-c909-11eb-9a48-ed707f36f5ec.png)
期望解析结果
![image](https://user-images.githubusercontent.com/21303785/121280973-bc8a4900-c909-11eb-9e96-ab36bf61e703.png)
![image](https://user-images.githubusercontent.com/21303785/121281025-d4fa6380-c909-11eb-92d7-fc36cc821679.png)

**Comment by tangcent** [comment]
got it. 按照你的需求应该是不需要额外配置，这里解析不出来可能是解析类时处理缓存的错误。

**Comment by bingyiyu1** [comment]
好的~谢谢~list的枚举用的也不多，出现问题我手动处理一下好了
