### ISSUE TITLE
在 请求对象中 像返回对象一样. 添加 默认值 和 mock 

### ISSUE THREAD

**Issue by AllenAlan** [tangcent/easy-yapi#506]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tangcent** [comment]
ref: http://easyyapi.com/setting/yapi-mock.html
![image](https://user-images.githubusercontent.com/17569144/121308104-3edb3300-c933-11eb-92b3-f6e46924b9f0.png)

**Comment by chenshun00** [comment]
奇怪，我这里好像不行

**Comment by chenshun00** [comment]
刚好我也想弄这个功能

**Comment by tangcent** [comment]
怎么配的?

**Comment by AllenAlan** [comment]
> 怎么配的?

上面这种是 application/json 这种格式可以用. 但是 简单的 Get 请求 在 Url 中参数没有配置 默认值的地方.  因为 yapi 中 这种情况没有显示参数的类型. 所以希望给一个默认值
![image](https://user-images.githubusercontent.com/18695383/122148408-0ab0c680-ce8d-11eb-892b-4c4b17a1ebbc.png)

**Comment by tangcent** [comment]
ref: https://github.com/tangcent/easy-yapi/issues/344
ref: http://easyyapi.com/setting/rules/param_doc.html
```
param.doc=groovy:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.",""))
field.doc=groovy:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.",""))
```

**Comment by AllenAlan** [comment]
> ref: #344
> ref: http://easyyapi.com/setting/rules/param_doc.html
> 
> ```
> param.doc=groovy:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.",""))
> field.doc=groovy:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.",""))
> ```

存在  java 项目的请求参数是一个对象的场景.

**Comment by tangcent** [comment]
可以按照自己的需求写，`groovy`语法兼容`java`的，不熟悉`groovy`可以直接当`java`来写

---

试试这样配:

```properties
param.doc[groovy:it.type().name().startsWith("java.lang.")]=groovy:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.",""))
param.doc[groovy:!it.type().name().contains(".")]=groovy:"类型:"+tool.uncapitalize(it.type().name())
field.doc[groovy:it.type().name().startsWith("java.lang.")]=groovy:"类型:"+tool.uncapitalize(it.type().name().replace("java.lang.",""))
field.doc[groovy:!it.type().name().contains(".")]=groovy:"类型:"+tool.uncapitalize(it.type().name())
```
