### ISSUE TITLE
@return注释未能在接口文档中显现

### ISSUE THREAD

**Issue by kaimeng110091** [tangcent/easy-yapi#507]
**Describe the bug**
使用easy-yapi插件自动生成到Yapi, `@return`标注的内容未能在文档中显现出来.

**version**
2.2.1.183.0

**expect**
希望`@return`标注的内容可以出现在接口备注中, 另起一行. 

**其它问题**
接口的备注在生成时, 前面出现了接口名称信息. 请问这是bug吗?

**Comment by tangcent** [comment]
> `@return`标注的内容未能在文档中显现出来.

你的需求是否是类似这样:
返回的是: https://github.com/Earth-1610/spring-demo/blob/master/cn/common/src/main/java/com/itangcent/common/dto/Result.java
而`@return`希望描述的是其中的`data`?
如果是这样你可以参考: http://easyyapi.com/setting/rules/method_return_main.html

---

> 接口的备注在生成时, 前面出现了接口名称信息. 请问这是bug吗?

需要提供一个demo才能确认

**Comment by kaimeng110091** [comment]
请问配置可以添加在easy-Yapi插件设置中吗? 如果可以, 请问是否是放在Built-in config中呢?

**Comment by tangcent** [comment]
> 请问配置可以添加在easy-Yapi插件设置中吗? 如果可以, 请问是否是放在Built-in config中呢?

都是可以的。

> 关于另外一个问题, 我提供个截图:

插件的实现与你想的相反，插件是先从javaDoc上读取注释，然后默认取注释的第一行作为api的名称。
1. 如何取api的名称可以通过[api.name](http://easyyapi.com/setting/rules/api_name.html)定制。
2. 当前并没有提供从注释里移除已经作为`api的名称`的字符串。
你可以暂时这样配置试试
``````
export.after=groovy:```
api.request.desc = tool.removePrefix(api.request.desc,api.request.name?.trim())
```
``````
下个版本提供一个简单的可选配置吧。

**Comment by kaimeng110091** [comment]
配置添加到Built-in config后, 未生效. 重启IDE也是如此. 可以详细说明下配置添加吗?

**Comment by tangcent** [comment]
就是这样:
![image](https://user-images.githubusercontent.com/17569144/121439867-5c52e000-c9b9-11eb-8590-ec6bcf663a9c.png)
你截个图我看看?没有把
``````
export.after=groovy:```
api.request.desc = tool.removePrefix(api.request.desc,api.request.name?.trim())
```
``````
里的```去掉吧?

**Comment by kaimeng110091** [comment]
不好意思, 我没有描述清楚. 关于: 去除注释里移除已经作为api的名称的字符串, 你所提供的脚本执行是正确的. 关于`@return`对应的脚本: method.return.main[groovy:it.returnType().isExtend("*******")]=data, 这个脚本在Built-in config中的正确写法是什么样子呢?

**Comment by tangcent** [comment]
看一下文档: http://easyyapi.com/setting/rules/method_return_main.html

method.return.main[groovy:it.returnType().isExtend("你的响应类qualifiedName")]=响应类的核心字段名

**Comment by kaimeng110091** [comment]
非常感谢, 已经解决问题.
