### ISSUE TITLE
2.2.3.183.0-rc版本不能识别枚举, 降级2.2.2.183.0-rc即可

### ISSUE THREAD

**Issue by winskin** [tangcent/easy-yapi#512]
2.2.3.183.0-rc版本不能识别枚举, 降级2.2.2.183.0-rc即可

IDEA版本2021.1.2 社区版

**Comment by tangcent** [comment]
[TestEnumCtrl](https://github.com/Earth-1610/spring-demo/blob/master/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/TestEnumCtrl.java)与[UserCtrl](https://github.com/Earth-1610/spring-demo/blob/master/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/UserCtrl.java)的测试结果是正常的。

---

请尝试提供一个demo以重现你的问题。

**Comment by sxqsfun** [comment]
遇到同样的问题, 2.2.3.183.0-rc版本不能识别枚举, 降级后能识别.<br/>
实体类
```
public class Unit extends BaseEntity<Unit> {

    public enum Type implements IEnum<Integer> {

        /**
         * 真实单位
         */
        real(0, " 真实单位"),
        /**
         * 虚拟单位
         */
        virtual(1, "虚拟单位");

        private int code;
        private String desc;

        Type(int code, String desc) {
            this.code = code;
            this.desc = desc;
        }

        @Override
        public Integer getValue() {
            return this.code;
        }

        public String getDesc() {
            return this.desc;
        }
    }

    /**
     * 类型
     */
    @NotNull
    private Type type;

}
```

Controller 

```
@Api(value = "Admin-公司单位管理", tags = "公司单位管理")
@RestController("unitController")
@RequestMapping("admin/unit")
public class UnitController {

    @ApiOperation(value = "修改公司单位")
    @PutMapping()
    public JsonResult update(Unit unit) {
        if (unitService.updateById(unit)) {
            return JsonResult.success("修改成功！");
        }
        return JsonResult.fail("修改失败！");
    }

}
```

**Comment by tangcent** [comment]
I got it.

**Comment by tangcent** [comment]
[easy-yapi-2.2.3.183.0.zip](https://github.com/tangcent/easy-yapi/files/6705313/easy-yapi-2.2.3.183.0.zip)

**Comment by sxqsfun** [comment]
> [easy-yapi-2.2.3.183.0.zip](https://github.com/tangcent/easy-yapi/files/6705313/easy-yapi-2.2.3.183.0.zip)

测试了一下, 这个版本也没识别枚举

**Comment by winskin** [comment]
> [easy-yapi-2.2.3.183.0.zip](https://github.com/tangcent/easy-yapi/files/6705313/easy-yapi-2.2.3.183.0.zip)


测试了该版本枚举实现接口, 也不能识别
```java
public enum BooleanEnum implements IEnum {
    YES(1, "是", "YES"),
    NO(0, "否", "NO");

    private int code;
    private String name;
    private String englishCode;

......

}
```

**Comment by tangcent** [comment]
![image](https://user-images.githubusercontent.com/17569144/123191380-c26c5680-d4d3-11eb-84cc-98b63d836323.png)
![image](https://user-images.githubusercontent.com/17569144/123191477-e29c1580-d4d3-11eb-83ac-9d236eac23fe.png)

---

试试fork [spring-demo](https://github.com/Earth-1610/spring-demo)提供一个demo?

**Comment by sxqsfun** [comment]
[这是我fork后添加的测试枚举demo](https://github.com/sxqsfun/spring-demo/tree/master/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/testenum)

**Comment by tangcent** [comment]
[easy-yapi-2.2.3.183.0.zip](https://github.com/tangcent/easy-yapi/files/6710275/easy-yapi-2.2.3.183.0.zip)

---

需要针对枚举再增加一些测试用例 :)
