### ISSUE TITLE
shift+alt+e 导出接口导致内存占满idea卡死

### ISSUE THREAD

**Issue by h496336011** [tangcent/easy-yapi#513]
**Describe the bug**
shift+alt+e 导出接口导致内存占满idea卡死
**To Reproduce**
1. shift+alt+e 导出接口
2. idea内存占满,查看cpu使用情况占用很高
3. idea卡死不动

**Expected behavior**
希望可以修复

**Screenshots**
![image](https://user-images.githubusercontent.com/29691396/122525517-e3ecbe80-d04b-11eb-90a3-04d1b7fce267.png)
![image](https://user-images.githubusercontent.com/29691396/122525560-eea75380-d04b-11eb-807b-117b22bc7229.png)

 - OS: WIN10
 - idea:2021.1.2
 - plugin Version: 2.2.3.183.0-rc

**Additional context**
只有这个接口导出时会产生问题,其他接口正常

**Comment by h496336011** [comment]
返回值改成null就可以正常上传接口了,可能是这句代码的问题
Db.use(hikariDataSource).query(columnSql, ColumnInfoVO.class, dataSource.getDbSchema(), metadata.getCode());

**Comment by tangcent** [comment]
看看idea的日志

**Comment by micuncang** [comment]
IDEA->perferences->other settings->EasyApi->关闭enable infer 看看是否可以规避这个问题

**Comment by h496336011** [comment]
@tangcent idea日志到这就卡死了
![image](https://user-images.githubusercontent.com/29691396/122697073-20503280-d277-11eb-970b-2a47b36946b5.png)

**Comment by h496336011** [comment]
@micuncang 关闭后可以了,谢谢!但是请问这个infer是做什么用途的呢?

**Comment by tangcent** [comment]
用来推断api的返回。比如:
https://github.com/Earth-1610/spring-demo/blob/cce465d2299a4dbab3e77775205a4a7934f97249/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/UserCtrl.java#L171-L193
推断出返回的是`Result<UserInfo>`

---

你这里返回的`List<ColumnInfoVO>`似乎不应该触发推断,我按照你提供的截图无法重现此问题。

**Comment by h496336011** [comment]
@tangcent 这个推断是否有可能是因为这个方法的返回值是泛型导致的,这个方法用的是hutool的DbUtil.
![image](https://user-images.githubusercontent.com/29691396/122712992-8cdb2980-d297-11eb-8dc1-e067bb4ad547.png)

**Comment by tangcent** [comment]
I got it.
https://github.com/tangcent/easy-yapi/blob/13e9973f6becf26e55d24cee29d28a0609f008f0/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/RequestClassExporter.kt#L742-L743
这里`jvmClassHelper!!.isInterface(duckType)`判断`List`需要推断。
这里判断接口需要推断的原本目的是处理这种情况:
https://github.com/Earth-1610/spring-demo/blob/cce465d2299a4dbab3e77775205a4a7934f97249/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/UserCtrl.java#L125
可以考虑移除。
