### ISSUE TITLE
YapiDashboard内存溢出卡死

### ISSUE THREAD

**Issue by micuncang** [tangcent/easy-yapi#514]
**Describe the bug**
YapiDashboard内存溢出卡死

**To Reproduce**
1. Go to 'IDEA->code'
2. Click on 'YapiDashboard'
3. See error：java.lang.OutOfMemoryError: Java heap space

**Expected behavior**
正常同步接口

**Screenshots**
![1](https://user-images.githubusercontent.com/3069117/122629688-74310f00-d0f1-11eb-9e51-e094a46acae3.jpg)
![2](https://user-images.githubusercontent.com/3069117/122629690-75fad280-d0f1-11eb-9b3e-2bd294714007.jpg)

**Desktop (please complete the following information):**
 - OS: [macOS Big Sur 11.3.1]

**Comment by micuncang** [comment]
初步判断内存溢出是由Controller中包含返回的对象为树结构的方法引起，需要确认下这种场景是否存在内存泄露。

public List<TreeNode> XXX() ....

**Comment by micuncang** [comment]
[idea.log](https://github.com/tangcent/easy-yapi/files/6680014/idea.log)
内存溢出卡死时IDEA日志

**Comment by micuncang** [comment]
> 初步判断内存溢出是由Controller中包含返回的对象为树结构的方法引起，需要确认下这种场景是否存在内存泄露。
> 
> public List XXX() ....

try infer return type of meth...时内存溢出，IDEA->perferences->other settings->EasyApi->关闭enable infer 可以暂时跳过这个问题

**Comment by tangcent** [comment]
> > 初步判断内存溢出是由Controller中包含返回的对象为树结构的方法引起，需要确认下这种场景是否存在内存泄露。
> > public List<TreeNode> XXX() ....
> 
> try infer return type of meth...时内存溢出，IDEA->perferences->other settings->EasyApi->关闭enable infer 可以暂时规避这个问题

还没有找到可用的推导方案

---

> **Screenshots**
> ![1](https://user-images.githubusercontent.com/3069117/122629688-74310f00-d0f1-11eb-9e51-e094a46acae3.jpg)
> ![2](https://user-images.githubusercontent.com/3069117/122629690-75fad280-d0f1-11eb-9b3e-2bd294714007.jpg)

这个看起来是jackson的问题，考虑在https://github.com/tangcent/easy-yapi/blob/13e9973f6becf26e55d24cee29d28a0609f008f0/idea-plugin/src/main/kotlin/com/itangcent/idea/utils/JacksonUtils.kt#L13-L16
中配置`objectMapper.configure(SerializationFeature.FAIL_ON_EMPTY_BEANS, false)`
