### ISSUE TITLE
有没有提供自动同步到yapi上的机制？或者是提供maven插件可以控制在打包时就同步到yapi上

### ISSUE THREAD

**Issue by 18819808012** [tangcent/easy-yapi#515]
有没有提供自动同步到yapi上的机制？或者是提供maven插件可以控制在打包时就同步到yapi上？或者像swagger一样提供一个对外访问的接口，可以返回接口定义的yaml文件?

**Comment by tangcent** [comment]
没有。
自动同步的话，多个需求同时开发的时候，同一个接口在不同的分支上不一致该如何处理呢?

**Comment by 18819808012** [comment]
> 没有。
> 自动同步的话，多个需求同时开发的时候，同一个接口在不同的分支上不一致该如何处理呢?

自动同步确实会有不一致的问题，可能导致交叉覆盖，比较难处理，是不是能够提供一个类似swagger的功能，只要服务启动，通过一个固定的api就能返回该项目所有接口生成的yaml文档，这样就能很快的接入yapi。

**Comment by tangcent** [comment]
是不是可以考虑直接用swagger呢?

**Comment by 18819808012** [comment]
> 是不是可以考虑直接用swagger呢?

就是想摆脱swagger的代码侵入性，才使用easyyapi的 。

**Comment by tangcent** [comment]
:) 目前没有合适的方案, 试试找其他方案吧

---

我以前尝试过几种方案。
1. 使用[javaparser](https://github.com/javaparser/javaparser)来做源码级api解析
处理maven/gradle太麻烦了，也可能是我没用对。
2. 也尝试过类`swagger`的模式，运行时解析
很难处理注释，尤其是引用的二方包。最后依然没能避免需要用一些注解来补充信息。

**Comment by 18819808012** [comment]
> :) 目前没有合适的方案, 试试找其他方案吧
> 
> 我以前尝试过几种方案。
> 
> 1. 使用[javaparser](https://github.com/javaparser/javaparser)来做源码级api解析
>    处理maven/gradle太麻烦了，也可能是我没用对。
> 2. 也尝试过类`swagger`的模式，运行时解析
>    很难处理注释，尤其是引用的二方包。最后依然没能避免需要用一些注解来补充信息。

好的，谢谢作者的耐心解答，我试下这几个方案。
