### ISSUE TITLE
filed.ignore此配置不起作用

### ISSUE THREAD

**Issue by wuzyu** [tangcent/easy-yapi#516]
在项目添加自定义规则文件.easy.api.config的时候
1.忽略指定名称的字段的配置无法生效，如下配置。
\# ignore field 'log' 
field.ignore=log
如下配置就可以生效
json.rule.field.ignore=groovy:it.toString()=="包名.UserContent#password"
2.忽略指定类型的字段，不能马上生效，要上传多次接口到yapi服务器才会生效，是否有缓存？

**Comment by tangcent** [comment]
> 1. 忽略指定名称的字段的配置无法生效。

bug. 可以暂时使用`field.ignore=groovy:it.name()=="需要忽略的名称"`代替

> 2.忽略指定类型的字段，不能马上生效，要上传多次接口到yapi服务器才会生效，是否有缓存？

部分`Action`有缓存，主要DashBoard中会使用缓存来加快加载速度。
可以在<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>General</kbd> > <kbd>Cache</kbd> 点击clear清除

**Comment by wuzyu** [comment]
好的，万分感谢。
