### ISSUE TITLE
当接口返回值为接口类型时无法正确生产文档

### ISSUE THREAD

**Issue by Songzhizong** [tangcent/easy-yapi#523]
**Describe the bug**
我的接口返回值类型为interface，导出文档后在yapi中返回数据描述为空，在旧的版本中是可以生效的。

**To Reproduce**
1. 接口返回interface而非class
2. 导出文档
3. yapi中返回数据描述为空

**Expected behavior**
生成接口文档中能够正确展示返回数据

**Screenshots**
![image](https://user-images.githubusercontent.com/22743270/123573188-12af2580-d800-11eb-8384-6d567d59fdba.png)
![image](https://user-images.githubusercontent.com/22743270/123573240-265a8c00-d800-11eb-8734-c871706228e7.png)
![image](https://user-images.githubusercontent.com/22743270/123573247-2b1f4000-d800-11eb-987e-26cedc4888bc.png)

**Comment by tangcent** [comment]
是否有在[设置](http://easyyapi.com/setting/ide-setting.html)勾选`getter as field`?

**Comment by Songzhizong** [comment]
勾选`getter as field`设置后生效
