### ISSUE TITLE
RequestMapping 多路由支持

### ISSUE THREAD

**Issue by kywvane** [tangcent/easy-yapi#527]
RequestMapping 的value实质是个数组，但是我发现解析的时候只能解析出第一路由，其他好几个相关特性都是这样的，这个影响最大。是不是可以通过配置解决这个问题？
另发现返回值为map的情况下，解析值会有个key，当然已通过不再返回map处理，本身返回map也的确不太合适

**Comment by tangcent** [comment]
[配置](http://easyyapi.com/setting/local-file-config.html)`path.multi=all`

---

https://github.com/tangcent/easy-yapi/blob/10cbc70d770f2468906e900d673541551ffed884/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/ClassExportRuleKeys.kt#L192-L195

https://github.com/tangcent/easy-yapi/blob/10cbc70d770f2468906e900d673541551ffed884/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/ResolveMultiPath.kt#L3-L9

**Comment by kywvane** [comment]
谢谢大佬，我用这个插件的预期，是将代码转换为yapi文档，为前端同事提供mock数据，并且变更代码后无需直接修改文档。有问题，再来请教，谢谢
