### ISSUE TITLE
好像碰到了证书的问题

### ISSUE THREAD

**Issue by SemFreud** [tangcent/easy-yapi#531]
[ERROR]	request https://domain/api/project/get?token=f2b1b72b34043xxx9ac58ccf870b9786917d537ecxxxcff failed
[TRACE]	javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

目前的使用设备是 m1 mac , idea是社区版2021.1   jdk 1.8.0_281

同事intel芯片+旗舰版IDEA都可以正常使用。

![c91a0e1473c528661c623c96468dda11](https://user-images.githubusercontent.com/49296527/125158953-d63bdc00-e1a6-11eb-859b-5f02693929c7.png)

[ERROR]	failed getProjectIdByToken by cache
也看到了这个错误， 点击第一张截图里的 get?token= 链接 并没有看到   projectId的数据 

![getToken截图](https://user-images.githubusercontent.com/49296527/125158992-25820c80-e1a7-11eb-8138-6ec6d2fff57c.png)

**Comment by tangcent** [comment]
ref: #532

---

[easy-yapi-2.2.4.183.0-rc.zip](https://github.com/tangcent/easy-yapi/files/6796286/easy-yapi-2.2.4.183.0-rc.zip)

**Comment by SemFreud** [comment]
> ref: #532
> 
> [easy-yapi-2.2.4.183.0-rc.zip](https://github.com/tangcent/easy-yapi/files/6796286/easy-yapi-2.2.4.183.0-rc.zip)

可以使用新的 plugin_version 么 ？不知道是不是插件缓存的问题   ，   我使用了这个版本的插件   还是有证书的问题。

**Comment by SemFreud** [comment]
目前我升级了版本号 ， 使用gradle进行编译打包， 但是网络环境的问题  下载 ideaIC.zip包很慢。
我自己进行尝试一下吧

**Comment by tangcent** [comment]
那可能是其他问题。如果你解决了的话，可以考虑提个PR。

---

开发和调试: https://github.com/tangcent/easy-yapi/issues/35#issuecomment-519738999

**Comment by SemFreud** [comment]
> 那可能是其他问题。如果你解决了的话，可以考虑提个PR。
> 
> 开发和调试: [#35 (comment)](https://github.com/tangcent/easy-yapi/issues/35#issuecomment-519738999)


调试了，调试过程中发布api没有问题 ， 打包之后  发布还是有问题。 
晚会我试一下旗舰版。
