### ISSUE TITLE
导出rpc文档为markdown响应数据表格缺失

### ISSUE THREAD

**Issue by liuqidong** [tangcent/easy-yapi#535]
![image](https://user-images.githubusercontent.com/16371127/125740312-f2a9b8af-b10c-403a-9b56-4b479e6da305.png)
![image](https://user-images.githubusercontent.com/16371127/125740368-e21d40bb-a243-4a74-81bc-ff07e604ce85.png)

**Comment by liuqidong** [comment]
请问下，您这边修复好问题之后是不是需要重新发布新的插件包啊，不然我这边导出markdown还是有问题。或者您这边提供一个打包插件的教程，我自己操作也可以。

**Comment by tangcent** [comment]
clone项目后，执行` ./plugin-script/package_plugin.sh`就可以了。

---

[easy-yapi-2.2.4.183.0-rc.zip](https://github.com/tangcent/easy-yapi/files/6838826/easy-yapi-2.2.4.183.0-rc.zip)

**Comment by tangcent** [comment]
clone项目后，执行` ./plugin-script/package_plugin.sh`就可以了。

---

[easy-yapi-2.2.4.183.0-rc.zip](https://github.com/tangcent/easy-yapi/files/6838826/easy-yapi-2.2.4.183.0-rc.zip)

**Comment by liuqidong** [comment]
好的，谢谢

**Comment by liuqidong** [comment]
> clone项目后，执行` ./plugin-script/package_plugin.sh`就可以了。
> 
> [easy-yapi-2.2.4.183.0-rc.zip](https://github.com/tangcent/easy-yapi/files/6838826/easy-yapi-2.2.4.183.0-rc.zip)

请问下什么时候会发布新的插件

**Comment by tangcent** [comment]
月底，这周末或者下周末
