### ISSUE TITLE
当返回值被封装为一个通用Json对象返回时，"是否必须"栏中，必须要使用javax.validation的注解才可以么

### ISSUE THREAD

**Issue by akaivn** [tangcent/easy-yapi#537]
![image](https://user-images.githubusercontent.com/76635823/126054145-6e611739-9503-49d4-8063-db0e104a9e04.png)
![image](https://user-images.githubusercontent.com/76635823/126054150-04234391-85c6-42fc-867e-b10a740b32b6.png)

**Comment by tangcent** [comment]
插件只是提供了一个规则[field.required](http://easyyapi.com/setting/rules/field_required.html)
然后通过推荐配置提供了对一些常用的三方库的支持:
https://github.com/tangcent/easy-yapi/blob/9890a4f3ea1d4506fe700414f08576c594c5ba30/idea-plugin/src/main/resources/.recommend.easy.api.config#L96-L114

---

如果你有特殊的需求，可以自行按需配置。
比如你可以配置`field.required=#required`,这样你可以通过注释`@required`来标记字段为`必须`:
```java
    /**
     * 用户类型
     *
     * @required
     * @see com.itangcent.common.constant.UserType
     */
    private int type;
```
