### ISSUE TITLE
在导出postman文档时，参数类型为int的时候能不能指定默认值

### ISSUE THREAD

**Issue by amrjlg** [tangcent/easy-yapi#538]
我这儿又不少分页的接口，导出的时候 页码、每页数量的参数默认值都变成了0。
这时候如果能指定默认值就比较好了，不然在postman执行测试的时候每一个接口都需要去改一下这两个参数的值
不知道有没有其他好的处理方式
我这里没有使用swagger，纯javadoc的方式

**Comment by tangcent** [comment]
有指定默认值的规则: [field.default.value](http://easyyapi.com/setting/rules/field_default_value.html)，但是目前只用在了`yapi`和`markdown`上，没渲染到`postman`。下个版本可以提供此支持。

---

在提供此支持前(1-2周)，你可以通过`export.after`强行修改,类似这样:
``````groovy
export.after=groovy:```
try {
    for (param in api.request.querys) {
        if (param.name == "page") {
            param.value = "10"
        }
    }
} catch (ignore) {
}
try {
    for (param in api.request.requestformParams) {
        if (param.name == "page") {
            param.value = "10"
        }
    }
} catch (ignore) {
}
try {
    if (api.request.body.page == 0) {
        api.request.body.page = 10
    }
} catch (ignore) {
}
```
``````

**Comment by tangcent** [comment]
may be fixed by #541

**Comment by amrjlg** [comment]
刚刚我下载了最新的release进行了一下测试
参考了这个配置[field.default.value](http://easyyapi.com/setting/rules/field_default_value.html)
在`.easy.api.config`配置文件中，添加了如下的配置
`field.default.value=#default`
然后在Javadoc中书写的文档如下
```java
    /**
     * 已评价列表
     *
     * @param pageNumber @default 1
     * @param pageSize   @default 20
     * @param dto        条件参数
     * @return 列表
     */
public Page<CommentedVo> commented(@RequestBody CommentedDto dto, @RequestParam("pageNumber") int pageNumber, @RequestParam("pageSize") int pageSize) {
}
```
然后进行导出文档，发现postman/markdown参数的默认值仍然是0。
如下图
![markdown](https://user-images.githubusercontent.com/31244260/127796711-71cbd216-b5bb-4f62-849c-9bb24a89ddd2.png)

![postman](https://user-images.githubusercontent.com/31244260/127796731-83eb0b17-43a0-4bc7-a0ab-65b8e51455ea.png)

是否是我哪儿使用错误。
不过我发现使用`@RequestParam`的`defaultValue`进行修饰后默认值会进行相应的变更

**Comment by tangcent** [comment]
`field.default.value=#default`对应的取的是
```java
    /**
     * @default xxx
     */
```

---

你这里似乎需要的是: [param.default.value](http://easyyapi.com/setting/rules/param_default_value.html)
可以考虑配:
```
param.default.value=groovy:it.method().doc("default",it.name)
```
对应读取的是
```java
    /**
     * @default pageNumber 1
     * @default pageSize 20
     */
```
