### ISSUE TITLE
在导出的过程中，发现IDEA有假死的情况，像这种情况有发生过么。

### ISSUE THREAD

**Issue by chenshun00** [tangcent/easy-yapi#539]
RT

**Comment by tangcent** [comment]
可能是:
1. 推断方法返回值假死。
可以在 IDEA->perferences->other settings->EasyApi->关闭enable infer
2. http请求一直未响应造成
试着在IDEA->perferences->other settings->EasyApi-> 调小http的timeout
3. 亦有可能是某些地方错误的在ui线程处理了太多与ui无关的逻辑

**Comment by chenshun00** [comment]
还有一个现象，就是我源代码在飘红。不确定这个有没有影响
