### ISSUE TITLE
上传到YAPI时 int[]类型的参数 会加上[0]

### ISSUE THREAD

**Issue by xyw1042971947** [tangcent/easy-yapi#540]
**Describe the bug**
上传到YAPI时 int[]类型的参数 会加上[0]

public class QueryEntListDto {
    private String entName;

    private int[] entMarks;
}

上传到YAPI后：
![image](https://user-images.githubusercontent.com/33142631/127301964-da96d3ef-2199-455b-b0a0-d15e3debe317.png)

**Comment by tangcent** [comment]
如果不需要展开的话，把<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Intelligent</kbd> >  <kbd>expended query</kbd>去掉就可以。
