### ISSUE TITLE
idea2021.1安装插件报错

### ISSUE THREAD

**Issue by huyounia** [tangcent/easy-yapi#544]
<img width="1098" alt="QQ20210802-234319@2x" src="https://user-images.githubusercontent.com/41253364/127888314-541f63d9-2f8f-417c-920a-0fe6fcdb08b9.png">

**Comment by tangcent** [comment]
是不是同时安装了[easy-api](https://github.com/tangcent/easy-api), 先卸载掉试试

**Comment by huyounia** [comment]
是安装了easy-api这个插件

**Comment by tangcent** [comment]
把easy-api卸载掉就可以了
