### ISSUE TITLE
当参数为map时，api展示的问题

### ISSUE THREAD

**Issue by chenguangcui** [tangcent/easy-yapi#545]
**我的参数实体对象如下：**
@ApiModel(value = "结果实体")
public class Result {
    @ApiModelProperty(value = "id", required = true)
    private Integer id;
    @ApiModelProperty(value = "结果", required = true, example = "{\"325\":100,\"326\":200}")
    private Map<String, Long> amount;
}
**我生成的api结果如下：**
![image](https://user-images.githubusercontent.com/18319435/127954827-8425076b-2ea2-47df-8086-92a618ecebc3.png)
**我在配置文件中添加了如下跟字段相关的配置：**
field.doc=@io.swagger.annotations.ApiModelProperty#value
field.doc=@io.swagger.annotations.ApiModelProperty#example
**我有两个问题：**
1、因为我的参数是map，但是map的key是不确定的，生成的文档里红框部分可以去掉吗
2、其他信息那一列看起来跟备注是重复的，有办法隐藏，或者针对某个字段隐藏，或者跟备注这一列区分开来吗

**Comment by tangcent** [comment]
> 1、因为我的参数是map，但是map的key是不确定的，生成的文档里红框部分可以去掉吗

目前没有提供对应的配置。
这里直接去掉似乎不大妥当，例如对于`private Map<String, User> userMap;`，进一步渲染`User`应该是有必要的。
- 考虑增加一条配置规则, 允许开发者配置不渲染指定条件的`map`

- 我对`example = "{"325":100,"326":200}"`很感兴趣，
如果配置为`field.default.value=@io.swagger.annotations.ApiModelProperty#example`, 让插件拿到`{"325":100,"326":200}`, 再尝试填充到`map`中，最终渲染为:
![image](https://user-images.githubusercontent.com/17569144/127983106-34b45575-07a2-42c0-b316-47b75ec7751e.png)
是否更合适?

> 2、其他信息那一列看起来跟备注是重复的，有办法隐藏，或者针对某个字段隐藏，或者跟备注这一列区分开来吗

这个其他信息似乎是`yapi`处理的逻辑，插件无法改变。需要修改`yapi`

**Comment by chenguangcui** [comment]
> * field.default.value=@io.swagger.annotations.ApiModelProperty#example

这是个好办法，但是配置之后对其他字段也会生效，我看到[框架支持](http://easyyapi.com/framwork/swagger.html)中可以在导出的时候自己写逻辑去做一些处理，有办法只针对map类型的参数生效该配置吗

**Comment by tangcent** [comment]
> > * field.default.value=@io.swagger.annotations.ApiModelProperty#example
> 
> 这是个好办法，但是配置之后对其他字段也会生效，我看到[框架支持](http://easyyapi.com/framwork/swagger.html)中可以在导出的时候自己写逻辑去做一些处理，有办法只针对map类型的参数生效该配置吗

 这样:
`field.default.value[groovy:it.type.isMap()]=@io.swagger.annotations.ApiModelProperty#example`

---

可以试试: [easy-yapi-2.2.4.183.0.zip](https://github.com/tangcent/easy-yapi/files/6928593/easy-yapi-2.2.4.183.0.zip)

**Comment by chenguangcui** [comment]
> 可以试试: [easy-yapi-2.2.4.183.0.zip](https://github.com/tangcent/easy-yapi/files/6928593/easy-yapi-2.2.4.183.0.zip)

我卸载了原来的插件，通过本地安装的方式重装了附件，导出时报如下错误：
[ERROR]	error eval script:it.type.isMap()
[TRACE]	javax.script.ScriptException: javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: type for class: com.itangcent.idea.plugin.rule.ScriptRuleParser$ScriptExplicitFieldContext
Possible solutions: core, name
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:162)
是不是打包打错了呢

**Comment by tangcent** [comment]
> > 可以试试: [easy-yapi-2.2.4.183.0.zip](https://github.com/tangcent/easy-yapi/files/6928593/easy-yapi-2.2.4.183.0.zip)
> 
> 我卸载了原来的插件，通过本地安装的方式重装了附件，导出时报如下错误：
> [ERROR] error eval script:it.type.isMap()
> [TRACE] javax.script.ScriptException: javax.script.ScriptException: groovy.lang.MissingPropertyException: No such property: type for class: com.itangcent.idea.plugin.rule.ScriptRuleParser$ScriptExplicitFieldContext
> Possible solutions: core, name
> at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:162)
> 是不是打包打错了呢

是这样:
`field.default.value[groovy:it.type().isMap()]=@io.swagger.annotations.ApiModelProperty#example`

**Comment by chenguangcui** [comment]
> `field.default.value[groovy:it.type().isMap()]=@io.swagger.annotations.ApiModelProperty#example`

已经解决问题，非常感谢！
