### ISSUE TITLE
如何给未明确类型输出完整的接口文档描述

### ISSUE THREAD

**Issue by ditunes** [tangcent/easy-yapi#546]
**Is your feature request related to a problem? Please describe.**

我有一个接口参数 是按如下配置
/**
     * 问题详细信息
     * @maybe {@link VariableProblemDTO}
     * @maybe {@link LogicFlowProblemNodeProblemDTO}
     */
    @JSONField(name = "props")
    @JsonProperty(value = "props" )
    private Map<String,Object> problemDetailInfo = new HashMap<>();

其中problemDetailInfo 会存放VariableProblemDTO 或者LogicFlowProblemNodeProblemDTO 这两个类的属性，我也跟进qa对maybe进行了配置，但生成出来的信息只能再LogicFlowProblemNodeProblemDTO这一层，如果他内部还有依赖某个对象 则解析不出来，也就是说我们要一层层去解析要写非常复杂脚本要考虑很多因素比如有没有用jsonproperty等 ，

**Describe the solution you'd like**
我希望有一个通用接口，可以实现这个逻辑，把这种不确定信息完整输出出来 ，保证文档的实时更新能力
**Describe alternatives you've considered**
我目前基于文档中api 也不知道怎么很好实现，希望可以得到帮助，知道怎么用groovy实现
**Additional context**

**Comment by tangcent** [comment]
虽然我大致能理解你的情况，但如果能够fork [spring-demo](https://github.com/Earth-1610/spring-demo)提供一份小demo，我们可以更准确的解决问题。
