### ISSUE TITLE
不能设置对应的setting配置文件

### ISSUE THREAD

**Issue by xwjstudyjava** [tangcent/easy-yapi#555]
不能打开对应的配置文件页，是插件和IDEA版本有冲突或者社区版不能使用吗？ IDEA是18年3月的社区版
![image](https://user-images.githubusercontent.com/46883941/128656135-7cea0212-1f20-444c-9bba-a5fa06e529b6.png)

**Comment by tangcent** [comment]
我可以重现此BUG，但是在2017.*与2020.*均正常。
推测是2018.3的插件类加载器有问题，但目前无法解决。
如果可能的话，使用更高版本的idea。

**Comment by tangcent** [comment]
see #556
thx.
