### ISSUE TITLE
有个项目一导出就死机。会把IDEA弄成死机，CPU100%

### ISSUE THREAD

**Issue by hiarno** [tangcent/easy-yapi#559]
请求解决，目前看来有点 json 死循环。

**Comment by tangcent** [comment]
可以尝试clone [spring-demo](https://github.com/Earth-1610/spring-demo) 以重现你的问题吗?
插件目前已经对潜在的循环解析做了很多处理，亦有对应的测试用例，所以现在很难简单的通过代码审查来定位解析错误的原因。

**Comment by hiarno** [comment]
![image](https://user-images.githubusercontent.com/18111070/128965279-e1ff968c-dde1-4139-82ab-c78ef0385a31.png)

**Comment by hiarno** [comment]
![image](https://user-images.githubusercontent.com/18111070/128965379-21ece4c8-dcfe-4659-810b-56705082feeb.png)

**Comment by hiarno** [comment]
![image](https://user-images.githubusercontent.com/18111070/128980049-ad17daab-8ee3-41aa-97a4-b422b54ab931.png)

**Comment by tangcent** [comment]
未能重现
https://github.com/tangcent/spring-demo/blob/aff5d19012e287661f0c6c7e30f550db148ada74/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/TestCtrl.java#L112-L115
