### ISSUE TITLE
field.parse.after与field.parse.before通过打印logger,发现并未触发方法

### ISSUE THREAD

**Issue by shiwanjiji** [tangcent/easy-yapi#574]
#[Jackson_JsonIgnoreProperties]
#支持 Jackson 注释 JsonIgnoreProperties

json.cache.disable=true
field.ignore=groovy:it.containingClass().annValue("com.fasterxml.jackson.annotation.JsonIgnoreProperties")?.contains(it.name())
json.group=@com.fasterxml.jackson.annotation.JsonIgnoreProperties
field.parse.before[@com.fasterxml.jackson.annotation.JsonIgnoreProperties]=groovy:```
    def properties = it.annValue("com.fasterxml.jackson.annotation.JsonIgnoreProperties")
    for(property in properties){
        def path = fieldContext.property(property)
        session.set("json-ignore", path, true)
    }
```
field.parse.after[@com.fasterxml.jackson.annotation.JsonIgnoreProperties]=groovy:```
    def properties = it.annValue("com.fasterxml.jackson.annotation.JsonIgnoreProperties")
    for(property in properties){
        def path = fieldContext.property(property)
        session.remove("json-ignore", path)
    }
```
field.ignore=groovy:```
    return session.get("json-ignore", fieldContext.path())
```

**Comment by tangcent** [comment]
未能重现

**Comment by shiwanjiji** [comment]
你用的是什么版本我用的是2021.1.3，如果你的版本和我的不同我可以装一下试试

**Comment by tangcent** [comment]
我在2021.1.3上测试亦可。
config:
```
field.parse.before=groovy:logger.info("before")
```

---

试试提供一个demo? https://github.com/Earth-1610/spring-demo
