### ISSUE TITLE
final 属性没办法导出？

### ISSUE THREAD

**Issue by zkpgds** [tangcent/easy-yapi#581]

**Comment by tangcent** [comment]
会忽略`static final` https://github.com/Earth-1610/intellij-kotlin/blob/8d03d1ae0f3e159b3d5004012bf02eef0cd83681/intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/AbstractPsiClassHelper.kt#L519-L520

**Comment by zkpgds** [comment]
为什么会忽略static 跟final？

**Comment by tangcent** [comment]
Ah! 这是个bug, 本意是只忽略`static final xxx`, 而不是忽略`static xxx` or `final xxx`

---

你这里的属性有没有对应的`getter`, 如果有话可以试试在[设置](http://easyyapi.com/setting/ide-setting.html)勾选`getter as field`能不能通过`getter`生成。
