### ISSUE TITLE
上传接口后，无法显示泛型内参数

### ISSUE THREAD

**Issue by naah69** [tangcent/easy-yapi#590]
**Describe the bug**
上传接口后，发现yapi无法显示泛型内参数名

![image](https://user-images.githubusercontent.com/25682169/133208269-38b080cf-c343-48d0-853c-4de3e2cb4575.png)
![image](https://user-images.githubusercontent.com/25682169/133208300-866246e4-c9b5-4ac1-8ada-fa7bac2d4bc4.png)

**Comment by tangcent** [comment]
可以提供Response的详细字段结构吗?

**Comment by naah69** [comment]
> 可以提供Response的详细字段结构吗?

response的字段，yapi是可以显示的
![image](https://user-images.githubusercontent.com/25682169/133212398-a48f9bbf-dbd6-4c1c-a242-f89e7c845273.png)

但是userdto就不行了，

![image](https://user-images.githubusercontent.com/25682169/133212462-554b71c3-2cc3-4c9f-9bbf-dafaaf4932ee.png)

yapi上虽然无法显示userDto，但是mock数据可以mock出来
![image](https://user-images.githubusercontent.com/25682169/133212560-9bb3b4ab-7c95-4873-ac7d-f2b57a05198f.png)

**Comment by tangcent** [comment]
你先尝试[忽略](http://easyyapi.com/setting/rules/field_ignore.html)`extra`看看能不能正常展示。
```
field.ignore=extra
```

---

我晚些时候来试试重现此bug。

**Comment by naah69** [comment]
> 你先尝试[忽略](http://easyyapi.com/setting/rules/field_ignore.html)`extra`看看能不能正常展示。
> 
> ```
> field.ignore=extra
> ```
> 
> 我晚些时候来试试重现此bug。

是在.`yapi.config`文件中配置么

**Comment by tangcent** [comment]
嗯，放在[项目里的配置文件里](http://easyyapi.com/setting/local-file-config.html)里，也可以直接放在 <kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>BuiltinConfig</kbd>里

**Comment by tangcent** [comment]
patch with Earth-1610/intellij-kotlin#134: [easy-yapi-2.2.7.183.0.zip](https://github.com/tangcent/easy-yapi/files/7162887/easy-yapi-2.2.7.183.0.zip)

**Comment by naah69** [comment]
![32FCD014](https://user-images.githubusercontent.com/25682169/133359919-06db5f24-c1ac-4faf-acb3-cc1d024a842a.png)
