### ISSUE TITLE
支持jackson的@JsonNaming的注解设置field的属性为驼峰转下划线的格式

### ISSUE THREAD

**Issue by MrJGuo** [tangcent/easy-yapi#592]
我需要通过jackson的@JsonNaming的注解设置field的属性为驼峰转下划线的格式，公司约定的入参出参都是下划线格式的，通常我们都是通过`@JsonNaming(value = PropertyNamingStrategy.SnakeCaseStrategy.class)`来实现这一需求。想知道如何通过本插件也支持这个需求呢?

**Comment by tangcent** [comment]
配置[field.name](http://easyyapi.com/setting/rules/field_name.html):
`field.name=groovy:tool.camel2Underline(it.name())`

**Comment by MrJGuo** [comment]
> 配置[field.name](http://easyyapi.com/setting/rules/field_name.html):
> `field.name=groovy:tool.camel2Underline(it.name())`

非常感谢，解决了我目前的问题。
但或许后续可以考虑下在Recommend加入下可选配置~
