### ISSUE TITLE
为什么YAPI没有返回值

### ISSUE THREAD

**Issue by luisxin** [tangcent/easy-yapi#593]
![image](https://user-images.githubusercontent.com/16147110/133533134-4e50b1d8-31a8-46f9-b730-8c8f3914c521.png)
代码如下
`/**
 * 查询客户券记录
 * @param customerId
 * @param type
 * @param pageIndex
 * @param pageSize
 * @return
 */
@RequestMapping(value = "/findCouponRecordById", method = RequestMethod.GET)
@ApiOperation(httpMethod = "GET", value = "查询客户券记录", response = String.class, notes = "")
public ResultVo findCouponRecordById(@ApiParam("客户编号") Long customerId,
                                     @ApiParam("可用类型") String type,
                                     @ApiParam("当前页") Integer pageIndex,
                                     @ApiParam("每页显示数量") Integer pageSize) {
    // 查找记录
    List<Map<String, Object>> couponList = smartCouponService.mallGetListByCustomerId(customerId);
//******
        // 返回数据
    return ResultVo.success(
            new Page<>(couponList, (long) (EmptyUtils.isNotEmpty(couponList.size()) ? couponList.size() : 0), pageSize, pageIndex, new Pageable(pageIndex, pageSize)));

}`

**Comment by tangcent** [comment]
是指`content`的结构？

这里的`ResultVo`未包含泛型信息，如`ResultVo<XXX>`
最好是能加上泛型信息, 否则的话只能尝试开启<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd> Intelligent</kbd> > <kbd>enable infer</kbd>来推断`api`的返回结构，不过这个功能还有缺陷，可能无法推断成功甚至导致IDEA假死。

**Comment by luisxin** [comment]
加了泛型，还是识别不到，还有可能是哪里有问题吗？
![image](https://user-images.githubusercontent.com/16147110/133562915-d32e0a87-b63a-4e56-a368-1a4ac260924b.png)



return ResBean.
                successWithObj(
                new Page<>(couponList, (long) (EmptyUtils.isNotEmpty(couponList.size()) ? couponList.size() : 0), pageSize, pageIndex, new Pageable(pageIndex, pageSize))
        );


public class ResBean<T> {

    private static final String SUCCESS_CODE = "200";

    /**
     * 返回code码，200成功，其他失败
     */
    private String code;

    /**
     * 错误信息
     */
    private String errorMsg;

    /**
     * 返回体
     */
    private T data;

    /**
     * 成功返回
     *
     * @return
     */
    public static <T> ResBean<T> success() {
        return new ResBean<>();
    }

    /**
     * 成功返回携带数据体
     *
     * @param data
     * @return
     */
    public static <T> ResBean<T> successWithObj(T data) {
        ResBean<T> resBean = new ResBean<>();
        resBean.setCode(SUCCESS_CODE);
        resBean.setData(data);
        return resBean;
    }
}

然后没开enable infer，也依然会假死

**Comment by tangcent** [comment]
有没有把
`public ResultVo findCouponRecordById`
修改成
`public ResultVo<XXX> findCouponRecordById`?

**Comment by luisxin** [comment]
我换了一个项目，也是一样的情况。这是那个项目的响应体

`
/**
 * 响应信息主体
 *
 * @param <T>
 * @author easyway
 */
@Builder
@ToString
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
@ApiModel(value = "响应信息主体")
public class R<T> implements Serializable {

	private static final long serialVersionUID = 1L;

	@Getter
	@Setter
	@ApiModelProperty(value = "返回标记：成功标记=0，失败标记=1")
	private int code;

	@Getter
	@Setter
	@ApiModelProperty(value = "返回信息")
	private String msg;

	@Getter
	@Setter
	@ApiModelProperty(value = "数据")
	private T data;

	public static <T> R<T> ok() {
		return restResult(null, CommonConstants.SUCCESS, null);
	}

	public static <T> R<T> ok(T data) {
		return restResult(data, CommonConstants.SUCCESS, null);
	}

	public static <T> R<T> ok(T data, String msg) {
		return restResult(data, CommonConstants.SUCCESS, msg);
	}

	public static <T> R<T> failed() {
		return restResult(null, CommonConstants.FAIL, null);
	}

	public static <T> R<T> failed(String msg) {
		return restResult(null, CommonConstants.FAIL, msg);
	}

	public static <T> R<T> failed(T data) {
		return restResult(data, CommonConstants.FAIL, null);
	}

	public static <T> R<T> failed(T data, String msg) {
		return restResult(data, CommonConstants.FAIL, msg);
	}

	private static <T> R<T> restResult(T data, int code, String msg) {
		R<T> apiResult = new R<>();
		apiResult.setCode(code);
		apiResult.setData(data);
		apiResult.setMsg(msg);
		return apiResult;
	}
	public R put(String key,Object value ,Object... args) {
		Map<String,Object> query = new HashMap<String, Object>();
		query.put(key, value);
		if(args!=null && args.length>0){
			if(args.length%2 != 0 ){
				throw new RuntimeException("key value要成对");
			}
			for(int i=0;i<args.length;){
				query.put((String)args[i],args[i+1]);
				i=i+2;
			}
		}
		return R.ok(query);
	}

}
`
