### ISSUE TITLE
泛型返回值还是没办法正常返回

### ISSUE THREAD

**Issue by luisxin** [tangcent/easy-yapi#602]
@GetMapping("/getPayRecordDetail")
	public R getPayRecordDetail(@RequestBody @Valid CashierVo vo){
		List<SmartAppCustomer> customerEntity = smartAppCustomerService.findCustomerMsgByCustomerName(vo.getCustomerVal());
		selectCustomerAndUser(customerEntity,vo);

		PageInfo<Map> pageInfo = smartAppOrderPayTypeService.findAll(vo);
		List<Map> list = pageInfo.getList();

		List<SmartAppOrder> orderList = smartAppOrderService.findPayOrderOfMsg(1);

		//支付记录的订单信息筛选
		list = list.stream().map(s->{
			List<SmartAppOrder> registerList = orderList.stream().filter(i -> EmptyUtils.compare(s.get("orderId"),i.getOrderId()) ).collect(Collectors.toList());
			if (EmptyUtils.isNotEmpty(registerList)){
				s.put("orderTypeInfo",registerList.get(0).getOrderTypeInfo());
				if (registerList.get(0).getOrderTypeInfo().equals(0)){
					s.put("orderTypeInfoName","项目订单");
				}else if(registerList.get(0).getOrderTypeInfo().equals(1)){
					s.put("orderTypeInfoName","处方订单");
				}else if(registerList.get(0).getOrderTypeInfo().equals(2)){
					s.put("orderTypeInfoName","产品订单");
				}else if(registerList.get(0).getOrderTypeInfo().equals(3)){
					s.put("orderTypeInfoName","储值卡订单");
				}else if(registerList.get(0).getOrderTypeInfo().equals(4)){
					s.put("orderTypeInfoName","套餐订单");
				}else if(registerList.get(0).getOrderTypeInfo().equals(7)){
					s.put("orderTypeInfoName","秒杀订单");
				}else if(registerList.get(0).getOrderTypeInfo().equals(8)){
					s.put("orderTypeInfoName","砍价订单");
				}
				s.put("customerId",registerList.get(0).getCustomerId());
				//订单总额
				s.put("orderAmount",registerList.get(0).getAmount());
				//欠款总额
				s.put("debtAmount",registerList.get(0).getDebtAmount());
				//置换项目金额
				s.put("totalReplaceAmount",registerList.get(0).getTotalReplaceAmount());
				//支付时间
				s.put("payTime",registerList.get(0).getPayTime());
				//支付人员
				s.put("payUserId",registerList.get(0).getPayUserId());
			}
			return s;
		}).collect(Collectors.toList());
		//查询客户
		List<SmartAppCustomer> customerList = smartAppCustomerService.findCustomerMsgByCustomerName(vo.getCustomerVal());
		//客户信息的过滤
		list = list.stream().map( s -> {
			List<SmartAppCustomer> registerList = customerList.stream().filter(i -> EmptyUtils.compare(s.get("customerId"),i.getCustomerId()) && i.getState().equals(1)
			).collect(Collectors.toList());
			if (EmptyUtils.isNotEmpty(registerList)){
				s.put("customerName",registerList.get(0).getCustomerName());
				s.put("customerMobile",registerList.get(0).getMobile());
			}
			return s;
		}).collect(Collectors.toList());

		List<SmartAppPayType> payTypeList = smartAppPayTypeService.findAll(SecurityUtils.getUser().getTenantId());

		list = list.stream().map( s -> {
			List<SmartAppPayType> registerList = payTypeList.stream().filter(i -> EmptyUtils.compare(s.get("payTypeId"),i.getPayTypeId())
			).collect(Collectors.toList());
			if (EmptyUtils.isNotEmpty(registerList)){
				s.put("payTypeName",registerList.get(0).getPayTypeName());
			}
			return s;
		}).collect(Collectors.toList());

		return R.ok(list).setMsg("获取成功!");
	}

响应体

public class R<T> implements Serializable {

	private static final long serialVersionUID = 1L;

	@Getter
	@Setter
	@ApiModelProperty(value = "返回标记：成功标记=0，失败标记=1")
	private int code;

	@Getter
	@Setter
	@ApiModelProperty(value = "返回信息")
	private String msg;

	@Getter
	@Setter
	@ApiModelProperty(value = "数据")
	private T data;

	public static <T> R<T> ok() {
		return restResult(null, CommonConstants.SUCCESS, null);
	}

	public static <T> R<T> ok(T data) {
		return restResult(data, CommonConstants.SUCCESS, null);
	}

	public static <T> R<T> ok(T data, String msg) {
		return restResult(data, CommonConstants.SUCCESS, msg);
	}

	public static <T> R<T> failed() {
		return restResult(null, CommonConstants.FAIL, null);
	}

	public static <T> R<T> failed(String msg) {
		return restResult(null, CommonConstants.FAIL, msg);
	}

	public static <T> R<T> failed(T data) {
		return restResult(data, CommonConstants.FAIL, null);
	}

	public static <T> R<T> failed(T data, String msg) {
		return restResult(data, CommonConstants.FAIL, msg);
	}

	private static <T> R<T> restResult(T data, int code, String msg) {
		R<T> apiResult = new R<>();
		apiResult.setCode(code);
		apiResult.setData(data);
		apiResult.setMsg(msg);
		return apiResult;
	}
	public R put(String key,Object value ,Object... args) {
		Map<String,Object> query = new HashMap<String, Object>();
		query.put(key, value);
		if(args!=null && args.length>0){
			if(args.length%2 != 0 ){
				throw new RuntimeException("key value要成对");
			}
			for(int i=0;i<args.length;){
				query.put((String)args[i],args[i+1]);
				i=i+2;
			}
		}
		return R.ok(query);
	}

}

**Comment by tangcent** [comment]
```
public class R implements Serializable {
```
这里有点奇怪，没有泛型参数的?
```
public class R<T> implements Serializable {
```

---

```
@GetMapping("/getPayRecordDetail")
public R getPayRecordDetail(@RequestBody @Valid CashierVo vo){
```
这里也给出泛型？

```
@GetMapping("/getPayRecordDetail")
public R<List<SmartAppPayType>> getPayRecordDetail(@RequestBody @Valid CashierVo vo){
```

**Comment by luisxin** [comment]
没有的原因是被github的编辑器吃掉了
public class R< T > implements Serializable {

已经OK了。
