### ISSUE TITLE
不支持@ApiModelProperty

### ISSUE THREAD

**Issue by bigbugbean** [tangcent/easy-yapi#604]
获取不到@ApiModelProperty的信息，导出到yapi备注为空
![image](https://user-images.githubusercontent.com/16144940/134861406-49fafcbd-19bb-4fbf-914f-eb7346381d23.png)
![image](https://user-images.githubusercontent.com/16144940/134861465-6aebebf5-e536-4cb7-a969-ed78e7139b52.png)

easy-api版本：2.2.7.183.0

**Comment by tangcent** [comment]
配置了吗? http://easyyapi.com/framwork/swagger.html

**Comment by bigbugbean** [comment]
![image](https://user-images.githubusercontent.com/16144940/134867296-5b435cfc-76ef-4ef8-aa33-3b8c4a8daa72.png)
是在这里配置吗

**Comment by bigbugbean** [comment]
问题解决了，建议还是默认支持swagger吧，毕竟现在大部分都是用swagger写文档的

**Comment by just-a-stone** [comment]
> ![image](https://user-images.githubusercontent.com/16144940/134867296-5b435cfc-76ef-4ef8-aa33-3b8c4a8daa72.png) 是在这里配置吗

老哥。怎么解决的

我也是操作了你图中配置。  to json5. 没注释
