### ISSUE TITLE
@RequestParam 没有生成对应字段的查询参数

### ISSUE THREAD

**Issue by x-chuiao** [tangcent/easy-yapi#607]
在springboot中我使用DTO去接受查询参数,导入postman里就只有DTO的名称而不是各个字段,请问我可以通过某些配置实现该需求么?
![image](https://user-images.githubusercontent.com/37545780/135384086-adb84cb1-9f2d-4f81-bccb-b3f15c80b3d5.png)
![image](https://user-images.githubusercontent.com/37545780/135384182-405885a4-e0c2-4730-9a6e-c35858de8a8d.png)

**Comment by tangcent** [comment]
并不需要做特殊配置。

---

我试着导出如下api:
```java
    /**
     * 更新用户信息
     */
    @PutMapping("update")
    public IResult update(@RequestParam UserInfo userInfo) {
        return Result.success(userInfo);
    }
```
导出是这样的:
![image](https://user-images.githubusercontent.com/17569144/135476595-b09ebbdf-9072-4fe4-8e41-778327a979f8.png)
这是否满足你的需求?

---

考虑fork一下https://github.com/Earth-1610/spring-demo
试着提供你当前遇到的导出有问题的case

**Comment by x-chuiao** [comment]
抱歉,是我的失误,TestDTO的属性不可访问导致的这个问题
