### ISSUE TITLE
@JsonIgnoreProperties 多层继承过滤失效

### ISSUE THREAD

**Issue by shiwanjiji** [tangcent/easy-yapi#611]
我继承了4层，头几层过滤失效
![image](https://user-images.githubusercontent.com/43093030/136703451-a4d8f2ad-252a-4592-8082-c3dc54834521.png)
![image](https://user-images.githubusercontent.com/43093030/136703457-8519bbda-8ded-49c1-ac34-660721ffa30c.png)

**Comment by tangcent** [comment]
I Got it!
