### ISSUE TITLE
导出到yapi 的格式不对了，ResponseEntity

### ISSUE THREAD

**Issue by woshiacun** [tangcent/easy-yapi#618]
org.springframework.http.ResponseEntity
 
不需要，status ，headers，body这样的数据结构。

![image](https://user-images.githubusercontent.com/90953328/137244344-d27f1929-b97d-4cab-b37d-d884d93c107e.png)

![image](https://user-images.githubusercontent.com/90953328/137244386-11ab5bed-30c1-4bcd-b914-4d15fdc7ff02.png)

**Comment by tangcent** [comment]
是规则解析逻辑里对正则处理的bug. 下周更新一个release修复.
[easy-yapi-2.2.8.183.0.zip](https://github.com/tangcent/easy-yapi/files/7343117/easy-yapi-2.2.8.183.0.zip)

**Comment by woshiacun** [comment]
这个 zip 包应该怎么使用？

**Comment by woshiacun** [comment]
![image](https://user-images.githubusercontent.com/90953328/137270387-c640954e-0c03-46cc-8d42-ba3db3b30faa.png)
 @ApiModelProperty(value = 
 这种方式也突然不会识别了。
