### ISSUE TITLE
请问有什么方式设置导出Yapi接口的请求参数类型

### ISSUE THREAD

**Issue by tothug** [tangcent/easy-yapi#619]
![2021-10-15_12-28-22](https://user-images.githubusercontent.com/3985265/137432449-99179ec6-60af-4abd-8bdc-49fa8f312853.png)

**Comment by tothug** [comment]
能否通过groovy本地扩展动态覆盖item里面的属性值？这样方便更改一些系统预置属性，也能导出一些当前版本不支持的属性
我不熟悉kotlin，不知这种方案是否可行

**Comment by tangcent** [comment]
> groovy本地扩展

这个是初期的一个探索，我自己没有地方使用到它。请慎重考虑是否使用

> 更改一些系统预置属性，也能导出一些当前版本不支持的属性

目前提供的配置项已经很多了, 大多数需求都可以通过配置来处理。
如果使用的`yapi`被定制过了的话，考虑在做二次开发吧.
`yapi`相关的代码都在https://github.com/tangcent/easy-yapi/tree/master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi
大可直接创建`java`类来继承现有的类来实现定制的功能

**Comment by tothug** [comment]
> > groovy本地扩展
> 
> 这个是初期的一个探索，我自己没有地方使用到它。请慎重考虑是否使用
> 
> > 更改一些系统预置属性，也能导出一些当前版本不支持的属性
> 
> 目前提供的配置项已经很多了, 大多数需求都可以通过配置来处理。 如果使用的`yapi`被定制过了的话，考虑在做二次开发吧. `yapi`相关的代码都在https://github.com/tangcent/easy-yapi/tree/master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/yapi 大可直接创建`java`类来继承现有的类来实现定制的功能

我在使用过程中发现groovy本地扩展这个功能很有用，比如接口的content-type需要倒出成plain/text，可以通过groovy本地扩展配合接口的Annotation来实现
我用的是原版的yapi，除了做api接口管理，还用来实现部分后台功能，需要对导出的接口做一些定制
我觉得groovy本地扩展的意义是“扩展”，原版和定制版的yapi都能支持，是一个很棒的设计
我先尝试通过Java类继承的方案，感谢你的建议和项目
