### ISSUE TITLE
支持 maven 自动上传

### ISSUE THREAD

**Issue by lifesign** [tangcent/easy-yapi#624]
希望可以加入一个机制，通过 maven 的方式来解析 easy-yapi 的规则，然后上传，这样可以将这部分放在 CICD 中，实现部署时自动上传一份最新的文档，现在 easy-yapi 更多是通过手动上传的

**Comment by tangcent** [comment]
那就是另一种解决方案了。主要的问题是: 
自动同步的话，多个需求同时开发的时候，同一个接口在不同的分支上不一致该如何处理?

see https://github.com/tangcent/easy-yapi/issues/515
