### ISSUE TITLE
配置咨询

### ISSUE THREAD

**Issue by lifesign** [tangcent/easy-yapi#626]
想实现这样一个效果，当注释中存在 `@tag {version}` 注解时，将 version 的值拼接到定义的接口后面，作为一个 param 存在，比如 /path_to_api?tag=v1.0 类似这样，同时也可以将 `@tag` 打到 yapi 的 tag 上

目的是为了让多版本对于同一个接口修改并存

**Comment by lifesign** [comment]
好的 感谢 我研究一下

**Comment by tangcent** [comment]
支持的，不过要确认配置的`url`是正确的。
错误示例: https://github.com/tangcent/easy-yapi/blob/master/third/swagger.config
正确示例: https://github.com/tangcent/easy-yapi/raw/master/third/swagger.config

**Comment by lifesign** [comment]
这个是对的，貌似是我们内网访问 gitlab 权限的问题，我开了个隐身窗口，访问对应的 raw 文件也是需要登录，那么 easy-yapi 程序中是不是也可能是程序在加载这个文件导致读取不到的问题。 所以得用公开的 github 路径，或者自己指定一个 oss 地址应该就可以了？
