### ISSUE TITLE
如何调试配置

### ISSUE THREAD

**Issue by lifesign** [tangcent/easy-yapi#629]
我看有内置一个 script executor 但是点击 execute 之后，就卡住了，也没法进行导出 api 操作，那这个 script executor 的作用是什么
如果我想调试一下自己写的配置脚本该如何操作？能否拦截掉上传，看下打印的值

**Comment by tangcent** [comment]
没做调试功能。
可以试试用[`logger`](http://easyyapi.com/setting/tools/logger.html)输出一些信息
