### ISSUE TITLE
JDK8的时间类型未解析成常规格式

### ISSUE THREAD

**Issue by qinkangdeid** [tangcent/easy-yapi#63]
**Describe the bug**

JDK8的时间类型解析出来成了下面样式
![image](https://user-images.githubusercontent.com/17582522/67260358-6b77d800-f4cd-11e9-8bec-63bc4e1d2551.png)
![image](https://user-images.githubusercontent.com/17582522/67260366-7a5e8a80-f4cd-11e9-905a-dd37f730fab5.png)

**Expected behavior**
希望可以解析成常规的时间字符串 例如：
- LocalDateTime  --->  2019-10-22 14:01:01
- LocalDate  --->  2019-10-22

**Comment by tangcent** [comment]
可以在配置里加入:
```
json.rule.convert[java.time. LocalDateTime]=java.lang.String
json.rule.convert[java.time. LocalDate]=java.lang.String
```
另外可以考虑加入配置规则(根据需求):
```
mock.[*.time|string]=@datetime
mock.[*Time|string]=@datetime
mock.[*.date|string]=@date
mock.[*Date|string]=@date
```


---

下个小版本把`java.time. LocalDateTime`和`java.time. LocalDate`写到[内置配置](https://github.com/tangcent/easy-yapi/blob/c5eaa279b0a78ca7257298d8350ee275418eb0e9/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/config/RecommendConfigReader.kt#L53-L111)中

**Comment by qinkangdeid** [comment]
好👌我试一下
