### ISSUE TITLE
不同接口，同一个类作为参数，参数不同，如何忽略字段

### ISSUE THREAD

**Issue by lovefiger** [tangcent/easy-yapi#630]
不同接口，同一个类作为参数，参数不同，如何忽略字段

**Comment by tangcent** [comment]
类似validation 分组： https://github.com/tangcent/easy-yapi/blob/7ddb7cbac3e1c5a64314008b39658a7acd3e6a0f/idea-plugin/src/main/resources/.recommend.easy.api.config#L122-L143

----

按以下思路[配置](http://easyyapi.com/setting/config-rule.html):

1. 禁用缓存:
`json.cache.disable=true`
2. `api.method.parse.before=groovy:api方法解析前，从方法上读你设置的信息到session里`
3. `api.method.parse.after=groovy:api方法解析后，从session里清除设置的信息`
4. 配置`field.required`，根据`session`里的信息来决定这个字段是否需要:
``````
field.required=groovy:```
tool.equalOrIntersect(session.get("json-group"),it.name())}
```
``````

**Comment by Pretends** [comment]
> 类似验证分组：
> 
> https://github.com/tangcent/easy-yapi/blob/7ddb7cbac3e1c5a64314008b39658a7acd3e6a0f/idea-plugin/src/main/resources/.recommend.easy.api.config#L122-L143
> 
> 按以下思路[配置](http://easyyapi.com/setting/config-rule.html)：
> 
> 1. 禁用缓存:
>    `json.cache.disable=true`
> 2. `api.method.parse.before=groovy:api方法解析前，从方法上读你设置的信息到session里`
> 3. `api.method.parse.after=groovy:api方法解析后，从session里清除设置的信息`
> 4. 配置，根据里的信息来决定这个字段是否需要:`field.required``session`
> 
> ```
> field.required=groovy:```
> tool.equalOrIntersect(session.get("json-group"),it.name())}
> ```
> ```

请教一下，这个在代码里用什么注释配合过滤呢

**Comment by AustinMing** [comment]
上面说的那个配置：

按以下思路[配置](http://easyyapi.com/setting/config-rule.html):
禁用缓存:
json.cache.disable=true
api.method.parse.before=groovy:api方法解析前，从方法上读你设置的信息到session里
api.method.parse.after=groovy:api方法解析后，从session里清除设置的信息
配置field.required，根据session里的信息来决定这个字段是否需要

是要写在哪里呀？idea -设置- 里的 -其他设置- 的 -EasyApi- 的 recommend  不让写，只能选择

是只要加了这些配置，导出的接口就会去查哪些属性是真正用到的是吗？

**Comment by tangcent** [comment]
> 是要写在哪里呀？idea -设置- 里的 -其他设置- 的 -EasyApi- 的 recommend 不让写，只能选择

<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>BuildInConfig</kbd> 或者
[配置文件](http://easyyapi.com/setting/local-file-config.html)

> 是只要加了这些配置，导出的接口就会去查哪些属性是真正用到的是吗？

插件没办法判断哪些属性是真正用到。这个配置还是由开发者告诉插件哪些属性是required的。
ref: http://easyyapi.com/setting/rules/field_required.html
