### ISSUE TITLE
希望增加Feign接口的扫描

### ISSUE THREAD

**Issue by zengcai** [tangcent/easy-yapi#635]
微服务有很多feign的接口，希望可以支持基于@FeignClient的扫描

**Comment by tangcent** [comment]
你是指从`Client`导出`API`?
类似这样?
```java
@FeignClient("stores")
public interface StoreClient {
    @RequestMapping(method = RequestMethod.GET, value = "/stores")
    List<Store> getStores();

    @RequestMapping(method = RequestMethod.POST, value = "/stores/{storeId}", consumes = "application/json")
    Store update(@PathVariable("storeId") Long storeId, Store store);
}
```

**Comment by zengcai** [comment]
> 
> 
> 你是指从`Client`导出`API`? 类似这样?
> 
> ```java
> @FeignClient("stores")
> public interface StoreClient {
>     @RequestMapping(method = RequestMethod.GET, value = "/stores")
>     List<Store> getStores();
> 
>     @RequestMapping(method = RequestMethod.POST, value = "/stores/{storeId}", consumes = "application/json")
>     Store update(@PathVariable("storeId") Long storeId, Store store);
> }
> ```

嗯 是的。有些情况下会用到，希望可以有个选择。了解了下，smart-docs也是后面才支持的
