### ISSUE TITLE
【问题咨询】请问easy-yapi与easy-api这两个项目的区别是什么呢？

### ISSUE THREAD

**Issue by wangzhen-fit2cloud** [tangcent/easy-yapi#637]

**Comment by tangcent** [comment]
`easy-api`是我以前使用`postman`时开发的。
后来开始用`yapi`就在`easy-api`的基础上增加`yapi`的支持，就成了`easy-yapi`。
本来有计划在`easy-api`再开发一个`easy-rap`, 但是有点忙，开发了也可能维护不过来, 就搁浅了。
