### ISSUE TITLE
如何重置配置

### ISSUE THREAD

**Issue by lifesign** [tangcent/easy-yapi#642]
发现卸载插件重装后之前的配置还在，但是想恢复一下出厂配置，想问下有办法么，清除 cache 没有用

**Comment by tangcent** [comment]
在idea的安装目录里搜索`EasyApiSetting.xml`和`EasyApiProjectSetting.xml`, 删掉它们就可以了

**Comment by lifesign** [comment]
Mac 下只有一个 IDEA 的安装包，没有搜索到额，右键点开 Contents 里面也没找到

**Comment by tangcent** [comment]
试试: `find ~ -iname "EasyApiSetting.xml"`
我能在这里找到: `~/Library/Application Support/JetBrains/IdeaIC2021.2/options/EasyApiSetting.xml`

**Comment by lifesign** [comment]
好的 找到了，这个是否考虑卸载的时候把这个清除掉啊

**Comment by tangcent** [comment]
没有强需求，以后有空想起来再看看。
你有兴趣可以尝试加这个功能。
