### ISSUE TITLE
请问 .yapi.config  是怎么配置的，我在easyyapi网站中没找到，我的配置如下，请帮看下是哪里不对

### ISSUE THREAD

**Issue by jialong5566** [tangcent/easy-yapi#644]
projectId=xx
projectToken=xx

**Comment by tangcent** [comment]
并不需要这样配置。直接导出即可，会弹框让你输入这些信息的。

配置文件的作用是帮助插件根据你的需求做额外的一些处理。 see: http://easyyapi.com/setting/local-file-config.html
