### ISSUE TITLE
注释和 swagger 注解共存时的逻辑

### ISSUE THREAD

**Issue by lifesign** [tangcent/easy-yapi#645]
目前注释和 swagger 注解共存时上传，发现 class.doc 和 method.doc 的处理不同
class.doc 是合并注释和 swagger 注解，method.doc 是以 swagger 注解内容为准，这块可以干预吗，比如我只想以注释优先或者 swagger 注解优先

**Comment by tangcent** [comment]
`method.doc`也是注释优先啊.

```java
    /**
     * 注释优先
     *
     * @return
     */
    @RequestMapping(value = "/index", method = RequestMethod.GET, produces = MediaType.TEXT_HTML_VALUE)
    @ApiOperation(value = "打个招呼接口")
    public String greeting() {
        return "hello world";
    }
```

**导出为:**

## 注释优先

### BASIC

**Path：** swagger/index

**Method：** GET

**Desc：**

打个招呼接口

### REQUEST


**Headers：**

| name  |  value  |  required  | desc  |
| ------------ | ------------ | ------------ | ------------ |
| token |  | YES | 认证Token |


### RESPONSE

**Header：**

| name  |  value  |  required  | desc  |
| ------------ | ------------ | ------------ | ------------ | ------------ |
| content-type | application/json;charset=UTF-8 | NO |   |

**Body：**

| name | type | desc |
| ------------ | ------------ | ------------ |
|  | string |  |

**Comment by lifesign** [comment]
但 class.doc 不是啊，所以这两块逻辑不一样了，所以想看下能否自己控制

**Comment by tangcent** [comment]
嗯，应该保持一致。不过连这个都要让开发者自己控制就过于复杂了。

**Comment by lifesign** [comment]
在没修复之前，现在有办法自己加个配置调整下吗？手动干预

**Comment by tangcent** [comment]
这个规则 [folder.name](http://easyyapi.com/setting/rules/folder_name.html)可以设置分类名
它对`class`/`method`都有效
