### ISSUE TITLE
直接使用对象接受post方法的参数时，对象属性的@default

### ISSUE THREAD

**Issue by qiuziyang1995** [tangcent/easy-yapi#646]
yapi版本：1.8.5
插件版本：2.1.5.183.0-rc

接口定义
![image](https://user-images.githubusercontent.com/82496399/141235325-09e4dde6-b92b-46e2-890f-194e78684f53.png)
can'shu

参数定义
![image](https://user-images.githubusercontent.com/82496399/141235350-e7cc84bc-2195-459e-9655-bae13c2aa7f1.png)

上传至yapi的结果
![image](https://user-images.githubusercontent.com/82496399/141235392-1fab9809-0743-4fe1-9b32-401e300cc88f.png)

希望能提供一种可以添加参数示例的方案

**Comment by tangcent** [comment]
试试 [field.default.value](http://easyyapi.com/setting/rules/field_default_value.html) 或者 [field.demo](http://easyyapi.com/setting/rules/field_demo.html)?

**Comment by qiuziyang1995** [comment]
> 试试 [field.default.value](http://easyyapi.com/setting/rules/field_default_value.html) 或者 [field.demo](http://easyyapi.com/setting/rules/field_demo.html)?

都尝试了还是不行，
参数定义
![image](https://user-images.githubusercontent.com/82496399/141245328-6ff057d9-8ac5-42bd-842e-499a2c642b30.png)

配置
![image](https://user-images.githubusercontent.com/82496399/141245351-bd230569-fb10-4dcf-a584-c07528fcfd18.png)

是否与我添加了这样的配置有关系呢？
![image](https://user-images.githubusercontent.com/82496399/141245406-cb09c28e-6b39-4dd1-a55a-1e534b23e477.png)

同时发现mock数据也不能生效

**Comment by tangcent** [comment]
并不会影响。也许你的未能正确的放置配置文件？
http://easyyapi.com/setting/local-file-config.html

**Comment by qiuziyang1995** [comment]
> 并不会影响。也许你的未能正确的放置配置文件？ http://easyyapi.com/setting/local-file-config.html
看起来是配置是生效的。
![image](https://user-images.githubusercontent.com/82496399/141713905-7bf56542-750a-4289-9728-3538770c2df3.png)

同时在给出的示例中，在UserInfo的成员变量中添加默认值的信息也是无法生成的。
https://github.com/Earth-1610/spring-demo/blob/master/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/FileCtrl.java

![image](https://user-images.githubusercontent.com/82496399/141714208-c49769b9-8ff6-4414-99e7-ca97ca706ed4.png)

**Comment by tangcent** [comment]
我测试可以:

**配置:**
```
field.default.value=#default
```

**UserInfo.java:**
```
public class UserInfo {

    private Long id;//用户id

    /**
     * @default 2
     * @see com.itangcent.common.constant.UserType
     */
    private int type;//用户类型

    /**
     * @mock tangcent
     * @default tang
     */
    @NotBlank
    private String name;//用户名

    /**
     * 年龄
     *
     * @mock 1${digit}
     */
    @NotNull
    private Integer age;

    /**
     * @deprecated It's a secret
     */
    private Integer sex;

    //生日
    private LocalDate birthDay;

    //注册时间
    private LocalDateTime regtime;
   
    ...
}
```

**导出结果:**

![image](https://user-images.githubusercontent.com/17569144/141732890-78e60ab3-7d50-4a20-97f6-9cb8b0ccc20a.png)

---

不如提供一份demo?

**Comment by qiuziyang1995** [comment]
使用的是官方给出的示例，感谢按照您的方式解决了。但还又一个问题，类型好像没有识别到，同时mock信息也没有上传。

@RestController
@RequestMapping(value = "file")
public class FileCtrl {
    /**
     * 增加新用户(上传头像)
     */
    @PostMapping("/add")
    public IResult add(@ModelAttribute UserDto userDto) {
        return Result.success("保存成功");
    }

    /**
     * 另一种增加新用户(上传头像)
     * 文件单独一个参数
     *
     * @undone
     */
    @PostMapping("/add2")
    public IResult add(UserInfo userInfo,
                       @RequestParam(name = "profileImg") MultipartFile profileImg) {
        return Result.success("保存成功");
    }

    /**
     * 试试上传多个头像
     *
     * @undone
     */
    @PostMapping("/add3")
    public IResult add(UserInfo userInfo,
                       @RequestParam(name = "profileImg") MultipartFile[] profileImgs) {
        return Result.success("保存成功");
    }
}



public class UserInfo {

    private Long id;//用户id

    /**
     * @demo 2
     * @see com.itangcent.common.constant.UserType
     */
    private int type;//用户类型

    /**
     * @demo tangcent
     * @mock tangcent
     */
    @NotBlank
    private String name;//用户名

    /**
     * 年龄
     * @mock 1${digit}
     */
    @NotNull
    private Integer age;

    /**
     * @deprecated It's a secret
     */
    private Integer sex;

    //生日
    private LocalDate birthDay;

    //注册时间
    private LocalDateTime regtime;
}

yapi结果
![image](https://user-images.githubusercontent.com/82496399/141890519-892948ea-7114-4f73-a947-10cd61e4dad0.png)

**Comment by tangcent** [comment]
> 但还又一个问题，类型好像没有识别到，同时mock信息也没有上传

`yapi` 表单不包含这些信息。只有`Body`为`json`时才有。即spring参数注解为`@RequestBody`
![image](https://user-images.githubusercontent.com/17569144/141910474-47bf9ab8-0c7b-493e-8437-b8a37350e3cd.png)

**Comment by qiuziyang1995** [comment]
> 我测试可以:
> 
> **配置:**
> 
> ```
> field.default.value=#default
> ```
> 
> **UserInfo.java:**
> 
> ```
> public class UserInfo {
> 
>     private Long id;//用户id
> 
>     /**
>      * @default 2
>      * @see com.itangcent.common.constant.UserType
>      */
>     private int type;//用户类型
> 
>     /**
>      * @mock tangcent
>      * @default tang
>      */
>     @NotBlank
>     private String name;//用户名
> 
>     /**
>      * 年龄
>      *
>      * @mock 1${digit}
>      */
>     @NotNull
>     private Integer age;
> 
>     /**
>      * @deprecated It's a secret
>      */
>     private Integer sex;
> 
>     //生日
>     private LocalDate birthDay;
> 
>     //注册时间
>     private LocalDateTime regtime;
>    
>     ...
> }
> ```
> 
> **导出结果:**
> 
> ![image](https://user-images.githubusercontent.com/17569144/141732890-78e60ab3-7d50-4a20-97f6-9cb8b0ccc20a.png)
> 
> 不如提供一份demo?

感谢，采用这样的方式已解决
