### ISSUE TITLE
[Bug] 返回结果包含字段类型是com.github.abel533.echarts.Option时 静默退出

### ISSUE THREAD

**Issue by lj7711622** [tangcent/easy-yapi#647]
**Describe the bug**

返回结果字段类型是com.github.abel533.echarts.Option时 静默退出

**To Reproduce**

1. 定义一个接口 返回结果里的包含一个字段 类型是com.github.abel533.echarts.Option （com.github.abel533.echarts.Option）
2. 使用快捷键导出markdown
3. 程序静默推出

**Expected behavior**

可以弹出选择保存文件目录的弹框

**Screenshots**

**Logs**

run easy-yapi
[INFO]	Start find apis...
[TRACE]	No config be found
[INFO]	use recommend config
[INFO]	search api from:xxx
[TRACE]	No config be found
[INFO]	use recommend config
[INFO]	search api from:xxx
[INFO]	Start parse apis

Process finished with exit code 0

**Environment (please complete the following information):**
 - OS: windos10 20H2 19042.1348
 - IDEA version [2020.3]
 - Plugin version [2.2.9]

**Demo Code**
https://github.com/lj7711622/yapi

**CheckList**

**Additional context**
使用的类对应的依赖
```xml
    <groupId>com.github.abel533</groupId>
    <artifactId>ECharts</artifactId>
    <version>3.0.0.5</version>
```

**Comment by tangcent** [comment]
`com.github.abel533.echarts.Option`类似乎内容过多.

- 尝试忽略此类:
```properties
field.ignore=groovy:it.type().name()=="com.github.abel533.echarts.Option"
```
- 如果确实需要此类, 也可以尝试忽略部分字段:
```properties
field.ignore=com.github.abel533.echarts.Option#toolbox
field.ignore=com.github.abel533.echarts.Option#tooltip
field.ignore=com.github.abel533.echarts.Option#xAxis
field.ignore=com.github.abel533.echarts.Option#yAxis
field.ignore=com.github.abel533.echarts.Option#series
field.ignore=com.github.abel533.echarts.Option#polar
field.ignore=com.github.abel533.echarts.Option#options
field.ignore=com.github.abel533.echarts.Option#itemStyle
field.ignore=com.github.abel533.echarts.Option#geo
field.ignore=com.github.abel533.echarts.Option#parallel
```
