### ISSUE TITLE
【配置咨询】非spring注解通过配置能解决吗？

### ISSUE THREAD

**Issue by fudl** [tangcent/easy-yapi#651]
请问，非spring注解通过配置能解决吗？
我看完关闭的 issues和配置说明，创建扩展文件 ${ActionName}Ext.groovy 的方式是不推荐了吗？

**Comment by tangcent** [comment]
有一套`Generic`的实现:
https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/generic/GenericRequestClassExporter.kt
完全靠规则来解析api, 但是我还没整理文档出来，所以你需要阅读一下这个类的源码来理解需要配置哪些规则。
可以参考https://github.com/tangcent/easy-yapi/blob/master/third/dubbo.config

note: 需要勾选<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Support</kbd> > <kbd>generic export</kbd>才会激活`GenericRequestClassExporter`。

---

如果是通用的框架，可以尝试参考: https://github.com/tangcent/easy-yapi/tree/master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/quarkus
来添加支持。
如果是企业内部框架也可以考虑维护一个内部版本的插件。

**Comment by fudl** [comment]
感谢回复，Generic的实现对我的情况来说复杂了点。可能是我没说清楚。
公司封装了spring的@RequestMapping，导致插件读不到 api和 method。
继承 SpringClassExporter 扩展方法比如SPRING_REQUEST_MAPPING_ANNOTATIONS增加新的注解名称会不会简单点？

**Comment by tangcent** [comment]
那考虑维护一个内部版本吧。
继承SpringRequestClassExporter，补一些特有的逻辑就行: https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/spring/SpringRequestClassExporter.kt

**Comment by fudl** [comment]
好的，我们再去评估吧。再次感谢。

**Comment by tangcent** [comment]
如果方便的话，考虑提供一个`demo`。我能更准确的判断是否是通用的需求。

对`Quarkus`的支持里有支持自定义注解上注解`Quarkus`的注解。
https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/quarkus/QuarkusCustomHttpMethodResolver.kt
我不确定你描述的是不是也是这种情况?
