### ISSUE TITLE
生成md文档时接口入参的必要性没有体现

### ISSUE THREAD

**Issue by qiuziyang1995** [tangcent/easy-yapi#655]
接口
`public SuccessVO<DataBaseInsertVO> uploadDataBase(
 @RequestBody DataBaseUploadParam dataBaseUploadParam) { }`

入参对象
public class DataBaseUploadParam implements Serializable {

    /**
     * 父数据id：关联早期版本数据.
     *
     * @default null
     */
    private Integer parentId;

    /**
     * 文件名称. 1.txt
     */
    @NotNull(message = "文件名称不能为空")
    private String fileName;
}

md示例
![image](https://user-images.githubusercontent.com/82496399/142362214-8fa78591-00c0-4d00-9491-5aec0a84a500.png)

**Comment by tangcent** [comment]
设置里面改一下markdown的输出类型

**Comment by qiuziyang1995** [comment]
> 设置里面改一下markdown的输出类型

完美解决~
