### ISSUE TITLE
当忽略参数字段带-的时候,无效

### ISSUE THREAD

**Issue by vsonctrl** [tangcent/easy-yapi#657]
比如
param.ignore[@org.springframework.web.bind.annotation.RequestHeader]=groovy:it.ann("org.springframework.web.bind.annotation.RequestHeader","name") == "Member-Id"
这样就无效

#param.ignore[@org.springframework.web.bind.annotation.RequestHeader]=groovy:it.ann("org.springframework.web.bind.annotation.RequestHeader","name") == "MemberId"
这样就有效

**Comment by tangcent** [comment]
我测试有效。
需要注意，插件目前未支持自动处理spring的`@AliasFor`.

所以你这里建议配置为:

```properties
param.ignore[@org.springframework.web.bind.annotation.RequestHeader]=groovy:it.ann("org.springframework.web.bind.annotation.RequestHeader") == "Member-Id"
param.ignore[@org.springframework.web.bind.annotation.RequestHeader]=groovy:it.ann("org.springframework.web.bind.annotation.RequestHeader","name") == "Member-Id"
```
