### ISSUE TITLE
自动生成的md文档，Header信息表格生成格式有误

### ISSUE THREAD

**Issue by qiuziyang1995** [tangcent/easy-yapi#661]
### RESPONSE

**Header：**

| name  |  value  |  required  | desc  |
| ------------ | ------------ | ------------ | ------------ | ------------ |
| content-type | application/json;charset=UTF-8 | NO |   |

**Body：**

| name | type | required | default | desc |
| ------------ | ------------ | ------------ | ------------ | ------------ |
|  | string |  |  |  |

看起来在header中表格列标识符"-----"多了一列导致idea解析有误

**Comment by tangcent** [comment]
see https://github.com/tangcent/easy-yapi/issues/650

插件的版本是最新的吗?
