### ISSUE TITLE
[Feature] 希望可以增加复制请求参数和格式化JSON功能

### ISSUE THREAD

**Issue by NotEdibleSalt** [tangcent/easy-yapi#666]

**Comment by NotEdibleSalt** [comment]
- 复制请求参数
当光标在接口上时，点击鼠标左键在出现的功能选项中出现出现一个名为复制请求参数的选项，点击这个功能选项就自动复制请求参数并转化为json格式的

- 格式化JSON功能
  希望有一个格式化json字符串的窗口用来将字符串转换为json

**Comment by tangcent** [comment]
> * 复制请求参数

虽说可行，但是这个功能看起来很鸡肋, 它的使用场景是什么?

> * 格式化JSON功能

对于这类额外的功能，我一直很矛盾，它的实现代价很小，放在这个插件里也说得过去。但是一方面有很多插件支持这个功能,  另一方面给`easy-api`加太多功能很难Keep It Simple and Stupid.  
我会考虑实现此功能，但它可能需要一段时间。你也可以安装另一个插件来支持此功能。

**Comment by NotEdibleSalt** [comment]
好的，开源不易，感谢作者
