### ISSUE TITLE
[Feature] 导出yapi返回内容为空 error to resolve class:null

### ISSUE THREAD

**Issue by damagez** [tangcent/easy-yapi#668]
问题场景：开开心心代码码完，加了个接口，发现导出的文档返回值是空的，WARN提示 **error to resolve class:null**

问题的原因：当导入同一个包的类过多时，IDEA会将导入转换为*

如何解决： File->settings->Editor->Code Style->java->imports
修改class count to use  import with '*'的数值大一些
[https://img-blog.csdn.net/20180308144851861](url)

期望功能：能够增加逻辑，处理import *的场景

easy-yapi版本：Version 2.2.4.183.0

**Comment by tangcent** [comment]
我没办法重现你的问题.
你可以试试clone这个项目: [web-demo](https://github.com/Earth-1610/web-demo)

将[UserCtrl](https://github.com/Earth-1610/web-demo/blob/master/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/UserCtrl.java)中的import改为:
```java
import com.itangcent.common.annotation.Public;
import com.itangcent.common.constant.UserType;
import com.itangcent.common.dto.*;
import com.itangcent.common.model.UserInfo;
import org.springframework.web.bind.annotation.*;

import java.util.Collections;
import java.util.List;
import java.util.Random;
import java.util.stream.Collectors;
import java.util.stream.Stream;
```
导出试试结果。

**Comment by damagez** [comment]
我尝试了一下，发现demo确实*也可以导入成功。我使用demo按照我的环境才能复现问题。

需要添加一些文件到工程
1.将工程中的已有的配置文件.easy.api.config删除，使用配置文件 .yapi.config，内容为
method.return[#return]=groovy: "com.itangcent.springboot.demo.response.MsgResult<" +  helper.resolveLink(it.doc("return")) +">"

2.maven增加依赖
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.12</version>
        </dependency>

3.创建目录com.itangcent.springboot.demo.response，并增加多个java文件
package com.itangcent.springboot.demo.response;

import lombok.Data;

@Data
public class MsgResult<T>  {
    private String resultCode;
    private BusinessMsg businessMsg;
    private String hash;
    protected T detailMsg;

    public MsgResult(String resultCode, BusinessMsg msg) {
        this(null, resultCode, msg);
    }

    public MsgResult() {
        this.resultCode = Status.OK.toString();
        this.businessMsg = new BusinessMsg();
    }

    public MsgResult(T detailMsg) {
        this.resultCode = Status.OK.toString();
        this.businessMsg = new BusinessMsg();
        this.detailMsg = detailMsg;
    }

    public MsgResult(T detailMsg, String resultCode, BusinessMsg businessMsg) {
        this.resultCode = Status.OK.toString();
        this.businessMsg = new BusinessMsg();
        this.detailMsg = detailMsg;
        this.resultCode = resultCode;
        this.businessMsg = businessMsg;
    }
}
========
package com.itangcent.springboot.demo.response;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class BusinessMsg {
    private int businessCode = 0;
    private String businessNote = "Success";
}
=======
package com.itangcent.springboot.demo.response;

public enum Status {
    OK("0"),
    BusinessException("400"),
    AccessTokenExpireException("401"),
    DeniedException("401"),
    ServerException("500");

    private String code;

    private Status(String code) {
        this.code = code;
    }

    @Override
    public String toString() {
        return this.code;
    }

}
4.修改UserCtrl的导入和接口，通过导入单个增加新用户接口进行测试
import com.itangcent.common.model.*;

    /**
     * 增加新用户
     * @param userInfo
     * @return {@link UserInfo}
     */
    @PostMapping("/add")
    public UserInfo add(@RequestBody UserInfo userInfo) {
        return userInfo;
    }
5.发现即使在UserCtrl增加import com.itangcent.springboot.demo.response.MsgResult;
日志为
[INFO]	use recommend config
[INFO]	search api from:com.itangcent.springboot.demo.controller.UserCtrl
[ERROR]	unable to resolve property:digit
[INFO]	To ignore this error,surround with:
###set ignoreUnresolved = true
###set ignoreUnresolved = false
[WARN]	error to resolve class:null
[INFO]	Export to 一个yapi地址 success

[ERROR]	unable to resolve property:digit可忽略，主要是[WARN]	error to resolve class:null
