### ISSUE TITLE
询问下json.rule.field.ignore的用法

### ISSUE THREAD

**Issue by qinkangdeid** [tangcent/easy-yapi#67]
**Describe the bug**
- 看到配置规则有可以忽略某个字段的功能，
![image](https://user-images.githubusercontent.com/17582522/67636292-15aa9200-f90a-11e9-8dc8-8122a3292645.png)

现在是这么个情况 我是直接吧数据库实体返回到做http响应信息了，项目里使用了mybatis的一个框架（mybatis-plus） 它有个ar模式 特点是数据库的实体类要继承一个父类 数据库实体形式如：
```java
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName("banner_info")
public class BannerInfoEntity extends Model<BannerInfoEntity> {
}
```
继承的`Model`类的结构如下：
```java
public abstract class Model<T extends Model<?>> implements Serializable {
    private static final long serialVersionUID = 1L;
    private transient Log log = LogFactory.getLog(this.getClass());
}
```
里面有个日志属性`log` 返回参数实体我不想被返回出去   里面还有一个`serialVersionUID`是`easy-yapi`自动过滤了吧

我在`.easy.api.config`文件里配置了这样：
`json.rule.field.ignore=com.baomidou.mybatisplus.extension.activerecord.Model#log` 
或者加个`@`符合在类路径前`json.rule.field.ignore=@com.baomidou.mybatisplus.extension.activerecord.Model#log`
貌似都没起作用  询问下json.rule.field.ignore的用法具体是怎么用的 我在demo里没看到这个的配置事例🙏

**Comment by tangcent** [comment]
1.  这里简单的写法应该是:
`json.rule.field.ignore=log`
忽略字段名为log的字段

2. 使用脚本表达式:
`json.rule.field.ignore=grovvy:it.name()=="log"`

3. 复杂点，根据字段类型:
`json.rule.field.ignore=grovvy:it.type().name()=="xxx.xxx.Log"`

4.  [支持的配置规则](https://github.com/tangcent/easy-yapi/blob/master/docs/cn/2.%20%E6%94%AF%E6%8C%81%E7%9A%84%E9%85%8D%E7%BD%AE%E8%A7%84%E5%88%99.md)

![image](https://user-images.githubusercontent.com/17569144/67643688-0866c500-f955-11e9-99ac-4f4daee0f3ba.png)

这里上下文`field`指的是使用脚本表达式时`it`的类型
即`json.rule.field.ignore=grovvy:it`中的it提供什么样的方法

5. 有个问题是测试覆盖度不够，有些方法可能有些问题.
比如我刚才尝试了下,`class`的`name()`方法有点问题
我会在稍晚时候修复它.

6. 另外,有发现[spring-demo](https://github.com/Earth-1610/spring-demo)未覆盖的场景，欢迎提供一个PR

**Comment by qinkangdeid** [comment]
好的

**Comment by tangcent** [comment]
抱歉。。。上面把`groovy`误写成了`grovvy`

**Comment by tangcent** [comment]
如果需要 `json.rule.field.ignore=groovy:it.type().name()=="xxx.xxx.Log"`可以到
[v1.1.1.4](https://github.com/tangcent/easy-yapi/releases/tag/v1.1.1.4)下载.

另外在v1.1.1.4上，默认配置中包含了
```
#ignore transient field
json.rule.field.ignore=groovy:it.hasModifier("transient")
```

**Comment by qinkangdeid** [comment]
> 如果需要 `json.rule.field.ignore=groovy:it.type().name()=="xxx.xxx.Log"`可以到
> [v1.1.1.4](https://github.com/tangcent/easy-yapi/releases/tag/v1.1.1.4)下载.
> 
> 另外在v1.1.1.4上，默认配置中包含了
> 
> ```
> #ignore transient field
> json.rule.field.ignore=groovy:it.hasModifier("transient")
> ```

啊啊～～～ 大佬 666 我刚想和你说`json.rule.field.ignore=groovy:it.type().name()=="xxx.xxx.Log"`在这个版本会报错 你加修复了 好快啊 我好喜欢 哈哈😄
