### ISSUE TITLE
[Question]你好，想问一下我目前是intelijj 2020.2.4，目前遇到编译错误，想问一下目前能够编译通过的intellij版本

### ISSUE THREAD

**Issue by zhouyi1991** [tangcent/easy-yapi#670]
Forms instrumentation failed for /easy-yapi-master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/dialog/ApiCallDialog.form: java.lang.RuntimeException: com.intellij.compiler.instrumentation.InstrumentationClassFinder$2: Class not found: java.util.List
想问一下目前master编译的环境是怎么样的，谢谢，按理说跟intellij版本应该没有关系，直接使用工程默认gradle配置就行了。

**Comment by zhouyi1991** [comment]
![image](https://user-images.githubusercontent.com/96456854/146868160-7b44e979-3113-4dd8-aadc-9f09b3a4c4fd.png)
目前gradle下载的编译版本是截图这个

**Comment by tangcent** [comment]
我用的JDK1.8。
https://github.com/tangcent/easy-yapi/blob/master/.github/workflows/ci.yml

你执行`./plugin-script/package_plugin.sh`试试?

**Comment by zhouyi1991** [comment]
编译通过了，目前需要的环境是，jdk1.8,我使用的是zulu jdk1.8,其他jdk应该也没啥问题。之前是jdk11,所以报错了。
