### ISSUE TITLE
老板,Data解析成对象了

### ISSUE THREAD

**Issue by tutuerhao** [tangcent/easy-yapi#68]
![image](https://user-images.githubusercontent.com/29938085/67667018-f2362480-f9a7-11e9-89be-a5ad6803e16d.png)

**Comment by tutuerhao** [comment]
![image](https://user-images.githubusercontent.com/29938085/67667070-09751200-f9a8-11e9-9330-fcc199a5d206.png)

**Comment by tangcent** [comment]
see #63
是和这个issue一样的问题吗?

**Comment by tutuerhao** [comment]
@tangcent 应该是,应该怎么解决呢,看不太懂你发的呀,在哪改配置呢

**Comment by tangcent** [comment]
放在项目根目录就行(不需要共享给别人的话加入gitignore).类似于这个: 
https://github.com/Earth-1610/spring-demo/blob/5427aef3e33864f58022790634079d023a3ffe62/cn/.easy.api.config#L85-L87

现在最新的插件里内置的配置有这些:
https://github.com/tangcent/easy-yapi/blob/1d6f610443edbef4c8a0a7ca7f30b8b5dacf5b72/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/config/RecommendConfigReader.kt#L82-L87

自动加载内置配置需要开启:
<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> 
![image](https://user-images.githubusercontent.com/17569144/67667554-09294680-f9a9-11e9-9bff-908cb56c9274.png)

**Comment by tangcent** [comment]
放在项目根目录就行(不需要共享给别人的话加入gitignore).类似于这个: 
https://github.com/Earth-1610/spring-demo/blob/5427aef3e33864f58022790634079d023a3ffe62/cn/.easy.api.config#L85-L87

现在最新的插件里内置的配置有这些:
https://github.com/tangcent/easy-yapi/blob/1d6f610443edbef4c8a0a7ca7f30b8b5dacf5b72/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/config/RecommendConfigReader.kt#L82-L87

自动加载内置配置需要开启:
<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> 
![image](https://user-images.githubusercontent.com/17569144/67667554-09294680-f9a9-11e9-9bff-908cb56c9274.png)

**Comment by tutuerhao** [comment]
![image](https://user-images.githubusercontent.com/29938085/67671706-6cb77200-f9b1-11e9-8921-52ec1e3fd2ea.png)
![image](https://user-images.githubusercontent.com/29938085/67671738-7b058e00-f9b1-11e9-8540-9dbd505a98e0.png)


@tangcent 写的long为啥显示的是integer呀

**Comment by tutuerhao** [comment]
@tangcent 感谢

**Comment by tangcent** [comment]
- 为了适应不同的JsonSerializer，所以有这条规则
`json.rule.convert`用于指定某些类型在json中输出为其他类型
另外有`mock.[name|type]=mock`这条规则用于设置yapi相关mock信息
---

如果希望将Date转换为String,即`yyyy-MM-dd HH:mm:ss`格式
应使用如下配置
```
json.rule.convertjava.util.Date]=java.lang.String
json.rule.convert[java.time.LocalDateTime]=java.lang.String
json.rule.convert[java.time.LocalDate]=java.lang.String

#根据项目model特征
mock.[*.time|string]=@datetime
mock.[*Time|string]=@datetime
mock.[*.date|string]=@date
mock.[*Date|string]=@date
```
---

如果希望将Date转换为Long,即时间戳格式
应使用如下配置
```
json.rule.convertjava.util.Date]=java.lang.Long
json.rule.convert[java.time.LocalDateTime]=java.lang.Long
json.rule.convert[java.time.LocalDate]=java.lang.Long

#根据项目model特征

#毫秒时间戳
mtimestamp=@timestamp@string("number", 3)

# 整型的xxxTime mock为时间戳
mock.[*Time|integer]=${mtimestamp}

```
---
更多的配置demo可以看这里:https://github.com/Earth-1610/spring-demo/blob/master/cn/.easy.api.config

另外任何问题还可以点这里:[![Gitter](https://badges.gitter.im/Earth-1610/easy-yapi.svg)](https://gitter.im/Earth-1610/easy-yapi?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
