### ISSUE TITLE
在idea上Export接口至Yapi访问错误

### ISSUE THREAD

**Issue by dingdinglijia** [tangcent/easy-yapi#681]
yapi部署到了服务器上，通过域名访问。使用idea上传接口时报：unable to find valid certification path to requested target错误
通过浏览器访问yapi服务器的/api/project/get接口没问题，插件不行，添加证书也无效，有什么解决的方法吗？
![image](https://user-images.githubusercontent.com/63435896/148352572-05508e75-be76-40a0-943b-1a89c8d90e0d.png)

**Comment by tangcent** [comment]
抱歉，这个问题一直没什么头绪，我没有办法重现这个问题，所以不确定问题出在哪里。
根据这个问题搜索到的解决方案都是说要导入证书，这似乎很难操作，

---

也许你可以试着改下面这段代码:
https://github.com/tangcent/easy-yapi/blob/746c58ecd42d860aa198d2baa7860258168bc34d/common-api/src/main/kotlin/com/itangcent/http/ApacheHttpClient.kt#L49-L68
