### ISSUE TITLE
json.rule.field.ignore=groovy:it.containingClass().name()失效

### ISSUE THREAD

**Issue by simonpdh** [tangcent/easy-yapi#682]
json.rule.field.ignore=groovy:it.containingClass().name()失效

idea版本2021.2专业版
easyYapi版本2.3.1.183.0

**Comment by tangcent** [comment]
测试正常，尝试补充一下代码和规则?

**Comment by simonpdh** [comment]
> 测试正常，尝试补充一下代码和规则?

json.rule.field.ignore=groovy:it.containingClass().name()=="xxx.BaseRpcRequest"

**Comment by tangcent** [comment]
> > 测试正常，尝试补充一下代码和规则?
> 
> json.rule.field.ignore=groovy:it.containingClass().name()=="xxx.BaseRpcRequest"
> 
> public class xxxRequest extends BaseRpcRequest { }

你需要的可能是:
```properties
json.rule.field.ignore=groovy:it.defineClass().name()=="xxx.BaseRpcRequest"
```

---

`containingClass`是当前解析的`class`，即`xxxRequest`
`defineClass`是声明这个`field`的`class`，即`BaseRpcRequest `

**Comment by simonpdh** [comment]
> > > 测试正常，尝试补充一下代码和规则?
> > 
> > 
> > json.rule.field.ignore=groovy:it.containingClass().name()=="xxx.BaseRpcRequest"
> > public class xxxRequest extends BaseRpcRequest { }
> 
> 你需要的可能是:
> 
> ```ini
> json.rule.field.ignore=groovy:it.defineClass().name()=="xxx.BaseRpcRequest"
> ```
> 
> `containingClass`是当前解析的`class`，即`xxxRequest` `defineClass`是声明这个`field`的`class`，即`BaseRpcRequest `

好的，感谢
