### ISSUE TITLE
[Question] 是否可以建多级目录

### ISSUE THREAD

**Issue by kuzfa** [tangcent/easy-yapi#684]
![image](https://user-images.githubusercontent.com/7540503/149911641-c1eeb09d-d056-4400-81e3-14f0483cc802.png)
我想在“分类名称”目录下再建一级，比如“子分类”，不知道是否可以

**Comment by tangcent** [comment]
对于这个问题，依旧还是:

> 目前yapi官方版本仅支持一级目录，这使得插件只能处理一级目录
实际上我公司内部亦是对yapi的做了二次开发亦支持多级目录
而对比网上其他二次开发版本，对如何组织多级目录各自实现方式不一.
我目前还没有想到如何抽象出处理多级目录的规则让用户自行配置.
