### ISSUE TITLE
[Question] 建议支持一个导出自定义json格式模板功能，方便对接不同系统

### ISSUE THREAD

**Issue by wulihuawuqia** [tangcent/easy-yapi#685]

**Comment by tangcent** [comment]
详细描述一下？

**Comment by wulihuawuqia** [comment]
目前支持导出为markdown形式，但是目前有其他对接的系统，接口入参识别不了，导入时是使用的自定义的格式。这个时候需要翻译markdown。

**Comment by tangcent** [comment]
我以前用`postman`的时候，就开发[easy-api](https://github.com/tangcent/easy-api)帮助我导入到`postman`。
后来开始用`yapi`, 我就在[easy-api](https://github.com/tangcent/easy-api)的基础上加入`yapi`的支持，成了现在的`easy-yapi`。
所以你如果要对接一个特定的系统，那fork这个插件增加你需要的功能, 可能会是更合适的选择。
如果需要帮助，你可以随时提交新的issue。

**Comment by wulihuawuqia** [comment]
能否提供一个整个项目各个目录的说明文档和主要流程文档。目前我想的是，在页面上新增一个导出动态模板json的按钮。我想对于您来说，应该是挺简单的，但是我以前没有开发过idea控件，而且对于您这个项目不太熟悉。可能帮忙指点一下么？我想应该有个公共接口，只需要实现公共接口即可。感谢，感谢
json示例：
`{
  "methods": [
    {
      "mname": "list",
      "params": [
        {
          "name": "name",
          "type": "java.lang.String",
          "order": 1,
          "children": [
            {
              "children": [
                {
                  "children": [],
                  "default_value": "",
                  "desc": "",
                  "name": "t4",
                  "order": 0,
                  "required": 1,
                  "type": "bean3"
                }
              ],
              "default_value": "",
              "desc": "",
              "name": "bean2",
              "order": 0,
              "required": 1,
              "type": "obj"
            }
          ]
        },
        {
          "name": "compontentTypeId",
          "type": "int",
          "desc": "",
          "order": 2
        },
        {
          "name": "pageSize",
          "type": "int",
          "desc": "",
          "order": 3
        },
        {
          "name": "start",
          "type": "int",
          "desc": "",
          "order": 4
        }
      ],
      "result": {
        "name": "param",
        "type": "ResultModel",
        "desc": ""
      },
      "desc": "列表查询"
    },
    {
      "mname": "search",
      "params": [
        {
          "name": "name",
          "type": "java.lang.String",
          "desc": "",
          "order": 1
        },
        {
          "name": "pageSize",
          "type": "int",
          "desc": "",
          "order": 2
        },
        {
          "name": "start",
          "type": "int",
          "desc": "",
          "order": 3
        }
      ],
      "result": {
        "name": "param",
        "type": "ResultModel",
        "desc": ""
      },
      "desc": "搜索列表"
    }
  ],
  "iname": "com.test.batchAdd",
  "desc": "测试批量添加接口方法和参数"
}`

**Comment by tangcent** [comment]
如果你只需要导出你想要的`json`格式。那可以模仿项目里`markdown`相关的代码来做。
1. 创建一个Action: [MarkdownExportAction](https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/actions/MarkdownExportAction.kt)
2. 声明在xml里: https://github.com/tangcent/easy-yapi/blob/746c58ecd42d860aa198d2baa7860258168bc34d/idea-plugin/src/main/resources/META-INF/easy-yapi-java.xml#L57-L64
3. 复制[markdown](https://github.com/tangcent/easy-yapi/tree/master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown)下的文件，你可以分别命名为`MyJsonApiExporter`,`MyJsonFormatter`
4. 重写`MyJsonFormatter`里的这段代码, 把插件生成的`Doc`序列化为你需要的`json`格式的信息: https://github.com/tangcent/easy-yapi/blob/746c58ecd42d860aa198d2baa7860258168bc34d/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown/MarkdownFormatter.kt#L51-L56

---

如果`kotlin`不熟悉，你可以直接创建`java`类

**Comment by wulihuawuqia** [comment]
请问调整完之后，怎么打包验证呀？

**Comment by tangcent** [comment]
打包脚本在：https://github.com/tangcent/easy-yapi/tree/master/plugin-script

---

ref: https://github.com/tangcent/easy-yapi/issues/35

**Comment by wulihuawuqia** [comment]
![image](https://user-images.githubusercontent.com/17930741/153813707-34e73b4b-affc-4992-9dd9-3d57c8a69c59.png)

**Comment by wulihuawuqia** [comment]
这个地方应该怎么注入呢？

**Comment by tangcent** [comment]
报什么错? 

---

一般只有 Interface + Implement 模式才需要显式的在Action注入
```
builder.bind(XXXInter::class) { it.with(XXXImpl::class).singleton() }
```
如果不是接口的话是不需要显式注入的

**Comment by wulihuawuqia** [comment]
没有报任何错，就是没有任何反应了。。。

**Comment by wulihuawuqia** [comment]
![image](https://user-images.githubusercontent.com/17930741/153829544-5cc87131-801d-4fc9-90d7-c14ba27c04eb.png)

这个我用的java 格式，
![image](https://user-images.githubusercontent.com/17930741/153829602-17d5b5cd-4870-47af-857c-2587024ca5e0.png)
目前执行到这就直接退出了，

**Comment by tangcent** [comment]
没有走到这行? https://github.com/tangcent/easy-yapi/blob/cfc7fabd905c2842821b9b5f05d5836878607a7a/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown/MarkdownApiExporter.kt#L102

---

你可以试着看看日志, debug情况下的日志在这里: idea-plugin/idea-sandbox/system/log/idea.log

**Comment by wulihuawuqia** [comment]
没有任务报错，发现原来生成 marldown 会先弹窗，但是我调整调用java 静态方法后，没有弹窗这一步了；直接跳过了。然后就跳转到
![image](https://user-images.githubusercontent.com/17930741/153836219-6bee0cd4-3004-481c-8950-e4600b8334ca.png)

**Comment by wulihuawuqia** [comment]
终于知道了，是因为java 文件没法正常编译，转换成kt 就行了。涨见识啦

**Comment by tangcent** [comment]
:)  对，没有编译java
https://github.com/tangcent/easy-yapi/blob/cfc7fabd905c2842821b9b5f05d5836878607a7a/idea-plugin/build.gradle#L130-L135
