### ISSUE TITLE
[Feature] ignore类中的某些字段，但仍然想让他可以被序列化

### ISSUE THREAD

**Issue by zhageLiu** [tangcent/easy-yapi#687]
目前ignore的用法，是使用@JsonIgnore来忽略掉类中的某些字段，但我只是不想让前端传给我，这个字段我还想让他会被序列化，这种情况下我该怎么做呢？或者添加对注释里的@ignore注解的支持？

**Comment by tangcent** [comment]
配置`field.ignore=#ignore`
然后就可以用注释`@ignore`来忽略字段了
