### ISSUE TITLE
[Bug] 选中接口右键 Export Yapi 时，导致 IDEA 直接卡死，程序未响应

### ISSUE THREAD

**Issue by misyili** [tangcent/easy-yapi#688]
系统：macOS Monterey
IDEA: 2021.1.3
插件版本：2.3.1.183.0

**Comment by misyili** [comment]
安装v2.3.0 后没有出现该问题

**Comment by tangcent** [comment]
hello, 可不可以按照以下步骤看看日志卡在哪里?
https://github.com/tangcent/easy-yapi/issues/new?assignees=&labels=type%3A+bug&template=bug_report.md&title=%5BBug%5D+Xxx
