### ISSUE TITLE
[Question] 我想配置返回数据格式如下

### ISSUE THREAD

**Issue by weihubeats** [tangcent/easy-yapi#699]
**Describe the question**

code
msg
data
因为我的接口是如下方式的:
![image](https://user-images.githubusercontent.com/42484192/155933820-e40b52d1-67d8-4362-b852-2f310b5d6f7a.png)
我统一返回的 code  msg 在mvc层封装了，所以不需要在这里弄一个对象去持有他，导致上传的接口没有code 和msg

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/42484192/155933958-fd22c5c0-6ed4-4e99-8640-8fdfd7b37f38.png">

**Comment by tangcent** [comment]
http://easyyapi.com/setting/rules/method_return.html

试试这样配:
```
method.return[#real_return]=groovy: "com.itangcent.common.dto.Result<" + it.returnType() +">"
```
