### ISSUE TITLE
 start up idea error with installed from disk

### ISSUE THREAD

**Issue by watersoona** [tangcent/easy-yapi#7]
**Describe the bug**

**To Reproduce**
1. Go to 'plugins'
2. Click on 'install'
3. install yapi.jar from disk.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/10571512/58392139-198c6c80-806b-11e9-9ee7-49dc16e9cb57.png)

**Desktop (please complete the following information):**
 - OS: [MacOs mojave]
 - Idea
 - Version [U 2019.2]
 - already installed easy-api plg jar

**Comment by tangcent** [comment]
uninstall plugin [easy-api]
