### ISSUE TITLE
[Bug] 从Java实体导出To Json5时，中文注释显示乱码

### ISSUE THREAD

**Issue by LiuHongZ** [tangcent/easy-yapi#702]
**Describe the bug**

在实体类中使用 alt + insert快捷键，选择 To Json5，导出的中文注释乱码.

**Screenshots**

![image](https://user-images.githubusercontent.com/25975575/156291745-975c76ef-d49b-4f82-a42a-7a6398b3c1f1.png)

**Comment by tangcent** [comment]
这可能和系统字符集有关系。部分windows用户存在此问题。

---

我会尝试在Settings里提供一个配置选项，用来切换控制台的字符集

**Comment by tangcent** [comment]
[easy-yapi-2.3.2.183.0.zip](https://github.com/tangcent/easy-yapi/files/8169700/easy-yapi-2.3.2.183.0.zip)

<img width="614" alt="image" src="https://user-images.githubusercontent.com/17569144/156365971-456f5484-b58c-4178-aab9-87a934a366b1.png">
