### ISSUE TITLE
[Question] 如何导出父类的API信息

### ISSUE THREAD

**Issue by li-keguo** [tangcent/easy-yapi#704]
**Describe the question**

我有一段代码实现如下：

```java
public interface PagedController<V, T> {
    
    @PostMapping("list/search")
    default ResponseEntity<ApiResult<PageResult<T>>> search(@RequestBody @Validated final PageCondition<V> pageCondition) {
        return RestResultUtil.ok(pageService().searchByPage(pageCondition));
    }
   //  ... ... 
}
```
这个是一个通用的接口，我在实际的controller类中继承这个接口，如下：
```java
public class XXXController implements PagedController<VO,DTO> {
    private final XXService xxxService;

    @GetMapping("xxx/{id}")
    public ResponseEntity<ApiResult<List<DTO>>> listById(@PathVariable final Long id) {
        return RestResultUtil.ok(xxxService.xxx(id));
    }
    // ... ...
}
```

**Expected result**

我实际的接口应该是两个，但我只能导出一个

**Screenshots**

我实际的接口应该是两个，但我只能导出一个，实际画面不方便展示.

**Additional context**

.

**Comment by tangcent** [comment]
没有考虑到api以default的形式定义的情况

**Comment by li-keguo** [comment]
大佬有计划支持一下吗？不会写kotlin,不然就提pr了，项目代码看着很优雅

**Comment by tangcent** [comment]
标了`work-in-progress`的都会得到处理。我有空就按照 [work-in-progress](https://github.com/tangcent/easy-yapi/issues?q=is%3Aissue+is%3Aopen+label%3A%22status%3A+work-in-progress%22) 列表实现

**Comment by li-keguo** [comment]
感谢

**Comment by tangcent** [comment]
试一下 [easy-yapi-2.3.2.183.0.zip](https://github.com/tangcent/easy-yapi/files/8178710/easy-yapi-2.3.2.183.0.zip)

**Comment by li-keguo** [comment]
非常棒，感谢大佬提供特性支持，期待下版本的发布
