### ISSUE TITLE
[Question] json.class.parse.before 和 json.class.parse.after 被执行两次？

### ISSUE THREAD

**Issue by dnovelty** [tangcent/easy-yapi#705]
**Describe the question**

如图片所示。请问这是正常的吗？

**Screenshots**

请求参数类，一个字段。

![微信截图_20220304100248](https://user-images.githubusercontent.com/45954889/156685532-3e35aa07-eb50-400f-8e4c-ee7cb20bf865.png)

请求controller，一个方法

![微信截图_20220304100306](https://user-images.githubusercontent.com/45954889/156685595-7a4f0c01-6639-411d-a6d7-8f45cc2883dc.png)

配置项。两个钩子函数json.class.parse.before 和 json.class.parse.after
![微信截图_20220304100226](https://user-images.githubusercontent.com/45954889/156685666-6857d51a-f442-4e43-88ba-afc20556ab9c.png)

日志。
![微信截图_20220304100338](https://user-images.githubusercontent.com/45954889/156685697-6565fbca-47f8-443f-a610-b414b8bd518c.png)

疑问：controller只有一个参数，钩子不应该只调用一次吗？

**Comment by tangcent** [comment]
> 配置项。两个钩子函数json.class.parse.before 和 json.class.parse.after

你是指`json.class.parse.before 和 json.class.parse.after`还是`api.param.parse.before和api.param.parse.after`?

---
`api.param.parse.before和api.param.parse.after`会被调用两次。

是因为第一次会尝试解析一遍参数:
https://github.com/tangcent/easy-yapi/blob/efac2f3efd4a64d974cddbc5de5046c05e734ac4/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/RequestClassExporter.kt#L479-L499

然后来判断参数里是不是包含`文件`，如果有文件则`content-type`需要处理为`multipart/form-data`，如果是api上没有指定请求方式则默认为`POST`:
https://github.com/tangcent/easy-yapi/blob/efac2f3efd4a64d974cddbc5de5046c05e734ac4/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/RequestClassExporter.kt#L501-L516

之后会重新遍历参数，解析到`api`中:
https://github.com/tangcent/easy-yapi/blob/efac2f3efd4a64d974cddbc5de5046c05e734ac4/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/RequestClassExporter.kt#L518-L531

之所以要这么做，是因为请求方式是否为`POST`, `content-type`是否为`multipart/form-data`会影响到参数的解析方式。

**Comment by dnovelty** [comment]
> > 配置项。两个钩子函数json.class.parse.before 和 json.class.parse.after
> 
> 你是指`json.class.parse.before 和 json.class.parse.after`还是`api.param.parse.before和api.param.parse.after`?
> 
> `api.param.parse.before和api.param.parse.after`会被调用两次。
> 
> 是因为第一次会尝试解析一遍参数:
> 
> https://github.com/tangcent/easy-yapi/blob/efac2f3efd4a64d974cddbc5de5046c05e734ac4/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/RequestClassExporter.kt#L479-L499
> 
> 然后来判断参数里是不是包含`文件`，如果有文件则`content-type`需要处理为`multipart/form-data`，如果是api上没有指定请求方式则默认为`POST`:
> 
> https://github.com/tangcent/easy-yapi/blob/efac2f3efd4a64d974cddbc5de5046c05e734ac4/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/RequestClassExporter.kt#L501-L516
> 
> 之后会重新遍历参数，解析到`api`中:
> 
> https://github.com/tangcent/easy-yapi/blob/efac2f3efd4a64d974cddbc5de5046c05e734ac4/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/RequestClassExporter.kt#L518-L531
> 
> 之所以要这么做，是因为请求方式是否为`POST`, `content-type`是否为`multipart/form-data`会影响到参数的解析方式。

明白了! 提问主要是为了排除执行两次会不会影响自己的逻辑。目前来看的话是不会影响的。感谢！
