### ISSUE TITLE
[Question] properties中的filter是否可以严格匹配

### ISSUE THREAD

**Issue by dnovelty** [tangcent/easy-yapi#706]
**Describe the question**

.easy.api.config文件中的key[filter]可以带有filter过滤特性。‘
注释中tag为@request.params.ignore注释的class字段，似乎都可以命中field.ignore[#request.params.ignore]和field.ignore[#request.params.ignore.method]，所以里面[filter]的似乎只要前缀匹配就命中了吗？
**Expected result**

希望[filter]里能精确匹配

**Screenshots**

![微信截图_20220304145155](https://user-images.githubusercontent.com/45954889/156714232-4f2e5721-e8a8-47b0-8918-2f29d4c7374c.png)

**Comment by tangcent** [comment]
以前有同学反馈过，这可能是idea的一个`bug`
https://github.com/JetBrains/intellij-community/blob/7f5dba2e30c772426dd5447e1a664354054d114b/java/java-psi-impl/src/com/intellij/psi/impl/source/javadoc/PsiDocCommentImpl.java#L64
由于影响面很小, 所以一直没有处理。

Anyway, 你可以尝试使用`it.doc(xx)!=null`来代替`it.hasDoc(xx)`/`#xx`
```
xxxx[groovy:it.doc("request.params.ignore.method")!=null]=xxxx
```
或者
``````
xxxx=groovy:```
   if(it.doc("request.params.ignore.method")==null){
      return null
   }
   ...
```
``````

**Comment by dnovelty** [comment]
> 以前有同学反馈过，这可能是idea的一个`bug` https://github.com/JetBrains/intellij-community/blob/7f5dba2e30c772426dd5447e1a664354054d114b/java/java-psi-impl/src/com/intellij/psi/impl/source/javadoc/PsiDocCommentImpl.java#L64 由于影响面很小, 所以一直没有处理。
> 
> Anyway, 你可以尝试使用`it.doc(xx)!=null`来代替`it.hasDoc(xx)`/`#xx`
> 
> ```
> xxxx[groovy:it.doc("request.params.ignore.method")!=null]=xxxx
> ```
> 
> 或者
> 
> ```
> xxxx=groovy:```
>    if(it.doc("request.params.ignore.method")==null){
>       return null
>    }
>    ...
> ```
> ```

感谢！顺利解决问题！
