### ISSUE TITLE
会支持apipost吗?

### ISSUE THREAD

**Issue by raoyh** [tangcent/easy-yapi#714]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tangcent** [comment]
https://open.apipost.cn/
等它的开放平台正式开放后，如果官方没有提供`idea`插件的计划，我会考虑提供。

**Comment by langar294** [comment]
apipost支持倒入postman.json，用postman导出，然后再使用是完全可以的
