### ISSUE TITLE
markdown 怎么自定义 目录格式为引用

### ISSUE THREAD

**Issue by langar294** [tangcent/easy-yapi#715]
![image](https://user-images.githubusercontent.com/76939156/158500669-ec10b679-a122-42da-87d9-86f8f1a5325c.png)
这个是默认的导出格式，但是如果接口非常多的话，导致md的目录特别长，不方便找接口，所以我建议改成引用格式，或者让用户自定义支持应用格式，或者说是我没有发现怎么自定义文档格式(官网和idea配置我都看过了)
下面是我期望得到的结果
![image](https://user-images.githubusercontent.com/76939156/158501007-814a2a0a-d9d5-45cd-92b2-a1d148739d6e.png)

**Comment by tangcent** [comment]
> 我没有发现怎么自定义文档格式(官网和idea配置我都看过了)

是的，目前没有。
我原来构想过，但是没有得到一个好的解决方案。
如果你有任何的想法，可以回复。

> 这个是默认的导出格式，但是如果接口非常多的话，导致md的目录特别长，不方便找接口，所以我建议改成引用格式，或者让用户自定义支持应用格式

如果你有更好的格式，可以提供一个示例?

---

当然你也可以直接修改[MarkdownFormatter](https://github.com/tangcent/easy-yapi/blob/master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown/MarkdownFormatter.kt)!

**Comment by langar294** [comment]
你好，下面是我个人的一些想法
1.首先，肯定是要把BASIC，REQUEST这些改成> 引用，不然目录太长了
2.返回体的建议
![9QUT7H{MKWYKF@KV5HJW98Q](https://user-images.githubusercontent.com/76939156/158585527-7de9efbe-31b9-42da-b318-9f16b3bd8985.png)
目前我能想到的只有这些，你做的这个我感觉是最好的，对系统的侵入性最低，太佩服了

**Comment by tangcent** [comment]
> 1.首先，肯定是要把BASIC，REQUEST这些改成> 引用，不然目录太长了

good idea

> 2.返回体的建议

- 如果不需要required&default可以修改<kbd>Preferences(Settings)</kbd> > <kbd>EasyApi</kbd>  > <kbd>Markdown</kbd>   > <kbd>format type</kbd> 
- 我不确定你是希望解析`@apidoc`，还是文档注释和`@apidoc`注释放在一起你觉得有问题? 你是否有添加自定义配置:
`field.doc=#apidoc`?
<img width="378" alt="image" src="https://user-images.githubusercontent.com/17569144/158709755-aa64c498-3802-4fa7-8c28-0bee39c1f336.png">

> data没有显示

I get it

**Comment by langar294** [comment]
ok,thank you.
