### ISSUE TITLE
[Bug] 导出接口枚举配置部分生效

### ISSUE THREAD

**Issue by FJiayang** [tangcent/easy-yapi#722]
**Describe the bug**

**To Reproduce**

Detailed Steps to reproduce the behavior:

1. Open '...'
3. See error
   
**Expected behavior**

实体类：
```java
	/**
	 * 输出类型
	 *
	 * @see NoticeOutPutTypeEnum#code
	 */
	String outPutType;

	/**
	 * Excel配置
	 */
	ExcelConfigDomain excelConfig;

	/**
	 * 分红方式
	 *
	 * @see DividendMethodEnum#code
	 */
	List<String> dividendMethodList;
```
其中NoticeOutPutTypeEnum是工程内枚举，DividendMethodEnum是maven依赖包内的枚举

生成接口只有工程内的枚举可以正确展示对应的值
<img width="1514" alt="image" src="https://user-images.githubusercontent.com/23110725/159659818-2462da95-4f07-4b7d-b86f-45645b077e70.png">

包已经引入
<img width="696" alt="image" src="https://user-images.githubusercontent.com/23110725/159661923-4bb261ff-5b01-4121-bc5b-26378122b548.png">

希望生成的文档和工程内枚举一致，展示枚举类的code值

**Logs**

1. Add config:
   无额外配置文件

2. Console output `easy_api`
run easy-yapi
[INFO]	Start find apis...
[TRACE]	No config be found
[INFO]	use recommend config
[INFO]	search api from:XXXController
[INFO]	Export to http://XXX success
[INFO]	Apis exported completed

**Comment by tangcent** [comment]
目前没有办法处理`通过maven仅下载了jar,没下载source的类`，`idea`对这种类提供的`AST`似乎不完整，导致解析不出来。
等我有空，尝试直接做文本解析试试，到时候和 [https://github.com/Earth-1610/intellij-kotlin/issues/120](https://github.com/Earth-1610/intellij-kotlin/issues/120)一起处理掉。
你现在可以尝试通过`Download Sources`来解决:
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/17569144/159691770-75dc683d-7bc0-44a3-90d8-c2bbad87b524.png">

**Comment by FJiayang** [comment]
> 目前没有办法处理`通过maven仅下载了jar,没下载source的类`，`idea`对这种类提供的`AST`似乎不完整，导致解析不出来。 等我有空，尝试直接做文本解析试试，到时候和 [Earth-1610/intellij-kotlin#120](https://github.com/Earth-1610/intellij-kotlin/issues/120)一起处理掉。 你现在可以尝试通过`Download Sources`来解决: <img alt="image" width="1118" src="https://user-images.githubusercontent.com/17569144/159691770-75dc683d-7bc0-44a3-90d8-c2bbad87b524.png">

好的，辛苦dalao
