### ISSUE TITLE
公司的RPC框架是自研的，如何做扩展支持？

### ISSUE THREAD

**Issue by crazy-pizza** [tangcent/easy-yapi#723]
RT

**Comment by crazy-pizza** [comment]
另外，我们想做成自动化上传API，有没有不通过IDEA插件，使用SDK的方式来上传的方式？

**Comment by tangcent** [comment]
> 另外，我们想做成自动化上传API，有没有不通过IDEA插件，使用SDK的方式来上传的方式？

如果有这个想法,就不需要回答上一个问题了。。。
看看#515

**Comment by crazy-pizza** [comment]
> > 另外，我们想做成自动化上传API，有没有不通过IDEA插件，使用SDK的方式来上传的方式？
> 
> 如果有这个想法,就不需要回答上一个问题了。。。 看看#515

@tangcent 感谢解答。
其实我觉得这个需求还是很有必要的，而且yapi不需要考虑不同的分支上同时上传导致文档不一致问题。
控制权交给用户，由用户来控制数据的一致性，更加灵活，各家公司也可以适配自己的场景。

另外，如果能有某种方式扫描我们自己的rpc接口并生成文档，比如支持扫描带有某个自定义注解的接口，这样会更加灵活，不必局限于某个rpc框架。

**Comment by tangcent** [comment]
> 其实我觉得这个需求还是很有必要的，而且yapi不需要考虑不同的分支上同时上传导致文档不一致问题。
控制权交给用户，由用户来控制数据的一致性，更加灵活，各家公司也可以适配自己的场景。

为何不需要考虑不同的分支上同时上传导致文档不一致问题?
我不是很理解这个意思。当不同的分支同时在开发时，文档被来回覆盖，似乎是个问题？

> 另外，如果能有某种方式扫描我们自己的rpc接口并生成文档

扫描方式基本上还是两种:
- 一种是类swagger的模式，运行时解析
- 另一种是使用[javaparser](https://github.com/javaparser/javaparser)之类的做源码级api解析
不管是第一中还是第二种，都可以考虑做成maven插件或者gradle插件

> 比如支持扫描带有某个自定义注解的接口，这样会更加灵活，不必局限于某个rpc框架。

灵活也有两种选择，一种是针对性的做配置
另一种是放弃解析`spring`/`rpc`框架代码，完全依靠与框架无关的`swagger`注解或者干脆依赖解析注释。
