### ISSUE TITLE
[Bug] 导出 markdown 时，POST 请求 body array 类型 处理失败，表格列数不一致，导致 required 字段没有

### ISSUE THREAD

**Issue by texousliu** [tangcent/easy-yapi#725]
导出 markdown 时，POST 请求 body array 类型 处理失败，表格列数不一致，导致 required 字段没有

**Comment by texousliu** [comment]
应该是 package com.itangcent.idea.plugin.api.export.markdown.Writer.kt 文件 282 行遗漏掉了

**Comment by tangcent** [comment]
Yes! 你有在修复它吗?

**Comment by texousliu** [comment]
提交了一个 PR，但是不知道你的开发分支是什么。所以直接提到 master 了

**Comment by tangcent** [comment]
close by #726
