### ISSUE TITLE
[Feature] Markdown导出添加全局 TOC 标签的配置

### ISSUE THREAD

**Issue by texousliu** [tangcent/easy-yapi#727]
## 需求来源：
- 想要实现 markdown [TOC] 目录导出：如下
![image](https://user-images.githubusercontent.com/27934702/160221290-1862bf71-76ec-4ad3-832f-3e6b167dcb4a.png)

## 临时兼容：
- 通过配置文件方式：如下图
![image](https://user-images.githubusercontent.com/27934702/160221335-1211df9a-c89c-4acb-9cc1-25765207e43f.png)

## 结果
- 配置里面能不能提供自定义属性就像 `md.toc=false` 这样的配置来开启或关闭 toc 支持

**Comment by tangcent** [comment]
https://github.com/tangcent/easy-yapi/blob/384263969a57bac5cc3d2d78c3cf5f776b9fa04d/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/markdown/MarkdownFormatter.kt#L78-L82

通过`md.header`可以配置:
```
md.header=[TOC]
```

**Comment by texousliu** [comment]
我看好像是昨天提交的特性？啥时候有计划发布呢？

**Comment by texousliu** [comment]
昨天为了修复导出body的问题，我在本地构建了插件。等你发布后我要替换回来

**Comment by tangcent** [comment]
> 我看好像是昨天提交的特性？啥时候有计划发布呢？

明天抽空发

**Comment by texousliu** [comment]
ok
