### ISSUE TITLE
[Feature] 导出 Markdown 全局变量配置支持

### ISSUE THREAD

**Issue by texousliu** [tangcent/easy-yapi#728]
## 需求来源：
- 比如 spring boot 项目想要实现全局 context-path
![image](https://user-images.githubusercontent.com/27934702/160221531-d20f926e-7ced-45e9-8a27-fa0dace45fa8.png)

## 临时兼容：
- 通过配置文件方式：如下图
![image](https://user-images.githubusercontent.com/27934702/160221575-2fb47ed9-fdcc-49cc-8281-32d78751cfab.png)

## 结果
- 配置里面能不能提供全局自定义属性，然后在需要使用的地方获取（这样我就可以把公共变量提取到配置文件头部，在不同项目中灵活配置）：如下图
![image](https://user-images.githubusercontent.com/27934702/160222117-2bf6a069-c040-4cd3-a2f8-84047171b65a.png)

**Comment by tangcent** [comment]
http://easyyapi.com/setting/tools/config.html

试试:
```
md.basic.path=groovy:"**路径参数:** "+config.get("md.global.base-path")+doc.path
```

---

http://easyyapi.com/setting/rules/class_prefix_path.html
