### ISSUE TITLE
无法导出Dubbo 接口文档

### ISSUE THREAD

**Issue by wuyongCloud** [tangcent/easy-yapi#733]
按照提供的spring-demo: https://github.com/Earth-1610/spring-demo ,导出 Dubbo类型接口，没有任何反馈
![image](https://user-images.githubusercontent.com/41030862/160563218-9184adc8-387a-49fd-b542-15e9f0183da2.png)

**Comment by tangcent** [comment]
导出`dubbo`相关的文档还没更新。

你可以这么做:

取消勾选 <kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Support</kbd> > <kbd>methodDoc</kbd>
勾选 <kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Support</kbd> > <kbd>generic export</kbd>

在<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>BuiltinConfig</kbd>或者[本地文件](http://easyyapi.com/setting/local-file-config.html)引入配置:
```
properties.additional=https://raw.githubusercontent.com/tangcent/easy-yapi/master/third/dubbo.config
```
如果配置不满足预期，复制并修改[dubbo.config](https://raw.githubusercontent.com/tangcent/easy-yapi/master/third/dubbo.config)的内容放在配置里，替换掉上面的引入配置,
