### ISSUE TITLE
[Bug] controller类很多时 export api 操作 idea直接卡死了

### ISSUE THREAD

**Issue by QiHong20** [tangcent/easy-yapi#736]

**Comment by tangcent** [comment]
hello, 跟着`BUG`提交页面的提示操作:
https://github.com/tangcent/easy-yapi/issues/new?assignees=&labels=type%3A+bug&template=bug_report.md&title=%5BBug%5D+Xxx

---

https://github.com/tangcent/easy-yapi/issues/634
