### ISSUE TITLE
导出yapi或者postman时，如何解析controller实现的接口类上的@RequestMapping

### ISSUE THREAD

**Issue by oversuperman** [tangcent/easy-yapi#737]
@RequestMapping("/test")
public interface A{
    @GetMapping("/test1")
    public String test1();
}

@RestController
public class B implements A{
    @Override
    public String test1(){ reutrn "ok";}

    @GetMapping("/test2")
    public String test2(){ reutrn "ok";}
}

在B操作导出yapi或postman
期望：两个接口路径分别是/test/test1和/test/test2
实际：无法识别到/test,生成的是/test1和/test2

**Comment by tangcent** [comment]
插件目前未处理所实现的接口类上的`RequestMapping`
由于[class](http://easyyapi.com/setting/tools/it.html)未提供获取`implements`, 所以也没办法通过目前提供的规则来到达此目的。

---

在此问题被修复之前，你可以采取如下配置:
```properties
class.prefix.path=#path
```
然后在`controller`上注释:
```java
/**
 * @path /test
 */
@RestController
public class B implements A {
         ...
}
```

---

todo list:

- [ ] [class](http://easyyapi.com/setting/tools/it.html)提供`implements`
- [ ] 当`controller`上没有`RequestMapping`时尝试获取所实现的接口类上的`RequestMapping`
