### ISSUE TITLE
api.tag的使用疑问

### ISSUE THREAD

**Issue by qinkangdeid** [tangcent/easy-yapi#74]
## use  version
yapi version：`1.8.5`
easy-yapi version：`easy-yapi.1.2.1.183.0.4`

![image](https://user-images.githubusercontent.com/17582522/68279806-2c41ad80-00af-11ea-92b9-07058c674926.png)
我看到配置示例是这样配置的

```bash
#yapi tag
api.tag=groovy:it.hasDoc("public")?"public":null
```
处理这个tag的写法的在接口上增加`@public`注解

我也照着写法写了一个
```bash
#yapi tag
api.tag=groovy:it.hasDoc("201911")?"201911":null
```
导出到yapi后，在yapi界面上无法按照tag进行filter
![image](https://user-images.githubusercontent.com/17582522/68280163-f5b86280-00af-11ea-8fca-e6366f08249e.png)

注释的tag是没创建在yapi标签库里的吗？

**Comment by tangcent** [comment]
> 注释的tag是没创建在yapi标签库里的吗？

- 是的，因为yapi的开放API接口中没有增加tag的API。
所以能打tag，但是需要筛选的话，需要手动去yapi的项目设置里加上.
---
另外:

- <kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd>
这里现在可以选择内置的推荐配置了
![image](https://user-images.githubusercontent.com/17569144/68282258-4fbb2700-00b4-11ea-9c75-e0581144a7a2.png)
---
```
#yapi tag
api.tag=groovy:it.hasDoc("201911")?"201911":null

```
可以简写成
```
api.tag[#201911]=201911
```

**Comment by qinkangdeid** [comment]
> > 注释的tag是没创建在yapi标签库里的吗？
> 
> * 是的，因为yapi的开放API接口中没有增加tag的API。
>   所以能打tag，但是需要筛选的话，需要手动去yapi的项目设置里加上.
> 
> 另外:
> 
> * Preferences(Settings) > Other Settings > EasyApi
>   这里现在可以选择内置的推荐配置了
>   ![image](https://user-images.githubusercontent.com/17569144/68282258-4fbb2700-00b4-11ea-9c75-e0581144a7a2.png)
> 
> ```
> #yapi tag
> api.tag=groovy:it.hasDoc("201911")?"201911":null
> ```
> 
> 可以简写成
> 
> ```
> api.tag[#201911]=201911
> ```

好的 明白了 代码标记的标签和yapi创建的标签名一致目前算是暂时解决了

**Comment by qinkangdeid** [comment]
IDEA UI 的recommend 是最新的版本吗？ easy-yapi.1.2.1.183.0.4.jar 这个还没这个UI

**Comment by tangcent** [comment]
对,在审核，要明天或者后天才能在[Jetbrains](https://plugins.jetbrains.com/plugin/12458-easyyapi)里搜到,现在只能在[releases](https://github.com/tangcent/easy-yapi/releases) 里下

**Comment by tangcent** [comment]
你现在找不到这个UI吗：
![image](https://user-images.githubusercontent.com/17569144/68292576-21931280-00c7-11ea-9761-0dfdd042c596.png)

---
是尝试的这个?[easy-yapi.1.2.1.183.0.4.jar](https://github.com/tangcent/easy-yapi/releases/download/v1.2.1.4/easy-yapi.1.2.1.183.0.4.jar)

**Comment by qinkangdeid** [comment]
> 你现在找不到这个UI吗：
> ![image](https://user-images.githubusercontent.com/17569144/68292576-21931280-00c7-11ea-9761-0dfdd042c596.png)
> 
> 是尝试的这个?[easy-yapi.1.2.1.183.0.4.jar](https://github.com/tangcent/easy-yapi/releases/download/v1.2.1.4/easy-yapi.1.2.1.183.0.4.jar)

重新下 清除缓存 现在有了 🙏
