### ISSUE TITLE
[Bug]新版本 概率 controller 生成卡死

### ISSUE THREAD

**Issue by zhuangjiaju** [tangcent/easy-yapi#742]
**Describe the bug**

![image](https://user-images.githubusercontent.com/18475586/163301837-422ba5c2-5d65-43dd-8696-00247830a199.png)

点个  controller  然后快捷键生成 有概率就卡死了， 不打开 controller  直接点

**To Reproduce**

Detailed Steps to reproduce the behavior:

1. Open '...'
3. See error
   
**Expected behavior**

**Screenshots**

**Logs**

1. Add config:
   
   ```properties
   http.call.before=groovy:logger.info("call:"+request.url())
   http.call.after=groovy:logger.info("response:"+response.string())
   api.class.parse.before=groovy:logger.info("[api] before parse class:"+it)
   api.class.parse.after=groovy:logger.info("[api] after parse class:"+it)
   api.method.parse.before=groovy:logger.info("[api] before parse method:"+it)
   api.method.parse.after=groovy:logger.info("[api] after parse method:"+it)
   api.param.parse.before=groovy:logger.info("[api] before parse param:"+it)
   api.param.parse.after=groovy:logger.info("[api] after parse param:"+it)
   json.class.parse.before=groovy:logger.info("[json] before parse class:"+it)
   json.class.parse.after=groovy:logger.info("[json] after parse class:"+it)
   json.method.parse.before=groovy:logger.info("[json] before parse method:"+it)
   json.method.parse.after=groovy:logger.info("[json] after parse method:"+it)
   json.field.parse.before=groovy:logger.info("[json] before parse field:"+it)
   json.field.parse.after=groovy:logger.info("[json] after parse field:"+it)
   ```

2. Console output `easy_api`
   - Please set <kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd> Common</kbd> > <kbd>log</kbd> to `LOW```
   
3. Logs of IDEA: <br>
   The easiest way to find the product log file is the Help menu, the item name would depend on the IDE version and OS:- Show Log in Explorer
   - Show Log in Finder
   - Show Log in Konqueror/Nautilus
   - Reveal Log in Explorer
   - Reveal Log in Finder/Finder/Nautilus

**Environment (please complete the following information):**
 - OS: [MAC]
 - IDEA version [2022.3.3]
 - Plugin version [2.3.5.191.0]
**Demo Code**

1. Fork https://github.com/Earth-1610/spring-demo
2. Write some code to reproduce this error
3. Now paste the forked repository hear: https://github.com/xxxx/spring-demo

**CheckList**

   - [ ] <kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd> Intelligent</kbd> > <kbd>enable infer</kbd>

**Additional context**

**Comment by zhuangjiaju** [comment]
卡着完全不动了 也不去生成 只能强行close

**Comment by tangcent** [comment]
偶尔有人反馈，但我没法重现，一直定位不到原因。
你能不能通过日志定位到这个问题产生的原因?
