### ISSUE TITLE
[Question]json.rule.convert使用

### ISSUE THREAD

**Issue by 410656275** [tangcent/easy-yapi#746]
通过json.rule.convert做类型转换的时候
使用json.rule.convert[java.lang.Long]=java.lang.String配置的时候可以把对应的long类型转到string类型

但是把配置换成json.rule.convert[groovy:it.contextType()=="field"&&it.type().name()=="java.lang.Long"]=java.lang.String时候执行export yapi时候没有生效

不知道这样设置还有其他要注意的地方么？
我试了好几种json.rule.convert[groovy:]只要filter里面用的groovy函数就没办法起效果

**Comment by tangcent** [comment]
json.rule.convert上下文对象是`class`, 所以
`json.rule.convert[java.lang.Long]=java.lang.String`对应的写法是
`json.rule.convert[groovy:it.name()=="java.lang.Long"]=java.lang.String`


---

https://github.com/Earth-1610/intellij-kotlin/blob/a87d071e72c88117f526f6c63de0682ffd913218/intellij-idea/src/main/kotlin/com/itangcent/intellij/psi/DefaultClassRuleConfig.kt#L32-L60
