### ISSUE TITLE
@PostMapping标记的get请求 @RequestBody标记的json参数上传结果为空

### ISSUE THREAD

**Issue by dev-sxl** [tangcent/easy-yapi#748]
@PostMapping标记的get请求接口 @RequestBody标记的json参数上传结果为空，
get请求的json参数无法上传

**Comment by tangcent** [comment]
> @PostMapping标记的get请求

这是指什么?

**Comment by dev-sxl** [comment]
> 

不好意思是@GetMapping哈

**Comment by tangcent** [comment]
- `yapi`不支持
- `postman`自己编辑时可以，但是通过`api`更新似乎不行, 因为没这方面的需求，所以没有深究
