### ISSUE TITLE
[Feature] 希望添加JAX-RS支持

### ISSUE THREAD

**Issue by VictorChow** [tangcent/easy-yapi#749]
目前支持Spring、Feign、Quarks，希望能增加对JAX-RS注解的支持，例如`@GET`、`@PUT`、`@POST`、`@DELETE`等。

**Comment by tangcent** [comment]
我看了一下，`Quarks`的实现似乎已经包含了`JAX-RS`

**Comment by VictorChow** [comment]
我测试一下看看😁
