### ISSUE TITLE
[Bug] 无参数枚举无法识别

### ISSUE THREAD

**Issue by noootime** [tangcent/easy-yapi#750]
**无参数枚举无法识别**

idea版本：IntelliJ IDEA 2021.1.3 (Ultimate Edition)  Build #IU-211.7628.21, built on June 30, 2021
easy-yapi版本：2.3.6.191.0

枚举类：
```
public enum SearchMode {
    // A查询
    A,
    // B查询
    B,
    // C查询
    C;
}
```
属性：
```
    /**
     * 搜索模式 {@link SearchMode}  
     * @see SearchMode 这个也不行
     */
    private SearchMode searchMode
```
提交到yapi后，该字段类型为string，没有出现枚举值。

我看了所有关于枚举的问题，貌似大家的枚举都是至少有一个参数的，我的这种没有参数的情况，无法被yapi识别。

且，我尝试了把我的枚举类改为：
```
public enum SearchMode {
    // A查询
    A(0),
    // B查询
    B(1),
    // C查询
    C(2);

    private int value;
    SearchMode(int value) {
        this.value = value;
    }
}
```
这样是ok的，但是我的场景其实并不需要这个value，麻烦帮忙看一下吧，感激不尽！

**Comment by tangcent** [comment]
没考虑到这种情况

**Comment by tangcent** [comment]
这个bug在Earth-1610/intellij-kotlin#159 修复:

[easy-yapi-2.3.6.191.0.zip](https://github.com/tangcent/easy-yapi/files/8549835/easy-yapi-2.3.6.191.0.zip)
