### ISSUE TITLE
.easy.api.config 配置无线

### ISSUE THREAD

**Issue by zhangle910522** [tangcent/easy-yapi#758]
我在当前项目根目录添加了  .easy.api.config 文件用于覆盖 idea settings中的配置 但是不生效

.easy.api.config 内容：
yapi.server=http://yapi.smart-xwork.cn/

exporter api 日志：
run easy-yapi
[INFO]	Start find apis...
[TRACE]	find config file:G:\workspace\training\zhangle\youlai-mall\youlai-admin\admin-boot\.easy.api.config
[TRACE]	find config file:G:\workspace\training\zhangle\youlai-mall\youlai-admin\.easy.api.config
[TRACE]	find config file:G:\workspace\training\zhangle\youlai-mall\.easy.api.config
[INFO]	use recommend config
[INFO]	search api from:com.youlai.admin.controller.SysDeptController
[ERROR]	request http://14.29.108.71:10930/api/project/get?token=4277276fd46558332e6e2ca1e0caa871e416d70a326835d69449343e883f66ae failed
[TRACE]	org.apache.http.conn.ConnectTimeoutException: Connect to 14.29.108.71:10930 [/14.29.108.71] failed: connect timed out

14.29.108.71:10930 为 idea setting的配置  为啥请求的不是  http://yapi.smart-xwork.cn/ 地址

**Comment by tangcent** [comment]
> [TRACE] find config file:G:\workspace\training\zhangle\youlai-mall\youlai-admin\admin-boot.easy.api.config
> [TRACE] find config file:G:\workspace\training\zhangle\youlai-mall\youlai-admin.easy.api.config
> [TRACE] find config file:G:\workspace\training\zhangle\youlai-mall.easy.api.config

<img width="767" alt="image" src="https://user-images.githubusercontent.com/17569144/167231156-f15f7182-bb13-46ac-bec0-24b504d08ffa.png">
<img width="885" alt="image" src="https://user-images.githubusercontent.com/17569144/167231132-f5130bff-f770-4c20-96ec-ec76e18dc841.png">
<img width="767" alt="image" src="https://user-images.githubusercontent.com/17569144/167231198-fad60273-a51e-4cee-a197-ba421b3be199.png">

我测试正常，我看你这里使用了多个配置文件，你可以在配置中加上以下配置试试:
``````
yapi.export.before=groovy:```
    logger.info("yapi.server:"+config.getValues("yapi.server"))
```
``````

**Comment by zhangle910522** [comment]
添加之后日志是正常的 yapi.server:[http://yapi.smart-xwork.cn/]

run easy-yapi
[INFO]	Start find apis...
[TRACE]	find config file:G:\workspace\training\zhangle\youlai-mall\youlai-admin\admin-boot\.easy.api.config
[TRACE]	find config file:G:\workspace\training\zhangle\youlai-mall\youlai-admin\.easy.api.config
[TRACE]	find config file:G:\workspace\training\zhangle\youlai-mall\.easy.api.config
[INFO]	use recommend config
[INFO]	search api from:com.youlai.admin.controller.SysDeptController
[INFO]	yapi.server:[http://yapi.smart-xwork.cn/]
[ERROR]	request http://14.29.108.71:10930/api/project/get?token=4277276fd46558332e6e2ca1e0caa871e416d70a326835d69449343e883f66ae failed
[TRACE]	org.apache.http.conn.ConnectTimeoutException: Connect to 14.29.108.71:10930 [/14.29.108.71] failed: connect timed out

**Comment by zhangle910522** [comment]
安装最新版可以了  感谢
