### ISSUE TITLE
接口方法上有自定义注解的参数 如何过滤掉 不作为接口的参数出现在文档中

### ISSUE THREAD

**Issue by qinkangdeid** [tangcent/easy-yapi#76]
哈哈 大佬 我又来了 🙏

## 软件版本：
IDEA：2019.2.4
yapi：easy-yapi.1.2.1.183.0.4.jar
## 情况描述
我在项目里对于用户信息的提取与装配使用了实现`HandlerMethodArgumentResolver`做了个参数解析器，在接口上标注了特定注解的时候触发 如下：
- 参数解析器
```java
/**
 * 登录用户信息处理Resolver
 *
 * @author qinkangdeid
 * @date 2019-10-29
 */
public class LoginUserArgumentResolver implements HandlerMethodArgumentResolver {


    @Override
    public boolean supportsParameter(MethodParameter parameter) {
// 这里断言成功执行resolveArgument
 boolean hasUserContextAnoo = parameter.hasParameterAnnotation(UserContext.class);
        return hasUserContextAnoo;
    }

    @Override
    public UserContent resolveArgument(MethodParameter parameter, ModelAndViewContainer container, NativeWebRequest request, WebDataBinderFactory factory) {
// 具体装配逻辑
        return new UserContent(1);
    }
}
```
- 标记注解
```java
@Target(ElementType.PARAMETER)
@Retention(RetentionPolicy.RUNTIME)
public @interface UserContext {

}
```

- 接口写法就是这样的
```java
    /**
     * 忽略自定义注解参数
     * //     * @param userDtoWithEnum 用户Dto与枚举
     *
//     * @param userContent 用户内容（并不想让他出现在文档请求参数中）
     * @return {@link com.itangcent.common.dto.IResult}
     */
    @PostMapping("")
    public IResult testParamsWithCustomAnno(@UserContext UserContent userContent) {
        return Result.success("ok");
    }
```
那么其实 我的接口对前端来说是没有参数的  所以我想把带有`@UserContext `注解的参数过滤掉 
我像之前忽略返回响应的写法配置了 好像没生效
```bash
# 过滤接口自定义参数
json.rule.field.ignore=groovy:it.type().name()=="com.itangcent.springboot.demo.UserContent"

json.rule.field.ignore=groovy:it.hasAnn("com.itangcent.springboot.demo.UserContext")
```
它还是会把接口上`UserContent`的内容提取出来
![image](https://user-images.githubusercontent.com/17582522/68451526-16a4c300-022a-11ea-8b9e-4c82ed6925e4.png)
应该怎样配置这个接口请求参数的忽略设定？
我发了一个pull request 里面有实例代码 在spring-demo上

可能还有另外一个问题 使用jwt对接口做鉴权返回得到一个token  把token放请求`header`里 类似于上面的操作 额外在另外的地方对token做解析 那么header的值也是不会写在接口方法上使用`@RequestHeader`，但是确实要请求接口时要header带上token 这个情况

**Comment by tangcent** [comment]
wow~目前的配置项没有覆盖到这个情况
---

考虑将`ignore`这个规则范围扩大到适用于忽略参数`param`?
还是另加一个规则`param.ignore`合适?

---
另外可以直接PR到[Earth-1610/spring-demo](https://github.com/Earth-1610/spring-demo)哦

**Comment by qinkangdeid** [comment]
> ## wow~目前的配置项没有覆盖到这个情况
> 考虑将`ignore`这个规则范围扩大到适用于忽略参数`param`?
> 还是另加一个规则`param.ignore`合适?
> 
> 另外可以直接PR到[Earth-1610/spring-demo](https://github.com/Earth-1610/spring-demo)哦

另加一个规则是会清晰些  接口只有出参和入参两个 最多也两个`ignore`配置 ` param.ignore`这样直观些呢

**Comment by tangcent** [comment]
see https://github.com/Earth-1610/spring-demo/blob/0868595be18ceb16ff0e21ac2990c92e9859afd2/cn/.easy.api.config#L111-L114

**Comment by tangcent** [comment]
[easy-yapi.1.2.1.183.0.4.jar.zip](https://github.com/tangcent/easy-yapi/files/3824721/easy-yapi.1.2.1.183.0.4.jar.zip)

**Comment by qinkangdeid** [comment]
> [easy-yapi.1.2.1.183.0.4.jar.zip](https://github.com/tangcent/easy-yapi/files/3824721/easy-yapi.1.2.1.183.0.4.jar.zip)

awesome~ 参数过滤解决了～  

是否支持 全局设置header值？ 这样理解:一个header里的值（例如token） 是所有需要鉴权的接口的隐藏参数 只是在接口上是不放@RequestHeader 不写出来   这个header值是在参数传递解析阶段判断是否存在的  类似的
在`com.itangcent.springboot.demo.LoginUserArgumentResolver#resolveArgument` 去校验
```java
  /**
     * 所有需鉴权统一校验鉴权header值
     *
     * @param parameter 参数
     * @param container 容器
     * @param request   请求
     * @param factory   factory
     * @return {@link com.itangcent.springboot.demo.UserContent}
     */
    @Override
    public UserContent resolveArgument(MethodParameter parameter, ModelAndViewContainer container, NativeWebRequest request, WebDataBinderFactory factory) {
        // 在Resolver进行必传header的校验 或 在拦截器校验 这种情况在接口上是不放@RequestHeader的
        // 等于是header里的token是所有需要鉴权的接口的隐藏参数
        String token = request.getHeader("Token");
        if (StringUtils.isEmpty(token)) {
            throw new RuntimeException("token is empty! you should set the token in the http header");
        }
        // 组装UserContent UseCache.getByToken(token)
        return new UserContent(1);
    }

```
这个是否可以放在配置里，类似：
```bash
# 全局请求配置
global.config.headers=[{"headerName1":"headerComment1","headerName2":"headerComment2"}]
```
创建接口到yapi时增加上这个隐藏参数？emm.... 不过获取鉴权的接口 也会被加上了token

**Comment by tangcent** [comment]
能理解，但是需要好好考虑一下通用性.
最好是把规则与API关联起来，从而可以使用API相关信息进行筛选(如排除开放接口)
比如:
```
method.additional.header={name: "",value: "",desc: "",required:false, example:""}
method.additional.param={name: "",value: "",desc: "",required:false}
```

---
如:获取鉴权的API方法为
```
public Result getToken() {
       ...
}
```
可以这样设置
```
method.additional.header[groovy:it.name()!=="getToken"]={name: "token",value: "",desc: "鉴权token",required:true, example:""}
```

--- 
考虑另起一个issue
