### ISSUE TITLE
[Bug]导出 markdown Java 的 validation 失效

### ISSUE THREAD

**Issue by heshangcode** [tangcent/easy-yapi#761]
也打开了 validation 的配置
<img width="611" alt="image" src="https://user-images.githubusercontent.com/39662806/168423827-d899b5bd-90d0-44b5-ae28-f043d14f4107.png">
@NotNull （导入的包对的）失效，导入markdown 失效
重试配置了config，但是报错：
[ERROR]	failed fetch:[https://raw.githubusercontent.com/tangcent/easy-yapi/master/third/javax.validation.config]
换成 gitee 上面的也不行，报错。
重试吧远程的配置放在本地，路径指向本地机器，不报错，但是还是没有出现@NotNull 的效果

**Comment by tangcent** [comment]
> [ERROR] failed fetch:[https://raw.githubusercontent.com/tangcent/easy-yapi/master/third/javax.validation.config]
换成 gitee 上面的也不行，报错。

网络不通畅可以尝试修改<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Http</kbd> 的`timeOut`

---

1. 确认一下使用的是`javax.validation.constraints.NotNull`
2. 尝试导出: https://github.com/Earth-1610/web-demo/blob/master/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/UserCtrl.java

看看`age`是否为必须:

| 名称 | 值 | 必须 | 备注 |
| ------------ | ------------ | ------------ | ------------ |
| age | 0 | 是 | 年龄 |

**Comment by heshangcode** [comment]
> > [ERROR] failed fetch:[https://raw.githubusercontent.com/tangcent/easy-yapi/master/third/javax.validation.config]
> > 换成 gitee 上面的也不行，报错。
> 
> 网络不通畅可以尝试修改Preferences(Settings) > Other Settings > EasyApi > Http 的`timeOut`
> 
> 1. 确认一下使用的是`javax.validation.constraints.NotNull`
> 2. 尝试导出: https://github.com/Earth-1610/web-demo/blob/master/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/UserCtrl.java
> 
> 看看`age`是否为必须:
> 
> 名称	值	必须	备注
> age	0	是	年龄

经过我的实测，如果在入参写上@RequestBody，导出来的入参就没有是否必须这一列。
<img width="701" alt="image" src="https://user-images.githubusercontent.com/39662806/168513274-98515452-af4e-4853-9ebe-ea10a88a242d.png">

**Comment by tangcent** [comment]
> 经过我的实测，如果在入参写上@requestbody，导出来的入参就没有是否必须这一列。

这里选的是哪种模式?
<img width="631" alt="image" src="https://user-images.githubusercontent.com/17569144/168514961-4b822efe-a768-45fb-aa2d-cf39c8f0cd00.png">

**Comment by heshangcode** [comment]
> > 经过我的实测，如果在入参写上@requestbody，导出来的入参就没有是否必须这一列。
> 
> 这里选的是哪种模式? <img alt="image" width="631" src="https://user-images.githubusercontent.com/17569144/168514961-4b822efe-a768-45fb-aa2d-cf39c8f0cd00.png">

用你图上的模式，修改之后，成功了，蟹蟹~

**Comment by tangcent** [comment]
:)
