### ISSUE TITLE
[Help] 接口使用数组输出到Yapi显示错误

### ISSUE THREAD

**Issue by abhty822** [tangcent/easy-yapi#763]
例如，
Java代码如下
`private List<String> applicationNameList;`
输出到Yapi的json如下
`{
...
name:"applicationNameList[0]"
...
}`

**Comment by tangcent** [comment]
> 例如，
> Java代码如下
> `private List<String> applicationNameList;`
> 输出到Yapi的json如下
> `{ ... name:"applicationNameList[0]" ... }`

你是指`Body`，`Form`还是`Query`?

**Comment by abhty822** [comment]
> 

请求参数 -- Query

get请求 controller 代码里使用了 @ModelAttribute注解 来接受请求参数

**Comment by tangcent** [comment]
默认是会展开`Query`和`Form`的，比如复杂子对象可能会处理为`?a.b.c=` / `?a[0].b.c[0]=`
如果不希望展开，可以在<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Intelligent</kbd> 中取消勾选`expanded form`和`expanded query`

**Comment by abhty822** [comment]
> 默认是会展开`Query`和`Form`的，比如复杂子对象可能会处理为`?a.b.c=` / `?a[0].b.c[0]=` 如果不希望展开，可以在Preferences(Settings) > Other Settings > EasyApi > Intelligent 中取消勾选`expanded form`和`expanded query`

3Q～ 有帮助
