### ISSUE TITLE
[Question] 生产Yapi时如何切换成表格样式的

### ISSUE THREAD

**Issue by zhangjunyong8888888** [tangcent/easy-yapi#767]
**Describe the question**

生产Yapi时如何切换成表格样式的

**Expected result**

![image](https://user-images.githubusercontent.com/44471442/169798992-99ba586d-a55d-4d90-99fb-0ce1f19788e9.png)

想生成下边这样需要怎么配置
![image](https://user-images.githubusercontent.com/44471442/169799080-552915ff-4500-4fa4-b487-70732b35f362.png)

**Comment by zhangjunyong8888888** [comment]
json-schema   模式

**Comment by tangcent** [comment]
<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Yapi</kbd> 中的`use json5`

**Comment by zhangjunyong8888888** [comment]
谢谢
