### ISSUE TITLE
子类对父类字段的注解校验需要怎么实现

### ISSUE THREAD

**Issue by xaiowei** [tangcent/easy-yapi#769]
子类对父类字段NotNull 的注解校验需要怎么实现     Override 了父类的get 方法  使用easyyapi 上传不生效 还是现实父类的字段约束

**Comment by tangcent** [comment]
`Override 了父类的get 方法` 这种写法似乎不是很优雅。
如果只是为了导出文档的需要的话，可以尝试使用注释:

1. 在子类上添加注释:
```java
/**
 * @required field1,field2,field3
 */
public class XxxXxx extends Xxx {
      ...
}
```

2. 在项目中增加如下配置:
``````properties
field.required=groovy:it.containingClass().doc("required")?.split(",")?.contains(it.name())
``````

---

如果一定要实现`Override父类的get方法+注解NotNull `的话也可以写对应的配置来处理。

**Comment by xaiowei** [comment]
谢谢! 目前是想使用注解 NotNull 配合代码里注解校验 直接生成接口文档 .子类对父类的字段增加扩展校验 只能是重写方法增加对应注解 还有其他优雅的写法吗? 有交流群吗方便交流
