### ISSUE TITLE
[Question] 每次在mac上使用快捷键control+e都会卡在search api

### ISSUE THREAD

**Issue by ihoment-wangtaiping** [tangcent/easy-yapi#774]
**mac下使用快捷键时会卡住**

**Demo Code**

run easy-yapi
[INFO]	Start find apis...
[TRACE]	find config file:./backend/.easy.api.config
[DEBUG]	use recommend config
[INFO]	search api from: com.ihoment.controller.FulfillmentOutBoundController

**Comment by tangcent** [comment]
提供一下信息: https://github.com/tangcent/easy-yapi/issues/new?assignees=&labels=type%3A+bug&template=bug_report.md&title=%5BBug%5D+Xxx
