### ISSUE TITLE
[Question] 怎样返回自定义格式数据呢？在YAPI上。

### ISSUE THREAD

**Issue by dawson-ao** [tangcent/easy-yapi#777]
**Describe the question**

例如我的接口返回的是一个Result的Map类，在YAPI上只能显示KEY，但是我想在YAPI的返回数据显示返回的所有数据结构，怎样搞呢？

**Expected result**

如果接口返回的是一个MAP类，无法显示返回相关数据。

**Comment by tangcent** [comment]
你这里的`相关数据`是什么样的呢? 具体的某个类吗?

**Comment by dawson-ao** [comment]
> 你这里的`相关数据`是什么样的呢? 具体的某个类吗?

你好！原来我返回的不是泛型，现在改为泛型是可以的了，谢谢！
