### ISSUE TITLE
[Question] 针对参数使用Mybatis-plus下的Page实体导出参数过多的问题

### ISSUE THREAD

**Issue by hanhuafeng** [tangcent/easy-yapi#778]
**get请求下，使用Mybatis-plus下的Page作为实体接受，导出文档中参数过多的问题**

有时候写get请求，会直接用Mybatis-plus中的实体类Page作为参数接收的实体，但是导出的接口文档中，会出现好多没有任何作用的参数，例如我只使用了current和size两个参数，但是导出的文档包含了各种无效参数
<img width="553" alt="image" src="https://user-images.githubusercontent.com/40729245/171542805-7168e5d4-a715-44ff-9c96-a7cc5020406e.png">

有没有方法能设置这个类只上传current、size这两个参数到接口文档，最好是能指定到这个类，不影响其他的类

**Comment by tangcent** [comment]
只保留指定类的部分字段, 配置类似这样:
```properties
field.ignore=groovy:it.defineClass().name() == "com.itangcent.common.model.UserInfo" && !["current","size"].contains(it.name())
```

**Comment by ztrue-zn** [comment]
> 只保留指定类的部分字段, 配置类似这样:
> 
> ```ini
> field.ignore=groovy:it.defineClass().name() == "com.itangcent.common.model.UserInfo" && !["current","size"].contains(it.name())
> ```

请问如果我要将 com.baomidou.mybatisplus.extension.plugins.pagination.Page 中的 records 成员，重命名成 “data”，由于Page是Mybatis-Plus提供的，我无法对其源码进行改动。有什么优雅方式重命名吗

**Comment by tangcent** [comment]
> > 只保留指定类的部分字段, 配置类似这样:
> > ```ini
> > field.ignore=groovy:it.defineClass().name() == "com.itangcent.common.model.UserInfo" && !["current","size"].contains(it.name())
> > ```
> 
> 请问如果我要将 com.baomidou.mybatisplus.extension.plugins.pagination.Page 中的 records 成员，重命名成 “data”，由于Page是Mybatis-Plus提供的，我无法对其源码进行改动。有什么优雅方式重命名吗

你是问插件怎么配置?

1. 简单配置为:
```properties
field.name[com.baomidou.mybatisplus.extension.plugins.pagination.Page#records]= data
```
2. 也可以配置为:
``````properties
field.name=groovy:(it.defineClass().name() == "com.baomidou.mybatisplus.extension.plugins.pagination.Page"&&it.name()=="records")?"data":null
``````

**Comment by ztrue-zn** [comment]
> > > 只保留指定类的部分字段, 配置类似这样:
> > > ```ini
> > > field.ignore=groovy:it.defineClass().name() == "com.itangcent.common.model.UserInfo" && !["current","size"].contains(it.name())
> > > ```
> > 
> > 
> > 请问如果我要将 com.baomidou.mybatisplus.extension.plugins.pagination.Page 中的 records 成员，重命名成 “data”，由于Page是Mybatis-Plus提供的，我无法对其源码进行改动。有什么优雅方式重命名吗
> 
> 你是问插件怎么配置?
> 
> 1. 简单配置为:
> 
> ```ini
> field.name[com.baomidou.mybatisplus.extension.plugins.pagination.Page#records]= data
> ```
> 
> 2. 也可以配置为:
> 
> ```ini
> field.name=groovy:(it.defineClass().name() == "com.baomidou.mybatisplus.extension.plugins.pagination.Page"&&it.name()=="records")?"data":null
> ```

感谢回复，配置上去后确实有效。希望可以添加到接口文档 `field.name` 的用法中    
   

另外，在由于我在使用 Mybatis-plus Page 的时候，Page 既充当请求参数，又充当返回参数。  
当Page为请求参数时，它的 records 字段我是需要屏蔽的。但是返回时，records我又是需要保留的。  
请问有办法解决吗？

**Comment by ztrue-zn** [comment]
> 你是问插件怎么配置?
> 
> 1. 简单配置为:
> 
> ```ini
> field.name[com.baomidou.mybatisplus.extension.plugins.pagination.Page#records]= data
> ```
> 
> 2. 也可以配置为:
> 
> ```ini
> field.name=groovy:(it.defineClass().name() == "com.baomidou.mybatisplus.extension.plugins.pagination.Page"&&it.name()=="records")?"data":null
> ```

感谢回复，配置上去后确实有效。希望可以添加到接口文档 `field.name` 的用法中    
   

另外，在由于我在使用 Mybatis-plus Page 的时候，Page 既充当请求参数，又充当返回参数。  
当Page为请求参数时，它的 records 字段我是需要屏蔽的。但是返回时，records我又是需要保留的。  
请问有办法解决吗？

**Comment by tangcent** [comment]
有，但是配置比较麻烦，大概是这个样子:
```
json.cache.disable=true
api.param.parse.before=groovy:session.set("isParam",true)
api.param.parse.after=groovy:session.remove("isParam")
json.rule.field.ignore[com.baomidou.mybatisplus.extension.plugins.pagination.Page#records]=groovy:session.get("isParam")
```

---

不过我一般不这么配，直接在字段上注释`请求时不需要传`.
像你这种情况就配置:`field.doc[com.baomidou.mybatisplus.extension.plugins.pagination.Page#records]=请求时不需要传`

**Comment by junpengzhou** [comment]
> 有，但是配置比较麻烦，大概是这个样子:
> 
> ```
> json.cache.disable=true
> api.param.parse.before=groovy:session.set("isParam",true)
> api.param.parse.after=groovy:session.remove("isParam")
> json.rule.field.ignore[com.baomidou.mybatisplus.extension.plugins.pagination.Page#records]=groovy:session.get("isParam")
> ```
> 
> 不过我一般不这么配，直接在字段上注释`请求时不需要传`. 像你这种情况就配置:`field.doc[com.baomidou.mybatisplus.extension.plugins.pagination.Page#records]=请求时不需要传`

这个不对，按这样配置会把请求的field和响应的field也都一起销毁了，两边都没有

**Comment by tangcent** [comment]
> 这个不对，按这样配置会把请求的field和响应的field也都一起销毁了，两边都没有

@junpengzhou 没办法重现你说的情况, 我这样测试records出现在Response里，没有出现在Request里。

我配置了:
```properties

json.cache.disable=true
api.param.parse.before=groovy:session.set("isParam",true)
api.param.parse.after=groovy:session.remove("isParam")
json.rule.field.ignore[com.baomidou.mybatisplus.extension.plugins.pagination.Page#records]=groovy:session.get("isParam")
```

导出这个api:
```java
    @GetMapping("/testPage")
    public Page<Integer> testPage(Page<Integer> request) {
        return request;
    }
```

结果是:
## testPage

> BASIC

**Path:** /demo/test/testPage

**Method:** GET

> REQUEST

**Query:**

| name | value | required | desc |
| ------------ | ------------ | ------------ | ------------ |
| total |  | NO |  |
| size |  | NO |  |
| current |  | NO |  |
| orders[0].column |  | NO |  |
| orders[0].asc | NO | NO |  |
| optimizeCountSql | NO | NO |  |
| searchCount | NO | NO |  |
| optimizeJoinOfCountSql | NO | NO |  |
| maxLimit |  | NO |  |
| countId |  | NO |  |


> RESPONSE

**Headers:**

| name | value | required | desc |
| ------------ | ------------ | ------------ | ------------ |
| content-type | application/json;charset=UTF-8 | NO |  |

**Body:**

| name | type | desc |
| ------------ | ------------ | ------------ |
| records | array |  |
| &ensp;&ensp;&#124;─ | integer |  |
| total | integer |  |
| size | integer |  |
| current | integer |  |
| orders | array |  |
| &ensp;&ensp;&#124;─ | object |  |
| &ensp;&ensp;&ensp;&ensp;&#124;─column | string |  |
| &ensp;&ensp;&ensp;&ensp;&#124;─asc | boolean |  |
| optimizeCountSql | boolean |  |
| searchCount | boolean |  |
| optimizeJoinOfCountSql | boolean |  |
| maxLimit | integer |  |
| countId | string |  |
| pages | integer |  |

**Response Demo:**

```json
{
  "records": [
    0
  ],
  "total": 0,
  "size": 0,
  "current": 0,
  "orders": [
    {
      "column": "",
      "asc": false
    }
  ],
  "optimizeCountSql": false,
  "searchCount": false,
  "optimizeJoinOfCountSql": false,
  "maxLimit": 0,
  "countId": "",
  "pages": 0
}
```
