### ISSUE TITLE
是否考虑做接口项目的全局配置例如全局统一header全局统一api前缀

### ISSUE THREAD

**Issue by qinkangdeid** [tangcent/easy-yapi#78]
是否支持 全局设置header值？ 这样理解:一个header里的值（例如token） 是所有需要鉴权的接口的隐藏参数 只是在接口上是不放@RequestHeader 不写出来   这个header值是在参数传递解析阶段判断是否存在的  类似的
在`com.itangcent.springboot.demo.LoginUserArgumentResolver#resolveArgument` 去校验
```java
  /**
     * 所有需鉴权统一校验鉴权header值
     *
     * @param parameter 参数
     * @param container 容器
     * @param request   请求
     * @param factory   factory
     * @return {@link com.itangcent.springboot.demo.UserContent}
     */
    @Override
    public UserContent resolveArgument(MethodParameter parameter, ModelAndViewContainer container, NativeWebRequest request, WebDataBinderFactory factory) {
        // 在Resolver进行必传header的校验 或 在拦截器校验 这种情况在接口上是不放@RequestHeader的
        // 等于是header里的token是所有需要鉴权的接口的隐藏参数
        String token = request.getHeader("Token");
        if (StringUtils.isEmpty(token)) {
            throw new RuntimeException("token is empty! you should set the token in the http header");
        }
        // 组装UserContent UseCache.getByToken(token)
        return new UserContent(1);
    }

```
这个是否可以放在配置里，类似：
```bash
# 全局请求配置
global.config.headers=[{"headerName1":"headerComment1","headerName2":"headerComment2"}]
```
创建接口到yapi时增加上这个隐藏参数？emm.... 不过获取鉴权的接口 也会被加上了token

mvc 还有一个 `context-path`设置接口统一前缀的 在`application.yml`设置
```yaml
server:
  servlet:
    context-path: /api-prefix


```
配置后所有接口的都会带上这个前缀` /api-prefix` 类似controller的接口写的是`/users/info`,整个请求url就会变成`/api-prefix/users/info` 能配成全局配置的话加更好了 
如[#76 ](https://github.com/tangcent/easy-yapi/issues/76)最后表述

**Comment by tangcent** [comment]
考虑支持配置额外的header/param:
```
method.additional.header={name: "",value: "",desc: "",required:false, example:""}
method.additional.param={name: "",value: "",desc: "",required:false}
```
允许使用`filter`例如:

```
#未注解xxx.Public的方法都需要header中带有token
method.additional.header[!@xxx.Public]={name: "token",value: "",desc: "认证token",required:true, example:""}
```
---
考虑支持加载配置文件:
```
properties.additional=properties.path
```
并内置推荐配置:
```
properties.additional=~/src/main/resources/application.properties
properties.additional=~/src/main/resources/application.yml
```
---

考虑支持额外的path前缀:
```
#追加在Controller的basePath之前
class.path.prefix.=/api-prefix
```

- 最后API的path为
`class.prefixPath + class.basePath +  method.path`
---
深入解析spring相关配置
如内置推荐配置
```
class.prefix.path=${server.servlet.context-path}
```

---

针对多module的项目，如果一次操作涉及到多个module,针对每个module创建解析任务,分别独立加载配置,使得module内部配置只影响当前module

---

**Comment by qinkangdeid** [comment]
> 考虑支持配置额外的header/param:
> 
> ```
> method.additional.header={name: "",value: "",desc: "",required:false, example:""}
> method.additional.param={name: "",value: "",desc: "",required:false}
> ```
> 
> 允许使用`filter`例如:
> 
> ```
> #未注解xxx.Public的方法都需要header中带有token
> method.additional.header[!@xxx.Public]={name: "token",value: "",desc: "认证token",required:true, example:""}
> ```
> 
> 考虑支持加载配置文件:
> 
> ```
> properties.additional=properties.path
> ```
> 
> 并内置推荐配置:
> 
> ```
> properties.additional=~/src/main/resources/application.properties
> properties.additional=~/src/main/resources/application.yml
> ```
> 
> 考虑支持额外的path前缀:
> 
> ```
> #追加在Controller的basePath之前
> class.path.prefix.=/api-prefix
> ```
> 
> * 最后API的path为
>   `class.prefixPath + class.basePath +  method.path`
> 
> 深入解析spring相关配置
> 如内置推荐配置
> 
> ```
> class.prefix.path=${server.servlet.context-path}
> ```
> 
> 针对多module的项目，如果一次操作涉及到多个module,针对每个module创建解析任务,分别独立加载配置,使得module内部配置只影响当前module

很棒🌹 解析spring boot外部配置文件这个很优秀啊 这样引用变量就不用写多次了 💯

**Comment by tangcent** [comment]
过两天再发,我自己先用用看有没有BUG
- 多模块一次性导出，上下文切换时重载配置这套逻辑可能影响到所有的功能.

[easy-yapi.1.2.1.183.0.4.jar.zip](https://github.com/tangcent/easy-yapi/files/3829830/easy-yapi.1.2.1.183.0.4.jar.zip)

**Comment by qinkangdeid** [comment]
> 过两天再发,我自己先用用看有没有BUG
> 
> * 多模块一次性导出，上下文切换时重载配置这套逻辑可能影响到所有的功能.
> 
> [easy-yapi.1.2.1.183.0.4.jar.zip](https://github.com/tangcent/easy-yapi/files/3829830/easy-yapi.1.2.1.183.0.4.jar.zip)

收到 🙏

**Comment by qinkangdeid** [comment]
@tangcent 目前版本支持 filter特殊接口了吗
```bash
#未注解xxx.Public的方法都需要header中带有token
method.additional.header[!@xxx.Public]={name: "token",value: "",desc: "认证token",required:true, example:""}
```

**Comment by tangcent** [comment]
> @tangcent 目前版本支持 filter特殊接口了吗
> 
> ```shell
> #未注解xxx.Public的方法都需要header中带有token
> method.additional.header[!@xxx.Public]={name: "token",value: "",desc: "认证token",required:true, example:""}
> ```
支持了,我测试过这三种写法:
- 全部加token

```properties
method.additional.header={name: "token",value: "",desc: "认证Token",required:true, example:""}
```
- 简单过滤

```properties
method.additional.header[!@com.itangcent.common.annotation.Public]={name: "token",value: "",desc: "认证Token",required:true, example:""}
```
- groovy过滤

```properties
method.additional.header[groovy:!it.hasAnn("com.itangcent.common.annotation.Public")]={name: "token",value: "",desc: "认证Token",required:true, example:""}
```

---
还没审核通过.你可以先从[releases](https://github.com/tangcent/easy-yapi/releases)里下载试用

**Comment by qinkangdeid** [comment]
> > @tangcent 目前版本支持 filter特殊接口了吗
> > ```shell
> > #未注解xxx.Public的方法都需要header中带有token
> > method.additional.header[!@xxx.Public]={name: "token",value: "",desc: "认证token",required:true, example:""}
> > ```
> 
> 支持了,我测试过这三种写法:
> 
> * 全部加token
> 
> ```ini
> method.additional.header={name: "token",value: "",desc: "认证Token",required:true, example:""}
> ```
> 
> * 简单过滤
> 
> ```ini
> method.additional.header[!@com.itangcent.common.annotation.Public]={name: "token",value: "",desc: "认证Token",required:true, example:""}
> ```
> 
> * groovy过滤
> 
> ```ini
> method.additional.header[groovy:!it.hasAnn("com.itangcent.common.annotation.Public")]={name: "token",value: "",desc: "认证Token",required:true, example:""}
> ```
> 
> 还没审核通过.你可以先从[releases](https://github.com/tangcent/easy-yapi/releases)里下载试用

看到demo上没有这个示例 我自己照着建了个枚举
```java
@Target({ METHOD, FIELD, ANNOTATION_TYPE, CONSTRUCTOR, PARAMETER, TYPE_USE })
@Retention(RUNTIME)
public @interface PublicMethod {

}
```
在接口上标注：
```java
/**
     * 忽略系统自动填充的token
     *
     * @param paramShouldNotIgnore 不应该被忽略的参数
     *                             //     * @param token                Token（系统自动给出,不会出现在API参数中）
     * 
     */
    @PostMapping("/auto/fill/token")
    public IResult testAutoFillToken(@PublicMethod @RequestParam("notIgnore") String paramShouldNotIgnore) {
        return Result.success("ok");
    }

```
在`.easy.api.config`配置上标注：

```bash

method.additional.header[!@com.itangcent.springboot.demo.PublicMethod]={name: "token",value: "",desc: "认证Token",required:true, example:"wdsadsad12312321ds"}
```

点击查看这个注解的使用 可以解析到 配置文件有引用

![image](https://user-images.githubusercontent.com/17582522/68863084-9c90a480-0729-11ea-817d-d76578f31c52.png)

但是生成的时候还是出来了  是不是我配置注解接口的地方有问题😭

**Comment by tangcent** [comment]
@qinkangdeid 需要放在方法上~，现在这条规则计算的对象是方法
https://github.com/tangcent/easy-yapi/blob/8c460db40f4e75524bd8753c544a3a501cd32f23/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/AbstractRequestClassExporter.kt#L206-L217

**Comment by tangcent** [comment]
我测试的代码是这样的:
```java
    /**
     * 打个招呼
     */
    @Public
    @RequestMapping(value = "/index")
    public String greeting() {
        return "hello world";
    }
```

**Comment by qinkangdeid** [comment]
好的 好的 理解错了 哈哈 😄 谢谢大佬指导

**Comment by qinkangdeid** [comment]
@tangcent  `server.servlet.context-path`目前是必填项了吗 未配置的情况下 导出api报错如下：
![image](https://user-images.githubusercontent.com/17582522/69021478-e069ff00-09f2-11ea-9274-1984df8f934b.png)
加上就OK了

**Comment by tangcent** [comment]
- 是个BUG~解析的地方跳过无法解析的值的时候没有replace掉
- 可以在推荐配置里把它先点掉
- 我找个时间修复

**Comment by tangcent** [comment]
@qinkangdeid 修复了
