### ISSUE TITLE
导入到yapi时 默认参数为null 或者 [] 怎么设置

### ISSUE THREAD

**Issue by wjgful4163** [tangcent/easy-yapi#780]
请求方式为post 参数中某些字段需要设置默认值为 null  []

**Comment by wjgful4163** [comment]
field.default.value=#default
这个是可以设置具体的值，但是如果要设置 值为null 不好使（因为字段较多）
生成的是json5方式

**Comment by tangcent** [comment]
> 这个是可以设置具体的值，但是如果要设置 值为null 不好使（因为字段较多）

需要确认清楚`什么样的字段`默认值需要设置为`什么`，
然后翻译为配置即可:
如
1. `UserInfo.nickName`默认值需要设置为`null`
->
`field.default.value[com.itangcent.common.model.UserInfo#nickName]=null`

2. `注释了@null`默认值需要设置为`null`
->
`field.default.value[#null]=null`

3. `基本类型包装类型`默认值需要设置为`null`
->
`field.default.value[groovy:it.type().isPrimitiveWrapper()]=null`
4. `数组`默认值需要设置为`[]`
->
`field.default.value[groovy:it.type().isArray()||it.type().isCollection()]=[]`
