### ISSUE TITLE
复杂对象导不出来，提示xxx is too complex. Blocked by deep reached 8

### ISSUE THREAD

**Issue by yizhishang** [tangcent/easy-yapi#781]
导出的对象结构
ResponseData<com.baomidou.mybatisplus.core.metadata.IPag<com.yizhishang.User>>

**Comment by tangcent** [comment]
看一下QA的最后一个:
http://easyyapi.com/qa/index.html#%e5%af%bc%e5%87%ba%e6%97%b6%e5%87%ba%e7%8e%b0com.xxx.xxx_is_to_complex._blocked_cause_by_xxx_reached_xxx%e5%a6%82%e4%bd%95%e5%a4%84%e7%90%86

放大下面两个限制
```
max.deep=8
max.elements=512
```
---

为了防止超复杂对象的解析卡死, 加了点限制。
这个数字是根据我遇到的情况设定的。你试试设置为多少合适。
我在下个版本再放大一点

**Comment by yizhishang** [comment]
谢谢，我增加了这个配置，修改了值就好了，但是有个问题。
controller有多个接口，发现只导出了最后2个

**Comment by tangcent** [comment]
没碰到过这种情况, 是必现吗?
每次都只能导出最后两个还是数量不固定?
所有的`controller`都存在这个问题还是个别的?

**Comment by yizhishang** [comment]
```properties
#swagger
doc.param=@io.swagger.annotations.ApiParam#value
#doc.class=@io.swagger.annotations.Api#value
doc.class=@io.swagger.annotations.Api#tags
doc.method=@io.swagger.annotations.ApiOperation#value
doc.field=@io.swagger.annotations.ApiModelProperty#value

#param.default.value=@io.swagger.annotations.ApiParam#defaultValue
param.required=@io.swagger.annotations.ApiParam#required
param.ignore=@io.swagger.annotations.ApiParam#hidden
api.tag=@io.swagger.annotations.ApiOperation#tags

field.default.value=#default
max.deep=18
max.elements=512
```

idea版本：IntelliJ IDEA 2021.1.3 (Ultimate Edition)
idea插件版本：2.3.9.191.0

我换了controller，只有2个api又导不出来了，电脑CPU直接飙升值100%，内存也是100%

**Comment by tangcent** [comment]
> controller又只能导出最后的两个api

我没办法重现这个问题
1. 试试换个项目
2. 换个导出方式(markdown/postman)
3. 回滚历史版本: https://plugins.jetbrains.com/plugin/12458-easyyapi/versions
4. 换个idea版本

**Comment by yizhishang** [comment]
> > controller又只能导出最后的两个api
> 
> 我没办法重现这个问题
> 
> 1. 试试换个项目
> 2. 换个导出方式(markdown/postman)
> 3. 回滚历史版本: https://plugins.jetbrains.com/plugin/12458-easyyapi/versions
> 4. 换个idea版本

请问你用的是什么版本idea，插件又是什么版本

**Comment by tangcent** [comment]
idea: 2022.1.2
easyyapi: 2.3.9

**Comment by yizhishang** [comment]
> idea: 2022.1.2 easyyapi: 2.3.9

还是没用哦，用的时候idea直接跪了无响应，
更新到2.4.0也是这样的

**Comment by yizhishang** [comment]
是不是插件代码哪里内存溢出了

**Comment by yizhishang** [comment]
简单的导出来
但是对泛型无法解析

**Comment by yizhishang** [comment]
以前低版本是可以解析泛型的，麻烦作者解决下这个问题

**Comment by tangcent** [comment]
还在尝试定位问题。但一直无法重现

**Comment by zhouwentong1993** [comment]
我遇到了同样的情况，2011.1(Ultimate Edition)，插件版本：2.4.1.191.0
我在导出前调整了一下 .yapi.config 文件的 folder.name 属性，结果其中一个导入不到新的目录下。
