### ISSUE TITLE
[Question] 生成的“接口路径” 里面能包含context-path 吗

### ISSUE THREAD

**Issue by AsiaChampion** [tangcent/easy-yapi#782]
**Describe the question**

我们的 yapi 包含多个微服务, 默认情况下生成的yapi接口里  “接口路径”不包含 context-path,我们的mock环境需要带上context-path,每次都需要手动添加,很麻烦

**Expected result**

“接口路径” 里 包含 context-path

**Screenshots**

![image](https://user-images.githubusercontent.com/31605459/172314765-3453cfdd-1b71-4e1f-82ea-201f43a2d417.png)

**Comment by tangcent** [comment]
http://easyyapi.com/setting/rules/class_prefix_path.html

**Comment by tangcent** [comment]
我不确定你是不是知道`yapi`中有个 `设置` ->  `项目配置` -> `接口基本路径`。

**Comment by tangcent** [comment]
如果引入`application.yml`麻烦的话，还是建议直接配置`class.prefix.path=/xxx`，配置文件不想上传的话，可以ignore掉
你也可以看看`yapi`中 `设置` ->  `项目配置` -> `接口基本路径`。

**Comment by AsiaChampion** [comment]
我们是多个微服务共用yapi的,所以 `class.prefix.path=/xxx` 和 `设置 -> 项目配置 -> 接口基本路径` 都不行, 这样会写死成一个微服务的.

**Comment by tangcent** [comment]
多个微服务的`api`放在一个`yapi`项目里吗? 为什么不分开呢?
