### ISSUE TITLE
[Question] 接口interface上的jackson注解(JsonProperty、JsonIgnore)不生效

### ISSUE THREAD

**Issue by zzhhss** [tangcent/easy-yapi#784]
**Describe the question**

JsonIgnore和JsonProperty的注解放到interface里不能生效，是配置问题还是bug？

**Expected result**

希望配置在接口上的jackson注解也能生效

**Screenshots**
![image](https://user-images.githubusercontent.com/41987633/172753711-011f93de-8655-4ad9-90f9-ca7059e9e042.png)

![image](https://user-images.githubusercontent.com/41987633/172753251-4c72b18e-ac9d-498a-8d17-0af673b35638.png)

![image](https://user-images.githubusercontent.com/41987633/172752926-9c83ace2-abd6-4fe8-9f46-f09fd20fdcd0.png)

**Demo Code**
```
    /**
     * 新建source
     *
     * @return source
     */
    @PostMapping("")
    Rest<String> createSource() {
        return null;
    }

    public interface Rest<T> {
        String getMsg();

        Integer getCode();

        T getData();

        @JsonIgnore
        String getSomething();
    }
```

**Additional context**
Idea插件版本：2.3.9.191.0

**Comment by zzhhss** [comment]
这个字段是通过`getter as field`配置解析到的，但是没有配套的配置参数。所有filed.xxx 配置都不能应用到这种字段上，因为它本质上是个method？

**Comment by tangcent** [comment]
BUG~
