### ISSUE TITLE
[Bug] kotlin接口导出文档时无法生成返回数据

### ISSUE THREAD

**Issue by Songzhizong** [tangcent/easy-yapi#788]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/22743270/173538584-b24ca46a-4bdc-49c0-899a-7afba1403d5f.png">
<img width="829" alt="image" src="https://user-images.githubusercontent.com/22743270/173539675-7f1db074-d02b-4137-9cae-c7c70c4f6940.png">
如上图，使用spring-webflux加kotlin协程开发的接口，导出文档时返回数据为空。
idea版本：2022.1.2
插件版本：2.4.0.191.0
YAPI版本：1.9.2

**Comment by tangcent** [comment]
能否提供一下`PageResult`的代码?

**Comment by Songzhizong** [comment]
<img width="599" alt="image" src="https://user-images.githubusercontent.com/22743270/173715942-eb69f1e3-4bab-4c9d-9cb7-2ef55c279a7e.png">
<img width="542" alt="image" src="https://user-images.githubusercontent.com/22743270/173715958-8f6c5d59-ab21-410c-8550-696abe227c7c.png">
<img width="517" alt="image" src="https://user-images.githubusercontent.com/22743270/173715991-1534d8c4-a5a9-49ae-98ee-1f9614af0dec.png">
<img width="338" alt="image" src="https://user-images.githubusercontent.com/22743270/173716018-25bb1959-253a-41b8-9a66-c978e8a767d1.png">
这是PageResult及其父类的代码

**Comment by tangcent** [comment]
确认问题是无法获得`suspend`方法正确的返回信息
