### ISSUE TITLE
[Feature] 能否设置see枚举的时候默认取某一个值

### ISSUE THREAD

**Issue by ekkoxusu** [tangcent/easy-yapi#789]
需求:
有统一的enum，返回值为枚举里的一个值而不是枚举类型，或者允许读取注释值之后可以写groovy表达式修改原值
比如说以下：

    /**
     * 订单状态
     * @see OrderStatusEnum
     */
    private Integer orderStatus;

只能写成这样

    /**
     * 订单状态
     * @see OrderStatusEnum#code
     */
    private Integer orderStatus;

期望可以设置当see某个类的时候，可以写一些表达式修改原值

**Comment by ekkoxusu** [comment]
您好，并不是
@see OrderStatusEnum#code
原因是因为项目本身是使用Long传输的，不是使用的枚举
然后的话因为有大量的枚举传输，所以想省略掉#code这一步
目前没找到办法处理。

**Comment by tangcent** [comment]
1. 能否提供`OrderStatusEnum`的代码?
2. 你的意思是不是希望只使用`@see OrderStatusEnum`但是到达`@see OrderStatusEnum#code`的等价效果?

**Comment by ekkoxusu** [comment]
1. 好的，示例代码如下

public interface BaseEnum {

    Long getCode();

    String getMessage();
}

public enum OrderStatusEnum implements BaseEnum{
    ORDER_DEMO_STATUS(1L,"demo");

    private Long code;

    private String message;

    OrderStatusEnum(Long code, String message) {
        this.code = code;
        this.message = message;
    }

    @Override
    public Long getCode() {
        return null;
    }

    @Override
    public String getMessage() {
        return null;
    }
}

public class OrderResponse {
    /**
     * 订单号
     */
    private String orderNo;
    /**
     * 订单状态
     * @see OrderStatusEnum
     */
    private Long orderStatus;
    /**
     * 其他参数
     */
    private String otherParameter;
}

2. 是的，原因是因为有大量的使用，期望可以。

如上代码会基于OrderStatusEnum的name来生成注释，可以写 `@see OrderStatusEnum#code`来生效，但是有以下几个问题：
1. IDEA默认会将code标记为红色[原因是无法访问，需要忽视此提示]
2. 项目中大量使用了这种用法，每个地方都标记要取code有点奇怪

期望的结果可能有以下几种方式：
1. `@see OrderStatusEnum`但是达到`@see OrderStatusEnum#code`
2. 读取某个注解值的时候允许写一定的表达式来自定义结果 [目前我的想法是BaseEnum的子类的话就取code来渲染]

thx

**Comment by tangcent** [comment]
目前没有提供这种规则。

**Comment by tangcent** [comment]
https://github.com/tangcent/easy-yapi/releases/tag/v2.4.1

试试这样的配置:
```
enum.use.custom[groovy:it.isExtend("com.itangcent.springboot.demo.mode.BaseEnum")]=code
```

**Comment by ekkoxusu** [comment]
好的，谢谢。
