### ISSUE TITLE
[Questrion] map类型的参数无法生成参数参数列表

### ISSUE THREAD

**Issue by xukaisjz** [tangcent/easy-yapi#793]
接口代码：
![image](https://user-images.githubusercontent.com/68056796/177268255-0d1e93bf-1077-4932-aaf5-56585f1bb224.png)

生成的api文档：
![image](https://user-images.githubusercontent.com/68056796/177268070-a2fa2bc6-f822-4a62-b62a-4e2a2fa9ac3f.png)

**Comment by tangcent** [comment]
考虑暂时用[param.ignore](http://easyyapi.com/setting/rules/param_ignore.html)忽略这种参数
在注释里写怎么传参吧

---

这种入参`Map`希望处理成什么样?
