### ISSUE TITLE
[Question] idea使用插件导入接口到yapi时无法执行检查spring security注解的配置

### ISSUE THREAD

**Issue by Xjy970707** [tangcent/easy-yapi#794]
**Describe the question**

按照官方文档来配置声明需要的springSecurity权限，导出到yapi时报错不支持javaScript类型

`**Screenshots**`

![image](https://user-images.githubusercontent.com/56180160/177726705-a8b60663-8d75-4673-8a4b-395db334137b.png)

![image](https://user-images.githubusercontent.com/56180160/177726849-11a027ed-6fc5-4b2a-8e7c-567a91ebc9ec.png)

![image](https://user-images.githubusercontent.com/56180160/177726949-9c542046-a473-4641-b99c-333364e5cebe.png)

**Demo Code**
配置如下
``
find_role_in_PreAuthorize=(function(exp){var str="hasAnyAuthority";if(exp.indexOf("hasAnyAuthority")!=-1){var roles=exp.match(/hasAnyAuthority\\((.*?)\\)/);if(roles&&roles.length>1){str+=" :"+roles[1];}};return str})
method.doc[@org.springframework.security.access.prepost.PreAuthorize]=js:${find_role_in_PreAuthorize}(it.ann("org.springframework.security.access.prepost.PreAuthorize"))

**Comment by tangcent** [comment]
高版本的JDK里面不再包含`js`引擎了。所以需要换成`groovy`.
这里等价的`groovy`是这样的:
``````properties
doc.method[@org.springframework.security.access.prepost.PreAuthorize]=groovy:```
    def preAuthorize = it.ann("org.springframework.security.access.prepost.PreAuthorize")
    if(tool.nullOrBlank(preAuthorize)){
        return
    }
    def role = regex.getGroup1("hasRole\\('(.*?)'\\)",preAuthorize)
    return "require role: $role"
```
``````
