### ISSUE TITLE
[Bug] 导入到yapi报错

### ISSUE THREAD

**Issue by ShenGuangYang** [tangcent/easy-yapi#800]
**Describe the bug**

导入返回参数的字段带有@see 报错
/**
 * @see enum
*/

   
**Expected behavior**

正确导出Excel，并且yapi 有对应的枚举备注信息

**Screenshots**
报错信息
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/18436796/180386606-b8ee604e-1dc5-4beb-af26-1acf3a091037.png">

controller 内容
<img width="891" alt="image" src="https://user-images.githubusercontent.com/18436796/180387181-347619a7-1d31-46f5-83ee-c2d203a052cf.png">

Vo的内容
<img width="785" alt="image" src="https://user-images.githubusercontent.com/18436796/180387344-313f680c-d204-4b0b-8c1c-5c7016e293db.png">

枚举内容
<img width="522" alt="image" src="https://user-images.githubusercontent.com/18436796/180387390-b1d6ec30-ef8c-4727-b457-32d2d1f6fcf0.png">

**Logs**

1. Add config:
   
   ```properties
      默认
   ```

**Environment (please complete the following information):**
 - OS: [e.g. mac]
 - IDEA version [e.g. 2022.1.4]
 - Plugin version [e.g. 2.4.2.191.0]
 - Yapi version [e.g. 1.8.8]

**Comment by tangcent** [comment]
我试了一下，可以正常导出。错误似乎不是这里的`@see`引起的。
你可以试试删除这里的`@see`再导出看看。
