### ISSUE TITLE
[Bug] YAPI网站设置中的接口基本路径，与生成的接口路径有重复

### ISSUE THREAD

**Issue by Muscleape** [tangcent/easy-yapi#803]
## YAPI网站设置中的接口基本路径

<img width="405" alt="image" src="https://user-images.githubusercontent.com/16682039/180747227-2404ba21-f1ab-464b-bf68-a6c3d0dcf770.png">

## 生成的问题的路径示例

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/16682039/180747361-e5caf3b8-119d-4197-81e6-2e8c1b4ce24e.png">

**Comment by tangcent** [comment]
如果你希望导出到`yapi`时移除一段前缀，可以试试这样配:
``````properties
export.after=groovy:api.setPath(tool.removePrefix(api.path(),"/xxx"))
``````
