### ISSUE TITLE
[Bug] 返回值无法导出枚举

### ISSUE THREAD

**Issue by KeaneT** [tangcent/easy-yapi#805]
**Describe the bug**

response里的枚举值无法识别，应该导出也有枚举值；

![image](https://user-images.githubusercontent.com/32267731/180918488-0339e893-92c9-404d-9885-1990ef2add07.png)

**To Reproduce**

easyYapi版本：2.4.2.191.0 
idea版本：2021.2.2（Utimate Edition）

测试一个接口，参数和返回值都是同一个枚举类型，导出到yapi文档里，参数显示枚举，返回值是空

   
我的枚举类：
![image](https://user-images.githubusercontent.com/32267731/180918682-9afbbd01-fa8b-4365-8b61-8f1911f78f43.png)

测试接口：
![image](https://user-images.githubusercontent.com/32267731/180918759-0069ccb5-f531-461b-b973-b48a994ca31a.png)

导出文档结果：
![image](https://user-images.githubusercontent.com/32267731/180918861-ec733e99-9bfa-4115-8087-ed7db61db4ac.png)

**Comment by tangcent** [comment]
fix by #807
