### ISSUE TITLE
[Bug] 一导出Idea就占用cpu99%，直接卡死，怎么回事儿？

### ISSUE THREAD

**Issue by tiger54910** [tangcent/easy-yapi#810]
**Describe the bug**

**To Reproduce**

Detailed Steps to reproduce the behavior:

1. Open '...'
3. See error
   
**Expected behavior**

**Screenshots**

**Logs**

1. Add config:
   
   ```properties
   http.call.before=groovy:logger.info("call:"+request.url())
   http.call.after=groovy:logger.info("response:"+response.string())
   api.class.parse.before=groovy:logger.info("[api] before parse class:"+it)
   api.class.parse.after=groovy:logger.info("[api] after parse class:"+it)
   api.method.parse.before=groovy:logger.info("[api] before parse method:"+it)
   api.method.parse.after=groovy:logger.info("[api] after parse method:"+it)
   api.param.parse.before=groovy:logger.info("[api] before parse param:"+it)
   api.param.parse.after=groovy:logger.info("[api] after parse param:"+it)
   json.class.parse.before=groovy:logger.info("[json] before parse class:"+it)
   json.class.parse.after=groovy:logger.info("[json] after parse class:"+it)
   json.method.parse.before=groovy:logger.info("[json] before parse method:"+it)
   json.method.parse.after=groovy:logger.info("[json] after parse method:"+it)
   json.field.parse.before=groovy:logger.info("[json] before parse field:"+it)
   json.field.parse.after=groovy:logger.info("[json] after parse field:"+it)
   ```

2. Console output `easy_api`
   - Please set <kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd> Common</kbd> > <kbd>log</kbd> to `LOW```
   
3. Logs of IDEA: <br>
   The easiest way to find the product log file is the Help menu, the item name would depend on the IDE version and OS:- Show Log in Explorer
   - Show Log in Finder
   - Show Log in Konqueror/Nautilus
   - Reveal Log in Explorer
   - Reveal Log in Finder/Finder/Nautilus

**Environment (please complete the following information):**
 - OS: [e.g. Windows]
 - IDEA version [e.g. 2021.2.3]
 - Plugin version [e.g. 2.2.9]
 - Yapi version [e.g. 1.9.1]

**Demo Code**

1. Fork https://github.com/Earth-1610/spring-demo
2. Write some code to reproduce this error
3. Now paste the forked repository hear: https://github.com/xxxx/spring-demo

**CheckList**

   - [ ] <kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd> Intelligent</kbd> > <kbd>enable infer</kbd>

**Additional context**

**Comment by tangcent** [comment]
1. 确认一下是所有接口无法导出还是某些接口无法导出?
2. 导出时Console有日志输出吗?

**Comment by yizhishang** [comment]
我也遇到了，所有接口都无法导出

**Comment by tangcent** [comment]
😂, 提供一点日志啊

**Comment by chenshun00** [comment]
把类型推断关闭掉试试
