### ISSUE TITLE
[Bug] getter as field 失效了

### ISSUE THREAD

**Issue by s1084796293** [tangcent/easy-yapi#811]
之前还能使用，今天试了一下就不行了，不知道是不是我升级了idea的问题
接口：
![image](https://user-images.githubusercontent.com/17758223/183845261-2048e6cb-7ded-4d5c-9cc5-ccf20745b907.png)

配置：
![image](https://user-images.githubusercontent.com/17758223/183845010-73b11014-e378-408c-b2fe-3fe8bfb09bf8.png)
 
包装类：
![image](https://user-images.githubusercontent.com/17758223/183845100-92c07ce7-8da2-4a85-a68d-a66553dc6a5a.png)

**Comment by s1084796293** [comment]
我下载了2.3.9.191.0 版本，然后试了下，发现可以了
最新版本2.4.4.191.0的就不行

**Comment by tangcent** [comment]
我测试正常。可能没get到你面临的情况。
可以的话，fork一下 https://github.com/Earth-1610/web-demo/blob/master/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/UserCtrl.java
尝试提供可以重现的case。

**Comment by s1084796293** [comment]
`public class ResultWrapper<T>  {
    @JsonIgnore
    private Result<T>  result;//响应数据

    public ResultWrapper(Result<T> t) {
    }

    public Integer getCode() {
        return result.getCode();
    }


    public String getMsg() {
        return result.getMsg();
    }


    public T getData() {
        return result.getData();
    }

}
`

UserCtrl.java

`    @PostMapping("/add")
    public ResultWrapper<UserInfo> add(@RequestBody UserInfo userInfo) {
        ResultWrapper<UserInfo> userInfoResultWrapper = new ResultWrapper<>(Result.success(userInfo));
        return userInfoResultWrapper;
    }`

**Comment by tangcent** [comment]
我确实没办法重现:
![image](https://user-images.githubusercontent.com/17569144/184159334-08a09cb8-b986-4e05-a46e-13ef7ac89df4.png)
![image](https://user-images.githubusercontent.com/17569144/184158868-f0783134-bf3a-4731-a126-dcc2abc173f8.png)
![image](https://user-images.githubusercontent.com/17569144/184159145-f419c578-c01f-4254-aaea-50e553760008.png)

**Comment by s1084796293** [comment]
这就奇怪了，我先用老版本吧

**Comment by tangcent** [comment]
OK. 哪个版本你用的舒服的话，可以一直不更新。插件的主体功能基本不会动，现在每次更新的功能基本上都只是部分人(maybe 10%~30%)需要的。当然，你也可以在更新前，看一下`changelog`来判断是否需要更新。
