### ISSUE TITLE
[Question] No token be found for moudle

### ISSUE THREAD

**Issue by gchzz** [tangcent/easy-yapi#815]
**Describe the question**

导出到yapi时提示找不到token，在IDEA2020版本时可以，换到了2022.02就不好用了，再换回2020版本也不好用，不知道是否是更换IDEA引起

**Expected result**

希望可以成功导出接口文档

**Screenshots**

![image](https://user-images.githubusercontent.com/87818948/185028393-6ece1a66-8c35-4e55-8dc4-c9aefebe41f2.png)

**Comment by tangcent** [comment]
在idea设置里把yapi的tokens清空试试

**Comment by gchzz** [comment]
> 
清空了还是不好用，这个token现在是这样的：e9bb255284351d59216d
我记得之前token比较长，是token问题吗
插件试了好多版本都不行

**Comment by gchzz** [comment]
> 在idea设置里把yapi的tokens清空试试
清空了还是不好用，这个token现在是这样的：e9bb255284351d59216d
我记得之前token比较长，是token问题吗
插件试了好多版本都不行

**Comment by gchzz** [comment]
> 在idea设置里把yapi的tokens清空试试

清空了还是不好用，这个token现在是这样的：![image](https://user-images.githubusercontent.com/87818948/185064215-ebf7893e-a1fa-4eb8-b97e-0f2ec3899525.png)
我记得之前token比较长，是token问题吗
插件试了好多版本都不行

**Comment by gchzz** [comment]
![image](https://user-images.githubusercontent.com/87818948/185066577-bee4491e-5a7d-4168-9a2d-53c556e62407.png)
![Uploading image.png…]()

**Comment by gchzz** [comment]
![image](https://user-images.githubusercontent.com/87818948/185067065-ea1130ba-7c29-4d68-aa39-5b9f72e67897.png)
![image](https://user-images.githubusercontent.com/87818948/185067119-5db3663e-0edf-4c89-827b-8a43c004d34f.png)
![image](https://user-images.githubusercontent.com/87818948/185067162-24b0a3de-48f0-4448-b3d1-96784269bf17.png)
![image](https://user-images.githubusercontent.com/87818948/185067205-ea9e5a63-8eb8-4d60-9d34-559d8881124f.png)

**Comment by tangcent** [comment]
你这个比较麻烦，yapi版本太老了
要切换到登录模式: http://easyyapi.com/documents/login_mode_yapi.html
具体怎么登录也要看你们有没有对yapi进行二开或者使用了sso。

**Comment by gchzz** [comment]
> 你这个比较麻烦，yapi版本太老了 要切换到登录模式: http://easyyapi.com/documents/login_mode_yapi.html 具体怎么登录也要看你们有没有对yapi进行二开或者使用了sso。

解决了，感谢大佬。
运维说没换过版本，但是之前就是用token推的现在就不行。
大家如果遇到这种问题，参考老版本解决方案，然后最后在这个框里输入项目id，不要输token。
![image](https://user-images.githubusercontent.com/87818948/185111469-120bfea2-7f03-43d4-8a37-7ec549b2496e.png)
