### ISSUE TITLE
[建议] 支持https

### ISSUE THREAD

**Issue by bingfen** [tangcent/easy-yapi#818]
什么时候能支持https 访问呢，现在配置https 会报错

**Comment by tangcent** [comment]
我这边的`yapi`也是使用`https`的，使用正常。
我现在没办法重现你们遇到的问题。
你可以试试修改这里的代码:
https://github.com/tangcent/easy-yapi/blob/fee3b75453e90d7f2f18cf98840286489a0d6931/common-api/src/main/kotlin/com/itangcent/http/ApacheHttpClient.kt#L66-L67

你可以使用这个脚本打包插件:
https://github.com/tangcent/easy-yapi/blob/master/plugin-script/package_plugin.sh
