### ISSUE TITLE
[Feature] 是否有考虑接入除yapi之外的平台呢

### ISSUE THREAD

**Issue by 1176933465** [tangcent/easy-yapi#822]
是否可以由开发者自己开发上传到其他平台的功能，比如上传到Apifox

**Comment by tangcent** [comment]
目前Apifox的开放 API还是todo状态。
如果你有想支持的其他平台，可以添加代码到这里：
https://github.com/tangcent/easy-yapi/tree/master/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export
