### ISSUE TITLE
[Bug] BigInteger类型会当对象处理

### ISSUE THREAD

**Issue by mulhyac** [tangcent/easy-yapi#825]
当对象的属性中存在BigInteger类型时不会当最简单的类型的处理，而是会继续当普通业务对象一样，继续包含这个类型的属性

**Comment by tangcent** [comment]
你先暂时配置一下:
```
json.rule.convert[java.math.BigInteger]=java.lang.Long
```

**Comment by mulhyac** [comment]
这个在哪配置，找不到地方
&nbsp;


Eziep系统服务
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月29日(星期一) 晚上7:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tangcent/easy-yapi] [Bug] BigInteger类型会当对象处理 (Issue #825)





 
你先暂时配置一下:
 json.rule.convert[java.math.BigInteger]=java.lang.Long

**Comment by mulhyac** [comment]
还有，这个能不能支持一下spring的validated，这样的话，非空也能体现 出来了



Eziep系统服务
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tangcent/easy-yapi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月29日(星期一) 晚上7:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tangcent/easy-yapi] [Bug] BigInteger类型会当对象处理 (Issue #825)





 
你先暂时配置一下:
 json.rule.convert[java.math.BigInteger]=java.lang.Long

**Comment by tangcent** [comment]
> 这个在哪配置，找不到地方

设置里: <kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Built-in config</kbd> 
或者本地文件: http://easyyapi.com/setting/local-file-config.html

> 还有，这个能不能支持一下spring的validated，这样的话，非空也能体现 出来了

看一下这个: http://easyyapi.com/framwork/javax_validation.html
你也可以自定义你需要的规则: http://easyyapi.com/setting/rules/field_required.html

**Comment by mulhyac** [comment]
配置好了，现在好用的很，非常感谢



Eziep系统服务
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tangcent/easy-yapi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月29日(星期一) 晚上7:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tangcent/easy-yapi] [Bug] BigInteger类型会当对象处理 (Issue #825)





  
这个在哪配置，找不到地方
  
设置里: Preferences(Settings) &gt; Other Settings &gt; EasyApi &gt; Built-in config
 或者本地文件: http://easyyapi.com/setting/local-file-config.html
  
还有，这个能不能支持一下spring的validated，这样的话，非空也能体现 出来了
  
看一下这个: http://easyyapi.com/framwork/javax_validation.html
 你也可以自定义你需要的规则: http://easyyapi.com/setting/rules/field_required.html
