### ISSUE TITLE
[Question] 如何将@FeignClient标识的接口推送到YAPI

### ISSUE THREAD

**Issue by KingStarIsMe** [tangcent/easy-yapi#826]
项目中使用@FeignClient标识的的接口,这部分接口不能被识别,无法推送到YAPI,这部分有识别或者说配置的可能么?

**Comment by tangcent** [comment]
在<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Support</kbd> 里勾选`feign`

**Comment by KingStarIsMe** [comment]
问题已经解决了谢谢
