### ISSUE TITLE
call api 窗口中怎么复制Response内容？

### ISSUE THREAD

**Issue by wencyGit** [tangcent/easy-yapi#831]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/21151964/188315742-64c07f07-76b4-4339-83ef-e7f245c6a65a.png">
想复制Response的内容都复制不了

**Comment by tangcent** [comment]
我一般是用Ctrl+A全选，然后Ctrl+C/V

**Comment by wencyGit** [comment]
@tangcent idea 下载最新版插件怎么 Ctrl+A全选不了

**Comment by wencyGit** [comment]
@tangcent 原来是这样子啊，我就是想没有发起请求也能复制
