### ISSUE TITLE
path.multi=ALL场景下 怎么根据uri来生成不同的接口名称

### ISSUE THREAD

**Issue by tangchen-blip** [tangcent/easy-yapi#839]
<img width="913" alt="image" src="https://user-images.githubusercontent.com/65538007/192464029-180f1af0-bbc8-4bf2-8ffc-105bbb75c016.png">
使用export.after回掉 没办法根据uri来自定义接口名称

**Comment by tangcent** [comment]
> 使用export.after回掉 没办法根据uri来自定义接口名称

是的

---

- 目前`export.after`发生在`api`解析完毕之后①,它对导出任何渠道都生效
- 而`path.multi`发生在解析为能导入`yapi`的结构之时②, 目前只有`postman`和`yapi`应用了这个规则.
- 我试试在导入`yapi`之前③再增加一个回调来处理导入`yapi`的每个解析处理都完成了的`yapi item`.

**Comment by tangchen-blip** [comment]
目前我结合export.after回调和自定义扩展导出（PostmanFormatter，YapiFormatter）实现这个功能了 比较复杂 希望下个版本能够支持相关回调
