### ISSUE TITLE
[Question] 如何Mock Map数据

### ISSUE THREAD

**Issue by CloudSen** [tangcent/easy-yapi#844]
**Describe the question**

例如某个类中，有一个MAP类型的变量。期望通过`@mock`来生成一些数据。
```
/**
 * Predicate参数MAP，key：参数名，value：参数值
 * @mock {"pattern": "/test-app/api"}
 */
private Map<String, String> args;
```

**Expected result**

期望的mock结果：  
```
{
  "name": "Path",
  "args": {
     "pattern": "/test-app/api"
  }
},
```

**Screenshots**

实际的mock结果为String类型：  
```
{
"name": "Path",
"args": "{\"pattern\": \"/test-app/api\"}"
},
```

**Demo Code**

```
@mock {"pattern": "/test-app/api"}
```

**Comment by tangcent** [comment]
目前没有对mock做这样的处理。
你可以先试试通过[field.demo](https://easyyapi.com/setting/rules/field_demo.html)或者[field.default.value](https://easyyapi.com/setting/rules/field_default_value.html)，来稍微补全一下Map结构的信息(效果不是很好).

_config:_
```
field.demo=#demo
```

_code:_
```
    /**
     * @demo {"pattern": "/test-app/api"}
     */
    private Map<String, String> args;
```

_结果:_
![image](https://user-images.githubusercontent.com/17569144/194785897-63ad14eb-e720-4c0b-b675-4267c0380315.png)

---

WIP:

- [ ]  尝试从`mock`补全字段信息
- [ ]  优化从`demo`/`default`补全字段信息

**Comment by CloudSen** [comment]
感谢解答，期待后续的优化～
