### ISSUE TITLE
[Question] 对于map类型的入参与返回值，该如何正常解析并显示到yapi上

### ISSUE THREAD

**Issue by linjiahui020** [tangcent/easy-yapi#854]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/48832114/199186043-b81f7bbc-cc44-4e66-827a-51634fdb8eb0.png">
目前显示的只能是这样

**Comment by tangcent** [comment]
ref: https://github.com/tangcent/easy-yapi/issues/844#issuecomment-1272664573

**Comment by linjiahui020** [comment]
我目前的场景map是直接放到api入参上面的，而不是放到一个类里面。你发的那个貌似只支持map成为类中的成员变量的场景

**Comment by linjiahui020** [comment]
<img width="447" alt="image" src="https://user-images.githubusercontent.com/48832114/199193842-1d972b97-b207-4168-8663-2ea1e5374df5.png">

**Comment by linjiahui020** [comment]
还有一个问题就是除了@RequestBody，还有什么其他注解或者配置方式能将参数从query放到json request body中。目前我这边的api中是多个参数的，不能用@RequestBody显示成json body

**Comment by linjiahui020** [comment]
> > 我目前的场景map是直接放到api入参上面的，而不是放到一个类里面。你发的那个貌似只支持map成为类中的成员变量的场景
> 
> 你希望导入到yapi中是什么样子的?
> 
> > 还有一个问题就是除了@requestbody，还有什么其他注解或者配置方式能将参数从query放到json request body中。目前我这边的api中是多个参数的，不能用@requestbody显示成json body
> 
> 可以试试: [param.http.type](http://easyyapi.com/setting/rules/param_http_type.html)

我希望的就是上面那种通过方法传的map入参能跟类的map成员变量这种形式一样，能通过@demo注释显示出我想要的map里面的字段结构

**Comment by tangcent** [comment]
有点麻烦，目前能用的规则可能只有: [export.after](http://easyyapi.com/setting/rules/export_after.html)
先用[param.ignore](http://easyyapi.com/setting/rules/param_ignore.html)忽略掉你这个入参的参数

再试试这样配置:
``````properties
export.after[#body]=groovy:```
    import groovy.json.JsonSlurper
    api.setJsonBody(new JsonSlurper().parseText(body), null)
```
``````

然后在api方法上注释:
```
    /**
     * @body {"a":"b"}
     */
```

**Comment by linjiahui020** [comment]
貌似运行会报错
![image](https://user-images.githubusercontent.com/48832114/199380301-2c742668-9bdb-430e-9625-f0ac4dae939a.png)
![image](https://user-images.githubusercontent.com/48832114/199380332-7dc1101c-19a0-4c0a-b467-1b231d4a8de8.png)


> 有点麻烦，目前能用的规则可能只有: [export.after](http://easyyapi.com/setting/rules/export_after.html) 先用[param.ignore](http://easyyapi.com/setting/rules/param_ignore.html)忽略掉你这个入参的参数
> 
> 再试试这样配置:
> 
> ```ini
> export.after[#body]=groovy:```
>     import groovy.json.JsonSlurper
>     api.setJsonBody(new JsonSlurper().parseText(body), null)
> ```
> ```
> 
> 然后在api方法上注释:
> 
> ```
>     /**
>      * @body {"a":"b"}
>      */
> ```

貌似运行会报错
![image](https://user-images.githubusercontent.com/48832114/199380409-ec4d27d0-856c-4ad4-8f62-97759cbb5c7a.png)

![image](https://user-images.githubusercontent.com/48832114/199380388-ad6957c5-662e-461c-96d8-84d485cc47dc.png)

**Comment by tangcent** [comment]
``````properties
export.after[#body]=groovy:```
    import groovy.json.JsonSlurper
    api.setJsonBody(new JsonSlurper().parseText(it.doc("body")), null)
```
``````

**Comment by linjiahui020** [comment]
> ```ini
> export.after[#body]=groovy:```
>     import groovy.json.JsonSlurper
>     api.setJsonBody(new JsonSlurper().parseText(it.doc("body")), null)
> ```
> ```

这个json 解析有没有办法解析出long类型，我看解析出来的数都是int。还有就是能不能在里面@link 绑定其他的类进行解析

**Comment by tangcent** [comment]
> 这个json 解析有没有办法解析出long类型，我看解析出来的数都是int。

是的，可以试试给一个超出int的大数

>还有就是能不能在里面@link 绑定其他的类进行解析

不能。

---

你这里为什么要使用map呢? 你有定义好的参数类吗?

**Comment by linjiahui020** [comment]
> 

还有就是，这种方式只能局限于方法参数只有一个map的情况吧...假如方法参数除了map也有其他参数，map也可能不止一个，那该如何利用javadoc注释构造整个方法的body 包含map的结构

**Comment by linjiahui020** [comment]
上传到yapi上面的模块文件夹显示

**Comment by tangcent** [comment]
[folder.name](https://easyyapi.com/setting/rules/folder_name.html)

**Comment by linjiahui020** [comment]
请问it.args()，it.argTypes()是什么类型的参数，我分别用

> 这种问题，应该分成两步。
> 
> * 第一步是思考如何利用javadoc注释来辅助描述清楚这个API的信息
>   第一步产生的结果应该类似这样:
>   
>   1. 忽略类型为map的参数
>   2. 从方法注释上读取`@body`作为`RequestBody`
>   3. ...
> * 第二步是思考如果利用规则让插件知道如何解析`第一步`定义出来的javadoc
>   第二步产生的就是对应第一步下列出来的每一条规则了:
>   
>   1. param.ignore=...
>   2. export.after[#body]=...
>   3. ...
> 
> 如果你对`easyyapi`的规则不熟悉的话，你可以先考虑第一步，然后提供一个demo给我，我帮你完成第二步。

按照你这个思路，我成功实现了，但是通过api.setJsonBody这种方式构造参数，貌似就不能显示参数是否必须以及备注的内容了，有解决的办法吗

**Comment by tangcent** [comment]
> 请问it.args()，it.argTypes()是什么类型的参数，我分别用

http://easyyapi.com/setting/tools/it.html

> 按照你这个思路，我成功实现了，但是通过api.setJsonBody这种方式构造参数，貌似就不能显示参数是否必须以及备注的内容了，有解决的办法吗

看看: http://easyyapi.com/setting/tools/api.html
还有个setBodyClass("class")方法，不知道你能不能用上

**Comment by linjiahui020** [comment]
> 

setBodyClass("class")这种我这边没法用，没有这样的类，现在我是自己构造json字符串然后解析成jsonObject传进api.setJsonBody里面，然后貌似这样子 参数的备注和是否必须 这些信息都会丢掉。有什么方式能用setJsonBody的同时，又能显示入参的其他信息

**Comment by tangcent** [comment]
你要提供这么多信息，javadoc准备怎么写呢? 可能会导致注释过于复杂?

**Comment by linjiahui020** [comment]
是否为必须参数这个信息不需要javadoc，用别的注解配置到参数上就好了。至于备注这个，也不复杂吧，类似@param 变量名 注释 不就好了。主要是不知道如何将这些信息放进jsonbody里

**Comment by tangcent** [comment]
> 如何将这些信息放进jsonbody里

很麻烦，需要理解现在插件里是怎么做的:
https://github.com/tangcent/easy-yapi/blob/master/common-api/src/main/kotlin/com/itangcent/common/constant/Attrs.kt
大概会是这样的结构: 
```json
{
    "field": 0,
    "@required": {
        "field": false,
        "id": false,
        "type": false,
        "name": true,
        "age": true,
        "sex": false,
        "birthDay": false,
        "regtime": false
    },
    "@comment": {
        "field": "End-Of-Line Comments",
        "id": "用户id",
        "type": "用户类型",
        "type@options": [
            {
                "value": 1,
                "desc": "管理员"
            },
            {
                "value": 2,
                "desc": "成员"
            },
            {
                "value": 3,
                "desc": "游客"
            }
        ],
        "name": "用户名",
        "age": "年龄",
        "sex": "「已废弃」It\u0027s a secret",
        "birthDay": "生日",
        "regtime": "注册时间"
    },
    "id": 0,
    "type": 0,
    "name": "",
    "age": 0,
    "sex": 0,
    "birthDay": "",
    "regtime": ""
}
```
---

> 至于备注这个，也不复杂吧，类似@param 变量名 注释 不就好了

不能完全想象出来这里的注释会是个什么样子.

**Comment by linjiahui020** [comment]
{"ssid":"","uid":"","room_type":"","@required":{"ssid":true,"uid":true,"room_type":true},"@comment":{"ssid":"ssid test","uid":"uid test","room_type":""}} 我最后构造出这样的结构，但是yapi上面并没有显示出参数的是否必须和备注

**Comment by tangcent** [comment]
这里的处理有点问题: https://github.com/tangcent/easy-yapi/pull/857

[easy-yapi-2.4.7.191.0.zip](https://github.com/tangcent/easy-yapi/files/9976239/easy-yapi-2.4.7.191.0.zip)
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/17569144/200973718-6ac0c99d-d5da-40f6-aa55-ff3bde3bc438.png">

**Comment by linjiahui020** [comment]
好的，感谢，可以正常显示了

**Comment by linjiahui020** [comment]
为什么map类型和list<map>类型的参数会在yapi上显示key.key参数名并且无法正常显示参数类型，这部分代码是在哪里？底层原因是什么？

**Comment by tangcent** [comment]
> 为什么map类型和list类型的参数会在yapi上显示key.key参数名并且无法正常显示参数类型

需要提供一个demo来重现你的问题

> 这部分代码是在哪里？底层原因是什么？

https://github.com/tangcent/easy-yapi/blob/b92b5ec3ad4499251ca4e83a8fc865235ae0821e/idea-plugin/src/main/kotlin/com/itangcent/intellij/util/KVKit.kt#L95

如果在Java中定义了一个`Map`参数, 插件并不能判断这个Map中会有哪些`key`, 所以这里默认给了个`key`

**Comment by linjiahui020** [comment]
<img width="196" alt="image" src="https://user-images.githubusercontent.com/48832114/203464277-d0b63e98-4068-48cb-a8a5-c4abe291c35b.png">
![image](https://user-images.githubusercontent.com/48832114/203464308-657512ab-ae4e-4436-9b6d-9b31dd627feb.png)
还有这个，貌似用上面那种api.setJsonBody()的方式只能显示number类型，而不是double类型。我的jsonbody是{"key": 0.1}类似这样

**Comment by linjiahui020** [comment]
<img width="238" alt="image" src="https://user-images.githubusercontent.com/48832114/203464506-9d172b50-269e-4b99-ae81-7ad94171e15c.png">

![企业微信截图_71489679-8a79-4c16-b8bc-0a1a2e6b5454](https://user-images.githubusercontent.com/48832114/203464461-fab0e2e7-5606-4ffd-9db0-6d1d2d18bed8.png)

还有这个，貌似用上面那种api.setJsonBody()的方式只能显示number类型，而不是double类型。我的jsonbody是{"key": 0.1}类似这样

**Comment by tangcent** [comment]
`yapi`似乎不支持`double`类型?

**Comment by lunfangyu** [comment]
> 还有一个问题就是除了@requestbody，还有什么其他注解或者配置方式能将参数从query放到json request body中。目前我这边的api中是多个参数的，不能用@requestbody显示成json body

使用@ModelAttribute ParamDTO paramDTO  既可以接收body参数，也可以接收query参数

**Comment by lunfangyu** [comment]
> 使用@ModelAttribute ParamDTO paramDTO 既可以接收body参数，也可以接收query参数
参数还是使用实体类比较好，使用Map对后面维护很不友好
