### ISSUE TITLE
[Bug] dubbo项目中会生成多余接口文档

### ISSUE THREAD

**Issue by worldcoding** [tangcent/easy-yapi#859]
1、会把没有任何注解标识的方法也生成到接口文档中
2、未使用标识api注解的方法也生成到接口文档中了，比如我定义的注解是@OpenApi来标识这个方法是开放的api，但是未标识的方法也会生成到文档中，针对方法配置如下：
# generic.method.has.api
generic.method.has.api=@com.universty.gateway.annotation.OpenApi

**Comment by tangcent** [comment]
http://easyyapi.com/documents/generic.html

使用`Generic`的同时，不要勾选`methodDoc`

**Comment by worldcoding** [comment]
没有勾选`methodDoc`
![image](https://user-images.githubusercontent.com/13378254/202659357-50cdc22d-b509-4067-8644-76b304bb1728.png)

**Comment by tangcent** [comment]
你是不是用了`dubbo.config`?
https://github.com/tangcent/easy-yapi/blob/b92b5ec3ad4499251ca4e83a8fc865235ae0821e/third/dubbo.config#L20

`dubbo.config`默认了全部方法都是API，如果你需要自定义的话，就不能引用`dubbo.config`，可以把`dubbo.config`里的内容copy到你自己的配置文件里

**Comment by worldcoding** [comment]
是的，引用了dubbo.config；`generic.method.has.api=true ` 是这个导致的是么？
