### ISSUE TITLE
[Question] Generic(自定义框架)

### ISSUE THREAD

**Issue by luckygqx** [tangcent/easy-yapi#861]
![image](https://user-images.githubusercontent.com/57888095/203036685-b4ef24b4-4eb8-4332-ab24-be138506fd10.png)
请问，这个配置修改后应该放在哪个配置文件呢，并且应该放在项目的什么位置

**Comment by luckygqx** [comment]
我需要用自定义注解替换spring的@Controller注解

**Comment by tangcent** [comment]
`generic`文档: http://easyyapi.com/documents/generic.html
配置放在项目根目录即可: http://easyyapi.com/setting/local-file-config.html
也可以放在<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>BuildInConfig</kbd> 或者<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> >  <kbd>Remote</kbd>里
