### ISSUE TITLE
关于@real_return标记使用场景

### ISSUE THREAD

**Issue by lunfangyu** [tangcent/easy-yapi#866]
在 [[所有响应统一包装配置](https://easyyapi.com/setting/rules/method_return.html)](https://easyyapi.com/setting/rules/method_return.html) 中，在添加如下配置后：

```
method.return[#real_return]=groovy: "com.itangcent.common.dto.Result<" +  helper.resolveLink(it.doc("real_return")) +">"
```

使用方式：

```
/**
 * @real_return {@link UserInfo}
 */
```

这里建议优化为：

```
/**
 * @return {@link UserInfo}
 */
```

理由：

1. 尽量使用javadoc原生标记，减少割裂感
2. 不用调整IDE注释模板，方便使用

如果是**部分接口进行返回包装**，则保持不变，仍然使用@real_return标记。

**Comment by tangcent** [comment]
文档都只是示例而已，最好根据自身的情况做响应的调整。
比如这里你可以自行配置为:
`method.return[#return]=groovy: "com.itangcent.common.dto.Result<" +  helper.resolveLink(it.doc("return")) +">"`

**Comment by lunfangyu** [comment]
> 文档都只是示例而已，最好根据自身的情况做响应的调整。 比如这里你可以自行配置为: `method.return[#return]=groovy: "com.itangcent.common.dto.Result<" + helper.resolveLink(it.doc("return")) +">"`

感谢回复，我明白了，我还以为那里仅限使用@real_return标记呢
