### ISSUE TITLE
[Bug] 导出返回值为List<T>类型的接口有警告错误

### ISSUE THREAD

**Issue by lunfangyu** [tangcent/easy-yapi#867]
当Controller存在返回值为List<T>类型的接口的接口时，导出会有如下警告报错。
![image_20221124181743](https://user-images.githubusercontent.com/41062458/203761599-4bd1657f-1b2e-43ae-bcac-f93f1e8ef653.png)

把List<T>类型的接口去掉后就正常

**Comment by tangcent** [comment]
- 这个错误可以忽略。我修改一下提示。
- 另外你这里的方法return的就是`List<ApiInfoDTO>`为什么还要用`@return`再写一遍?

**Comment by lunfangyu** [comment]
> * 另外你这里的方法return的就是`List<ApiInfoDTO>`为什么还要用`@return`再写一遍?

我是刚接触easyYapi；一开始@return后面我是不写类型的，但发现如果不写，又会有如下报错：
![image_20221124214948](https://user-images.githubusercontent.com/41062458/203800814-930020f7-0c29-4811-a0e8-c23fbd09a2e0.png)

之后我参考官方文档看到有写，并且写了之后不再有这个报错，我就给每个接口都加上了。
我个人也觉得不写才是比较简洁的，但因为那个错误警告，我又加上了
如有使用得不对的地方，请多指教.

**Comment by tangcent** [comment]
- 这里的`WARN`日志我看看是什么原因产生的。
- `EasyYapi`提供这么多规则的初衷是让开发者们: 尽量利用规则来让插件适配代码，而不是改动代码来适配插件。
思路可以参考: https://github.com/tangcent/easy-yapi/issues/854#issuecomment-1305586201

**Comment by lunfangyu** [comment]
学习了，非常感谢！
