### ISSUE TITLE
Are there any plans to support the playframework project?

### ISSUE THREAD

**Issue by zmingchun** [tangcent/easy-yapi#87]

**Comment by tangcent** [comment]
- Hi~,I am a newbie to play, I will try to support play as much as possible, but there may be some situations that are not considered.
- Required feature list:
  - Try read HTTP Method&Path from route:it seems that the `routes` could always be found at `$module/conf/routes`
  - Try rend result of api: [PostController.java](https://github.com/playframework/play-samples/blob/2.7.x/play-java-rest-api-example/app/v1/post/PostController.java), Hum, it seems diffcult to~
  - Support for scala: It will take a looong time~

**Comment by zmingchun** [comment]
WOW! Thank you for your work !
