### ISSUE TITLE
使用${}时，报错unable to resolve property XX

### ISSUE THREAD

**Issue by yejunxi** [tangcent/easy-yapi#873]
版本：IDEA 2021
EASY YAPI：最新版本

根据文档：http://easyyapi.com/setting/rules/class_prefix_path.html
插件配置：class.prefix.path=${server.servlet.context-path}
application.yml与bootstrap.yml 均配置了server.servlet.context-path}
但是
生成文档时会报错：[ERROR]	unable to resolve property:server.servlet.context-path

**Comment by tangcent** [comment]
可能的问题:
1.  <kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd>Recommend</kbd> 中的`import_spring_properties`未勾选  
https://github.com/tangcent/easy-yapi/blob/5aa7a7c04c9ace3de881614755ad6283b4243d29/idea-plugin/src/main/resources/.recommend.easy.api.config#L210-L218
2. 如1所示，插件找的是`${module_path}/src/main/resources/`目录, 如果`yml `文件并未存放在该目录下，插件将无法解析。
3. `application.yml`与`bootstrap.yml`中有占位符${}，导致插件无法解析`yml`。  
  这个问题我还没有找到好的解决方案

---

Anyway, 兜底方案是直接设置: `class.prefix.path=/xxx`

**Comment by yejunxi** [comment]
感谢解惑，问题已解决。

**Comment by tangcent** [comment]
我想到一个方案，解析`yml`前做一次文本替换，解析后处理过程中再换回来，也许可以解决这个问题。
