### ISSUE TITLE
[Question] 无法解决自定义validation注解的分组问题

### ISSUE THREAD

**Issue by sandangjia** [tangcent/easy-yapi#875]
**Describe the question**

无法解决自定义validation注解的分组问题

**Expected result**

比如，系统中定义了一些自定义注解，最常见的比如 @NotEmpty 这个注解，这个注解实际上是不能达到预计的效果的，实践中发现，有时候前端会将 undefined 或 null 这些字符串上传，所以我定义了一个自定义注解代替原来的注解。
代码中这样使用
    @CheckNotNull(message = "请输入测试工具名称")
    private String name;
这样是正常的，但有时候会有特殊情况，

@Null(message = "无效ID", groups = AddGroup.class)
@CheckNotNull(message = "非法ID", groups = UpdGroup.class)
private String id;

这个时候，根据分组来区分的配置就无效了，上传到y-api 都是显示必填。

我所做的尝试有如下：
1、将这里的配置修改了
2、增加了配置文件

![图片](https://user-images.githubusercontent.com/22360223/206639089-6ee47eb0-0c1c-4d64-8ca2-88e5c0cd402e.png)

![图片](https://user-images.githubusercontent.com/22360223/206639217-5392f4fa-3584-480d-a29c-53cc28391381.png)

**Screenshots**

**Demo Code**

1. Fork https://github.com/Earth-1610/spring-demo
2. Write some code
3. Now paste the forked repository hear: https://github.com/xxxx/spring-demo

**Additional context**

**Comment by tangcent** [comment]
1. 勾选`javax.validation(grouped)`
2. 模仿https://github.com/tangcent/easy-yapi/blob/5aa7a7c04c9ace3de881614755ad6283b4243d29/idea-plugin/src/main/resources/.recommend.easy.api.config#L171-L173
``````
field.required[@com.rs.testplatform.annotations.CheckNotNull]=groovy:```
    it.annMaps("com.rs.testplatform.annotations.CheckNotNull")?.any{tool.equalOrIntersect(session.get("json-group"),it["groups"])}
```
``````

**Comment by sandangjia** [comment]
非常感谢

**Comment by sandangjia** [comment]
经过测试，发现在配置中添加
field.required[@com.rs.testplatform.annotations.CheckNotNull]=groovy:```
    it.annMaps("com.rs.testplatform.annotations.CheckNotNull")?.any{tool.equalOrIntersect(session.get("json-group"),it["groups"])}
```
后发现有一个问题，
首先说下已有的配置，
1、开启recommend 中的选项，选择 javax.validation(grouped)
2、在配置文件中添加

# 自定义注解
field.required=@com.rs.testplatform.annotations.CheckNotNull


# ===================================================================
# validation 相关
# ===================================================================

# 对分组进行验证，需要开启分组
field.required[@com.rs.testplatform.annotations.CheckNotNull]=groovy:```
    it.annMaps("com.rs.testplatform.annotations.CheckNotNull")?.any{tool.equalOrIntersect(session.get("json-group"),it["groups"])}
```
如上配置
3、代码中的使用方式为
![图片](https://user-images.githubusercontent.com/22360223/206730767-5ee47694-573d-4794-832f-41e2f8068881.png)
![图片](https://user-images.githubusercontent.com/22360223/206730947-b7c4c0f3-eba4-4c8d-844c-49a5fe2d2b12.png)

以上这种方式的使用，还存在一个问题会导致在yapi中都显示必传，当是新增的时候 @Null(message = "无效ID", groups = AddGroup.class) 这个是无效的。

排查原因在 定义的接口，
![图片](https://user-images.githubusercontent.com/22360223/206731424-3e6bcc23-740a-4523-be01-99cc17e0e7a4.png)
如上这种写法有问题，下面注释的这种写法 不会有问题，下面这种写法上传到yapi则是正常的，但必须添加这个继承关系。
如果不添加默认的validation 的继承，在model的编写时候，如下方式将不能进行验证
![图片](https://user-images.githubusercontent.com/22360223/206731881-f8e6dab9-1fe9-4a78-aa5f-7478890b0f7d.png)
要写成这样才行
![图片](https://user-images.githubusercontent.com/22360223/206732158-0c020fcd-deeb-47f1-bd10-7ae7381ad449.png)
这会导致增加很大的负担，如何解决这个问题呢？

**Comment by sandangjia** [comment]
感觉上面说的有点凌乱，问题就在于，如果 定义的分组接口继承了默认的 Default 接口，会导致上传后都显示必传，如果不继承，又会导致自定义注解增加非常多的工作量

**Comment by tangcent** [comment]
`field.required`是`ANY`模式，只要有一个规则返回`true`就是必填的。
https://github.com/tangcent/easy-yapi/blob/5aa7a7c04c9ace3de881614755ad6283b4243d29/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/api/export/core/ClassExportRuleKeys.kt#L92-L95
https://github.com/Earth-1610/intellij-kotlin/blob/4e6b4ebc45fe0dba5a6d84c0e9db68103e3ceb54/intellij-idea/src/main/kotlin/com/itangcent/intellij/config/rule/RuleMode.kt#L51

所以你这里同时定义了两个规则的情况下，即使配了`groups`,也会因为命中了第一条规则，被插件识别为必填
``````
# 自定义注解
field.required=@com.rs.testplatform.annotations.CheckNotNull


# ===================================================================
# validation 相关
# ===================================================================

# 对分组进行验证，需要开启分组
field.required[@com.rs.testplatform.annotations.CheckNotNull]=groovy:```
    it.annMaps("com.rs.testplatform.annotations.CheckNotNull")?.any{tool.equalOrIntersect(session.get("json-group"),it["groups"])}
```
``````

**Comment by sandangjia** [comment]
是否有什么办法可以解决这个问题呢？是否只能去掉Default 的继承关系解决？

**Comment by tangcent** [comment]
去掉
```
# 自定义注解
field.required=@com.rs.testplatform.annotations.CheckNotNull
```
就可以了

**Comment by sandangjia** [comment]
最早我就怀疑是这个问题，然后将这个代码注释掉
# 自定义注解
# field.required=@com.rs.testplatform.annotations.CheckNotNull
但测试并没有效果，然后又将
# field.required=@"javax.validation.constraints.NotBlank
# field.required=@javax.validation.constraints.NotNull
# field.required=@javax.validation.constraints.NotEmpty
这一块的代码全部注释掉，也达不到想要的效果，最终确定最优解就是将
public interface UpdGroup extends Default {
}

这一块的代码不继承 Default

**Comment by sandangjia** [comment]
然而去掉Default又会增加代码的复杂度，要写大量的
@CheckNotNull(message = "非法ID", groups = UpdGroup.class) 代码

**Comment by tangcent** [comment]
我知道了。我很少用`validation`包，所以没考虑到`javax.validation.groups.Default`。

**Comment by sandangjia** [comment]
这是要等待idea最新的插件更新了吗？似乎idea2018好像版本就一直 v2.3.3.183.0 这个版本了，这些旧版本不在更新了吗？

**Comment by tangcent** [comment]
对，维护对太多旧的版本兼容性负担太大了, 所以基本上支持的版本会控制在近3年左右。
