### ISSUE TITLE
[Question] unsupported script type:groovy,script:it.name().endsWith("Service")

### ISSUE THREAD

**Issue by Jabriel0602** [tangcent/easy-yapi#880]
插件版本：2.5.0.191.0
问题描述：dubbo接口导出，偶尔出现 unsupported script type:groovy,script:it.name().endsWith("Service")

**Comment by Jabriel0602** [comment]
> 请大佬指点 感谢

**Comment by Jabriel0602** [comment]
日志如下
[INFO]	Start find apis...
[TRACE]	find config file:/Users/didi/workspace/java/optimus/api/.yapi.config
[DEBUG]	use recommend config
[DEBUG]	use built-in config
[ERROR]	unsupported script type:groovy,script:it.name().endsWith("Service")

**Comment by Jabriel0602** [comment]
unsupported script type:groovy,script:it.name().endsWith("Service")
IDEA 2022.2 功能昨天正常使用,今天开始报错
IDEA 更新到 2022.3 功能又正常啦。这个报错是 IDEA 的兼容问题吗

**Comment by tangcent** [comment]
不属于 IDEA 的兼容问题，不过和IDEA运行时的JDK有关，按说如果有问题的话应该是必现的。
你点击`About Intellij IDEA`看看JDK版本是多少

**Comment by Jabriel0602** [comment]
当前最新版本恢复正常了, 信息如下
Runtime version: 17.0.5+1-b653.14 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.
