### ISSUE TITLE
[Question] 作者您好，在我的response中存在嵌套引用了很多其他对象，导致导出的json response Demo达到了几万行，请问该如何解决。

### ISSUE THREAD

**Issue by chuanglc** [tangcent/easy-yapi#883]
![image](https://user-images.githubusercontent.com/72680521/208041813-f482e7bd-5db7-44c0-95c7-41a1081ea1a7.png)

**Comment by tangcent** [comment]
- 利用 [field.ignore](http://easyyapi.com/setting/rules/field_ignore.html)过滤掉一些不需要序列化的字段。
- 利用[json.rule.convert](https://easyyapi.com/setting/rules/json_rule_convert.html)处理一些特殊的类

**Comment by chuanglc** [comment]
作者，您好，我还有个问题。可不可以限制json序列化的层级数量呢，比如4层以后，所有的引用类型都被解析为obj或者null。

**Comment by tangcent** [comment]
这个页面有列出一些简单的规则: https://easyyapi.com/setting/config-rule.html

这里你可以这样配置：
```properties
max.deep=4
```

你也可以这样限制最大字段数：
```properties
max.elements=512
```

**Comment by chuanglc** [comment]
感谢解答。

**Comment by JTongChen** [comment]
> 这个页面有列出一些简单的规则: https://easyyapi.com/setting/config-rule.html
> 
> 这里你可以这样配置：
> 
> ```ini
> max.deep=4
> ```
> 
> 你也可以这样限制最大字段数：
> 
> ```ini
> max.elements=512
> ```

碰到类似的需求，类的字段较多，层级嵌套多层，但是加了这个配置，生成的文档还是会出现null
![企业微信截图_17323341054919](https://github.com/user-attachments/assets/18eb40cb-aca8-42e2-a981-f2d505895638)

![image](https://github.com/user-attachments/assets/aa53f8ce-646b-41d7-91e4-fe2baa370426)

**Comment by tangcent** [comment]
@JTongChen 要不你试试只配`max.deep`不配`max.elements`? 看看效果怎么样
