### ISSUE TITLE
[Question] 实体类里面的json字段解析

### ISSUE THREAD

**Issue by xuguoqin** [tangcent/easy-yapi#886]
**描述**

我有一个实体类，里面有个字符串的json字段，我现在需要给生成的文档上面加一个json的备注，目前的备注是手动拼写的，可不可以通过什么方式指定实体类来生成对应的json字符串呢，我这里有多种类型的json值，所以只能用字符串接收

**Demo Code**
mode类
```
@Data
public class Demo implements Serializable {

    /**
     * 配置json {"from":0,"to":0,"bonus":0}
     */
    @NotNull
    private String configJson;

}
```
实体类
```
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Range {

    /**
     * from
     */
    private Integer from;

    /**
     * to
     */
    private Integer to;

    /**
     * 奖金
     */
    private Integer bonus;
}
```

**Comment by tangcent** [comment]
https://easyyapi.com/qa/index.html#%e6%9c%89%e7%9a%84%e5%ad%97%e6%ae%b5%e5%8f%af%e8%83%bd%e6%9c%89%e4%b8%8d%e5%90%8c%e7%b1%bb%e5%9e%8b%e7%9a%84%e5%80%bc

**Comment by xuguoqin** [comment]
ok，解决了我的问题，感谢

**Comment by xuguoqin** [comment]
有一个小的疑问，就是这种生成的json里面不能添加字段注释吗，结果只是一个json结构

**Comment by tangcent** [comment]
`it.toJson`改成`it.toJson5`试试

**Comment by xuguoqin** [comment]
可以了，非常感谢

**Comment by SuperCC25513** [comment]
可以问下最后怎么成功的吗,我添加一下的配置后 无法运行 脚本错误
` field.doc[#maybe]=groovy:it.docs("maybe").collect{helper.resolveLink(it)}.collect{"可能是:\n\n```json\n" + it.toJson5(true) +"\n```\n\n"}.join("\n")
`

**Comment by SuperCC25513** [comment]
您好，我在添加该配置后 导出报错
`field.doc[#maybe]=groovy:it.docs("maybe").collect{helper.resolveLink(it)}.collect{"\n\n```json\n" + it.toJson(true) +"\n```\n\n"}.join("\n")
`
错误信息：
ScriptRuleParser$ScriptPsiClassContext.toJson() is applicable for argument types: (Boolean) values: [true]
Possible solutions: toJson(), toJson(boolean, boolean), toJson5(), toJson5(boolean, boolean), docs(java.lang.String)

**Comment by tangcent** [comment]
改用`it.toJson(true,true)`或者`it.toJson5(true,true)`, 文档没及时更新
