### ISSUE TITLE
[Question] 作者大大您好！想问一下接口参数中，如何忽略掉@RequestAttribute修饰的参数，不识别上传到yapi中呢

### ISSUE THREAD

**Issue by GHASCZ** [tangcent/easy-yapi#887]
另外还有就是上传到yapi的接口信息里，是否可以用注解来区分query param 和body呀

**Comment by GHASCZ** [comment]
param.ignore这个是不是要安装swagger才可以使用呀

**Comment by tangcent** [comment]
不是，那只是示例。
看这个页面最下面: https://easyyapi.com/setting/config-rule.html

**Comment by GHASCZ** [comment]
这样写可以吗
![image](https://user-images.githubusercontent.com/33053791/211557646-d00e551e-e78c-416b-9b5f-4571bb231946.png)
可是我最终识别的结果 还是将这个注解修饰的对象识别成了body

**Comment by tangcent** [comment]
是这样写，不过yaml解析`@`还是有问题。
你试试换成`.easy.api.config`
```properties
param.ignore=@org.springframework.web.bind.annotation.RequestAttribute
```

**Comment by GHASCZ** [comment]
好的 谢谢作者大大 已解决
