### ISSUE TITLE
api.tag[#tag]=groovy:"kop=" + it.doc("tag"), 当 tag 中存在字符n时,n 会被解析为分隔符

### ISSUE THREAD

**Issue by Jabriel0602** [tangcent/easy-yapi#891]
插件版本：2.5.0.191.0 
问题描述：
api.tag[#tag]=groovy:"kop=" + it.doc("tag"), 当 tag 中存在字符n时,n 会被解析为分隔符
示例：当@tag action_add 时, 生成 tag 为 actio, _add。

**Comment by tangcent** [comment]
对tag的处理有问题。
你先配一下
```
api.tag.delimiter=,
```

**Comment by Jabriel0602** [comment]
> 
新增配置 api.tag.delimiter=, 后解决了该问题 感谢。
