### ISSUE TITLE
[Question] 接口参数类型为 String 类型, 想把参数渲染为json形式

### ISSUE THREAD

**Issue by Jabriel0602** [tangcent/easy-yapi#899]
插件版本: 2.5.0.191.0

一、问题描述。
接口参数 param 类型为 String.calss, 使用上入参为 InputEnum.class 的jsonString形式。期待效果 param 直接渲染为 InputEnum.class 。
使用 @link 方式效果不符合预期, 我的使用方式是否正确呢? 

二、问题补充-本地配置及导出效果。
1).配置内容 
参考文档: http://easyyapi.com/documents/java_doc_demo.html#api-demo （api-demo 模块）
    /**
     * 用户标签列表
     * @param param {@link InputEnum}
     */
    RpcResult<List<InputEnum>> queryDriverTagList(String param);

2).导出效果
Query：
参数名称 | 是否必须 | 示例 | 备注
param      | 否             |           |  [InputEnum]

**Comment by tangcent** [comment]
`InputEnum`是枚举还是`DTO`类?
期望的导出效果是什么样的?

**Comment by Jabriel0602** [comment]
InputEnum 为 DTO 类
期望使用 InputEnum 的渲染代替 原参数的渲染

--------------原始邮件--------------
发件人："tangcent ***@***.***&gt;;
发送时间：2023年1月10日(星期二) 上午9:16
收件人："tangcent/easy-yapi" ***@***.***&gt;;
抄送："Jabriel0602 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [tangcent/easy-yapi] [Question] 接口参数类型为 String 类型, 想把参数渲染为json形式 (Issue #899)
-----------------------------------

 

 
InputEnum是枚举还是DTO类?
 期望的导出效果是什么样的?

**Comment by tangcent** [comment]
目前的规则不好实现这样的效果

**Comment by tangcent** [comment]
Patch with #903:  [easy-yapi-2.5.2.191.0.zip](https://github.com/tangcent/easy-yapi/files/10420162/easy-yapi-2.5.2.191.0.zip)


config:
``````
param.ignore=groovy:```
    def doc = it.method().doc("param",it.name())
    if(doc==null){
        return
    }
    def cls = helper.resolveLink(doc)
    return cls!=null
```
export.after=groovy:```
    for(param in it.args()){
        def doc = it.doc("param",param.name())
        if(doc==null){
            return
        }
        def cls = helper.resolveLink(doc)
        if(cls!=null){
            api.addModelAsParam(cls.toObject(true,true,true))
        }
    }
```
``````

**Comment by Jabriel0602** [comment]
这个方式解决了我的问题，十分感谢您！
