### ISSUE TITLE
SpringBoot export api to Yapi server with @RequestMapping("adv“)

### ISSUE THREAD

**Issue by watersoona** [tangcent/easy-yapi#9]
**Describe the bug**
SpringBoot export api to Yapi server with @RequestMapping("adv“)

**To Reproduce**

**Expected behavior**
auto fill '/' to path.

**Screenshots**
error log:
search api from:com.pengshu.thanos.admin.controller.AdvCustomerController
[INFO]	Post failed:path第一位必需为 /, 只允许由 字母数字-/_:.! 组成

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tangcent** [comment]
This looks like the path in [RequestMapping] on the controller does not start with "/",
And yapi does not support such path pattern, so we need to format it with prefix "/" while parsing the api for yapi.
