### ISSUE TITLE
[Question] 作者您好！想问下接口处提供注解用来指定上传到不同的项目和分类吗

### ISSUE THREAD

**Issue by GHASCZ** [tangcent/easy-yapi#901]
我看module注解作用在类上并且只指定上传的项目，目前有木有作用在接口上的指定项目和分类的注解呢

**Comment by tangcent** [comment]
`module`对method也有效
你可以试试在接口上注释`@module xxxx`

**Comment by GHASCZ** [comment]
这个我尝试使用了@module 项目名.分类名   或者  @module 项目名/分类名  发现都没能上传到项目下指定的分类呢

**Comment by tangcent** [comment]
哦，我知道你的意思了。
你可以用`@module`来指定项目。

再利用[folder.name](http://easyyapi.com/setting/rules/folder_name.html)来指定分类
你需要配置一下:
```properties
# read folder name from tag `folder`
folder.name=#folder
```

**Comment by GHASCZ** [comment]
好的 已解决
