### ISSUE TITLE
Delete Prefix Path

### ISSUE THREAD

**Issue by yanye666** [tangcent/easy-yapi#902]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/42414099/211986998-0072b754-b1ba-46a3-acff-bfb4a706832a.png)
代码：
![image](https://user-images.githubusercontent.com/42414099/211987049-391ba5ee-3c73-41d2-99a6-6b92303b3bcc.png)
结果：
![image](https://user-images.githubusercontent.com/42414099/211987087-9c28aac5-08d1-46db-a29b-c963d864ccad.png)

希望：
想要删除前缀，也就是只有一个support前缀，因为yapi是有一个自带前缀的了

**Comment by tangcent** [comment]
试试[export.after](http://easyyapi.com/setting/rules/export_after.html):
``````
export.after=groovy:```
    api.setPath(tool.removePrefix(api.path(),"/support"))
```
``````

**Comment by yanye666** [comment]
ok，可以了，感谢
