### ISSUE TITLE
[Question]  如何解析groovy编写的接口

### ISSUE THREAD

**Issue by Xavi2r** [tangcent/easy-yapi#906]
**Describe the question**

您好，我有一个controller类是通过groovy实现的，请问下可以通过什么方式解析这个类

**Expected result**

解析groovy实现类

**Comment by Xavi2r** [comment]
在本地加上groovy枚举后执行./gradlew :idea-plugin:runIde上传ok了 
![image](https://user-images.githubusercontent.com/16552762/212654841-b0a7d3c3-78a2-497e-aceb-0608aaf84cac.png)

**Comment by tangcent** [comment]
> 在本地加上groovy枚举后执行./gradlew :idea-plugin:runIde上传ok了

`groovy`和`scala`一样, PSI结构和`java`有相当一部分是一致的。但是可能会有一些兼容性的问题需要处理。
等我有时间的时候试试`groovy`的兼容性问题有多少。

**Comment by Xavi2r** [comment]
> > 在本地加上groovy枚举后执行./gradlew :idea-plugin:runIde上传ok了
> 
> `groovy`和`scala`一样, PSI结构和`java`有相当一部分是一致的。但是可能会有一些兼容性的问题需要处理。 等我有时间的时候试试`groovy`的兼容性问题有多少。

棒！感谢作者大大~

**Comment by tangcent** [comment]
Patch with #912: [easy-yapi-2.5.3.191.0.zip](https://github.com/tangcent/easy-yapi/files/10702273/easy-yapi-2.5.3.191.0.zip)

有空的话试试看
