### ISSUE TITLE
[Feature] 接口路径增加.do这样的配置项

### ISSUE THREAD

**Issue by HumorChen** [tangcent/easy-yapi#907]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
弄一个配置项，可以设置接口后缀名

**Describe alternatives you've considered**

**Additional context**

**Comment by tangcent** [comment]
参考 https://github.com/tangcent/easy-yapi/issues/902#issuecomment-1380398558

**Comment by HumorChen** [comment]
挺好的，已解决
export.after=groovy:```
    api.setPath(api.path()+".do")
```
