### ISSUE TITLE
[Bug] 生成带默认参数的接口&符号转义问题

### ISSUE THREAD

**Issue by shiwenyuan** [tangcent/easy-yapi#909]
配置如图
![image](https://user-images.githubusercontent.com/29530604/216912022-a5961867-bb27-4368-aa6c-ff0042a8db2e.png)
![image](https://user-images.githubusercontent.com/29530604/216912124-9d79be03-94ed-4f98-9380-4d7022195124.png)

控制台打印结果是看起来没有问题的
[INFO]	apiName flag append, kopuri:gateway?api=freight.open.platform.flowchannel.queryCancelAlert&appKey=4329d266f40144829ca5fd47a025e106&appVersion=1.0.0

但是系统实际录入的时候吧&符号转换成了/

![image](https://user-images.githubusercontent.com/29530604/216912482-dd1e5e8d-7a55-473a-a08b-5035255b5c30.png)

**Comment by tangcent** [comment]
看一下： http://easyyapi.com/setting/config-rule.html
配置`auto.format.url=false`

Note: 如果你使用的`yapi`没有二次开发过的话，即使你这样设置，也可能得不到你想要的结果。
