### ISSUE TITLE
[Feature] 作者大大，是否考虑支持SpringDoc的注解呢？

### ISSUE THREAD

**Issue by JoieLu** [tangcent/easy-yapi#910]
例如 Spring Doc 的 @Schema 注解

**Comment by tangcent** [comment]
我没用过，是不是和[swagger3.config](https://github.com/tangcent/easy-yapi/blob/master/third/swagger3.config)差不多?

**Comment by JoieLu** [comment]
是的 我用这个配置文件稍微修改一下就可以了
