### ISSUE TITLE
[Question] 不同接口，同一个类做参数，每个接口的参数不一样，如何过滤掉没用到的参数呢

### ISSUE THREAD

**Issue by Pretends** [tangcent/easy-yapi#911]
**Describe the question**

A clear and concise description of what the question is.

**Expected result**

A clear and concise description of what you expected to get.

**Screenshots**

**Demo Code**

1. Fork https://github.com/Earth-1610/spring-demo
2. Write some code
3. Now paste the forked repository hear: https://github.com/xxxx/spring-demo

**Additional context**

**Comment by tangcent** [comment]
参考一下之前的issues:

- https://github.com/tangcent/easy-yapi/issues/630#issuecomment-950238874
- https://github.com/tangcent/easy-yapi/issues/703
- https://github.com/tangcent/easy-yapi/issues/549

基本上套路都是一样的
