### ISSUE TITLE
[Question] tag使用报错

### ISSUE THREAD

**Issue by JTongChen** [tangcent/easy-yapi#914]
接口注释使用@tag XXX，yapi上面保存编辑保存之后会报错
![image](https://user-images.githubusercontent.com/17989583/219345586-e9f743b3-4009-4295-bbb1-c5a9eb0a64c7.png)

**Comment by tangcent** [comment]
这是`yapi`里的一个BUG，由于`yapi`目前处于无人维护的状态，这个BUG也一直没有修复。
ref: https://github.com/YMFE/yapi/pull/2374
