### ISSUE TITLE
[Bug]开启 infer enable 后，field.ignore 定义的注解就失效了

### ISSUE THREAD

**Issue by hyuk-sudo** [tangcent/easy-yapi#919]
**Describe the bug**

当开启 enable infer 后，原来用 field.ignore 定义的注解忽略某个字段去生成文档，文档里返回值又包含这个字段定义了。

idea 版本：2022.3.3 Preview
插件版本：2.5.3.191.0

**Comment by tangcent** [comment]
> `field.ignore 定义的注解`

规则是怎样的?

**Comment by hyuk-sudo** [comment]
> > `field.ignore 定义的注解`
> 
> 规则是怎样的?

就是在项目里自定义了一个注解，因为不想用 json 那些，怕对原来的那些有影响。
类似这种 field.ignore=@com.ignore.annotaion.TestIgnore#value

**Comment by tangcent** [comment]
我没能重现这个问题

### API:
```java
    @RequestMapping("/return/infer")
    public Object testInfer() {
        return new TestJsonIgnoreBean();
    }
```

### TestJsonIgnoreBean:
```java

public class TestJsonIgnoreBean {

    @Expose(serialize = true)
    private Long shouldNotIgnoreForGson;

    @Expose(serialize = false)
    private Long shouldIgnoreForGson;

    @JsonIgnore(false)
    private Long shouldNotIgnoreForJackson;

    @JsonIgnore
    private Long shouldIgnoreForJackson;
}

```


### 导出结果:


---
## testInfer

> BASIC

**Path:** /test/return/infer

**Method:** GET

> REQUEST

**Headers:**

| name | value | required | desc |
| ------------ | ------------ | ------------ | ------------ |
| token |  | YES | 认证Token |



> RESPONSE

**Headers:**

| name | value | required | desc |
| ------------ | ------------ | ------------ | ------------ |
| content-type | application/json;charset=UTF-8 | NO |  |

**Body:**

| name | type | desc |
| ------------ | ------------ | ------------ |
| shouldNotIgnoreForGson | integer |  |
| shouldNotIgnoreForJackson | integer |  |

**Response Demo:**

```json
{
  "shouldNotIgnoreForGson": 0,
  "shouldNotIgnoreForJackson": 0
}
```

**Comment by hyuk-sudo** [comment]
可以试试这样, 返回类型 Result<T>
忽略字段为 Result 类里的 traceId;
```
@RequestMapping("/return/infer")
    public Result<TestJsonIgnoreBean> testInfer() {
        return Result.success(new TestJsonIgnoreBean());
    }
```

1、开始 enable infer
* 接口返回值设置成 Result<TestJsonIgnoreBean> ，生成文档可正常忽略 traceId;
* 接口返回值设置成 Result<Object>，生成文档 Result 里带 traceId，忽略注解失效;
* 接口返回值直接设置成 Result，不带泛型，生成文档 Result 里带 traceId，忽略注解失效;

2、不开启 enable infer
* 接口返回值设置成 Result<TestJsonIgnoreBean> ，生成文档可正常忽略 traceId;
* 接口返回值设置成 Result<Object>，生成文档可正常忽略 traceId;
* 接口返回值直接设置成 Result，不带泛型，生成文档可正常忽略 traceId;

**Comment by tangcent** [comment]
我还是没能重现这个问题

### API:
```java
    @RequestMapping("/return/infer")
    public Result testInfer() {
        return Result.success(new TestJsonIgnoreBean());
    }
```

### Result:
```java
public class Result<T> implements IResult {

    private Integer code;//响应码

    private String msg;//响应消息

    @JsonIgnore
    private String traceId;

    private T data;//响应数据
}

```


### 导出结果:


---
## testInfer

> BASIC

**Path:** /demo/test/return/infer

**Method:** GET

> REQUEST



> RESPONSE

**Headers:**

| name | value | required | desc |
| ------------ | ------------ | ------------ | ------------ |
| content-type | application/json;charset=UTF-8 | NO |  |

**Body:**

| name | type | required | default | desc |
| ------------ | ------------ | ------------ | ------------ | ------------ |
| code | integer | NO |  | 响应码 |
| msg | string | NO |  | 响应消息 |
| data | object | NO |  | 响应数据 |
| &ensp;&ensp;&#124;─shouldNotIgnoreForGson | integer | NO |  |  |
| &ensp;&ensp;&#124;─shouldNotIgnoreForJackson | integer | NO |  |  |

**Response Demo:**

```json
{
  "code": 0,
  "msg": "success",
  "data": {
    "shouldNotIgnoreForGson": 0,
    "shouldNotIgnoreForJackson": 0
  }
}
```


---

> 就是在项目里自定义了一个注解，因为不想用 json 那些，怕对原来的那些有影响。
类似这种 field.ignore=@com.ignore.annotaion.TestIgnore#value


你会不会是规则写错了?

**Comment by hyuk-sudo** [comment]
因为之前是直接在项目里用的，今天我写了个 demo，可以参考下

.easy.api.config 文件
`field.ignore=@cn.hyuk.annotation.TestIgnore#value`

TestIgnore 注解
```
@Target({ElementType.ANNOTATION_TYPE, ElementType.METHOD, ElementType.CONSTRUCTOR, ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
public @interface TestIgnore {

    boolean value() default true;
}
```

Result 类
```
@AllArgsConstructor
@Data
public class Result<T> implements Serializable {

    private static final long serialVersionUID = 7060006725416008103L;

    private int code;

    private String msg;

    @TestIgnore
    private String traceId;

    private T data;

    public static <T> Result<T> success(T t) {
        return new Result<>(0, "success", "1234", t);
    }
}
```

TestController 类
```
/**
 * 测试接口
 *
 * @module test
 * @author hyuk
 */
@RestController("/test")
public class TestController {

    /**
     * 测试 infer
     *
     * @return
     */
    @GetMapping("/infer")
    public Result testInfer() {
        TestJsonIgnoreBean testJsonIgnoreBean = new TestJsonIgnoreBean();
        return Result.success(testJsonIgnoreBean);
    }
}
```

开启 enable infer 情况下:

# 测试接口

测试接口


---
## 测试 infer

> BASIC

**Path:** /infer

**Method:** GET

> REQUEST



> RESPONSE

**Headers:**

| name | value | required | desc |
| ------------ | ------------ | ------------ | ------------ |
| content-type | application/json;charset=UTF-8 | NO |  |

**Body:**

| name | type | desc |
| ------------ | ------------ | ------------ |
| code | object |  |
| msg | object |  |
| data | object |  |
| traceId | object |  |

**Response Demo:**

```json
{
  "code": null,
  "msg": null,
  "data": null,
  "traceId": null
}
```

关闭 enable infer ：
# 测试接口

测试接口


---
## 测试 infer

> BASIC

**Path:** /infer

**Method:** GET

> REQUEST



> RESPONSE

**Headers:**

| name | value | required | desc |
| ------------ | ------------ | ------------ | ------------ |
| content-type | application/json;charset=UTF-8 | NO |  |

**Body:**

| name | type | desc |
| ------------ | ------------ | ------------ |
| code | integer |  |
| msg | string |  |
| data | object |  |

**Response Demo:**

```json
{
  "code": 0,
  "msg": "",
  "data": {}
}
```

**Comment by tangcent** [comment]
加这个配置，看看输出日志:
``````properties
TestIgnore=com.itangcent.common.constant.TestIgnore
field.ignore=@${TestIgnore}#value
api.class.parse.before=groovy:```
    logger.info("TestIgnore qualifiedName: ${TestIgnore}")
    logger.info("[field.ignore]:\n"+config.getValues("field.ignore").join("\n"))
```
json.field.parse.before=groovy:```
    logger.info("开始解析:"+it.name())
    logger.info(it.name()+" 定义:\n"+it.sourceCode())
    logger.info("ignore "+it.name()+"? "+it.annValue("${TestIgnore}","value"))
```
``````

**Comment by hyuk-sudo** [comment]
[INFO]	search api from: cn.hyuk.TestController
[INFO]	TestIgnore qualifiedName: cn.hyuk.annotation.TestIgnore
[INFO]	[field.ignore]:
@cn.hyuk.annotation.TestIgnore#value
@com.fasterxml.jackson.annotation.JsonIgnore#value
!@com.google.gson.annotations.Expose#serialize
groovy:it.hasModifier("transient")
[INFO]	try infer return type of method[cn.hyuk.TestController#testInfer()]
[INFO]	开始解析:shouldNotIgnoreForGson
[INFO]	shouldNotIgnoreForGson 定义:
private Long shouldNotIgnoreForGson;
[INFO]	ignore shouldNotIgnoreForGson? null
[INFO]	开始解析:shouldIgnoreForGson
[INFO]	shouldIgnoreForGson 定义:
private Long shouldIgnoreForGson;
[INFO]	ignore shouldIgnoreForGson? null
[INFO]	开始解析:shouldNotIgnoreForJackson
[INFO]	shouldNotIgnoreForJackson 定义:
private Long shouldNotIgnoreForJackson;
[INFO]	ignore shouldNotIgnoreForJackson? null
[INFO]	开始解析:shouldIgnoreForJackson
[INFO]	shouldIgnoreForJackson 定义:
private Long shouldIgnoreForJackson;
[INFO]	ignore shouldIgnoreForJackson? null
[INFO]	开始解析:code
[INFO]	code 定义:
private int code;
[INFO]	ignore code? null
[INFO]	开始解析:msg
[INFO]	msg 定义:
private String msg;
[INFO]	ignore msg? null
[INFO]	开始解析:traceId
[INFO]	traceId 定义:
@TestIgnore
    private String traceId;
[INFO]	ignore traceId? true
[INFO]	开始解析:data
[INFO]	data 定义:
private T data;
[INFO]	ignore data? null
[INFO]	开始解析:code
[INFO]	code 定义:
private int code;
[INFO]	ignore code? null
[INFO]	开始解析:msg
[INFO]	msg 定义:
private String msg;
[INFO]	ignore msg? null
[INFO]	开始解析:traceId
[INFO]	traceId 定义:
@TestIgnore
    private String traceId;
[INFO]	ignore traceId? true
[INFO]	开始解析:data
[INFO]	data 定义:
private T data;
[INFO]	ignore data? null
[INFO]	Start parse apis
[INFO]	Exported data are copied to clipboard,you can paste to a md file now

**Comment by tangcent** [comment]
> [INFO]	ignore traceId? true

这日志看起来正常啊，traceId应该被忽略掉了

**Comment by hyuk-sudo** [comment]
> > [INFO]	ignore traceId? true
> 
> 这日志看起来正常啊，traceId应该被忽略掉了

但是生成的 md，traceId 还是有，并且 code、msg 的类型也都变成了 object
