### ISSUE TITLE
[Bug] GET接口导出集合型入参时，参数名应该不是 param[0] 而直接是 param

### ISSUE THREAD

**Issue by ReberMusk** [tangcent/easy-yapi#920]
**Describe the bug**

GET接口导出集合型入参时，参数名(以 param 举例)，应该不是 param[0] 而直接是 param.
现在导出到 Yapi 是 param[0] ，在规范里，其URI 其实直接是: `?param=参数1&param=参数2` 就可以达到后端用集合型入参接收的效果。

**To Reproduce**

Detailed Steps to reproduce the behavior:

1. 定义一个集合型的 GeTMapping  入参
2. 导出到 Yapi
3. Yapi 的参数名变为了 参数名[0]
   
**Expected behavior**

希望直接得到按参数名的效果，更好的情况是直接导出两个相同参数名的 Yapi param （Yapi 支持）

**Screenshots**
问题：
![image](https://user-images.githubusercontent.com/45549577/220811061-0c9b5647-ea3a-4a35-a1fa-9720e73ffea3.png)
预期：
![image](https://user-images.githubusercontent.com/45549577/220811497-926e5e6a-37fe-4e7d-9b00-fe5a8192c504.png)

**Comment by tangcent** [comment]
ref: https://github.com/tangcent/easy-yapi/issues/763#issuecomment-1127183105

**Comment by ReberMusk** [comment]
> ref: [#763 (comment)](https://github.com/tangcent/easy-yapi/issues/763#issuecomment-1127183105)

收到，感谢。
