### ISSUE TITLE
可以获取到生成的方式吗？

### ISSUE THREAD

**Issue by yanye666** [tangcent/easy-yapi#921]
**Describe the question**

我想在yapi删除前缀path，但是postman不删除，能实现吗？
目前是这样实现的
export.after=groovy:api.setPath(tool.removePrefix(api.path(),"/xxx"))

**Comment by tangcent** [comment]
目前只能选则不同的配置文件: https://easyyapi.com/setting/local-file-config.html

**Comment by soldierjw** [comment]
这个可以使用脚本 来实现
export.after=groovy:``` 
    // 为postman时走以下逻辑   获取当前导出的渠道: markdown/postman/yapi
    if(!"postman".equals(runtime.channel())){
        return
    }

export.after=groovy:api.setPath(api.path().replaceAll("\\{app.base-path\\}/","").replace("\$",""))
```
