### ISSUE TITLE
[Question] 实体类某一属性类型为枚举，按文档使用@see指定枚举类型导出到YApi没有枚举信息

### ISSUE THREAD

**Issue by Nevermor7** [tangcent/easy-yapi#926]
注释：
    /**
     * 使用@see来说明当前字段的取值是某个枚举
     * @see com.xxx.entity.enums.XxxEnum 
     */
    private XxxEnum field;
导出到YApi是报警告
can not resolve com.xxx.entity.enums.XxxEnum for com.xxx.entity.vo.xxxVO#field
导出的YApi文档显示field字段类型为String，且没有枚举的相关信息

**Comment by tangcent** [comment]
这是插件无法推断你这里的field要取XxxEnum里的哪个值。
你这里已经是`private XxxEnum field;`为什么还要`@see`?

---

ref: http://easyyapi.com/setting/yapi-mock.html

**Comment by Nevermor7** [comment]
![image](https://user-images.githubusercontent.com/44044408/221491103-4f7fdaf9-6497-494c-a128-dada847ff45d.png)
我的疑问就是怎样写注释导出到YApi后其他信息这一栏能把枚举的key和意思显示出来，还是说要改配置？

**Comment by tangcent** [comment]
看一下这个文档: http://easyyapi.com/setting/yapi-mock.html

字段名与关联的枚举值字段名相同时`@see UserType`
字段名与关联的枚举值字段名不同时`@see UserType#type`

**Comment by Nevermor7** [comment]
我找到demo里面的UserType枚举类对比了一下，找到问题所在了。感谢您的回复:)
