### ISSUE TITLE
[Feature] json.rule.convert 不支持根据注解定义目标转换类型

### ISSUE THREAD

**Issue by axdlee** [tangcent/easy-yapi#930]
json.rule.convert 的it contextType是class，但这个class不支持https://easyyapi.com/setting/tools/it.html 里定义的class 类型方法。
比如我定义一个 
json.rule.convert[java.lang.Integer]=groovy:```
    logger.log(it.name())
    logger.log(it.defineCode())
    return "java.lang.String"
```
我无法在groovy代码块里使用 hasAnn() 方法，我也无法直接 json.rule.convert[@xxx.xxx.xxxAnnotation] 这样进行过滤
请问是否后续考虑支持，或者目前有什么替代方案？

**Comment by tangcent** [comment]
可不可以给一个例子?
你定义的代码是怎样的? 希望达到什么效果?

**Comment by axdlee** [comment]
@tangcent 比如我有一个自定义的注解 DiyAnnotation
该注解被我加在了一个对象的字段上
@Data
public class SomeDto implements Serializable {
    @DiyAnnotation
    private Integer createTime;
}
我期望可以通过  json.rule.convert[@xxx.xxx.DiyAnnotation]=java.lang.String 这样的配置能够实现所有被添加了该注解的Integer字段输出为json的时候转为String。没有被添加该注解的Integer字段输出为json的时候依然为Integer.

**Comment by axdlee** [comment]
@tangcent 我看到你在 [issue 746](https://github.com/tangcent/easy-yapi/issues/746) 回复说 json.rule.convert上下文对象是class。但我验证了一下 ， json.rule.convert上下文对象不支持https://easyyapi.com/setting/tools/it.html 里定义的class 类型大部分方法。仅支持it.name()这种

**Comment by tangcent** [comment]
`json.rule.convert`这个规则是用于使用了Spring的自定义类型转换器的情况
所以这里`json.rule.convert`应用的对象`it`是`Integer`而不是`createTime`
```
@Data
public class SomeDto implements Serializable {
    @DiyAnnotation
    private Integer createTime;
}
```

针对你这里的情况，目前没有好的替代方案

**Comment by tangcent** [comment]
`json.rule.convert`这个规则是用于使用了Spring的自定义类型转换器的情况
所以这里`json.rule.convert`应用的对象`it`是`Integer`而不是`createTime`
```
@Data
public class SomeDto implements Serializable {
    @DiyAnnotation
    private Integer createTime;
}
```

针对你这里的情况，目前没有好的替代方案
