### ISSUE TITLE
mock 配置疑问点

### ISSUE THREAD

**Issue by yanye666** [tangcent/easy-yapi#935]
#配置如下
#mock.[code|integer]=200
#mock.[*.day|integer]=20230101
#mock.[*day|integer]=20230102
#mock.[day|integer]=20230103
#代码

>   private Integer code;
   private Integer day;

为什么code可以，但是day的第三种配置不可以，前两种可以

**Comment by tangcent** [comment]
> private Integer code;
> private Integer day;

`mock.[day|integer]`表示json里第一级day

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/17569144/226935038-e4a03371-4d53-4026-9077-b22ef674101c.png">


`mock.[*.day|integer]`表示json里任意级day
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/17569144/226935385-290e5853-8b62-4572-aa52-dc72227a419e.png">


---

outer的day全路径为`day` 能匹配`day`和`*.day`
inner的day全路径为`data.day` 无法匹配`day`

**Comment by yanye666** [comment]
> > private Integer code;
> 
> > private Integer day;
> 
> 
> 
> `mock.[day|integer]`表示json里第一级day
> 
> 
> 
> <img width="1277" alt="image" src="https://user-images.githubusercontent.com/17569144/226935038-e4a03371-4d53-4026-9077-b22ef674101c.png">
> 
> 
> 
> 
> 
> `mock.[*.day|integer]`表示json里任意级day
> 
> <img width="1223" alt="image" src="https://user-images.githubusercontent.com/17569144/226935385-290e5853-8b62-4572-aa52-dc72227a419e.png">
> 
> 
> 
> 
> 
> ---
> 
> 
> 
> outer的day全路径为`day` 能匹配`day`和`*.day`
> 
> inner的day全路径为`data.day` 无法匹配`day`
> 
> 

谢谢解答，的确是这样的情况
