### ISSUE TITLE
可以实现动态切换token吗？

### ISSUE THREAD

**Issue by yanye666** [tangcent/easy-yapi#936]
目前一个项目moudle里面有多个目录，也就有多个token，多个controller有不同前缀和包名前缀不同，所以有办法可以实现自动切换token吗？

**Comment by tangcent** [comment]
配置[module](http://easyyapi.com/setting/rules/module.html)

**Comment by tangcent** [comment]
用规则实现你的想法就可以了。
比如每个类作为一个`module`:
```
module[groovy:it.contextType()=="class"]=groovy:it.name()
```

**Comment by yanye666** [comment]
module[groovy:it.contextType()=="class"]=groovy:tool.substringBetween(it.annValue("org.springframework.web.bind.annotation.RequestMapping"), "/", "/") 

这样可以实现，截取第一个/中间的内容来切换modle

**Comment by yanye666** [comment]
@tangcent 我想修改文件夹名，有什么好的办法获取到当前java项目名，之前module默认是项目名，但是我现在把module也改了，这就没法获取了。
#module=groovy:localStorage.set("module",runtime.module())

**Comment by tangcent** [comment]
试试`runtime.projectName()`

**Comment by yanye666** [comment]
> 试试`runtime.projectName()`

这个我试过了，如果是聚合项目这个获取的是父项目，而不是当前子项目名称

**Comment by tangcent** [comment]
既不是`runtime.projectName()`也不是`runtime.module()`? 你的项目结构是怎么样的?

**Comment by yanye666** [comment]
> 既不是`runtime.projectName()`也不是`runtime.module()`? 你的项目结构是怎么样的?
> 
> 
例如我现在项目
a
-b
__c.java 类url：test

c这里生成yapi
正常会使用b当token来选择，我现在会改module取值为test（为了切换token），这样的话我就没法获取到原来的b了，直接变成获取为test了，
所以runtime.projectname为a，module为test，实际上我想要b，但是会跟我切换token有影响😂😂

**Comment by yanye666** [comment]
> 为什么module不是b是test?
> 
> 
> 
> ```
> 
> 项目a
> 
> ├── 子项目b
> 
> │   ├── src
> 
> │   │   ├── main
> 
> │   │   │   ├── java
> 
> │   │   │   │   └── com
> 
> │   │   │   │       └── **
> 
> │   │   │   │           └── **
> 
> │   │   │   │               └── **
> 
> │   │   │   │                   └── c.java
> 
> │   │   │   └── resources
> 
> ```

module[groovy:it.contextType()=="class"]=groovy:tool.substringBetween(it.annValue("org.springframework.web.bind.annotation.RequestMapping"), "/", "/")

加上这个配置，c类注解是RequestMapping 是test，就不是moduleb，是module test

**Comment by tangcent** [comment]
对，这里的`runtime.module()`是逻辑module也会计算`module=xxx`规则。
需要重新暴露一个不计算`module=xxx`规则的方法。

**Comment by yanye666** [comment]
> 对，这里的`runtime.module()`是逻辑module也会计算`module=xxx`规则。
> 
> 需要重新暴露一个不计算`module=xxx`规则的方法。

是的，这里会出行循环调用，所以如果改了module就获取不到原来的了，还有其他办法吗

**Comment by tangcent** [comment]
那试试`config.get("module_path")`

**Comment by yanye666** [comment]
> 那试试`config.get("module_path")`

一样的结果是test
