### ISSUE TITLE
[Question] 如何将token配置在配置文件里，优先读取配置文件的token

### ISSUE THREAD

**Issue by GeekHM** [tangcent/easy-yapi#953]
场景描述：同一个项目源码，但每一个项目做完二次开发交付出去部署的yapi环境都可能不一样，使用@module的话要改比较多的地方，且也不够灵活。所以想问是否有方法可以将图中的server和token配置到配置文件中，使用时，优先读取配置文件，这样的话一个人配置完以后，团队成员在使用的时候，可以直接读取配置文件，无需再配置，且不同环境，也只需要调整配置文件，不需要每一个人都单独去改idea关于yapi的配置。

![image](https://user-images.githubusercontent.com/34578736/231326300-204cfaac-3ec0-433e-9026-4a809079377e.png)

如果@module可以实现，是否可以给一些具体的演示。可以只写在配置文件里，不会入侵每一个类。
我不太会写groovy脚本，如果有相关用法，希望可以给一些示例，启发一下

万分感谢

**Comment by tangcent** [comment]
没有提供这样的功能，目前只能通过配置自行实现:
``````
api.method.parse.before=```
def module = runtime.module()
def yapiSettingsHelper = runtime.getBean("com.itangcent.idea.plugin.settings.helper.YapiSettingsHelper")
if (yapiSettingsHelper.getPrivateToken(module,true) == null) {
    def token = config.get("$token.$module")
    if (token == null) {
        logger.info("need config $token.$module")
        return
    }
    yapiSettingsHelper.setToken(module, token)
}
```
``````
只是随手写的，没有测试，你可以自己修改。

**Comment by GeekHM** [comment]
> 没有提供这样的功能，目前只能通过配置自行实现:
> 
> ```
> api.method.parse.before=```
> def module = runtime.module()
> def yapiSettingsHelper = runtime.getBean("com.itangcent.idea.plugin.settings.helper.YapiSettingsHelper")
> if (yapiSettingsHelper.getPrivateToken(module,true) == null) {
>     def token = config.get("$token.$module")
>     if (token == null) {
>         logger.info("need config $token.$module")
>         return
>     }
>     yapiSettingsHelper.setToken(module, token)
> }
> ```
> ```
> 
> 只是随手写的，没有测试，你可以自己修改。

好的，谢谢！因为实在太忙了，可能暂时没时间研究这个写法。后面再看看。
将server和token放到配置文件里，优先读配置文件，可能是很多人都需要的一个改进，如果可以的话，后面版本可以考虑加进去。

**Comment by GeekHM** [comment]
作者你好，很开心看到这个功能已经增加到产品里了，并且我从idea的插件中也看到了发布的最新版。
但我查询了wiki和相关文档，没有看见应该怎样在配置里面配server和token，是否可以给出一些示例
万分感谢

**Comment by tangcent** [comment]
文档还没时间更新。 :)

```properties
yapi.server=http://xxxxxx
```
https://github.com/tangcent/easy-yapi/blob/bbc6959b4b0733c68a202dacd0522ac9033a9534/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/helper/YapiSettingsHelper.kt#L54

```properties
yapi.token.$module=xxxxxxx
```
https://github.com/tangcent/easy-yapi/blob/bbc6959b4b0733c68a202dacd0522ac9033a9534/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/helper/YapiSettingsHelper.kt#L96

**Comment by GeekHM** [comment]
> 文档还没时间更新。 :)
> 
> ```ini
> yapi.server=http://xxxxxx
> ```
> 
> https://github.com/tangcent/easy-yapi/blob/bbc6959b4b0733c68a202dacd0522ac9033a9534/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/helper/YapiSettingsHelper.kt#L54
> 
> ```ini
> yapi.token.$module=xxxxxxx
> ```
> 
> https://github.com/tangcent/easy-yapi/blob/bbc6959b4b0733c68a202dacd0522ac9033a9534/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/helper/YapiSettingsHelper.kt#L96

好的谢谢，已经在项目只开始使用了，在这里记录一下，有相关场景的朋友可以参考一下：

1.在项目根目录下创建配置文件：
![image](https://user-images.githubusercontent.com/34578736/233330090-56daa28e-c3a5-4279-97d7-b32a45258a03.png)
2.写对应格式的配置
![image](https://user-images.githubusercontent.com/34578736/233330493-26792e5e-6c89-4cb1-a0aa-8e866297a3a9.png)

**Comment by bigbaibaibai** [comment]
> > 文档还没时间更新。 :)
> > ```ini
> > yapi.server=http://xxxxxx
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/tangcent/easy-yapi/blob/bbc6959b4b0733c68a202dacd0522ac9033a9534/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/helper/YapiSettingsHelper.kt#L54
> > 
> > ```ini
> > yapi.token.$module=xxxxxxx
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/tangcent/easy-yapi/blob/bbc6959b4b0733c68a202dacd0522ac9033a9534/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/helper/YapiSettingsHelper.kt#L96
> 
> 好的谢谢，已经在项目只开始使用了，在这里记录一下，有相关场景的朋友可以参考一下：
> 
> 1.在项目根目录下创建配置文件： ![图像](https://user-images.githubusercontent.com/34578736/233330090-56daa28e-c3a5-4279-97d7-b32a45258a03.png) 2.写对应格式的配置 ![image](https://user-images.githubusercontent.com/34578736/233330493-26792e5e-6c89-4cb1-a0aa-8e866297a3a9.png)


你好作者
yapi.token.$module=
这个配置的值好像不能使用下面这种写法
yapi.token.xxx=groovy:```
   if(?){return "a"} else{return "b"}
```
是故意而为之，还是遗漏了呢？

**Comment by tangcent** [comment]
这里只是简单的读配置，没有应用规则。
https://github.com/tangcent/easy-yapi/blob/bbc6959b4b0733c68a202dacd0522ac9033a9534/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/helper/YapiSettingsHelper.kt#L96

你这是什么场景需要这么复杂的处理?

**Comment by bigbaibaibai** [comment]
我们的项目里包含多端的接口，根据类名后缀做区分，现需要根据类名的后缀导出到不同的api文档中

**Comment by bigbaibaibai** [comment]
大佬，还有一个问题，我们这个工程下有5  6个模块，但是只需要使用一个token，可以加一个

```properties
yapi.token.*=xx
#或者
yapi.token.all=xx
```

这样的配置吗

**Comment by tangcent** [comment]
> 我们的项目里包含多端的接口，根据类名后缀做区分，现需要根据类名的后缀导出到不同的api文档中

你看一下[module](https://easyyapi.com/setting/rules/module.html), 导出yapi时,每个module对应yapi中的一个项目, 所以你可以根据类名的后缀设置不同的module，然后为每个module配一个token就可以了



> 大佬，还有一个问题，我们这个工程下有5 6个模块，但是只需要使用一个token，可以加一个
> 
> ```ini
> yapi.token.*=xx
> #或者
> yapi.token.all=xx
> ```
> 
> 这样的配置吗

你这种的感觉可以直接`module=share`, 然后`yapi.token.share=xx`

**Comment by bigbaibaibai** [comment]
感谢作者，问题已解决
