### ISSUE TITLE
[Feature]tokens存储不用子包名字

### ISSUE THREAD

**Issue by zhuangjiaju** [tangcent/easy-yapi#954]
**Is your feature request related to a problem? Please describe.**

我们有2个项目，子项目名字都是 start ，然后每次上传到YAPI都要手动去toknes 注释 并打开另外一个，能否有区分两个项目有相同子包的方案。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tangcent** [comment]
试试配一个[module](http://easyyapi.com/setting/rules/module.html):
`module=groovy:runtime.projectName()+"/"+runtime.moduleName()`

**Comment by tangcent** [comment]
> 我们有2个项目，子项目名字都是 start ，然后每次上传到YAPI都要手动去toknes 注释 并打开另外一个，能否有区分两个项目有相同子包的方案。

按说yapi token的配置是项目级的不是全局的，不同的项目之间应该是不影响的。

**Comment by linzi007** [comment]
> > 我们有2个项目，子项目名字都是 start ，然后每次上传到YAPI都要手动去toknes 注释 并打开另外一个，能否有区分两个项目有相同子包的方案。
> 
> 按说yapi token的配置是项目级的不是全局的，不同的项目之间应该是不影响的。

我这边也是不同项目之间会互相影响
