### ISSUE TITLE
小白求问,返回值为啥获取有问题...

### ISSUE THREAD

**Issue by mm2m123** [tangcent/easy-yapi#96]
`      //登录成功
        Map<String, Object> mapData = new HashMap<>();
        mapData.put("LOGINTOKEN", uuid);
        mapData.put("user", getUserFromRedis(uuid));
        return ResultUtil.success(mapData);`
这个能正常解析出来为 map,里面一个user 一个 token
`List<Province> list = provinceRepository.findAll();
                return ResultUtil.success(list);`
这个正常返回应该是list,里面包含 A 类,但是解析出来就是 B类了...

**Comment by tangcent** [comment]
- 你是开启了`inferEnable`功能么
- 这个没有经过大量测试，不过我自己用的基本正常
- 可以尝试提供一个demo吗?你可以`clone` [springboot-demo](https://github.com/Earth-1610/spring-demo/tree/master/cn/springboot-demo)

**Comment by mm2m123** [comment]
对的,开启了inferEnable.不开启的话返回值识别不出来..
我把 demo 放到[这里了](https://github.com/mm2m123/easy-yapi-demo.git)
里面还附上了录屏.
劳您费心.

**Comment by tangcent** [comment]
这确实是个BUG.
我会尽快修复它.

**Comment by tangcent** [comment]
已修复:[intellij-kotlin#28](https://github.com/Earth-1610/intellij-kotlin/pull/28)
你可以先行尝试使用:[easy-yapi.1.3.0.183.0.8.jar.zip](https://github.com/tangcent/easy-yapi/files/3905312/easy-yapi.1.3.0.183.0.8.jar.zip)

**Comment by tangcent** [comment]
- 任何使用相关的问题你可以在这里提交issue
- 可以尝试使用yapi的mock功能: [yapi-mock](http://easyyapi.com/setting/yapi-mock.html)
