### ISSUE TITLE
[Question] 复杂对象导出，导出到yapi失败，导出到markdown是成功的.

### ISSUE THREAD

**Issue by kot-zhang** [tangcent/easy-yapi#962]
复杂对象导出，导出到yapi失败，导出到markdown是成功的。
复杂对象导出到markdown文件大小大概为20M

**Comment by tangcent** [comment]
> 复杂对象导出，导出到yapi失败

是部分对象导出失败还是很多对象都导出失败？

> 复杂对象导出到markdown文件大小大概为20M

看看markdown的内容呢，有可能是 #63 这样的问题

**Comment by kot-zhang** [comment]
> > 复杂对象导出，导出到yapi失败
> 
> 是部分对象导出失败还是很多对象都导出失败？
> 
> > 复杂对象导出到markdown文件大小大概为20M
> 
> 看看markdown的内容呢，有可能是 #63 这样的问题

应该是大对象，对象里面存在嵌套。配置信息：
max.deep=12
max.elements=1024
json.rule.convert[java.time. LocalDateTime]=java.lang.String
json.rule.convert[java.time. LocalDate]=java.lang.String

没有报错，但是yapi库里面没有展示

**Comment by tangcent** [comment]
看看markdown的内容，应该能看出来是哪个字段解析内容过大

**Comment by kot-zhang** [comment]
可以看看

**Comment by kot-zhang** [comment]
[https://s1.ax1x.com/2023/04/19/p9FEg0g.png](url)

**Comment by kot-zhang** [comment]
> 

这个模型属性将近200多个，里面嵌套当前模型，且还有一些其他大模型

**Comment by tangcent** [comment]
> 导出到yapi失败

控制台有报错信息?
