### ISSUE TITLE
[Bug] 导出接口到YAPI,响应结果中的data显示不出来

### ISSUE THREAD

**Issue by AustinMing** [tangcent/easy-yapi#963]
响应结果只是套娃了1，2层 ，也不算很复杂，主要是同样的一个Controller,有同事导出看得到data里面的东西，我导出点开data是空白，还有一个同事也是一样，快捷键导出也是看不到data，我和能导出的那个同事配置是一样的

**Comment by tangcent** [comment]
你们使用的插件版本一致吗?

Controller响应是什么样的呢?

导出 [UserCtrl.java#L92](https://github.com/Earth-1610/spring-demo/blob/master/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller/UserCtrl.java#L92) 试试

**Comment by AustinMing** [comment]
1 我的插件版本




2 同事导出正常的插件版本




3 难道是我的插件太新？还是idea太老？我的idea是2020版本的

4 spring-demo 导出 UserCtrl&nbsp; 获取用户列表也是没显示&nbsp;
&nbsp;





5 我们的controller 返回值





Result



Page



BimSystemReportRespDTO











大佬你那边有我同事那个版本的yapi吗？有的话麻烦发我一份，我感觉是版本太新的问题




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Wed, Apr 19, 2023 10:12 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [tangcent/easy-yapi] [Bug] 导出接口到YAPI,响应结果中的data显示不出来 (Issue #963)

&nbsp;



 
你们使用的插件版本一致吗?
 
Controller响应是什么样的呢?
 
导出 UserCtrl.java#L92 试试

**Comment by tangcent** [comment]
> spring-demo 导出 UserCtrl&nbsp; 获取用户列表也是没显示&nbsp;

获取用户列表是没明确定义返回值的，需要开启<kbd>Preferences(Settings)</kbd> > <kbd>Other Settings</kbd> > <kbd>EasyApi</kbd> > <kbd> Intelligent</kbd> > <kbd>enable infer</kbd>。而且，API最好都明确定义返回值，不要依赖infer，还不是那么好用。

> 大佬你那边有我同事那个版本的yapi吗？有的话麻烦发我一份，我感觉是版本太新的问题

easyyapi的历史版本可以在[release](https://github.com/tangcent/easy-yapi/releases)里找到

**Comment by AustinMing** [comment]
感谢大佬，已经能看到返回值数据了，就是要开启： Preferences(Settings) > Other Settings > EasyApi > Intelligent > enable infer 。而且，API最好都明确定义返回值
