### ISSUE TITLE
实体类中字段存在继承关系的情况下，如何控制字段的注释取值

### ISSUE THREAD

**Issue by heilaoyang** [tangcent/easy-yapi#967]
现在有这么一个情况，有一个实体类的字段同时出现在父子类中吗，现在生成文档默认读取的是父类字段的注释，我想要让他取子类字段的注释，也就是同样字段的情况下，子类注释优先级>父类注释优先级，我该如何做？

**Comment by tangcent** [comment]
能提供一个例子吗?

**Comment by he429134733** [comment]
@tangcent 这种情况如何重写父类的注释

class CommonBean{
   /**
     * 搜索字段
     */
    private String searchField;

}


class Student extend CommonBean {


}
我希望上传的时候能自定义父类的注释。

class Student extend CommonBean {
    /**
     * 重写的搜索字段
     */
    @Override
    public String getSearchField() {
        return super.getSearchField();
    }
}
我尝试这样写，但是不生效
