### ISSUE TITLE
[Question] 导出到postman时，集合里面总会有个空字符串这个怎么取消，

### ISSUE THREAD

**Issue by soldierjw** [tangcent/easy-yapi#969]
**Describe the question**

A clear and concise description of what the question is.

**Expected result**

A clear and concise description of what you expected to get.

**Screenshots**

**Demo Code**

1. Fork https://github.com/Earth-1610/spring-demo
2. Write some code
3. Now paste the forked repository hear: https://github.com/xxxx/spring-demo

**Additional context**

**Comment by soldierjw** [comment]
输出结果：
{  
  "bigAreaList": [""  ]
}
预期结果：
{
    "bigAreaList": [ ]  或   "bigAreaList": null
}

**Comment by tangcent** [comment]
目前没支持这个配置。可以试试通过`export.after`处理

``````
export.after=groovy:```
def removeEmptyString
removeEmptyString = { map ->
    for(k in map.keySet().toList()){
        def v = map[k]
        if(v instanceof List){
            map[k] = []
        }else{
            removeEmptyString(v)
        }
    }
}
def body = api.request.response?.first()?.body
if(body!=null && body instanceof Map){
    removeEmptyString(body)
    logger.info("body:"+body)
}
```
``````

**Comment by soldierjw** [comment]
export.after=groovy:``` 
	// 为yapi时不走以下逻辑   获取当前导出的渠道: markdown/postman/yapi
    	if("yapi".equals(runtime.channel())){
		return
	}
	// 获取 请求参数数据
    	def body = api.request.body 

    	if(body!=null && body instanceof Map){ 
 	    for(k in body.keySet().toList()){
		// 为集合时才置为空
            	if(body[k] instanceof List){
		    body[k]=[]
		}	
            } 
        }
 	logger.info("正在导出: "+api.name())
	// 将处理好的请求参数设置回去
	api.setBody(body)
```

感谢，试了好久才写出来这个，真的是一点一点摸索出来的，根本没有这方法的资料

**Comment by soldierjw** [comment]
`
export.after=groovy:``` 
	// 为yapi时不走以下逻辑   获取当前导出的渠道: markdown/postman/yapi
    	if("yapi".equals(runtime.channel())){
		return
	}
	// 获取 请求参数数据
    	def body = api.request.body 

    	if(body!=null && body instanceof Map){ 
 	    for(k in body.keySet().toList()){
		// 为集合时才置为空
            	if(body[k] instanceof List){
		    body[k]=[]
		}	
            } 
        }
 	logger.info("正在导出: "+api.name())
	// 将处理好的请求参数设置回去
	api.setBody(body)
````
