### ISSUE TITLE
[Question] 请问如何让请求参数根据validation注解生成，返回字段全部设为必须？

### ISSUE THREAD

**Issue by zhangxiaoqiang1998** [tangcent/easy-yapi#970]
前端用ytt生成接口请求方法，需要规范字段是否必须。不想在返回对象中添加validation注解

**Comment by tangcent** [comment]
[field.required](http://easyyapi.com/setting/rules/field_required.html)

`field.required=true`

**Comment by zhangxiaoqiang1998** [comment]
这样会造成请求参数全部变成必须

**Comment by tangcent** [comment]
> 请问如何让请求参数根据validation注解生成，返回字段全部设为必须？
> 不想在返回对象中添加validation注解

不是很能理解你的想法。是有注解还是没注解呢?

**Comment by zhangxiaoqiang1998** [comment]
请求参数需要校验，有注解。返回对象是专门用来返回结果的，现在需要添加注解才能让yapi中的是否必须为必须，想在减少入侵的情况下实现返回结果中所有字段在yapi中显示为必须

**Comment by tangcent** [comment]
有点麻烦，类似这样: https://github.com/tangcent/easy-yapi/issues/703#issuecomment-1057816165

``````properties
json.cache.disable=true
json.group=groovy:session.get("json-group")
api.param.parse.before=groovy:```
    session.set("json-group", "request")
```
api.param.parse.after=groovy:```
    session.remove("json-group")
```
field.required=groovy:session.get("json-group") != "request"

``````

**Comment by zhangxiaoqiang1998** [comment]
好的，可以实现，谢谢你的解答！
