### ISSUE TITLE
[Bug] 修改文件后导出到yapi 导致 IDEA卡死，并且修改的内容会回滚

### ISSUE THREAD

**Issue by w-a-n-g-s-h-u-n** [tangcent/easy-yapi#971]
**Describe the bug**

修改文件后导出到yapi 导致 IDEA卡死，并且修改的内容会回滚

**Expected behavior**

成功上传 api

**Comment by tangcent** [comment]
是所有文件导出都会卡死还是某些文件会导致 IDEA卡死?

**Comment by w-a-n-g-s-h-u-n** [comment]
所有文件
第一次导出到 yapi都会成功，修改一下内容，再导出就会卡死，只能强制退出 idea
重启 idea 后 有时修改的文件内容没有保存
如果修改后先点 git提交，弹出git提交窗口，直接关闭窗口不用真的提交，再去导出就不会卡死了

**Comment by w-a-n-g-s-h-u-n** [comment]
从今年的某个版本开始出现，也可能和 idea 版本有关，我一直在用 idea最新版

**Comment by w-a-n-g-s-h-u-n** [comment]
对了 是mac 系统

**Comment by suhaoran99** [comment]
不止是导出api，请求api也会概率性导致整个idea完全卡死，只能强制退出，而且这个概率不低，一般4，5次之后就会出现
同M1 PRO idea最新版

**Comment by tangcent** [comment]
> 请求api弹出的窗口是空白，没有api列表

这个问题我之前碰到过，但是之前概率不高。

---

这个问题排查有点麻烦，需要一段时间。

你试试导出[demo/controller](https://github.com/Earth-1610/spring-demo/tree/master/cn/springboot-demo/src/main/java/com/itangcent/springboot/demo/controller)，看看会不会稳定复现这个问题。

**Comment by SiTranJum** [comment]
我的是win10，idea也是最新版，在加上配置：field.doc=@io.swagger.v3.oas.annotations.media.Schema#description后(实体类注解@Schema()也加上了）就出现了这个问题

**Comment by w-a-n-g-s-h-u-n** [comment]
我的 yapi.yml配置
`method.additional.header[!@javax.annotation.security.PermitAll]={name: "Authorization",value: "Bearer {{global.accessToken}}",desc: "认证Token",required:true, example:"Bearer xxx"}
enum.use.custom=groovy:it.fields().find{i->i.hasAnn("com.fasterxml.jackson.annotation.JsonValue")}
json.rule.enum.convert=groovy:it.fields().find{i->i.hasAnn("com.fasterxml.jackson.annotation.JsonValue")}
json.rule.convert[java.time.ZoneOffset]=java.lang.String
json.rule.convert[java.time.Instant]=java.lang.Long
`

**Comment by w-a-n-g-s-h-u-n** [comment]
> 不止是导出api，请求api也会概率性导致整个idea完全卡死，请求api弹出的窗口是空白，没有api列表，只能强制退出，而且这个概率不低，一般4，5次之后就会出现 M1 PRO idea最新版

我的是 inter 芯片

**Comment by tangcent** [comment]
试试根据这个提示，看下日志卡在哪里了。
[Issue/BUG](https://github.com/tangcent/easy-yapi/issues/new?assignees=&labels=type%3A+bug&projects=&template=bug_report.md&title=%5BBug%5D+Xxx)

**Comment by w-a-n-g-s-h-u-n** [comment]
加了输出日志的配置之后 第一次导出输出了大量日志
修改文件后再次导出 最后一行日志是
[INFO] [api] before parse class:xx.xx.xx.xx

不加输出日志的配置 ，也是卡在这里

**Comment by ZiboCui** [comment]
我也遇到了类似问题，几率很大。
系统：m1 
easyyapi版本：2.6.8.212.0
idea版本：2023.3.4

当easyyapi的setting的yapi export_mode 设置为ALWAYS_ASK时卡死，卡死的位置是[INFO]	search api from: xxx
多次强行停止之后 发现当我修改完代码然后clean maven之后export yapi才会成功，否则必定卡死
