### ISSUE TITLE
[Question] 怎么判断方法参数类里面的成员变量是否有某个注解？

### ISSUE THREAD

**Issue by soldierjw** [tangcent/easy-yapi#972]
```
 @PostMapping("/summary/data")
 public Result getData(@RequestBody RequestClass request) {

}
class RequestClass{
  @RowPrivilegeProperty(dataType = "BI.Data.Car.Model")
    private List<String> carModelList;
}
```

怎么判断 RequestClass 里面的成员变量是否有   RowPrivilegeProperty 注解，且获取里面的值

**Comment by tangcent** [comment]
`@xxx.xxx. RowPrivilegeProperty#dataType`

**Comment by soldierjw** [comment]
> `@xxx.xxx. RowPrivilegeProperty#dataType`

这个是怎么用，没太明白

**Comment by tangcent** [comment]
http://easyyapi.com/setting/config-rule.html

**Comment by soldierjw** [comment]
> dataType

以下两种配置到  BuildInConfig  都不生效，
field.doc[@xxx.xxxx.RowPrivilegeProperty#dataType]=groovy: logger.info("===="+it)
@xxx.xxxx.RowPrivilegeProperty#dataType=groovy: logger.info("===="+it)

 这种是可以生效的，但是拿不到注解里面配置的值
field.doc[@xxx.xxxx.RowPrivilegeProperty]=groovy: logger.info("===="+it)

另外还有一个问题，如果拿到注解里面的值 ，有什么方法将处理结果 写到api.appendDesc("“）吗？

**Comment by soldierjw** [comment]
> http://easyyapi.com/setting/config-rule.html

以下两种配置到 BuildInConfig 都不生效，
field.doc[@xxx.xxxx.RowPrivilegeProperty#dataType]=groovy: logger.info("===="+it)
@xxx.xxxx.RowPrivilegeProperty#dataType=groovy: logger.info("===="+it)

这种是可以生效的，但是拿不到注解里面配置的值
field.doc[@xxx.xxxx.RowPrivilegeProperty]=groovy: logger.info("===="+it)

另外还有一个问题，如果拿到注解里面的值 ，有什么方法将处理结果 写到api.appendDesc("“）吗？

**Comment by tangcent** [comment]
把`xxx.xxxx.RowPrivilegeProperty`里面的`xxx.xxxx`换成你实际的包名

**Comment by tangcent** [comment]
``````
field.doc[@xxx.xxxx.RowPrivilegeProperty#dataType]=groovy: ```
logger.info("===="+it)
return "any" + it + "any"
```
``````

**Comment by soldierjw** [comment]
> 把`xxx.xxxx.RowPrivilegeProperty`里面的`xxx.xxxx`换成你实际的包名

是写的实际包名，能将处理结果 写到api.appendDesc("“）吗？

**Comment by soldierjw** [comment]
> ```
> field.doc[@xxx.xxxx.RowPrivilegeProperty#dataType]=groovy: ```
> logger.info("===="+it)
> return "any" + it + "any"
> ```
> ```

大佬，你的电脑可以打印出来 吗？我的插件是最新版本，就是打印不出来

**Comment by tangcent** [comment]
试试用: [export.after](http://easyyapi.com/setting/rules/export_after.html)
``````properties
export.after=groovy:```
   for(arg in it.args()){
     def dataType = arg.annValue("xxx.xxxx.RowPrivilegeProperty","dataType")
     if(dataType!=null){
       api.appendDesc(dataType)
     }
  }
```
``````

**Comment by soldierjw** [comment]
> ```ini
> dataType
> ```


注解的位置是在 方法的参数类  的某个字段上面，it.args获取的只是参数名称，参数类里面的信息是怎么获取

**Comment by tangcent** [comment]
`arg.type().fields()`
