### ISSUE TITLE
page对象无法解析，老版本是支持的。

### ISSUE THREAD

**Issue by xtsteven** [tangcent/easy-yapi#974]
业务代码返回结果是 Page<xxxxx>

框架中，重新对这个结果做了封装，将业务代码的返回封装到了value字段，如下图

![image](https://github.com/tangcent/easy-yapi/assets/33415855/b3454b15-fc8f-4053-9959-beeac728bac2)

然后上图是老版本的上传到Yapi的数据，且value中的数据结构也是正确的。版本号：2.1.4.183.0

新版本没有勾选getter as field 时，上传的数据是空的。

如果勾选上getter as field后 获取的就是单独的 page这个类的解析。这个要怎么配置

**Comment by tangcent** [comment]
我没办法复现这个问题，能提供一个API示例吗

**Comment by xtsteven** [comment]
任意一个demo都可以的。

**Comment by xtsteven** [comment]
我举个例子：
首先统一返回结果，重写MappingJackson2HttpMessageConverter中的writeInternal方法，将业务接口的返回结果填入统一返回结果集的 value中。
让返回结果统一为：
public class Resp {
 
	private String code="200";
 
	private String msg="成功";
 
	private Object value;
}

然后随便一个编写一个接口，这里业务接口返回的结果集为：Page<xxxx>
这个Page类，是org.springframework.data.domain.Page

你尝试下看。因为2.1.4.183.0这个版本是好的，所以我也很奇怪

**Comment by tangcent** [comment]
插件版本:
<img width="239" alt="image" src="https://github.com/tangcent/easy-yapi/assets/17569144/ae1ebcb1-cf80-429f-aad8-9fc57b8d5457">

API:
```java
    @RequestMapping("/return/user-page")
    public org.springframework.data.domain.Page<UserInfo> queryUser() {
        return null;
    }
```

导出结果:
<img width="857" alt="image" src="https://github.com/tangcent/easy-yapi/assets/17569144/1abec540-c8a5-4b20-adaf-f0bb3c1c5b19">

**Comment by xtsteven** [comment]
我写个demo，关键点的代码我贴出来
