### ISSUE TITLE
[Question] 屏蔽参数类里面的注释，重写新的注释

### ISSUE THREAD

**Issue by soldierjw** [tangcent/easy-yapi#975]
参数类里面的注释为：  数据code

我想把一些特定的字段统一刷为   1:aaa  2:bbb   3:ccc
配置：
field.doc[#see]= 1:aaa  2:bbb   3:ccc

但是yapi上的结果为：

      数据code
      1:aaa  2:bbb   3:ccc

怎么能把注释里面的 **数据code**  给抹掉，只保留统一刷的注释数据

**Comment by soldierjw** [comment]
还有一个postman报这个错误 是什么问题	[malformedRequestError] Found 9 errors with the supplied collection.

**Comment by soldierjw** [comment]
第三个问题：枚举类写成   MODEL_SSS("1", "SS1","SS2")
会有警告日志，can not resolve xxx.xxx.CarModelEnum for xxx.xxx.RealtimeDetailRequert#carModelList
而且@see  不生效

**Comment by tangcent** [comment]
没有支持这样的能力，字段上的注释保留在yapi上有什么问题吗?

**Comment by soldierjw** [comment]
问题不是很大，只是有些字段写的不是很规范或是后期字段进行扩容了，要改好多地方的注释
