### ISSUE TITLE
[Feature] 老哥有没考虑一下直接支持点击触发接口请求

### ISSUE THREAD

**Issue by sandangjia** [tangcent/easy-yapi#977]
之前一直使用yapi 来进行开发，新公司这边不能使用这东西了，然后现在都是cp到接口工具中再点击发送的，但实际你这插件已经解析出参数了，只要增加一个入口就可以实现调用controller的接口，是否考虑下支持

**Comment by suhaoran99** [comment]
已经支持了啊，菜单中有一个call api选项

**Comment by sandangjia** [comment]
大意了，确实是

**Comment by tangcent** [comment]
这个功能并不完善，我自己大部分还是以PostMan为主，只有开发阶段会用这个功能做些简单的测试。

**Comment by tangcent** [comment]
这个功能并不完善，我自己大部分还是以PostMan为主，只有开发阶段会用这个功能做些简单的测试。
