### ISSUE TITLE
[Feature] 希望可以支持 curl 接口的生成

### ISSUE THREAD

**Issue by sandangjia** [tangcent/easy-yapi#978]
![图片](https://github.com/tangcent/easy-yapi/assets/22360223/7e6bb15c-12e4-4e03-bde2-80267c75f288)

希望可以支持生成 curl 的接口，比如这样的：curl -H "Authorization:Bearer 5d3d3101-881f-4219-bfdf-b69540f960ba" -H "Content-Type:application/json;charset=UTF-8" -XPOST http://ip:port/addxxx -d '{"task_sn":"VG21","business_system_id":"xxx","vuln_info":[{"vuln_id":"123","vuln_title":"title"}]}'

可以快速方便的支持更多的接口工具

**Comment by tangcent** [comment]
你点这个`Export Api`之后，渠道里应该有个`Curl`，你试试

**Comment by tangcent** [comment]
你点这个`Export Api`之后，渠道里应该有个`Curl`，你试试
