### ISSUE TITLE
[Bug] easyyap 和 apifox不兼容

### ISSUE THREAD

**Issue by zhuangjiaju** [tangcent/easy-yapi#979]
**Describe the bug**
![image](https://github.com/tangcent/easy-yapi/assets/18475586/7a8780ab-8d65-423c-a59b-881842021f24)
![image](https://github.com/tangcent/easy-yapi/assets/18475586/1073d68f-9788-4958-8c62-04c822c4570e)

先装easyyapi 再装apfox

现在 不管怎么上传接口 都是让我输入token 我token已经有了

有没有什么办法删除的项目的配置的？

我现在就一个项目不行，其他项目都可以。

```
[DEBUG]	use recommend config
[INFO]	Start find apis...
[TRACE]	find config file:/Users/zhuangjiaju/IdeaProjects/ata-super/.easy.api.config
[DEBUG]	use recommend config
[INFO]	search api from: com.alibaba.atasuper.web.controller.OssV2Controller
[WARN]	project:1000360 may be deleted.
[WARN]	token:2895fdd4fac74eb01fb02efbe9e801234769a56389d947d94f17e7c54dd0188c may be invalid.
[INFO]	No token be found for web
[INFO]	Apis exported completed

Process finished with exit code 0
```
而且 现在 [WARN]	project:1000360 may be deleted. 很明显再调用apifox的

**Comment by zhuangjiaju** [comment]
然后 我看您以前回复的一个 bug 说 理论上来说 token分项目的，我是 mac系统 ，所有的 token都是胡同的，我一个项目有所有的token

**Comment by zhuangjiaju** [comment]
bug 肯定在的 我把用户目录的.easy_yap .api_fox 删了就行了。

**Comment by tangcent** [comment]
这个表现有点不合理。虽然apifox基于easy-yapi，但是easy-yapi不大会去读取`.easy_yap.api_fox `

> 而且 现在 [WARN] project:1000360 may be deleted. 很明显再调用apifox的

看看请求是啥样的:
```
http.call.before=groovy:logger.info("call:"+request.url())
http.call.after=groovy:logger.info("response:"+response.string())
```

> 理论上来说 token分项目的，我是 mac系统 ，所有的 token都是胡同的，我一个项目有所有的token

是分项目的，但同时全局也有一份，每个项目保存配置的时候也会把当前的tokens更新到全局。
其他已经更新过token的项目不会受影响，但是新的项目or从没保存过配置的项目会直接用全局的。
这是当时从`全局共享`到`项目区分`的一个兼容措施，防止大家更新新版本后很多项目需要重新去找`token`

底层存储是这样的:
https://github.com/tangcent/easy-yapi/blob/e0a92dc7d73d378d381369c13bfd32a7d951623f/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/xml/ApplicationSettings.kt#L30

https://github.com/tangcent/easy-yapi/blob/e0a92dc7d73d378d381369c13bfd32a7d951623f/idea-plugin/src/main/kotlin/com/itangcent/idea/plugin/settings/xml/ProjectSettings.kt#L17
