### ISSUE TITLE
[Bug] IDEA2022生成SpringBoot带有泛型的分页IPage对象有问题

### ISSUE THREAD

**Issue by oujiangping** [tangcent/easy-yapi#981]
YAPI商民不能正确的显示mybatisplus的IPage分页对象
![image](https://github.com/tangcent/easy-yapi/assets/5906374/1b7b4e20-d985-4eb9-bce3-137c7b8c2783)
![image](https://github.com/tangcent/easy-yapi/assets/5906374/870d9ea4-2f8f-4773-841b-846ff2cde344)

**Comment by tangcent** [comment]
> 不能正确的显示mybatisplus的IPage分页对象

是什么问题? 

---

我猜测你可能需要在[设置](http://easyyapi.com/setting/ide-setting.html)里勾选`getter as field`

**Comment by mywnlb** [comment]
您好，在idea 2023.1.2  easyYapi 2.5.8.212.0下设置如下
![image](https://github.com/tangcent/easy-yapi/assets/26537851/2d5009b0-5d7d-438f-930f-d4d486a7d690)
上传api之后，返回数据并不是表格，请问如何处理
![image](https://github.com/tangcent/easy-yapi/assets/26537851/fa72ebba-134b-43e4-adea-4bf97f817105)

**Comment by tangcent** [comment]
去掉勾选`use json5(response)`就行

**Comment by mywnlb** [comment]
> 去掉勾选`use json5(response)`就行

感谢大佬，已经解决

**Comment by miyi2** [comment]
> > 不能正确的显示mybatisplus的IPage分页对象
> 
> 是什么问题?
> 
> 我猜测你可能需要在[设置](http://easyyapi.com/setting/ide-setting.html)里勾选`getter as field`

这个在apifox的idea插件中应该怎么配置呢？
