### ISSUE TITLE
作者大大请教个问题，接口参数使用JSON对象或者Map做RequestBody参数的时候生成yapi取不到字段

### ISSUE THREAD

**Issue by pplliang** [tangcent/easy-yapi#985]
这种情况能不能通过swagger注解直接配置出来？

**Comment by tangcent** [comment]
这里配置可以使用[export.after](http://easyyapi.com/setting/rules/export_after.html)这条规则:
比如: `export.after=groovy:api.setBodyClass(it.doc("body"))`

```java
/**
 * @body java.util.Map<java.lang.String,com.itangcent.common.model.UserInfo>
 */
```

看看`swagger`注解是怎样的? 替换到这里取`body`的逻辑就可以了

**Comment by pplliang** [comment]
没有swagger注解 我试了用@ApiImplicitParam 但是最多只能生效path query 和form  无法生成@RequestBody这种json形式的

**Comment by pplliang** [comment]
能否支持 @ApiImplicitParam#paramType="body"时的解析？

**Comment by tangcent** [comment]
可

**Comment by pplliang** [comment]
> 可

现在还不支持吧？
![image](https://github.com/tangcent/easy-yapi/assets/31211417/544d7ced-a28d-41b2-9c2f-15d11d586cd6)

**Comment by tangcent** [comment]
对，你也可以自己改改看

**Comment by pplliang** [comment]
> 对，你也可以自己改改看

api好像没有暴露出来 直接设置json body的参数  有个setJsonBody 但是不能生成备注，
并且再参数未设置@RequestBody的情况下，我设置了请求头api.setHeader("Content-Type","application/json",true,"application/json")，但是生成的文档中Content-Type的默认值依然是 x-www-form-urlencoded  没有找到能重新设置默认值的地方

**Comment by tangcent** [comment]
- 你这里的`body`会是什么样的? 试试`setBodyClass`?
   - 另一个通过class名称获取带备注的json结构的方法是这样: `helper.findClass("xxx.xxx.Xxxx").toObject(true,true,true)`
- `setHeader`这个方法里没处理好大小写等问题，你试试改成`content-type`

**Comment by pplliang** [comment]
> * 你这里的`body`会是什么样的? 试试`setBodyClass`?
>   
>   * 另一个通过class名称获取带备注的json结构的方法是这样: `helper.findClass("xxx.xxx.Xxxx").toObject(true,true,true)`
> * `setHeader`这个方法里没处理好大小写等问题，你试试改成`content-type`

![image](https://github.com/tangcent/easy-yapi/assets/31211417/00298add-e46d-4150-b3de-0ea14539d49c)
改成小写会生成2个contentType
我的想法是不通过指定class 因为用的map做参数接收的 直接通过注释或者注解给插进jsonMap里  RequestRuleWrap这个类中没有找到符合的方法，只有setJsonBody能用 缺点就是不能生成备注以及字段是否必填，如果不能满足的话 只能临时先整个class，替换参数生成后再修改回去

**Comment by pplliang** [comment]
获取content-type可以通过method.content.type=#contentType 然后通过注释（@contentType application/json）设置实现

**Comment by tangcent** [comment]
> 我的想法是不通过指定class 因为用的map做参数接收的 直接通过注释或者注解给插进jsonMap里 RequestRuleWrap这个类中没有找到符合的方法，只有setJsonBody能用 缺点就是不能生成备注以及字段是否必填，如果不能满足的话 只能临时先整个class，替换参数生成后再修改回去

你尝试过使用`helper.findClass("xxx.xxx.Xxxx").toObject(true,true,true)`了吗?
我这边测试是有备注信息的.
```properties
export.after=groovy:api.setJsonBody(helper.findClass("com.itangcent.common.model.UserInfo").toObject(true,true,true), "request")
```

**Comment by tangcent** [comment]
> 能否支持 @ApiImplicitParam#paramType="body"时的解析？

我看了下`swagger`官方文档，paramType设为body似乎不是推荐写法。
另外，在swagger3里，ParameterIn也没有支持body了:
```java

public enum ParameterIn {
    DEFAULT(""),
    HEADER("header"),
    QUERY("query"),
    PATH("path"),
    COOKIE("cookie");

    private String value;

    ParameterIn(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}
```

**Comment by pplliang** [comment]
> > 能否支持 @ApiImplicitParam#paramType="body"时的解析？
> 
> 我看了下`swagger`官方文档，paramType设为body似乎不是推荐写法。 另外，在swagger3里，ParameterIn也没有支持body了:
> 
> ```java
> public enum ParameterIn {
>     DEFAULT(""),
>     HEADER("header"),
>     QUERY("query"),
>     PATH("path"),
>     COOKIE("cookie");
> 
>     private String value;
> 
>     ParameterIn(String value) {
>         this.value = value;
>     }
> 
>     @Override
>     public String toString() {
>         return String.valueOf(value);
>     }
> }
> ```

那应该就是不支持了，没有办法

**Comment by pplliang** [comment]
> > 我的想法是不通过指定class 因为用的map做参数接收的 直接通过注释或者注解给插进jsonMap里 RequestRuleWrap这个类中没有找到符合的方法，只有setJsonBody能用 缺点就是不能生成备注以及字段是否必填，如果不能满足的话 只能临时先整个class，替换参数生成后再修改回去
> 
> 你尝试过使用`helper.findClass("xxx.xxx.Xxxx").toObject(true,true,true)`了吗? 我这边测试是有备注信息的.
> 
> ```ini
> export.after=groovy:api.setJsonBody(helper.findClass("com.itangcent.common.model.UserInfo").toObject(true,true,true), "request")
> ```

这么写是可以，但是有点本末倒置了，估计之前就是因为没有Bean才用的Map或者json当的参数，在存在bean的情况下直接放到参数里生成文档就行了，可以临时写个bean然后放参数里 生成后再改回来，特殊情况特殊处理

**Comment by pplliang** [comment]
谢谢了，提了这么多麻烦
