### ISSUE TITLE
[Bug] Controller类有继承结构时的问题

### ISSUE THREAD

**Issue by dragonfly135** [tangcent/easy-yapi#987]
Controller类有继承结构时，对父类（泛型）也提示输入token，此时父类里的api可以生成（父类里的api生成接口时，泛型可以转化为具体的对象）。但如果在另一个项目中也继承这个父类，插件里已经保存了前一个项目的token，这个父类里的api就无法生成了。

tokens里大概保存成这个样子
project1-controller=fd562379b306ff4f9a76b1ca8744bd6ed8dc1cd46993c9d894be36312d064c8f
project2-controller=f76310b30260375e6e433ae6c4aab8c7bfe7b33ce4d1dbfdf01187ef107c6297
parent-controller=fd562379b306ff4f9a76b1ca8744bd6ed8dc1cd46993c9d894be36312d064c8f==project1-controller
希望parent-controller，不要出现，相应的接口直接使用每个项目的token。

**Comment by tangcent** [comment]
试试在每个project里手动改一下token

> token是分项目的，但同时全局也有一份，每个项目保存配置的时候也会把当前的tokens更新到全局。
> 其他已经更新过token的项目不会受影响，但是新的项目or从没保存过配置的项目会直接用全局的。
> 这是当时从全局共享到项目区分的一个兼容措施，防止大家更新新版本后很多项目需要重新去配token


---

https://github.com/tangcent/easy-yapi/issues/979#issuecomment-1577779000
