### ISSUE TITLE
[Question] 怎么判断是否存在注释

### ISSUE THREAD

**Issue by keeleys** [tangcent/easy-yapi#992]
### 情况描述
比如下面的，如果注释和ApiModelProperty都存在，导出到yapi就会显示2行重复的备注。
```properties
field.doc=@io.swagger.annotations.ApiModelProperty#value
```

```java
/**
 * 策略名称
 */
@ApiModelProperty(value = "策略名称")
private String strategyName;
```
<img width="661" alt="image" src="https://github.com/tangcent/easy-yapi/assets/6245401/75dfd02c-7b14-4c48-81c1-6c612df22e0e">

## 问题
怎么配置假如有ApiModelProperty的时候不使用注释呢，或者有备注的时候不使用ApiModelProperty？

**Comment by tangcent** [comment]
试试:`field.doc[groovy:tool.isNullOrEmpty(it.doc())]=@io.swagger.annotations.ApiModelProperty#value`

另外，如果使用了ApiModelProperty是不是不需要再额外加相同的注释了？

**Comment by keeleys** [comment]
> 试试:`field.doc[groovy:tool.isNullOrEmpty(it.doc())]=@io.swagger.annotations.ApiModelProperty#value`
> 
> 另外，如果使用了ApiModelProperty是不是不需要再额外加相同的注释了？

有效果，另外有没有ApiModelProperty优先的写法呢？

插件是不需要额外的注释的，但是历史项目需要接入的时候要做一点兼容处理，这个框架优先注释了，导致之前注释不规范的可能都要去调整，所以如果能配置swagger优先的话，旧项目就不需要更新了

**Comment by tangcent** [comment]
> 有效果，另外有没有ApiModelProperty优先的写法呢？

目前没有好的写法
