### ISSUE TITLE
[建议]readme里可以加上运行项目所需环境，

### ISSUE THREAD

**Issue by wzdlagrange** [tangcent/easy-yapi#993]
我说下我的情况供萌新参考
我一开始用的idea2021旗舰版，jdk17。
后面还遇到各种问题，一一摸索解决，期间调到了jdk11，
最后遇到 找不到com.itangcent.intellij.context.ActionContext类
解决不动了，寻思是不是我idea版本问题
换到idea2023以后，编译不出错了，能好好看代码了。

现在我这成功运行的环境是，社区版idea2023，jdk11，
调节三个位置的jdk版本为11，分别是gradle，project，module三个位置
国内网络环境记得提前把gradle的仓库设置阿里云或者其他国内仓库，否则jar包下载很慢。

**Comment by tangcent** [comment]
IC
